import Mathlib.Util.AssertNoSorry
import ObserverPatchHolography.EinsteinBranch.Composition
import ObserverPatchHolography.EinsteinBranch.DarkSector
import ObserverPatchHolography.EinsteinBranch.CollarScaleSaturation
import ObserverPatchHolography.EinsteinBranch.DeepProfileClosure
import ObserverPatchHolography.EinsteinBranch.PerCutCollarComposition
import ObserverPatchHolography.EinsteinBranch.SparseRecordDefectWitness
import ObserverPatchHolography.EinsteinBranch.CollarPremiseDerivation
import ObserverPatchHolography.EinsteinBranch.FiniteCapGeneratorSplit
import ObserverPatchHolography.EinsteinBranch.FixedCapacityWLaw
import Geometry.SourceOrderEinsteinComposition

/-!
# Einstein-branch theorem audit

This file is the machine-checked counterpart of `EINSTEIN_BRANCH_INDEX.md`.
Every public result in the corrected Einstein-branch kernel is checked for
`sorryAx`, and the per-theorem `#print axioms` receipts below expose any
remaining logical dependencies to CI and human review.
-/

namespace OPH.EinsteinBranch

/-! ## Finite tower, non-entailment, and boundary composition -/

assert_no_sorry not_boundaryFiber_of_witness
assert_no_sorry demoTower_nondegenerate
assert_no_sorry demoTower_boundaryFiber
assert_no_sorry counterextensions_share_reduct
assert_no_sorry einsteinEq_demoEinsteinExtension
assert_no_sorry not_einsteinEq_demoNonEinsteinExtension
assert_no_sorry bare_consensus_not_einstein_complete
assert_no_sorry boundary_fiber_readout_composition

/-! ## Direct-sum entropy, finite first law, and MaxEnt envelope -/

assert_no_sorry directSumEntropy_eq_bulk_add_edge
assert_no_sorry centralVariation_eq_edgeEntropyVariation
assert_no_sorry central_edge_normalization_defect
assert_no_sorry finite_bulk_edge_central_first_law
assert_no_sorry passingFirstLawData_passes
assert_no_sorry failingFirstLawData_fails
assert_no_sorry maxEnt_envelope_identity
assert_no_sorry passingMaxEntTangent_passes
assert_no_sorry failingMaxEntTangent_fails

/-! ## Exact small-ball arithmetic and a negative asymptotic receipt -/

assert_no_sorry diamondKernelIntegral_eq
assert_no_sorry bulkSmallBallCoefficient
assert_no_sorry fixedVolumeAreaCoefficient
assert_no_sorry constantRadiusData_fails
assert_no_sorry restFrameEinsteinRelation

/-! ## Strict manifests and deletion failures -/

assert_no_sorry strictManifest_dependency
assert_no_sorry strictManifest_erase_required_fails
assert_no_sorry nonzero_defect_fails_entropy
assert_no_sorry extra_scale_stabilizer_fails

/-! The tensor/tomography assertions are kept next to the implementation and
are repeated here once the public API is imported. -/

assert_no_sorry bilinOf_add_left
assert_no_sorry bilinOf_add_right
assert_no_sorry bilinOf_smul_left
assert_no_sorry bilinOf_smul_right
assert_no_sorry bilinOf_single_single
assert_no_sorry quadOf_sub_smul
assert_no_sorry quadOf_smul
assert_no_sorry quadOf_double
assert_no_sorry quadOf_triple
assert_no_sorry eta_symm
assert_no_sorry eta_zero_zero
assert_no_sorry eta_diag_spatial
assert_no_sorry eta_off_diag
assert_no_sorry e_zero_at_zero
assert_no_sorry double_at_zero
assert_no_sorry triple_at_zero
assert_no_sorry tomographyDirections_null
assert_no_sorry tomographyCharge_eq_design
assert_no_sorry tomographyDecoder_design
assert_no_sorry tomographyDecoder_charge
assert_no_sorry tomographyDecoder_zero
assert_no_sorry tomographyCharge_injective
assert_no_sorry traceFreeMat_symm
assert_no_sorry invSqrtThree_sq
assert_no_sorry traceFree_decomposition
assert_no_sorry nine_null_directions_determine_mod_metric
assert_no_sorry nine_charge_metric_ambiguity
assert_no_sorry unit_timelike_determines
assert_no_sorry null_cone_determines
assert_no_sorry tensor_upgrade
assert_no_sorry jacobson_step
assert_no_sorry ddiv_lam_eta
assert_no_sorry row_eta_cancel
assert_no_sorry step_invariant_of_divergence_free
assert_no_sorry lam_eq_of_symmReachable
assert_no_sorry lambda_constant_symm
assert_no_sorry einstein_equation_with_constant_symm

/-! ## End-to-end conditional composition -/

assert_no_sorry continuumEinstein_from_explicit_premises
assert_no_sorry composedEinsteinBranch
assert_no_sorry composedEinsteinAdmissibleTower

/-! ## Source-order/source-direction conditional Einstein composition -/

/-! The finite source carrier is constructed as positive-scale canonical
longest-path time times the exact rank-three quotient.  A supplied spatial
placement plus an edge-speed bound gives the forward causal map; faithful
equivalence requires the explicit converse-support certificate. -/

assert_no_sorry OPH.Provenance.SemanticEventLog.sourceHeight_eq
assert_no_sorry OPH.Provenance.SemanticEventLog.sourceHeight_lt_of_parent
assert_no_sorry OPH.Provenance.SemanticEventLog.sourceHeight_eq_zero_iff
assert_no_sorry OPH.Provenance.SemanticEventLog.sourceHeight_lt_of_generatedBefore
assert_no_sorry OPH.Provenance.SemanticEventLog.withSourceHeight
assert_no_sorry OPH.SourceDerivedSpacetime.sourceSpacetimeCarrier_finrank
assert_no_sorry OPH.SourceDerivedSpacetime.sourceCarrier_one_three_signature
assert_no_sorry OPH.SourceDerivedSpacetime.sourceUnitNullVector_null
assert_no_sorry OPH.SourceDerivedSpacetime.sourceUnitNullVector_futureCausal
assert_no_sorry OPH.SourceDerivedSpacetime.RankSpatialCausalPlacement.parentEdge_sourceCausalLE
assert_no_sorry OPH.SourceDerivedSpacetime.RankSpatialCausalPlacement.generatedBefore_sourceCausalLE
assert_no_sorry OPH.SourceDerivedSpacetime.RankSpatialCausalPlacement.sourceHeight_le_of_sourceCausalLE
assert_no_sorry OPH.Provenance.SemanticEventLog.generatedBeforeEq_isPartialOrder
assert_no_sorry OPH.Provenance.SemanticEventLog.finiteCausalSetAxioms
assert_no_sorry OPH.SourceDerivedSpacetime.sourceCausalLE_isPartialOrder
assert_no_sorry OPH.SourceDerivedSpacetime.FaithfulRankSpatialCausalPlacement.generatedBeforeEq_iff_sourceCausalLE
assert_no_sorry OPH.SourceDerivedSpacetime.FaithfulRankSpatialCausalPlacement.mem_interval_iff_sourceCausalInterval
assert_no_sorry OPH.SourceDerivedSpacetime.FaithfulRankSpatialCausalPlacement.eventPoint_injective
assert_no_sorry OPH.SourceDerivedSpacetime.FaithfulRankSpatialCausalPlacement.toSourceDerivedCausalChartInterface
assert_no_sorry OPH.SourceOrderFrameCompatibilityPacket.ofFaithfulPlacementStandardFrame
assert_no_sorry OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.faithfulPlacement
assert_no_sorry OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.exactDiamondConeOrder
assert_no_sorry OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.responses_spacelike
assert_no_sorry OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.parentEdge_null
assert_no_sorry OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.sourceOrderFramePacket
assert_no_sorry OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.sourceOrderFramePacket_consequences

/-! The audited nine-element direction family is the fixed algebraic inverse
image of the pre-existing coordinate tomography frame.  It is not selected by
the generated poset/source dynamics and is not invariant, as a distinguished
set, under Lorentz or `SO(3)` transformations.  Only each fixed direction's
`(1,n)` future-null representative is canonical. -/

assert_no_sorry OPH.sourceNullEinsteinVector_null
assert_no_sorry OPH.sourceNullEinsteinVector_time
assert_no_sorry OPH.sourceNullEinsteinVector_sourceTomographyDirections
assert_no_sorry OPH.SourceDirectionEinsteinShapePremises.tomographyBalance
assert_no_sorry OPH.SourceDirectionEinsteinShapePremises.pointwiseMetricAmbiguity
assert_no_sorry OPH.SourceDirectionEinsteinShapePremises.nullBalance
assert_no_sorry OPH.SourceDirectionEinsteinShapePremises.constantMetricAmbiguity
assert_no_sorry OPH.sourceOrderEinsteinShape_from_minimal_source_directions
assert_no_sorry OPH.SourceIndexedEinsteinPremises.tomographyBalance
assert_no_sorry OPH.SourceIndexedEinsteinPremises.pointwiseMetricAmbiguity
assert_no_sorry OPH.SourceIndexedEinsteinPremises.nullBalance
assert_no_sorry OPH.SourceIndexedEinsteinPremises.toContinuumEinsteinPremises
assert_no_sorry OPH.SourceIndexedEinsteinPremises.constantMetricAmbiguity
assert_no_sorry OPH.SourceIndexedEinsteinPremises.einsteinEquation
assert_no_sorry OPH.sourceOrderEinstein_from_source_directions

/-! ## Generic dark sector and modular-anomaly source -/

assert_no_sorry totalStress_eq_luminous_add_dark
assert_no_sorry geometry_responds_to_all_charge
assert_no_sorry luminousOnlyRelation_iff_darkStress_eq_zero
assert_no_sorry exists_dark_source_of_geometric_excess
assert_no_sorry darkStress_nonneg_of_charges_nonneg
assert_no_sorry anomalousStress_abs_le
assert_no_sorry anomalousStress_eq_zero_of_recovered
assert_no_sorry anomalousStress_tendsto_zero
assert_no_sorry comovingDensity_mul_scale_cubed
assert_no_sorry enclosedMass_hasDerivAt
assert_no_sorry deep_radial_acceleration
assert_no_sorry circularSpeedSq_const
assert_no_sorry baryonic_tully_fisher
assert_no_sorry isotropic_quadrupole_projection_zero
assert_no_sorry localHaloTidal_below_cassini

/-! Human-readable per-theorem reports are emitted into the build receipt. -/

#print axioms bare_consensus_not_einstein_complete
#print axioms boundary_fiber_readout_composition
#print axioms directSumEntropy_eq_bulk_add_edge
#print axioms finite_bulk_edge_central_first_law
#print axioms maxEnt_envelope_identity
#print axioms diamondKernelIntegral_eq
#print axioms restFrameEinsteinRelation
#print axioms tomographyDirections_null
#print axioms tomographyDecoder_design
#print axioms tomographyDecoder_charge
#print axioms tomographyCharge_injective
#print axioms nine_null_directions_determine_mod_metric
#print axioms nine_charge_metric_ambiguity
#print axioms unit_timelike_determines
#print axioms null_cone_determines
#print axioms tensor_upgrade
#print axioms jacobson_step
#print axioms ddiv_lam_eta
#print axioms step_invariant_of_divergence_free
#print axioms lambda_constant_symm
#print axioms einstein_equation_with_constant_symm
#print axioms strictManifest_erase_required_fails
#print axioms continuumEinstein_from_explicit_premises
#print axioms composedEinsteinBranch
#print axioms composedEinsteinAdmissibleTower
#print axioms OPH.SourceDerivedSpacetime.sourceCarrier_one_three_signature
#print axioms OPH.SourceDerivedSpacetime.RankSpatialCausalPlacement.generatedBefore_sourceCausalLE
#print axioms OPH.SourceDerivedSpacetime.FaithfulRankSpatialCausalPlacement.generatedBeforeEq_iff_sourceCausalLE
#print axioms OPH.SourceDerivedSpacetime.FaithfulRankSpatialCausalPlacement.mem_interval_iff_sourceCausalInterval
#print axioms OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.exactDiamondConeOrder
#print axioms OPH.SourceDerivedSpacetime.BooleanDiamondPlacement.responses_spacelike
#print axioms OPH.SourceDirectionEinsteinShapePremises.constantMetricAmbiguity
#print axioms OPH.sourceOrderEinsteinShape_from_minimal_source_directions
#print axioms OPH.SourceIndexedEinsteinPremises.nullBalance
#print axioms OPH.SourceIndexedEinsteinPremises.einsteinEquation
#print axioms OPH.sourceOrderEinstein_from_source_directions
#print axioms luminousOnlyRelation_iff_darkStress_eq_zero
#print axioms exists_dark_source_of_geometric_excess
#print axioms anomalousStress_tendsto_zero

/-! ## Collar-scale saturation and deep-profile characterization -/

assert_no_sorry eta_and_stress_tendsto_zero_of_depth
assert_no_sorry eta_and_stress_tendsto_zero_of_density
assert_no_sorry anomalousStress_exponential_rate
assert_no_sorry envelopeBound_lt_iff
assert_no_sorry recoveryEnvelope_admits_zero_defect
assert_no_sorry recoveryEnvelope_admits_order_one_defect
assert_no_sorry sparseCutRemainder_stress_pos
assert_no_sorry linear_on_pos_of_additive_monotone
assert_no_sorry deepProfile_characterization
assert_no_sorry law_baryonic_tully_fisher_exists
assert_no_sorry anomalous_dominates_iff
assert_no_sorry additiveLaw_not_quadratureClosed
assert_no_sorry sqrtLaw_not_scaleCovariant
assert_no_sorry varianceSlope
assert_no_sorry perCut_isDeepRegimeLaw
assert_no_sorry perCut_a0_dictionary
assert_no_sorry perCut_a0_unique
assert_no_sorry perCut_nonidentifiability

/-! ## Sparse-record mechanism, premise derivation, and cap-generator split -/

assert_no_sorry recordDefect_isLeast
assert_no_sorry recordDefect_isLeast_randomized
assert_no_sorry unrecordedCut_error_ge_half
assert_no_sorry recordDefect_lt_iff
assert_no_sorry sparseRecordRemainder_stress_pos
assert_no_sorry recordRemainder_eta_and_stress_tendsto_zero
assert_no_sorry AtomicDefectModel.compoundVariance_disjUnion
assert_no_sorry composed_deep_law
assert_no_sorry correlated_pair_breaks_variance_additivity
assert_no_sorry density_necessary
assert_no_sorry modularGenerator_split
assert_no_sorry split_unique
assert_no_sorry split_nonunique_without_normalization
assert_no_sorry anomalousPart_rescale
assert_no_sorry anomalousPart_supported_on_collar
assert_no_sorry anomalousPart_collar_boost_free
assert_no_sorry boostedState_anomalousPart

/-! ## Fixed-capacity dark-energy w-law -/

assert_no_sorry CapacityLaw.w_eq_neg_one_of_constN
assert_no_sorry CapacityLaw.w_eq_drift
assert_no_sorry CapacityLaw.w_ge_neg_one_of_monotone
assert_no_sorry CapacityLaw.deriv_N_neg_of_w_lt_neg_one
assert_no_sorry cpl_at_neg_one_unique
assert_no_sorry CapacityLaw.cpl_forced_of_constN
assert_no_sorry powerCapacity_w
assert_no_sorry decreasingCapacity_w_lt_neg_one

#print axioms eta_and_stress_tendsto_zero_of_depth
#print axioms eta_and_stress_tendsto_zero_of_density
#print axioms anomalousStress_exponential_rate
#print axioms envelopeBound_lt_iff
#print axioms recoveryEnvelope_admits_zero_defect
#print axioms recoveryEnvelope_admits_order_one_defect
#print axioms sparseCutRemainder_stress_pos
#print axioms linear_on_pos_of_additive_monotone
#print axioms deepProfile_characterization
#print axioms law_baryonic_tully_fisher_exists
#print axioms anomalous_dominates_iff
#print axioms additiveLaw_not_quadratureClosed
#print axioms sqrtLaw_not_scaleCovariant
#print axioms varianceSlope
#print axioms perCut_isDeepRegimeLaw
#print axioms perCut_a0_dictionary
#print axioms perCut_a0_unique
#print axioms perCut_nonidentifiability
#print axioms recordDefect_isLeast
#print axioms recordDefect_isLeast_randomized
#print axioms unrecordedCut_error_ge_half
#print axioms recordDefect_lt_iff
#print axioms sparseRecordRemainder_stress_pos
#print axioms recordRemainder_eta_and_stress_tendsto_zero
#print axioms AtomicDefectModel.compoundVariance_disjUnion
#print axioms composed_deep_law
#print axioms correlated_pair_breaks_variance_additivity
#print axioms density_necessary
#print axioms modularGenerator_split
#print axioms split_unique
#print axioms split_nonunique_without_normalization
#print axioms anomalousPart_rescale
#print axioms anomalousPart_supported_on_collar
#print axioms anomalousPart_collar_boost_free
#print axioms boostedState_anomalousPart
#print axioms CapacityLaw.w_eq_neg_one_of_constN
#print axioms CapacityLaw.w_eq_drift
#print axioms CapacityLaw.w_ge_neg_one_of_monotone
#print axioms CapacityLaw.deriv_N_neg_of_w_lt_neg_one
#print axioms cpl_at_neg_one_unique
#print axioms CapacityLaw.cpl_forced_of_constN
#print axioms powerCapacity_w
#print axioms decreasingCapacity_w_lt_neg_one

end OPH.EinsteinBranch
