import Mathlib
import TrichotomyCases

namespace OPH.A2HolonomyBridge

/-!
# Abstract A2 holonomy bridge and the finite compact-product selector

This module isolates the two finite logical steps in the canonical
holonomy-fullness bridge for the twelve-port current argument.

* `carrier_projective_witness_of_holonomy` keeps the closed path, its
  projective implementer, the response-generated factor, and the
  response-silent factor in one theorem.  The two internal-action corollaries
  are `carrierResponse_internal_of_holonomy` and
  `internalImplementation_of_holonomy`.
* `four_factor_fixed_dimension_ne_one` rules out a four-factor branch whose
  factorwise fixed dimensions are each zero or three when the full fixed space
  has dimension one.
* `faithful_twelve_port_response_has_dimension_twelve` proves the total
  response-image dimension used by the finite selector from an injective
  linear response on the twelve-port space.
* `compact_product_dimensions_of_fixed_space` feeds that exclusion into
  `TrichotomyCases.inner_action_selection`.

BOUNDARY.  Every load-bearing bridge is visible in the theorem signatures.
The type `Q` is an abstract projective-unitary group.  A physical
instantiation must set it to the relevant `PU(H)`.  The supplied
`responseFlow : V → Q` must be the projectivized response flow generated by
the A1 port operators.  This file neither constructs that flow nor proves its
source provenance.  The subgroup called response-generated is exactly the
algebraic subgroup generated by the range of this supplied flow; it cannot be
replaced by an arbitrary implementer group in the theorem.

The kernel of the action `Q →* Equiv.Perm L` is the formal centralizer or
spectator factor.  It is allowed because it acts identically on the response
codomain, and therefore cannot implement a nontrivial carrier action there.
The same holonomy element is used for its carrier projection and projective
implementer.  The core theorem requires one endogenous path witness for each
carrier automorphism.  It does not require every closed path to be
endogenous.  This file does not prove holonomy fullness from A1--A3, extract
implementers from overlap logs, construct `D`, prove compact reductive
decomposition, or classify compact simple Lie algebras.
`SimpleDims = {3, 8, 10}`, the centre bound, and the factorwise fixed-space
description of the centreless branch remain explicit classical inputs.  The
selected closed path is pointwise in the carrier automorphism; no homomorphic
section from carrier automorphisms back to holonomy is asserted.
-/

universe uA uH uQ uV uL

section Holonomy

variable {A : Type uA} {H : Type uH} {Q : Type uQ}
variable {V : Type uV} {L : Type uL}
variable [Group A] [Group H] [Group Q]

/-- Every carrier symmetry has a reversible closed-holonomy preimage. -/
def HolonomyFull (project : H →* A) : Prop :=
  Function.Surjective project

/-- The subgroup generated by the supplied projectivized port-response flow.

In a Lie-group instantiation `responseFlow v` is the projective class of the
unitary flow generated by the port response `D v`.  The abstract theorem uses
only the subgroup generated by those elements. -/
def ResponseGeneratedGroup (responseFlow : V → Q) : Subgroup Q :=
  Subgroup.closure (Set.range responseFlow)

/-- Interpretation of a transported port response agrees with the projective
implementer assigned to the same holonomy element. -/
def ProjectiveResponseNatural
    (portAction : A →* Equiv.Perm V)
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (D : V → L) : Prop :=
  ∀ h v,
    D (portAction (project h) v) =
      projectiveAction (implementer h) (D v)

/-- The carrier action on the current codomain is the action induced through
the response map. -/
def CarrierCovariant
    (portAction : A →* Equiv.Perm V)
    (currentAction : A →* Equiv.Perm L)
    (D : V → L) : Prop :=
  ∀ a v, D (portAction a v) = currentAction a (D v)

/-- Strong convenience condition: every closed-path implementer factors into
the subgroup generated by the supplied port-response flow and a
response-silent factor.

The silent factor is not merely named as a "centralizer": it is an element of
the kernel of the projective action on `L`, so its trivial response action is
part of the type.  The A2 bridge below uses the weaker
`CarrierHolonomyFullEndogenous`, which asks for one such path per carrier
automorphism. -/
def ProjectiveResponseEndogenous
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q) : Prop :=
  ∀ h,
    ∃ g : ResponseGeneratedGroup responseFlow,
      ∃ c : projectiveAction.ker,
        implementer h = (g : Q) * (c : Q)

/-- Every carrier automorphism has one closed-path preimage whose implementer
factors through the response-generated subgroup and a response-silent factor.

This is the quantifier used by A2.  Other closed paths need not satisfy the
factorization. -/
def CarrierHolonomyFullEndogenous
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q) : Prop :=
  ∀ a,
    ∃ h : H,
      ∃ g : ResponseGeneratedGroup responseFlow,
        ∃ c : projectiveAction.ker,
          project h = a ∧
          implementer h = (g : Q) * (c : Q)

/-- The stronger global fullness and all-path endogeneity conditions imply
the one-witness-per-action condition used by the core bridge. -/
theorem carrierHolonomyFullEndogenous_of_full
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (hfull : HolonomyFull project)
    (hendogenous :
      ProjectiveResponseEndogenous
        implementer projectiveAction responseFlow) :
    CarrierHolonomyFullEndogenous
      project implementer projectiveAction responseFlow := by
  intro a
  obtain ⟨h, hproject⟩ := hfull a
  obtain ⟨g, c, hfactor⟩ := hendogenous h
  exact ⟨h, g, c, hproject, hfactor⟩

/-- One same-path projective witness for every carrier automorphism.  The
response-silent factor is retained in the witness, while the last line records
that it disappears from the action on the response image. -/
def CarrierProjectivelyEndogenous
    (portAction : A →* Equiv.Perm V)
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (D : V → L) : Prop :=
  ∀ a,
    ∃ h : H,
      ∃ g : ResponseGeneratedGroup responseFlow,
        ∃ c : projectiveAction.ker,
          project h = a ∧
          implementer h = (g : Q) * (c : Q) ∧
          ∀ v,
            D (portAction a v) =
              projectiveAction (g : Q) (D v)

/-- Pointwise response-generated implementation of every carrier action.
This does not assert that the selected closed paths form a homomorphic section
of the holonomy projection. -/
def InternallyImplemented
    (currentAction : A →* Equiv.Perm L)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q) : Prop :=
  ∀ a,
    ∃ g : ResponseGeneratedGroup responseFlow,
      currentAction a = projectiveAction (g : Q)

/-- Response-generated implementation stated directly on the response image. -/
def CarrierResponseInternallyImplemented
    (portAction : A →* Equiv.Perm V)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (D : V → L) : Prop :=
  ∀ a,
    ∃ g : ResponseGeneratedGroup responseFlow,
      ∀ v,
        D (portAction a v) =
          projectiveAction (g : Q) (D v)

/-- The core projective A2 bridge.  The bridge premise supplies one
endogenous closed path for a carrier automorphism.  Naturality uses that same
path's implementer. -/
theorem carrier_projective_witness_of_holonomy
    (portAction : A →* Equiv.Perm V)
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (D : V → L)
    (hbridge :
      CarrierHolonomyFullEndogenous
        project implementer projectiveAction responseFlow)
    (hnatural :
      ProjectiveResponseNatural
        portAction project implementer projectiveAction D) :
    CarrierProjectivelyEndogenous
      portAction project implementer projectiveAction responseFlow D := by
  intro a
  obtain ⟨h, g, c, hproject, hfactor⟩ := hbridge a
  refine ⟨h, g, c, hproject, hfactor, ?_⟩
  intro v
  calc
    D (portAction a v) =
        D (portAction (project h) v) := by rw [hproject]
    _ = projectiveAction (implementer h) (D v) := hnatural h v
    _ = projectiveAction ((g : Q) * (c : Q)) (D v) := by rw [hfactor]
    _ = projectiveAction (g : Q) (D v) := by
      have hc : projectiveAction (c : Q) = 1 := c.property
      rw [map_mul, hc, mul_one]

/-- Discarding the path and response-silent witnesses leaves pointwise
response-generated implementation on the response image. -/
theorem carrierResponse_internal_of_holonomy
    (portAction : A →* Equiv.Perm V)
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (D : V → L)
    (hbridge :
      CarrierHolonomyFullEndogenous
        project implementer projectiveAction responseFlow)
    (hnatural :
      ProjectiveResponseNatural
        portAction project implementer projectiveAction D) :
    CarrierResponseInternallyImplemented
      portAction projectiveAction responseFlow D := by
  have hwitness := carrier_projective_witness_of_holonomy
    portAction project implementer projectiveAction responseFlow D
      hbridge hnatural
  intro a
  obtain ⟨_, g, _, _, _, haction⟩ := hwitness a
  exact ⟨g, haction⟩

/-- A nontrivial carrier action on the response image cannot be discharged by
the response-silent kernel alone.  Any internal implementation of such an
action contains an element of the response-generated subgroup whose action on
the response codomain is nontrivial. -/
theorem nontrivial_carrier_requires_generated_response
    (portAction : A →* Equiv.Perm V)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (D : V → L)
    (hinternal :
      CarrierResponseInternallyImplemented
        portAction projectiveAction responseFlow D)
    (a : A) (v : V)
    (hne : D (portAction a v) ≠ D v) :
    ∃ g : ResponseGeneratedGroup responseFlow,
      projectiveAction (g : Q) ≠ 1 := by
  obtain ⟨g, hg⟩ := hinternal a
  refine ⟨g, ?_⟩
  intro htrivial
  apply hne
  calc
    D (portAction a v) = projectiveAction (g : Q) (D v) := hg v
    _ = D v := by rw [htrivial]; rfl

/-- One endogenous holonomy witness per carrier action, together with
naturality, forces the action on a response-generated current codomain to be
internal.

Surjectivity of `D` expresses that `L` is the current codomain generated by
the visible response directions, rather than a larger ambient operator space.
-/
theorem internalImplementation_of_holonomy
    (portAction : A →* Equiv.Perm V)
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (currentAction : A →* Equiv.Perm L)
    (D : V → L)
    (hbridge :
      CarrierHolonomyFullEndogenous
        project implementer projectiveAction responseFlow)
    (hD : Function.Surjective D)
    (hnatural :
      ProjectiveResponseNatural
        portAction project implementer projectiveAction D)
    (hcarrier : CarrierCovariant portAction currentAction D) :
    InternallyImplemented currentAction projectiveAction responseFlow := by
  have hresponse := carrierResponse_internal_of_holonomy
    portAction project implementer projectiveAction responseFlow D
      hbridge hnatural
  intro a
  obtain ⟨g, hg⟩ := hresponse a
  refine ⟨g, ?_⟩
  apply Equiv.ext
  intro x
  obtain ⟨v, rfl⟩ := hD x
  calc
    currentAction a (D v) = D (portAction a v) := (hcarrier a v).symm
    _ = projectiveAction (g : Q) (D v) := hg v

end Holonomy

section PortDimension

variable {R : Type*} {W : Type*}
variable [Field R] [AddCommGroup W] [Module R W]

/-- A faithful linear response on the full twelve-port space has a
twelve-dimensional image.  This discharges the finite dimension count itself;
identifying that image with a compact reductive Lie algebra remains a separate
adapter. -/
theorem faithful_twelve_port_response_has_dimension_twelve
    (D : (Fin 12 → R) →ₗ[R] W)
    (hD : Function.Injective D) :
    Module.finrank R D.range = 12 := by
  rw [LinearMap.finrank_range_of_inj hD]
  simp

end PortDimension

section FixedSpace

open OPHSelection (SimpleDims)

/-- Four simple three-dimensional factors cannot have total fixed dimension
one if the action on each factor has fixed dimension zero or three. -/
theorem four_factor_fixed_dimension_ne_one
    (fixedDim : Fin 4 → ℕ)
    (hfactor : ∀ i, fixedDim i = 0 ∨ fixedDim i = 3) :
    (∑ i, fixedDim i) ≠ 1 := by
  intro hsum
  have heach : ∀ i ∈ (Finset.univ : Finset (Fin 4)), 3 ∣ fixedDim i := by
    intro i _
    rcases hfactor i with hi | hi
    · rw [hi]
      exact dvd_zero 3
    · rw [hi]
  have hdiv : 3 ∣ ∑ i, fixedDim i := Finset.dvd_sum heach
  rw [hsum] at hdiv
  norm_num at hdiv

/-- The fixed-space description supplied by a centreless `su(2)^4` branch.

The total fixed dimension is kept as a separate argument.  This prevents the
branch premise from containing the desired contradiction `fixedDim = 1`.
Identifying a centreless compact twelve-dimensional algebra with four
three-dimensional simple factors, and showing that each restricted action has
fixed dimension zero or three, remain explicit classical Lie-theoretic inputs.
-/
def CentrelessFourFactorFixedSpaceDescription
    (dz carrierFixedDim : ℕ) : Prop :=
  dz = 0 →
    ∃ fixedDim : Fin 4 → ℕ,
      (∀ i, fixedDim i = 0 ∨ fixedDim i = 3) ∧
      (∑ i, fixedDim i) = carrierFixedDim

theorem centre_nonzero_of_four_factor_fixed_space
    (dz carrierFixedDim : ℕ)
    (hfixed : carrierFixedDim = 1)
    (hbranch :
      CentrelessFourFactorFixedSpaceDescription dz carrierFixedDim) :
    dz ≠ 0 := by
  intro hzero
  obtain ⟨fixedDim, hfactor, hsum⟩ := hbranch hzero
  rw [hfixed] at hsum
  exact four_factor_fixed_dimension_ne_one fixedDim hfactor hsum

/-- Finite selector conclusion under the explicit compact-Lie inputs.

`hm` is the declared compact-simple dimension list below twelve, `hsum` is
the reductive dimension split, `hle` is the one-dimensional centre bound
obtained when the carrier action is internal, and `hbranch` is the fixed-space
exclusion of the centreless four-factor branch.  The conclusion is dimension
data only.  Identifying the factors as `su(2)` and `su(3)` uses the external
classification of compact simple real Lie algebras.
-/
theorem compact_product_dimensions_of_fixed_space
    (dz carrierFixedDim : ℕ) (m : Multiset ℕ)
    (hm : ∀ d ∈ m, d ∈ SimpleDims)
    (hsum : dz + m.sum = 12)
    (hle : dz ≤ 1)
    (hfixed : carrierFixedDim = 1)
    (hbranch :
      CentrelessFourFactorFixedSpaceDescription dz carrierFixedDim) :
    dz = 1 ∧ m = {3, 8} := by
  exact OPH.TrichotomyCases.inner_action_selection
    dz m hm hsum hle
      (centre_nonzero_of_four_factor_fixed_space
        dz carrierFixedDim hfixed hbranch)

end FixedSpace

section Assembly

open OPHSelection (SimpleDims)

variable {A : Type uA} {H : Type uH} {Q : Type uQ}
variable {V : Type uV} {L : Type uL}
variable [Group A] [Group H] [Group Q]

/-- The assembled abstract bridge from projective A2 holonomy to the compact
product dimension conclusion.

The two adapter hypotheses `hcentreBound` and `hcentreless` are deliberately
functions of the proved response-generated implementation.  They mark the
remaining classical Lie-theory layer:

* inner automorphisms fix the centre, and the carrier module has one fixed
  line, giving `dz ≤ 1`;
* a centreless compact twelve-dimensional branch decomposes into four
  three-dimensional factors, each with fixed dimension zero or three.

This theorem does not prove either adapter, the compact-simple dimension list,
or the reductive dimension split.  It prevents the projective holonomy result
from being cited as though those independent inputs had disappeared. -/
theorem compact_product_dimensions_of_projective_holonomy
    (portAction : A →* Equiv.Perm V)
    (project : H →* A)
    (implementer : H →* Q)
    (projectiveAction : Q →* Equiv.Perm L)
    (responseFlow : V → Q)
    (D : V → L)
    (hbridge :
      CarrierHolonomyFullEndogenous
        project implementer projectiveAction responseFlow)
    (hnatural :
      ProjectiveResponseNatural
        portAction project implementer projectiveAction D)
    (dz carrierFixedDim : ℕ)
    (m : Multiset ℕ)
    (hm : ∀ d ∈ m, d ∈ SimpleDims)
    (hsum : dz + m.sum = 12)
    (hfixed : carrierFixedDim = 1)
    (hcentreBound :
      CarrierResponseInternallyImplemented
        portAction projectiveAction responseFlow D →
      dz ≤ 1)
    (hcentreless :
      CarrierResponseInternallyImplemented
        portAction projectiveAction responseFlow D →
      CentrelessFourFactorFixedSpaceDescription dz carrierFixedDim) :
    dz = 1 ∧ m = {3, 8} := by
  have hinternal : CarrierResponseInternallyImplemented
      portAction projectiveAction responseFlow D :=
    carrierResponse_internal_of_holonomy
      portAction project implementer projectiveAction responseFlow D
        hbridge hnatural
  exact compact_product_dimensions_of_fixed_space
    dz carrierFixedDim m hm hsum (hcentreBound hinternal) hfixed
      (hcentreless hinternal)

end Assembly

end OPH.A2HolonomyBridge

/- Axiom audit: standard axioms only; no native_decide. -/

#print axioms OPH.A2HolonomyBridge.carrier_projective_witness_of_holonomy
#print axioms OPH.A2HolonomyBridge.carrierHolonomyFullEndogenous_of_full
#print axioms OPH.A2HolonomyBridge.internalImplementation_of_holonomy
#print axioms OPH.A2HolonomyBridge.carrierResponse_internal_of_holonomy
#print axioms OPH.A2HolonomyBridge.nontrivial_carrier_requires_generated_response
#print axioms OPH.A2HolonomyBridge.faithful_twelve_port_response_has_dimension_twelve
#print axioms OPH.A2HolonomyBridge.four_factor_fixed_dimension_ne_one
#print axioms OPH.A2HolonomyBridge.centre_nonzero_of_four_factor_fixed_space
#print axioms OPH.A2HolonomyBridge.compact_product_dimensions_of_fixed_space
#print axioms OPH.A2HolonomyBridge.compact_product_dimensions_of_projective_holonomy
