import KogutSusskindFiberRateComparison

set_option autoImplicit false

namespace OPH.GaugeOrbitQuotientGap

open OPH.KogutSusskindFiberRate

/-!
# Gauge-orbit quotient of the independent fiber product: descent of the generator and the minimum-rate Dirichlet bound

`KogutSusskindFiberRateComparison` proves the variable-rate Dirichlet
comparison on the independent product of two-point fibers and names the
gauge-orbit quotient as the exact open step, because the committed
quotient structure (`Z2GaugeOrbits` in
`code/yang_mills/z2_finite_transfer_receipt.py`) had no Lean
formalization.  This module closes the finite descent-and-restriction
part of that step:

* the committed gauge action, formalized: the producer represents a `Z2`
  gauge transformation as an XOR mask on link configurations (one bit per
  link, flipped when the link is incident to an odd number of transformed
  sites, with incidence counted over distinct incident sites, the
  producer's OR; on the `1 × 1` periodic torus a self-loop's two endpoints
  coincide, so endpoint-multiplicity counting would give the empty mask
  where the producer's `star_masks` gives the both-links mask, and the
  committed receipt tori `L ∈ {2, 3}` have no self-loops, so the two
  countings agree there) and the gauge group as the set of subset-XORs of
  the site star masks.  Here a mask acts by `xorMask`, its permutation is `maskPerm`,
  and the gauge group of a generating mask set `S` is `gaugeGroup S`, the
  permutation subgroup generated by the mask translations.  Every element
  of `gaugeGroup S` is itself a mask translation supported on the moved
  links (`exists_mask_of_mem_gaugeGroup`);
* descent: with fiber weights symmetric on every moved link, each collar
  conditional expectation and the full product generator commute with
  every gauge translation (`condExp_translate`, `generator_translate`),
  the product weight is gauge invariant (`prodWeight_xorMask`), and the
  generator maps the gauge-invariant submodule to itself
  (`generator_mem_invariantSubmodule`).  The quotient generator is the
  restriction `quotientGenerator` to that submodule, which contains the
  constants (`const_mem_invariantSubmodule`);
* the bound: restriction shrinks the constraint set of a Dirichlet
  inequality, so every product-space Dirichlet constant survives on the
  quotient (`dirichlet_bound_restricts`).  In particular every uniform
  fiber-rate floor, the minimum fiber rate, and the Kogut--Susskind `2λ`
  floor are Dirichlet constants for the quotient generator on mean-zero
  gauge-invariant observables (`quotient_dirichlet_lower_bound`,
  `quotient_dirichlet_min_rate`, `quotient_kogutSusskind_floor`);
* a worked two-fiber instance with the star mask flipping both links, the
  mask the committed `star_masks` convention evaluates to on the `1 × 1`
  periodic torus.  Its gauge group has order two (`starMask_perm_sq`,
  `starMask_perm_ne_one`), its invariant mean-zero observables are
  eigenvectors of the generator with eigenvalue `c 0 + c 1`
  (`generator_invariant_eigen`), and the exact best quotient Dirichlet
  constant is `c 0 + c 1` (`instance_quotient_gap`); with the committed
  rates at `λ = 1` the value is `4`, strictly above the `2λ = 2` floor
  (`instance_ks_quotient_gap`).

## Convention re-derivation (recorded, not transcribed)

A `Z2` gauge transformation at a site multiplies each incident link
variable by `-1`; in the producer's bit representation multiplication by
`-1` is a bit flip, so the transformation is XOR with the site's star
mask, and composing transformations XORs their masks.  The producer's
`gauge_group_masks` builds exactly the subset-XORs of the star masks and
acts by `configs ^ mask`; `maskPerm` with `gaugeGroup` reproduces this
action, and `maskPerm_mul`, `maskPerm_zero`, `maskPerm_inv` are the
composition receipts.  The weight-symmetry hypothesis on moved links is
the gauge invariance of the product stationary law in this convention:
`prodWeight_xorMask` proves invariance from symmetry, and under the
`π = Ω²` fiber weights symmetry at a link is exactly ratio one there
(`ksWeight_symm_iff`), the equality case of the `2λ` floor.

## What is not proved here

The quotient is formalized as the gauge-invariant subspace of the product
observable space; no orbit-space carrier type is built, and no theorem is
stated on functions over a quotient type.  The two formulations agree for
a free action through averaging along orbits, and that identification is
the named residual formalization delta.  The committed receipt tori
(`L ∈ {2, 3}`) carry star-generated groups with several generators and a
stationary law `π = Ω²` that is a non-product measure over orbits with
orbit-dependent rates; neither is formalized here, and the
approximate-tensorization comparison that would control the non-product
law stays open, as do the anisotropic Wilson-to-Hamiltonian scan,
refinement and volume extension, and every continuum statement.  The
minimum-rate bound is one-sided: the instance shows the quotient constant
can sit strictly above it, and no sharpness on the quotient is claimed.
Nothing here is a mass-gap theorem, a Clay-problem step, an all-coupling
result, or evidence for OPH; no data enters and no comparison is scored.
-/

noncomputable section

variable {n : ℕ}

/-- XOR translation of a configuration by a mask: coordinate `l` is
flipped exactly when `g l = true`. -/
def xorMask (g x : Config n) : Config n := fun l => xor (g l) (x l)

theorem xorMask_involutive (g : Config n) (x : Config n) :
    xorMask g (xorMask g x) = x := by
  funext l
  simp [xorMask]

theorem xorMask_zero (x : Config n) : xorMask (fun _ => false) x = x := by
  funext l
  simp [xorMask]

theorem xorMask_xorMask (g h x : Config n) :
    xorMask g (xorMask h x) = xorMask (fun l => xor (g l) (h l)) x := by
  funext l
  simp [xorMask]

/-- The mask translation as a permutation of the configuration space.  The
translation is an involution, so it is its own inverse. -/
def maskPerm (g : Config n) : Equiv.Perm (Config n) where
  toFun := xorMask g
  invFun := xorMask g
  left_inv := xorMask_involutive g
  right_inv := xorMask_involutive g

@[simp] theorem maskPerm_apply (g x : Config n) : maskPerm g x = xorMask g x := rfl

theorem maskPerm_zero : maskPerm (fun _ => false) = (1 : Equiv.Perm (Config n)) :=
  Equiv.ext fun x => xorMask_zero x

theorem maskPerm_mul (g h : Config n) :
    maskPerm g * maskPerm h = maskPerm (fun l => xor (g l) (h l)) :=
  Equiv.ext fun x => xorMask_xorMask g h x

theorem maskPerm_inv (g : Config n) : (maskPerm g)⁻¹ = maskPerm g := rfl

/-- A mask is supported on a link set when every flipped link lies in the
set. -/
def SupportedOn (A : Set (Fin n)) (g : Config n) : Prop :=
  ∀ l, g l = true → l ∈ A

/-- The links moved by at least one mask of the generating set. -/
def movedSet (S : Set (Config n)) : Set (Fin n) :=
  {l | ∃ g ∈ S, g l = true}

theorem supportedOn_movedSet {S : Set (Config n)} {g : Config n} (hg : g ∈ S) :
    SupportedOn (movedSet S) g := fun _ hl => ⟨g, hg, hl⟩

/-- The subgroup of all mask translations supported on a fixed link set. -/
def supportedTranslations (A : Set (Fin n)) : Subgroup (Equiv.Perm (Config n)) where
  carrier := {p | ∃ g, SupportedOn A g ∧ p = maskPerm g}
  one_mem' := ⟨fun _ => false, fun _ hl => absurd hl (by simp), maskPerm_zero.symm⟩
  mul_mem' := by
    rintro p q ⟨g, hg, rfl⟩ ⟨h, hh, rfl⟩
    refine ⟨fun l => xor (g l) (h l), fun l hl => ?_, maskPerm_mul g h⟩
    cases hgl : g l
    · exact hh l (by simpa [hgl] using hl)
    · exact hg l hgl
  inv_mem' := by
    rintro p ⟨g, hg, rfl⟩
    exact ⟨g, hg, maskPerm_inv g⟩

/-- The gauge group of a generating mask set: the permutation subgroup
generated by its mask translations.  With the star masks of a periodic
torus as generators this is the committed gauge action on link
configurations. -/
def gaugeGroup (S : Set (Config n)) : Subgroup (Equiv.Perm (Config n)) :=
  Subgroup.closure (maskPerm '' S)

theorem maskPerm_mem_gaugeGroup {S : Set (Config n)} {g : Config n} (hg : g ∈ S) :
    maskPerm g ∈ gaugeGroup S :=
  Subgroup.subset_closure ⟨g, hg, rfl⟩

theorem gaugeGroup_le_supportedTranslations (S : Set (Config n)) :
    gaugeGroup S ≤ supportedTranslations (movedSet S) := by
  refine (Subgroup.closure_le _).mpr ?_
  rintro p ⟨g, hg, rfl⟩
  exact ⟨g, supportedOn_movedSet hg, rfl⟩

/-- Every element of the gauge group is a mask translation whose mask is
supported on the moved links of the generating set. -/
theorem exists_mask_of_mem_gaugeGroup {S : Set (Config n)}
    {p : Equiv.Perm (Config n)} (hp : p ∈ gaugeGroup S) :
    ∃ g, SupportedOn (movedSet S) g ∧ p = maskPerm g :=
  gaugeGroup_le_supportedTranslations S hp

/-! ## Translation on observables and equivariance of the collar terms -/

/-- Pullback of an observable along the mask translation. -/
def translate (g : Config n) (f : Obs n) : Obs n := fun x => f (xorMask g x)

@[simp] theorem translate_apply (g : Config n) (f : Obs n) (x : Config n) :
    translate g f x = f (xorMask g x) := rfl

theorem translate_sub (g : Config n) (f h : Obs n) :
    translate g (f - h) = translate g f - translate g h := rfl

theorem translate_smul (g : Config n) (a : ℝ) (f : Obs n) :
    translate g (a • f) = a • translate g f := rfl

theorem translate_sum {ι : Type*} (g : Config n) (t : Finset ι) (F : ι → Obs n) :
    translate g (∑ i ∈ t, F i) = ∑ i ∈ t, translate g (F i) := by
  funext x
  simp [translate, Finset.sum_apply]

/-- Interaction of the mask translation with a single-coordinate update:
updating before translating equals translating and then updating with the
XOR-shifted value. -/
theorem xorMask_update (g x : Config n) (l : Fin n) (b : Bool) :
    xorMask g (Function.update x l b)
      = Function.update (xorMask g x) l (xor (g l) b) := by
  funext m
  by_cases hm : m = l
  · subst hm
    simp [xorMask]
  · simp [xorMask, Function.update_of_ne hm]

/-- Equivariance of one collar conditional expectation under one mask
translation.  The hypothesis asks the fiber weights of every flipped link
to be symmetric; unflipped links need nothing. -/
theorem condExp_translate {w : Fin n → Bool → ℝ} {g : Config n} (l : Fin n)
    (hsymm : g l = true → w l false = w l true) (f : Obs n) :
    condExp w l (translate g f) = translate g (condExp w l f) := by
  funext x
  rw [translate_apply, condExp_apply, condExp_apply, translate_apply,
    translate_apply, xorMask_update, xorMask_update]
  cases hgl : g l
  · rw [Bool.false_xor, Bool.false_xor]
  · rw [Bool.true_xor, Bool.true_xor, hsymm hgl]
    simp only [Bool.not_false, Bool.not_true]
    ring

/-- Equivariance of the product generator under one mask translation whose
flipped links all carry symmetric fiber weights.  The per-fiber rates are
constants, so they need no hypothesis. -/
theorem generator_translate {w : Fin n → Bool → ℝ} {g : Config n}
    (hsymm : ∀ l, g l = true → w l false = w l true)
    (c : Fin n → ℝ) (f : Obs n) :
    generator w c (translate g f) = translate g (generator w c f) := by
  rw [generator_apply, generator_apply, translate_sum]
  refine Finset.sum_congr rfl fun l _ => ?_
  rw [condExp_translate l (hsymm l) f, translate_smul, translate_sub]

/-- Gauge invariance of the product weight under one mask translation with
symmetric weights on the flipped links. -/
theorem prodWeight_xorMask {w : Fin n → Bool → ℝ} {g : Config n}
    (hsymm : ∀ l, g l = true → w l false = w l true) (x : Config n) :
    prodWeight w (xorMask g x) = prodWeight w x := by
  unfold prodWeight
  refine Finset.prod_congr rfl fun l _ => ?_
  show w l (xor (g l) (x l)) = w l (x l)
  cases hgl : g l
  · rw [Bool.false_xor]
  · rw [Bool.true_xor]
    cases hxl : x l
    · exact (hsymm l hgl).symm
    · exact hsymm l hgl

/-! ## The invariant subspace and the descended generator -/

/-- The permutations fixing an observable, as a subgroup.  Invariance under
a generating set therefore extends to the generated subgroup. -/
def fixingSubgroup (f : Obs n) : Subgroup (Equiv.Perm (Config n)) where
  carrier := {p | ∀ x, f (p x) = f x}
  one_mem' := fun _ => rfl
  mul_mem' := by
    intro p q hp hq x
    rw [Equiv.Perm.mul_apply, hp, hq]
  inv_mem' := by
    intro p hp x
    have h := hp (p⁻¹ x)
    rw [show p (p⁻¹ x) = x from p.apply_symm_apply x] at h
    exact h.symm

/-- Gauge invariance of an observable: invariance under every element of
the gauge group of the generating mask set. -/
def GaugeInvariant (S : Set (Config n)) (f : Obs n) : Prop :=
  ∀ p ∈ gaugeGroup S, ∀ x, f (p x) = f x

/-- Invariance under the generating masks extends to the whole gauge
group. -/
theorem gaugeInvariant_of_generators {S : Set (Config n)} {f : Obs n}
    (h : ∀ g ∈ S, ∀ x, f (xorMask g x) = f x) : GaugeInvariant S f := by
  intro p hp
  refine (Subgroup.closure_le (fixingSubgroup f)).mpr ?_ hp
  rintro q ⟨g, hg, rfl⟩ x
  exact h g hg x

/-- Gauge invariance restated through the translation operator. -/
theorem gaugeInvariant_iff_translate {S : Set (Config n)} {f : Obs n} :
    GaugeInvariant S f
      ↔ ∀ g, SupportedOn (movedSet S) g → maskPerm g ∈ gaugeGroup S →
          translate g f = f := by
  constructor
  · intro hf g _ hgmem
    funext x
    exact hf (maskPerm g) hgmem x
  · intro h p hp x
    obtain ⟨g, hgsupp, rfl⟩ := exists_mask_of_mem_gaugeGroup hp
    exact congrFun (h g hgsupp hp) x

/-- The gauge-invariant observables as a submodule of the observable
space. -/
def invariantSubmodule (S : Set (Config n)) : Submodule ℝ (Obs n) where
  carrier := {f | GaugeInvariant S f}
  add_mem' := by
    intro f h hf hh p hp x
    simp only [Pi.add_apply, hf p hp x, hh p hp x]
  zero_mem' := fun _ _ _ => rfl
  smul_mem' := by
    intro a f hf p hp x
    simp only [Pi.smul_apply, hf p hp x]

theorem mem_invariantSubmodule {S : Set (Config n)} {f : Obs n} :
    f ∈ invariantSubmodule S ↔ GaugeInvariant S f := Iff.rfl

/-- The invariant subspace contains every constant observable. -/
theorem const_mem_invariantSubmodule (S : Set (Config n)) (a : ℝ) :
    (fun _ => a : Obs n) ∈ invariantSubmodule S := fun _ _ _ => rfl

/-- Descent of the product generator: with symmetric fiber weights on
every moved link, the generator maps gauge-invariant observables to
gauge-invariant observables. -/
theorem generator_mem_invariantSubmodule {w : Fin n → Bool → ℝ}
    {S : Set (Config n)}
    (hwsym : ∀ l ∈ movedSet S, w l false = w l true)
    (c : Fin n → ℝ) {f : Obs n} (hf : f ∈ invariantSubmodule S) :
    generator w c f ∈ invariantSubmodule S := by
  intro p hp x
  obtain ⟨g, hgsupp, rfl⟩ := exists_mask_of_mem_gaugeGroup hp
  have hfg : translate g f = f := by
    funext y
    exact hf (maskPerm g) hp y
  have hsymm : ∀ l, g l = true → w l false = w l true :=
    fun l hl => hwsym l (hgsupp l hl)
  have h := congrFun (generator_translate hsymm c f) x
  rw [hfg] at h
  exact h.symm

/-- The quotient generator: the restriction of the product generator to
the invariant subspace, under symmetric fiber weights on every moved
link.  Its target is the invariant subspace by
`generator_mem_invariantSubmodule`. -/
def quotientGenerator (w : Fin n → Bool → ℝ) (c : Fin n → ℝ)
    {S : Set (Config n)}
    (hwsym : ∀ l ∈ movedSet S, w l false = w l true) :
    invariantSubmodule S →ₗ[ℝ] invariantSubmodule S :=
  (generator w c).restrict fun _ hf =>
    generator_mem_invariantSubmodule hwsym c hf

@[simp] theorem quotientGenerator_coe {w : Fin n → Bool → ℝ} {c : Fin n → ℝ}
    {S : Set (Config n)}
    (hwsym : ∀ l ∈ movedSet S, w l false = w l true)
    (f : invariantSubmodule S) :
    (quotientGenerator w c hwsym f : Obs n) = generator w c (f : Obs n) := rfl

/-! ## Dirichlet lower bounds for the quotient generator -/

/-- Restriction principle: a Dirichlet constant on all mean-zero
observables is a Dirichlet constant on the mean-zero members of any
submodule.  Restriction shrinks the constraint set, so every lower bound
survives. -/
theorem dirichlet_bound_restricts {w : Fin n → Bool → ℝ} {c : Fin n → ℝ}
    {gam : ℝ}
    (h : ∀ f : Obs n, piMean w f = 0 →
      gam * statePairing (prodWeight w) f f
        ≤ statePairing (prodWeight w) f (generator w c f))
    (P : Submodule ℝ (Obs n)) :
    ∀ f ∈ P, piMean w f = 0 →
      gam * statePairing (prodWeight w) f f
        ≤ statePairing (prodWeight w) f (generator w c f) :=
  fun f _ hf => h f hf

/-- Every uniform lower bound on the fiber rates is a Dirichlet constant
for the quotient generator on mean-zero gauge-invariant observables.  The
proof is the inclusion structure: the invariant subspace embeds in the
product observable space, the pairing and the mean restrict along the
embedding, and the product-space bound applies to every member. -/
theorem quotient_dirichlet_lower_bound {w : Fin n → Bool → ℝ}
    (hw : ∀ l b, 0 < w l b) (hsum : ∀ l, w l false + w l true = 1)
    {S : Set (Config n)} (hwsym : ∀ l ∈ movedSet S, w l false = w l true)
    {c : Fin n → ℝ} (hc : ∀ l, 0 ≤ c l) {gam : ℝ} (hgam : ∀ l, gam ≤ c l)
    (f : invariantSubmodule S) (hf : piMean w (f : Obs n) = 0) :
    gam * statePairing (prodWeight w) (f : Obs n) (f : Obs n)
      ≤ statePairing (prodWeight w) (f : Obs n)
          ((quotientGenerator w c hwsym f : Obs n)) := by
  rw [quotientGenerator_coe]
  exact dirichlet_lower_bound hw hsum hc hgam hf

/-- The minimum fiber rate is a Dirichlet constant for the quotient
generator on mean-zero gauge-invariant observables (`n ≥ 1`). -/
theorem quotient_dirichlet_min_rate {w : Fin n → Bool → ℝ}
    (hne : (Finset.univ : Finset (Fin n)).Nonempty)
    (hw : ∀ l b, 0 < w l b) (hsum : ∀ l, w l false + w l true = 1)
    {S : Set (Config n)} (hwsym : ∀ l ∈ movedSet S, w l false = w l true)
    {c : Fin n → ℝ} (hc : ∀ l, 0 ≤ c l)
    (f : invariantSubmodule S) (hf : piMean w (f : Obs n) = 0) :
    (Finset.univ.inf' hne c)
        * statePairing (prodWeight w) (f : Obs n) (f : Obs n)
      ≤ statePairing (prodWeight w) (f : Obs n)
          ((quotientGenerator w c hwsym f : Obs n)) :=
  quotient_dirichlet_lower_bound hw hsum hwsym hc
    (fun l => Finset.inf'_le c (Finset.mem_univ l)) f hf

/-- Symmetry of the induced fiber weights characterizes ratio one: for
`r > 0`, `ksWeight` has equal fiber weights exactly at `r = 1`. -/
theorem ksWeight_symm_iff {r : Fin n → ℝ} (l : Fin n) (hr : 0 < r l) :
    ksWeight r l false = ksWeight r l true ↔ r l = 1 := by
  have hden : (0 : ℝ) < 1 + (r l) ^ 2 := by positivity
  unfold ksWeight
  simp only [Bool.cond_false, Bool.cond_true]
  constructor
  · intro h
    have h2 : (r l) ^ 2 = 1 := by
      field_simp at h
      linarith
    have h3 : (r l - 1) * (r l + 1) = 0 := by nlinarith
    rcases mul_eq_zero.mp h3 with h4 | h4
    · linarith
    · linarith
  · intro h
    rw [h]
    norm_num

/-- Uniform Kogut--Susskind floor on the quotient: with the committed
rates `c_l = λ (r_l + 1/r_l)` and the induced `π = Ω²` fiber weights, the
quotient generator dominates `2λ` in the Dirichlet pairing on mean-zero
gauge-invariant observables, uniformly in the ratios of the unmoved
links.  Symmetric weights pin the moved-link ratios to one, the exact
condition under which the product weight is gauge invariant and the
generator descends. -/
theorem quotient_kogutSusskind_floor {lam : ℝ} (hlam : 0 < lam)
    {r : Fin n → ℝ} (hr : ∀ l, 0 < r l)
    {S : Set (Config n)} (hrone : ∀ l ∈ movedSet S, r l = 1)
    (f : invariantSubmodule S) (hf : piMean (ksWeight r) (f : Obs n) = 0) :
    2 * lam * statePairing (prodWeight (ksWeight r)) (f : Obs n) (f : Obs n)
      ≤ statePairing (prodWeight (ksWeight r)) (f : Obs n)
          ((quotientGenerator (ksWeight r) (fun l => fiberRate lam (r l))
              (fun l hl => (ksWeight_symm_iff l (hr l)).mpr (hrone l hl))
              f : Obs n)) := by
  rw [quotientGenerator_coe]
  exact kogutSusskind_ksWeight_floor hlam hr hf

end

/-! ## Worked instance: two fibers, one star mask flipping both links -/

section Instance

noncomputable section

/-- The mask flipping both links.  This is the single star mask the
committed producer's `star_masks` evaluates to on the `1 × 1` periodic
torus, where both links are incident to the one site. -/
def gAll : Config 2 := fun _ => true

/-- The generating set of the instance: one star mask. -/
def starSet : Set (Config 2) := {gAll}

theorem gAll_mem_starSet : gAll ∈ starSet := Set.mem_singleton gAll

/-- Symmetric fiber weights, the exact condition for gauge invariance of
the product weight when every link is moved. -/
def wHalf : Fin 2 → Bool → ℝ := fun _ _ => 1 / 2

theorem wHalf_pos : ∀ (l : Fin 2) (b : Bool), 0 < wHalf l b := by
  intro l b
  norm_num [wHalf]

theorem wHalf_sum : ∀ l : Fin 2, wHalf l false + wHalf l true = 1 := by
  intro l
  norm_num [wHalf]

theorem wHalf_symm : ∀ l ∈ movedSet starSet, wHalf l false = wHalf l true :=
  fun _ _ => rfl

/-- The configuration with the two given link values. -/
def cfg (a b : Bool) : Config 2 := (piFinTwoEquiv fun _ => Bool).symm (a, b)

theorem cfg_zero (a b : Bool) : cfg a b 0 = a := rfl

theorem cfg_one (a b : Bool) : cfg a b 1 = b := rfl

theorem eq_cfg (x : Config 2) : x = cfg (x 0) (x 1) :=
  ((piFinTwoEquiv fun _ => Bool).symm_apply_apply x).symm

/-- Enumeration of the four configurations. -/
theorem sum_config_two (F : Config 2 → ℝ) :
    ∑ x : Config 2, F x
      = F (cfg false false) + F (cfg false true)
        + F (cfg true false) + F (cfg true true) := by
  rw [← Equiv.sum_comp (piFinTwoEquiv fun _ => Bool).symm F,
    Fintype.sum_prod_type]
  simp only [Fintype.sum_bool, cfg]
  ring

theorem prodWeight_wHalf (x : Config 2) : prodWeight wHalf x = 1 / 4 := by
  unfold prodWeight wHalf
  rw [Fin.prod_univ_two]
  norm_num

/-- The star translation swaps the two configurations of each gauge
orbit. -/
theorem xorMask_gAll_cfg (a b : Bool) :
    xorMask gAll (cfg a b) = cfg (!a) (!b) := by
  conv_lhs => rw [eq_cfg (xorMask gAll (cfg a b))]
  show cfg (xor (gAll 0) (cfg a b 0)) (xor (gAll 1) (cfg a b 1))
      = cfg (!a) (!b)
  rw [cfg_zero, cfg_one, show gAll 0 = true from rfl,
    show gAll 1 = true from rfl, Bool.true_xor, Bool.true_xor]

theorem invariant_flip {f : Obs 2} (hf : GaugeInvariant starSet f)
    (a b : Bool) : f (cfg (!a) (!b)) = f (cfg a b) := by
  have h := hf (maskPerm gAll) (maskPerm_mem_gaugeGroup gAll_mem_starSet)
    (cfg a b)
  rwa [maskPerm_apply, xorMask_gAll_cfg] at h

theorem update_zero_eq (x : Config 2) (b : Bool) :
    Function.update x 0 b = cfg b (x 1) := by
  rw [eq_cfg (Function.update x 0 b), Function.update_self,
    Function.update_of_ne (by decide : (1 : Fin 2) ≠ 0)]

theorem update_one_eq (x : Config 2) (b : Bool) :
    Function.update x 1 b = cfg (x 0) b := by
  rw [eq_cfg (Function.update x 1 b),
    Function.update_of_ne (by decide : (0 : Fin 2) ≠ 1),
    Function.update_self]

/-- On a gauge-invariant mean-zero observable, both orbit pair sums
vanish. -/
theorem pairSum_eq_zero {f : Obs 2} (hf : GaugeInvariant starSet f)
    (hmean : piMean wHalf f = 0) :
    f (cfg false true) + f (cfg true true) = 0 := by
  have h1 := invariant_flip hf false false
  have h2 := invariant_flip hf true false
  simp only [Bool.not_false, Bool.not_true] at h1 h2
  unfold piMean at hmean
  rw [sum_config_two (fun x => prodWeight wHalf x * f x)] at hmean
  simp only [prodWeight_wHalf] at hmean
  linarith

/-- Both collar conditional expectations annihilate every gauge-invariant
mean-zero observable of the instance. -/
theorem condExp_wHalf_eq_zero {f : Obs 2} (hf : GaugeInvariant starSet f)
    (hmean : piMean wHalf f = 0) (l : Fin 2) :
    condExp wHalf l f = 0 := by
  have h1 := invariant_flip hf false false
  have h2 := invariant_flip hf true false
  simp only [Bool.not_false, Bool.not_true] at h1 h2
  have hkey := pairSum_eq_zero hf hmean
  have hl : l = 0 ∨ l = 1 := by omega
  rcases hl with rfl | rfl
  · funext x
    rw [Pi.zero_apply, condExp_apply, update_zero_eq, update_zero_eq]
    show (1 : ℝ) / 2 * f (cfg false (x 1)) + 1 / 2 * f (cfg true (x 1)) = 0
    cases hx : x 1
    · linarith
    · linarith
  · funext x
    rw [Pi.zero_apply, condExp_apply, update_one_eq, update_one_eq]
    show (1 : ℝ) / 2 * f (cfg (x 0) false) + 1 / 2 * f (cfg (x 0) true) = 0
    cases hx : x 0
    · linarith
    · linarith

/-- The quotient generator of the instance acts as the scalar `c 0 + c 1`
on gauge-invariant mean-zero observables. -/
theorem generator_invariant_eigen (c : Fin 2 → ℝ) {f : Obs 2}
    (hf : GaugeInvariant starSet f) (hmean : piMean wHalf f = 0) :
    generator wHalf c f = (c 0 + c 1) • f := by
  rw [generator_apply, Fin.sum_univ_two,
    condExp_wHalf_eq_zero hf hmean 0, condExp_wHalf_eq_zero hf hmean 1,
    sub_zero, ← add_smul]

/-- Exact Dirichlet identity of the instance on gauge-invariant mean-zero
observables. -/
theorem instance_dirichlet_identity (c : Fin 2 → ℝ) {f : Obs 2}
    (hf : GaugeInvariant starSet f) (hmean : piMean wHalf f = 0) :
    statePairing (prodWeight wHalf) f (generator wHalf c f)
      = (c 0 + c 1) * statePairing (prodWeight wHalf) f f := by
  rw [generator_invariant_eigen c hf hmean, statePairing_smul_right]

/-- Gauge-invariant mean-zero witness: `+1` on the equal-links orbit,
`-1` on the unequal-links orbit. -/
def diagWitness : Obs 2 := fun x => if x 0 = x 1 then 1 else -1

theorem diagWitness_cfg (a b : Bool) :
    diagWitness (cfg a b) = if a = b then 1 else -1 := by
  unfold diagWitness
  rw [cfg_zero, cfg_one]

theorem diagWitness_invariant : GaugeInvariant starSet diagWitness := by
  refine gaugeInvariant_of_generators ?_
  intro g hg x
  rw [Set.mem_singleton_iff.mp hg, eq_cfg x, xorMask_gAll_cfg,
    diagWitness_cfg, diagWitness_cfg]
  cases hx0 : x 0 <;> cases hx1 : x 1 <;> simp

theorem diagWitness_meanZero : piMean wHalf diagWitness = 0 := by
  unfold piMean
  rw [sum_config_two (fun x => prodWeight wHalf x * diagWitness x)]
  simp only [prodWeight_wHalf, diagWitness_cfg]
  norm_num

theorem diagWitness_pairing :
    statePairing (prodWeight wHalf) diagWitness diagWitness = 1 := by
  unfold statePairing
  rw [sum_config_two
    (fun x => prodWeight wHalf x * diagWitness x * diagWitness x)]
  simp only [prodWeight_wHalf, diagWitness_cfg]
  norm_num

/-- Worked instance, exact quotient gap: with the both-links star mask and
symmetric weights, the best Dirichlet constant of the generator on
mean-zero gauge-invariant observables is exactly `c 0 + c 1`, the full
level-set eigenvalue.  The minimum fiber rate stays a valid lower bound
and is not sharp here whenever both rates are positive. -/
theorem instance_quotient_gap (c : Fin 2 → ℝ) :
    IsGreatest
      {gam : ℝ | ∀ f : Obs 2, GaugeInvariant starSet f →
        piMean wHalf f = 0 →
        gam * statePairing (prodWeight wHalf) f f
          ≤ statePairing (prodWeight wHalf) f (generator wHalf c f)}
      (c 0 + c 1) := by
  constructor
  · intro f hf hmean
    rw [instance_dirichlet_identity c hf hmean]
  · intro gam hgam
    have h := hgam diagWitness diagWitness_invariant diagWitness_meanZero
    rw [instance_dirichlet_identity c diagWitness_invariant
      diagWitness_meanZero, diagWitness_pairing, mul_one, mul_one] at h
    exact h

/-- At the ratio forced by symmetric weights the committed rate meets the
floor: `λ (1 + 1/1) = 2λ`, evaluated at `λ = 1`. -/
theorem instance_ks_rate : fiberRate 1 1 = 2 := by
  unfold fiberRate
  norm_num

/-- Exact quotient gap of the instance with the committed rates at
`λ = 1`: the value is `4`, twice the `2λ` floor, so the minimum-rate
lower bound holds strictly on this quotient. -/
theorem instance_ks_quotient_gap :
    IsGreatest
      {gam : ℝ | ∀ f : Obs 2, GaugeInvariant starSet f →
        piMean wHalf f = 0 →
        gam * statePairing (prodWeight wHalf) f f
          ≤ statePairing (prodWeight wHalf) f
              (generator wHalf (fun _ => fiberRate 1 1) f)}
      4 := by
  have h4 : (fun _ : Fin 2 => fiberRate 1 1) 0
      + (fun _ : Fin 2 => fiberRate 1 1) 1 = 4 := by
    show fiberRate 1 1 + fiberRate 1 1 = 4
    rw [instance_ks_rate]
    norm_num
  have h := instance_quotient_gap (fun _ => fiberRate 1 1)
  rwa [h4] at h

theorem instance_gap_strictly_above_floor : (2 : ℝ) * 1 < 4 := by norm_num

/-- Order receipt: the star translation squares to the identity. -/
theorem starMask_perm_sq :
    maskPerm gAll * maskPerm gAll = (1 : Equiv.Perm (Config 2)) := by
  rw [maskPerm_mul]
  have h : (fun l : Fin 2 => xor (gAll l) (gAll l))
      = (fun _ : Fin 2 => false) := by
    funext l
    simp
  rw [h, maskPerm_zero]

/-- Faithfulness receipt: the star translation is a nonidentity
permutation, so the instance gauge group has order two. -/
theorem starMask_perm_ne_one :
    maskPerm gAll ≠ (1 : Equiv.Perm (Config 2)) := by
  intro h
  have h1 : xorMask gAll (cfg false false) = cfg false false := by
    have h2 := congrArg
      (fun p : Equiv.Perm (Config 2) => p (cfg false false)) h
    simpa using h2
  have h3 := congrFun h1 0
  rw [cfg_zero, show xorMask gAll (cfg false false) 0
      = xor (gAll 0) (cfg false false 0) from rfl, cfg_zero,
    show gAll 0 = true from rfl, Bool.true_xor, Bool.not_false] at h3
  exact Bool.noConfusion h3

end

end Instance

end OPH.GaugeOrbitQuotientGap

/- Axiom audit: propext, Classical.choice, and Quot.sound only. -/

#print axioms OPH.GaugeOrbitQuotientGap.maskPerm_mul
#print axioms OPH.GaugeOrbitQuotientGap.exists_mask_of_mem_gaugeGroup
#print axioms OPH.GaugeOrbitQuotientGap.gaugeInvariant_of_generators
#print axioms OPH.GaugeOrbitQuotientGap.condExp_translate
#print axioms OPH.GaugeOrbitQuotientGap.generator_translate
#print axioms OPH.GaugeOrbitQuotientGap.prodWeight_xorMask
#print axioms OPH.GaugeOrbitQuotientGap.const_mem_invariantSubmodule
#print axioms OPH.GaugeOrbitQuotientGap.generator_mem_invariantSubmodule
#print axioms OPH.GaugeOrbitQuotientGap.dirichlet_bound_restricts
#print axioms OPH.GaugeOrbitQuotientGap.quotient_dirichlet_lower_bound
#print axioms OPH.GaugeOrbitQuotientGap.quotient_dirichlet_min_rate
#print axioms OPH.GaugeOrbitQuotientGap.ksWeight_symm_iff
#print axioms OPH.GaugeOrbitQuotientGap.quotient_kogutSusskind_floor
#print axioms OPH.GaugeOrbitQuotientGap.pairSum_eq_zero
#print axioms OPH.GaugeOrbitQuotientGap.condExp_wHalf_eq_zero
#print axioms OPH.GaugeOrbitQuotientGap.generator_invariant_eigen
#print axioms OPH.GaugeOrbitQuotientGap.instance_dirichlet_identity
#print axioms OPH.GaugeOrbitQuotientGap.diagWitness_invariant
#print axioms OPH.GaugeOrbitQuotientGap.diagWitness_meanZero
#print axioms OPH.GaugeOrbitQuotientGap.diagWitness_pairing
#print axioms OPH.GaugeOrbitQuotientGap.instance_quotient_gap
#print axioms OPH.GaugeOrbitQuotientGap.instance_ks_rate
#print axioms OPH.GaugeOrbitQuotientGap.instance_ks_quotient_gap
#print axioms OPH.GaugeOrbitQuotientGap.starMask_perm_sq
#print axioms OPH.GaugeOrbitQuotientGap.starMask_perm_ne_one
