import Mathlib

/-!
# Finite path holonomy and character phases

This issue-scoped module supplies the algebraic B6 packet.  An oriented edge
label in a group defines transport along a typed finite path.  Reversing a
path inverts transport, so the transport ratio of two paths with common
endpoints is exactly the holonomy of the resulting closed loop.  A
one-dimensional unitary character sends that identity to a relative phase.

Local vertex recharting changes an open-path transport by its two endpoint
factors and hence changes based holonomy by conjugation.  For an abelian
structure group the holonomy itself is invariant.  A four-vertex control has
trivial defect on every declared local triangular face but a nontrivial
unfilled loop.  Finally, every character of `Multiplicative (ZMod n)` takes
values among the `n`th roots of unity.

The edge labels, local faces, character, and cyclic sector are supplied finite
data.  Nothing here constructs them from observer-patch source records or
identifies a character phase with a laboratory interference fringe, gauge
connection, spacetime loop, clock, charge, or physical flux.
-/

namespace OPH.HolonomyInterference

universe uV uG

/-! ## Typed finite paths -/

/-- A path is generated by successively appending a vertex.  Its indices keep
the initial and final vertices in the type.  Edges are allowed between any two
vertices; a physical or combinatorial graph may impose its own admissibility
predicate separately. -/
inductive Path (V : Type uV) : V → V → Type uV where
  | nil (v : V) : Path V v v
  | snoc {a b : V} (p : Path V a b) (c : V) : Path V a c

namespace Path

variable {V : Type uV}

/-- Concatenation of endpoint-compatible typed paths. -/
def append {a b c : V} (p : Path V a b) : Path V b c → Path V a c
  | .nil _ => p
  | .snoc q d => .snoc (append p q) d

@[simp]
theorem append_nil {a b : V} (p : Path V a b) :
    append p (.nil b) = p := rfl

@[simp]
theorem append_snoc {a b c d : V} (p : Path V a b)
    (q : Path V b c) :
    append p (.snoc q d) = .snoc (append p q) d := rfl

/-- A one-edge path. -/
def edge (a b : V) : Path V a b := .snoc (.nil a) b

/-- Prepend one oriented edge to a typed path. -/
def prepend (x : V) {a b : V} : Path V a b → Path V x b
  | .nil _ => edge x a
  | .snoc p c => .snoc (prepend x p) c

/-- Reverse a typed path, reversing the order and orientation of its edges. -/
def reverse {a : V} : {b : V} → Path V a b → Path V b a
  | _, .nil _ => .nil a
  | _, .snoc p c => prepend c (reverse p)

@[simp]
theorem reverse_nil (a : V) : reverse (.nil a) = .nil a := rfl

/-- Close two paths with the same endpoints by following the first and then
the reverse of the second. -/
def closeRatio {a b : V} (p q : Path V a b) : Path V a a :=
  append p (reverse q)

end Path

/-! ## Transport and closed-loop ratios -/

section Transport

variable {V : Type uV} {G : Type uG} [Group G]

/-- Ordered transport along a typed finite path. -/
def transport (edgeLabel : V → V → G) {a b : V} : Path V a b → G
  | .nil _ => 1
  | @Path.snoc _ _ b p c => transport edgeLabel p * edgeLabel b c

@[simp]
theorem transport_nil (edgeLabel : V → V → G) (a : V) :
    transport edgeLabel (.nil a) = 1 := rfl

@[simp]
theorem transport_snoc (edgeLabel : V → V → G)
    {a b : V} (p : Path V a b) (c : V) :
    transport edgeLabel (.snoc p c) =
      transport edgeLabel p * edgeLabel b c := rfl

theorem transport_append (edgeLabel : V → V → G)
    {a b c : V} (p : Path V a b) (q : Path V b c) :
    transport edgeLabel (Path.append p q) =
      transport edgeLabel p * transport edgeLabel q := by
  induction q with
  | nil => simp
  | snoc q d ih =>
      simp only [Path.append_snoc, transport_snoc, ih]
      rw [mul_assoc]

theorem transport_prepend (edgeLabel : V → V → G)
    (x : V) {a b : V} (p : Path V a b) :
    transport edgeLabel (Path.prepend x p) =
      edgeLabel x a * transport edgeLabel p := by
  induction p with
  | nil => simp [Path.prepend, Path.edge]
  | snoc p c ih =>
      simp only [Path.prepend, transport_snoc, ih]
      rw [mul_assoc]

/-- Edge reversal is represented by group inverse. -/
def ReversalCompatible (edgeLabel : V → V → G) : Prop :=
  ∀ a b, edgeLabel b a = (edgeLabel a b)⁻¹

theorem transport_reverse (edgeLabel : V → V → G)
    (hrev : ReversalCompatible edgeLabel)
    {a b : V} (p : Path V a b) :
    transport edgeLabel (Path.reverse p) =
      (transport edgeLabel p)⁻¹ := by
  induction p with
  | nil => simp
  | @snoc b p c ih =>
      rw [Path.reverse, transport_prepend, ih, hrev b c]
      simp

/-- Holonomy is simply transport around a typed closed loop. -/
def holonomy (edgeLabel : V → V → G) {a : V}
    (loop : Path V a a) : G :=
  transport edgeLabel loop

/-- The path-transport ratio is the holonomy of the closed loop obtained by
following `p` and returning along `q`.  The displayed multiplication order is
the noncommutative convention used throughout this file. -/
theorem transportRatio_eq_closedLoopHolonomy
    (edgeLabel : V → V → G)
    (hrev : ReversalCompatible edgeLabel)
    {a b : V} (p q : Path V a b) :
    transport edgeLabel p * (transport edgeLabel q)⁻¹ =
      holonomy edgeLabel (Path.closeRatio p q) := by
  simp [holonomy, Path.closeRatio, transport_append,
    transport_reverse edgeLabel hrev q]

end Transport

/-! ## One-dimensional character phases -/

section Character

variable {V : Type uV} {G : Type uG} [Group G]

/-- A one-dimensional unitary character.  Its values lie in the complex unit
circle by type, so no separate modulus-one premise is hidden. -/
abbrev UnitaryCharacter (G : Type uG) [Group G] := G →* Circle

/-- Character phase accumulated along a path. -/
noncomputable def characterPhase (chi : UnitaryCharacter G)
    (edgeLabel : V → V → G) {a b : V} (p : Path V a b) : Circle :=
  chi (transport edgeLabel p)

/-- Applying a one-dimensional character turns the transport-ratio identity
into an exact relative-phase identity. -/
theorem relativeCharacterPhase_eq_closedLoopPhase
    (chi : UnitaryCharacter G)
    (edgeLabel : V → V → G)
    (hrev : ReversalCompatible edgeLabel)
    {a b : V} (p q : Path V a b) :
    characterPhase chi edgeLabel p * (characterPhase chi edgeLabel q)⁻¹ =
      characterPhase chi edgeLabel (Path.closeRatio p q) := by
  rw [characterPhase, characterPhase, characterPhase]
  rw [← map_inv, ← map_mul]
  congr 1
  exact transportRatio_eq_closedLoopHolonomy edgeLabel hrev p q

end Character

/-! ## Recharting and the finite Cech-sector invariant -/

section Rechart

variable {V : Type uV} {G : Type uG} [Group G]

/-- Local change of vertex chart. -/
def rechart (gauge : V → G) (edgeLabel : V → V → G)
    (a b : V) : G :=
  (gauge a)⁻¹ * edgeLabel a b * gauge b

/-- Rechart factors telescope, leaving only the two endpoints. -/
theorem transport_rechart (gauge : V → G)
    (edgeLabel : V → V → G)
    {a b : V} (p : Path V a b) :
    transport (rechart gauge edgeLabel) p =
      (gauge a)⁻¹ * transport edgeLabel p * gauge b := by
  induction p with
  | nil => simp
  | snoc p c ih =>
      simp only [transport_snoc, ih, rechart]
      group

/-- In a general group, a local rechart changes based loop holonomy only by
conjugation at the basepoint. -/
theorem holonomy_rechart_conjugate (gauge : V → G)
    (edgeLabel : V → V → G)
    {a : V} (loop : Path V a a) :
    holonomy (rechart gauge edgeLabel) loop =
      (gauge a)⁻¹ * holonomy edgeLabel loop * gauge a := by
  exact transport_rechart gauge edgeLabel loop

/-- For an abelian structure group the loop holonomy itself, rather than only
its conjugacy class, is invariant under every local rechart/coboundary. -/
theorem holonomy_rechart_invariant
    {A : Type uG} [CommGroup A]
    (gauge : V → A) (edgeLabel : V → V → A)
    {a : V} (loop : Path V a a) :
    holonomy (rechart gauge edgeLabel) loop = holonomy edgeLabel loop := by
  rw [holonomy_rechart_conjugate]
  simp [mul_comm]

/-- Every one-dimensional character gives a rechart-invariant closed-loop
phase even when the structure group itself is noncommutative.  The character
annihilates the endpoint conjugation; this is the precise gauge-invariant
quantity used by the finite interference theorem below. -/
theorem characterPhase_rechart_invariant
    (chi : UnitaryCharacter G)
    (gauge : V → G) (edgeLabel : V → V → G)
    {a : V} (loop : Path V a a) :
    characterPhase chi (rechart gauge edgeLabel) loop =
      characterPhase chi edgeLabel loop := by
  unfold characterPhase
  rw [transport_rechart]
  simp [map_mul, mul_comm]

end Rechart

/-! ## Explicit local-flat/global-holonomy control -/

inductive FourVertex where
  | v0 | v1 | v2 | v3
  deriving DecidableEq, Fintype

namespace FourVertexControl

/-- A four-vertex connection with one nontrivial oriented edge. -/
noncomputable def connection (z : Circle) (a b : FourVertex) : Circle :=
  if a = FourVertex.v2 ∧ b = FourVertex.v3 then z
  else if a = FourVertex.v3 ∧ b = FourVertex.v2 then z⁻¹
  else 1

theorem connection_reversalCompatible (z : Circle) :
    ReversalCompatible (connection z) := by
  intro a b
  cases a <;> cases b <;> simp [connection]

/-- Two declared local triangular faces.  Neither fills the global loop that
uses the distinguished `v2–v3` edge. -/
def localTriangle : Bool → Path FourVertex FourVertex.v0 FourVertex.v0
  | false => .snoc (.snoc (.snoc (.nil FourVertex.v0)
      FourVertex.v1) FourVertex.v2) FourVertex.v0
  | true => .snoc (.snoc (.snoc (.nil FourVertex.v0)
      FourVertex.v1) FourVertex.v3) FourVertex.v0

/-- Every declared local face has trivial triangle defect. -/
theorem localTriangle_holonomy_eq_one (z : Circle) (f : Bool) :
    holonomy (connection z) (localTriangle f) = 1 := by
  cases f <;> simp [holonomy, localTriangle, connection]

/-- A separate closed loop that crosses the distinguished edge. -/
def globalLoop : Path FourVertex FourVertex.v0 FourVertex.v0 :=
  .snoc (.snoc (.snoc (.nil FourVertex.v0)
    FourVertex.v2) FourVertex.v3) FourVertex.v0

theorem globalLoop_holonomy (z : Circle) :
    holonomy (connection z) globalLoop = z := by
  simp [holonomy, globalLoop, connection]

/-- The long arm crosses the distinguished edge. -/
def longPath : Path FourVertex FourVertex.v0 FourVertex.v3 :=
  .snoc (.snoc (.nil FourVertex.v0) FourVertex.v2) FourVertex.v3

/-- The reference arm joins the same endpoints directly. -/
def referencePath : Path FourVertex FourVertex.v0 FourVertex.v3 :=
  .snoc (.nil FourVertex.v0) FourVertex.v3

@[simp]
theorem closeRatio_long_reference :
    Path.closeRatio longPath referencePath = globalLoop := rfl

/-- Explicit finite Aharonov--Bohm algebra: two arms have relative character
phase `z`, although every declared local triangular face is flat.  This is an
algebraic interference phase, not yet a laboratory-fringe attachment. -/
theorem long_reference_relativeCharacterPhase (z : Circle) :
    characterPhase (MonoidHom.id Circle) (connection z) longPath *
        (characterPhase (MonoidHom.id Circle)
          (connection z) referencePath)⁻¹ = z := by
  rw [relativeCharacterPhase_eq_closedLoopPhase
    (MonoidHom.id Circle) (connection z)
      (connection_reversalCompatible z) longPath referencePath]
  rw [closeRatio_long_reference]
  change holonomy (connection z) globalLoop = z
  exact globalLoop_holonomy z

/-- Finite explicit control: local triangular flatness does not force global
loop triviality when the declared faces do not fill that loop. -/
theorem exists_localTriangleFlat_globalHolonomy_nontrivial :
    ∃ edgeLabel : FourVertex → FourVertex → Circle,
      ReversalCompatible edgeLabel ∧
      (∀ f : Bool, holonomy edgeLabel (localTriangle f) = 1) ∧
      holonomy edgeLabel globalLoop ≠ 1 := by
  refine ⟨connection (Circle.exp Real.pi),
    connection_reversalCompatible _, ?_, ?_⟩
  · exact localTriangle_holonomy_eq_one _
  · rw [globalLoop_holonomy]
    exact Circle.exp_pi_ne_one

/-- The identity character detects the nontrivial global relative phase in
the same finite control. -/
theorem identityCharacter_detects_globalPhase :
    characterPhase (MonoidHom.id Circle)
      (connection (Circle.exp Real.pi)) globalLoop ≠ 1 := by
  change holonomy (connection (Circle.exp Real.pi)) globalLoop ≠ 1
  rw [globalLoop_holonomy]
  exact Circle.exp_pi_ne_one

/-- One witness packages local flatness and a nontrivial two-arm relative
phase together. -/
theorem exists_localTriangleFlat_relativeCharacterPhase_nontrivial :
    ∃ edgeLabel : FourVertex → FourVertex → Circle,
      ∃ chi : UnitaryCharacter Circle,
        ReversalCompatible edgeLabel ∧
        (∀ f : Bool, holonomy edgeLabel (localTriangle f) = 1) ∧
        characterPhase chi edgeLabel longPath *
            (characterPhase chi edgeLabel referencePath)⁻¹ ≠ 1 := by
  refine ⟨connection (Circle.exp Real.pi), MonoidHom.id Circle,
    connection_reversalCompatible _, ?_, ?_⟩
  · exact localTriangle_holonomy_eq_one _
  · rw [long_reference_relativeCharacterPhase]
    exact Circle.exp_pi_ne_one

end FourVertexControl

/-! ## Cyclic-sector phase quantization -/

section Cyclic

/-- Every one-dimensional character of the supplied cyclic sector
`Multiplicative (ZMod n)` has `n`th-root values.  `NeZero n` excludes the
degenerate modulus-zero convention; no claim is made that OPH selects `n`, a
character, or a physical charge sector. -/
theorem zmodCharacter_phase_pow_order
    (n : ℕ) [NeZero n]
    (chi : UnitaryCharacter (Multiplicative (ZMod n)))
    (k : ZMod n) :
    (chi (Multiplicative.ofAdd k)) ^ n = 1 := by
  have hk : n • k = 0 := by
    rw [nsmul_eq_mul]
    simp
  have hp : (Multiplicative.ofAdd k) ^ n = 1 := by
    change Multiplicative.ofAdd (n • k) = 1
    rw [hk]
    rfl
  rw [← map_pow, hp, map_one]

/-- Quantization persists after a supplied cyclic-sector homomorphism into an
arbitrary group.  In a center application `sector` is the supplied center
embedding; neither centrality nor source selection is inferred here. -/
theorem cyclicSectorCharacter_phase_pow_order
    {G : Type uG} [Group G]
    (n : ℕ) [NeZero n]
    (sector : Multiplicative (ZMod n) →* G)
    (chi : UnitaryCharacter G)
    (k : ZMod n) :
    (chi (sector (Multiplicative.ofAdd k))) ^ n = 1 := by
  exact zmodCharacter_phase_pow_order n (chi.comp sector) k

/-- A closed loop has an `n`th-root character phase whenever its supplied
holonomy is certified to lie in the image of a supplied cyclic sector. -/
theorem loopCharacterPhase_pow_order_of_cyclicHolonomy
    {G : Type uG} [Group G]
    (n : ℕ) [NeZero n]
    {V : Type uV}
    (sector : Multiplicative (ZMod n) →* G)
    (chi : UnitaryCharacter G)
    (edgeLabel : V → V → G)
    {a : V} (loop : Path V a a) (k : ZMod n)
    (hsector :
      transport edgeLabel loop = sector (Multiplicative.ofAdd k)) :
    (characterPhase chi edgeLabel loop) ^ n = 1 := by
  unfold characterPhase
  rw [hsector]
  exact cyclicSectorCharacter_phase_pow_order n sector chi k

/-- The same quantization statement for the holonomy of any supplied closed
path whose edge labels take values in the cyclic sector. -/
theorem cyclicLoopPhase_pow_order
    (n : ℕ) [NeZero n]
    {V : Type uV}
    (chi : UnitaryCharacter (Multiplicative (ZMod n)))
    (edgeLabel : V → V → Multiplicative (ZMod n))
    {a : V} (loop : Path V a a) :
    (characterPhase chi edgeLabel loop) ^ n = 1 := by
  exact zmodCharacter_phase_pow_order n chi
    (Multiplicative.toAdd (transport edgeLabel loop))

end Cyclic

#print axioms OPH.HolonomyInterference.transportRatio_eq_closedLoopHolonomy
#print axioms OPH.HolonomyInterference.relativeCharacterPhase_eq_closedLoopPhase
#print axioms OPH.HolonomyInterference.holonomy_rechart_conjugate
#print axioms OPH.HolonomyInterference.holonomy_rechart_invariant
#print axioms OPH.HolonomyInterference.characterPhase_rechart_invariant
#print axioms OPH.HolonomyInterference.FourVertexControl.exists_localTriangleFlat_globalHolonomy_nontrivial
#print axioms OPH.HolonomyInterference.FourVertexControl.long_reference_relativeCharacterPhase
#print axioms OPH.HolonomyInterference.FourVertexControl.exists_localTriangleFlat_relativeCharacterPhase_nontrivial
#print axioms OPH.HolonomyInterference.zmodCharacter_phase_pow_order
#print axioms OPH.HolonomyInterference.cyclicSectorCharacter_phase_pow_order
#print axioms OPH.HolonomyInterference.loopCharacterPhase_pow_order_of_cyclicHolonomy
#print axioms OPH.HolonomyInterference.cyclicLoopPhase_pow_order

end OPH.HolonomyInterference
