import Compact12
import S2DesignSignature
import TopThreeKernelFix
import UnitSplit12
import Z6Exact
import A2HolonomyBridge
import HolonomyInterference
import A5PrimitivePortPrediction
import A5OrbitRaySeparation
import DiscreteRefinement
import LabeledEventReadout
import BaryonDimensionSix
import BipoSHInverseBoundary
import BipoSHFrameInvariant
import VolumeReadoutBridge
import PrimitivePortTranslationBridge
import PrimitivePortScaleBoundary
import PrimitivePortMetricAttachment
import PrimitivePortOperatorSelectionBoundary
import KineticFamilyCancellation
import ElectroweakPoleScaleQuotient
import PrimitivePortDualMeasure
import PrimitiveHopSelection
import PrimitivePortFrameQuotient
import PortGramRepairBand
import PortGramRepairCovariance
import PortGramA5Isometry
import RepairWordCarrierReadout
import SeamCurrentCarrierQuotient
import RegionalContinuity
import DiscreteGauss
import SeamCurrentEdge30Moment
import SeamCurrentEdge30Remainder
import SeamCurrentHomogeneousAction
import SeamCurrentDirichletGenerator
import SeamCurrentAuxiliaryOscillatorLift
import SeamCurrentFreePhotonLift
import ModalMaxwellFactorizationBoundary
import SeamCurrentPhysicalMetricAttachment
import SeamCurrentPhotonLeptonThreshold
import CarrierFrequencySpeed
import SeamMaxwellContinuum
import NeutralPairCoupledAction
import NeutralPairJointStationaryWitness
import CurlStoneClockBridge
import GaugeKineticInvariantForms
import OrientedFaceBracketSelector
import ExteriorComponentBridge
import QuantumMatterIntegration
import B10EdgeCenterAction
import B10QuantumLimitations

/-!
# OPH screen arithmetic umbrella

Root module for the independently configured `OPHScreen` Lean library. Each
import retains its own stated scope boundary; this file adds no theorem or
physical identification.
-/
