import Compact12
import S2DesignSignature
import TopThreeKernelFix
import UnitSplit12
import Z6Exact
import A2HolonomyBridge
import A5PrimitivePortPrediction
import A5OrbitRaySeparation
import DiscreteRefinement
import BaryonDimensionSix
import BipoSHInverseBoundary
import BipoSHFrameInvariant
import VolumeReadoutBridge
import PrimitivePortTranslationBridge
import PrimitivePortScaleBoundary
import PrimitivePortMetricAttachment
import PrimitivePortOperatorSelectionBoundary
import KineticFamilyCancellation
import PrimitivePortDualMeasure
import PrimitiveHopSelection
import PrimitivePortFrameQuotient
import PortGramRepairBand
import PortGramRepairCovariance
import PortGramA5Isometry
import RepairWordCarrierReadout
import SeamCurrentCarrierQuotient
import SeamCurrentEdge30Moment

/-!
# OPH screen arithmetic umbrella

Root module for the independently configured `OPHScreen` Lean library. Each
import retains its own stated scope boundary; this file adds no theorem or
physical identification.
-/
