import Mathlib
import EqualStateWeights
import PortFrameGram
import PrimitivePortTranslationBridge

open scoped BigOperators

namespace OPH.PrimitivePortOperatorSelectionBoundary

/-!
# Selection boundary for the primitive-port scalar operator

This file composes the exact A3 equal-state-weight theorem with the
conditional continuous-three-space translation adapter.  If a scalar
first-hop action is separately attached to the A3 port state by using those
state weights as its reciprocal hop weights, A3 forces that action to be the
equal-weight primitive-port operator.

The attachment is a visible premise.  A1 supplies twelve primitive ports,
A2 supplies natural internal implementation of proper carrier rechartings,
and A3 fixes the normalized state weights.  None of those statements equates
a state probability with a kinetic coefficient, identifies a port with a
spatial translation, chooses a direct first-hop law, or excludes multi-range
terms generated by repeated hops.  Once the complete direct first-hop orbit
and its antipodal spatial frame are admitted, reciprocal pairing follows and
does not require a further coefficient choice.

The second half gives an exact normalized two-range family.  Every member is
an equal-direction-weight, reciprocal, carrier-covariant scalar symbol on the
same declared continuous space.  Its quadratic Taylor coefficient is one,
while its quartic coefficient varies.  This proves why first-hop completeness
or an equivalent source-selection theorem remains necessary even after equal
state weights and continuum normalization are available.
-/

open OPH.PrimitivePortTranslationBridge

/-- The A1-derived antipode as an explicit port permutation. -/
def portAntipodeEquiv : Equiv.Perm (Fin 12) where
  toFun := OPH.PortFrameGram.antipode
  invFun := OPH.PortFrameGram.antipode
  left_inv := OPH.PortFrameGram.antipode_involutive
  right_inv := OPH.PortFrameGram.antipode_involutive

/-- A declared spatial frame realizes the A1-derived antipode by vector
negation.  This is attained by the conditional source adapter; A1 incidence
alone has no Euclidean coordinates. -/
def AntipodalSpatialFrame (u : Fin 12 → Vec3) : Prop :=
  ∀ i, u (portAntipodeEquiv i) = -(u i)

/-! ## What A3 closes under a state-to-hop attachment -/

/-- Reciprocal first-hop operator whose directional coefficients are the
declared port-state weights.  The prefactor is chosen so uniform normalized
weights reproduce `primitivePortOperator`.  This definition is an attachment
model, not an A1--A3 consequence. -/
noncomputable def stateWeightedFirstHopOperator
    (a : ℝ) (u : Fin 12 → Vec3) (w : Fin 12 → ℝ)
    (f : Vec3 → ℂ) : Vec3 → ℂ :=
  fun x => (6 / a ^ 2 : ℂ) *
    ∑ i : Fin 12, (w i : ℂ) * pairedDifference (a • u i) f x

/-- Simultaneous recharting of the port frame and its state weights leaves the
attached operator unchanged.  This is the relabeling naturality available
from A2; it does not choose the attachment itself. -/
theorem stateWeightedFirstHopOperator_reindex
    (a : ℝ) (u : Fin 12 → Vec3) (w : Fin 12 → ℝ)
    (g : Equiv.Perm (Fin 12)) :
    stateWeightedFirstHopOperator a (fun i => u (g i)) (fun i => w (g i)) =
      stateWeightedFirstHopOperator a u w := by
  funext f x
  unfold stateWeightedFirstHopOperator
  congr 1
  exact g.bijective.sum_comp
    (fun i : Fin 12 =>
      (w i : ℂ) * pairedDifference (a • u i) f x)

/-! ## Reciprocity from a complete directed antipodal orbit -/

/-- One directed translation difference. -/
noncomputable def directedDifference
    (v : Vec3) (f : Vec3 → ℂ) : Vec3 → ℂ :=
  fun x => f x - f (x + v)

/-- Direct complete-port first-hop action weighted by the A3 port state.  No
inverse average is inserted in this definition. -/
noncomputable def stateWeightedDirectedFirstHopOperator
    (a : ℝ) (u : Fin 12 → Vec3) (w : Fin 12 → ℝ)
    (f : Vec3 → ℂ) : Vec3 → ℂ :=
  fun x => (6 / a ^ 2 : ℂ) *
    ∑ i : Fin 12, (w i : ℂ) * directedDifference (a • u i) f x

/-- On an antipodal spatial frame, summing every directed primitive hop is
exactly the same operation as summing the reciprocal paired differences.
Reciprocity follows from complete antipodal support rather than an inserted
inverse average. -/
theorem directedDifference_sum_eq_pairedDifference_sum
    (a : ℝ) (u : Fin 12 → Vec3) (hanti : AntipodalSpatialFrame u)
    (f : Vec3 → ℂ) (x : Vec3) :
    (∑ i : Fin 12, directedDifference (a • u i) f x) =
      ∑ i : Fin 12, pairedDifference (a • u i) f x := by
  let d : Fin 12 → ℂ :=
    fun i => directedDifference (a • u i) f x
  let p : Fin 12 → ℂ :=
    fun i => pairedDifference (a • u i) f x
  have hreindex :
      (∑ i : Fin 12, d (portAntipodeEquiv i)) = ∑ i : Fin 12, d i :=
    portAntipodeEquiv.bijective.sum_comp d
  have hpair : ∀ i, d i + d (portAntipodeEquiv i) = 2 * p i := by
    intro i
    unfold d p directedDifference pairedDifference
    rw [hanti]
    rw [smul_neg]
    rw [show x + -(a • u i) = x - a • u i by simp [sub_eq_add_neg]]
    ring
  change (∑ i : Fin 12, d i) = ∑ i : Fin 12, p i
  calc
    (∑ i : Fin 12, d i) =
        ((∑ i : Fin 12, d i) + ∑ i : Fin 12, d i) / 2 := by ring
    _ = ((∑ i : Fin 12, d i) +
        ∑ i : Fin 12, d (portAntipodeEquiv i)) / 2 := by rw [hreindex]
    _ = (∑ i : Fin 12, (d i + d (portAntipodeEquiv i))) / 2 := by
      rw [Finset.sum_add_distrib]
    _ = (∑ i : Fin 12, 2 * p i) / 2 := by
      congr 1
      exact Finset.sum_congr rfl fun i _ => hpair i
    _ = ∑ i : Fin 12, p i := by
      rw [← Finset.mul_sum]
      ring

/-- Equal state weights and complete antipodal directed support recover the
same primitive reciprocal operator without assuming inverse pairing as an
independent coefficient choice. -/
theorem stateWeightedDirectedFirstHopOperator_of_uniform
    (a : ℝ) (u : Fin 12 → Vec3) (w : Fin 12 → ℝ)
    (hanti : AntipodalSpatialFrame u)
    (huniform : ∀ i, w i = 1 / 12) :
    stateWeightedDirectedFirstHopOperator a u w =
      primitivePortOperator a u := by
  funext f x
  unfold stateWeightedDirectedFirstHopOperator primitivePortOperator
  simp_rw [huniform]
  push_cast
  rw [← Finset.mul_sum]
  rw [directedDifference_sum_eq_pairedDifference_sum a u hanti f x]
  ring

/-- Equal normalized state weights make the state-weighted attachment exactly
the frozen equal-weight first-hop operator. -/
theorem stateWeightedFirstHopOperator_of_uniform
    (a : ℝ) (u : Fin 12 → Vec3) (w : Fin 12 → ℝ)
    (huniform : ∀ i, w i = 1 / 12) :
    stateWeightedFirstHopOperator a u w = primitivePortOperator a u := by
  funext f x
  unfold stateWeightedFirstHopOperator primitivePortOperator
  simp_rw [huniform]
  push_cast
  rw [← Finset.mul_sum]
  ring

/-- Exact composition theorem.  The A3 hypotheses force uniform state
weights; the separate state-to-reciprocal-first-hop attachment then fixes the
candidate operator.  The equality named `hattach` is the unresolved physical
and dynamical bridge, not a conclusion of this theorem. -/
theorem a3_closes_attached_reciprocal_first_hop
    (K : Set (Fin 12 → ℝ)) (F : (Fin 12 → ℝ) → ℝ)
    (G : Set ((Fin 12) → (Fin 12)))
    (hK : ∀ g ∈ G, ∀ x ∈ K, (x ∘ g) ∈ K)
    (hF : ∀ g ∈ G, ∀ x ∈ K, F (x ∘ g) = F x)
    (xstar : Fin 12 → ℝ)
    (hmem : xstar ∈ K)
    (hmin : ∀ y ∈ K, F xstar ≤ F y)
    (huniq : ∀ y ∈ K, (∀ z ∈ K, F y ≤ F z) → y = xstar)
    (htrans : ∀ p q : Fin 12, ∃ g ∈ G, g p = q)
    (hsum : (∑ i : Fin 12, xstar i) = 1)
    (a : ℝ) (u : Fin 12 → Vec3)
    (candidate : (Vec3 → ℂ) → Vec3 → ℂ)
    (hattach : candidate = stateWeightedFirstHopOperator a u xstar) :
    candidate = primitivePortOperator a u := by
  have huniform : ∀ i, xstar i = 1 / 12 :=
    OPH.EqualStateWeights.equal_state_weights
      K F G hK hF xstar hmem hmin huniq htrans hsum
  exact hattach.trans
    (stateWeightedFirstHopOperator_of_uniform a u xstar huniform)

/-- Strongest composition supported by the current A1 frame and A3 state
theorems.  The complete directed primitive orbit becomes reciprocal from its
antipodal spatial realization; A3 fixes its directional weights.  The
candidate still has to be identified with this direct first-hop action by
`hattach`. -/
theorem a3_closes_attached_direct_first_hop_on_antipodal_frame
    (K : Set (Fin 12 → ℝ)) (F : (Fin 12 → ℝ) → ℝ)
    (G : Set ((Fin 12) → (Fin 12)))
    (hK : ∀ g ∈ G, ∀ x ∈ K, (x ∘ g) ∈ K)
    (hF : ∀ g ∈ G, ∀ x ∈ K, F (x ∘ g) = F x)
    (xstar : Fin 12 → ℝ)
    (hmem : xstar ∈ K)
    (hmin : ∀ y ∈ K, F xstar ≤ F y)
    (huniq : ∀ y ∈ K, (∀ z ∈ K, F y ≤ F z) → y = xstar)
    (htrans : ∀ p q : Fin 12, ∃ g ∈ G, g p = q)
    (hsum : (∑ i : Fin 12, xstar i) = 1)
    (a : ℝ) (u : Fin 12 → Vec3) (hanti : AntipodalSpatialFrame u)
    (candidate : (Vec3 → ℂ) → Vec3 → ℂ)
    (hattach : candidate =
      stateWeightedDirectedFirstHopOperator a u xstar) :
    candidate = primitivePortOperator a u := by
  have huniform : ∀ i, xstar i = 1 / 12 :=
    OPH.EqualStateWeights.equal_state_weights
      K F G hK hF xstar hmem hmin huniq htrans hsum
  exact hattach.trans
    (stateWeightedDirectedFirstHopOperator_of_uniform
      a u xstar hanti huniform)

/-! ## Normalized reciprocal multi-range counterfamily -/

/-- Convex two-range mixture of separately normalized primitive-port
operators.  Both ranges use the same complete port orbit and reciprocal
paired differences. -/
noncomputable def mixedRangeOperator
    (t a : ℝ) (u : Fin 12 → Vec3) (f : Vec3 → ℂ) : Vec3 → ℂ :=
  fun x => ((1 - t : ℝ) : ℂ) * primitivePortOperator a u f x +
    (t : ℂ) * primitivePortOperator (2 * a) u f x

/-- Exact symbol of the normalized two-range family. -/
noncomputable def mixedRangeSymbol
    (t a : ℝ) (k : Vec3) (u : Fin 12 → Vec3) : ℝ :=
  (1 - t) * cosineSymbol a k u + t * cosineSymbol (2 * a) k u

/-- Plane waves diagonalize every member of the two-range family. -/
theorem mixedRangeOperator_planeWave
    (t a : ℝ) (k x : Vec3) (u : Fin 12 → Vec3) :
    mixedRangeOperator t a u (planeWave k) x =
      (mixedRangeSymbol t a k u : ℂ) * planeWave k x := by
  unfold mixedRangeOperator mixedRangeSymbol
  rw [primitivePortOperator_planeWave, primitivePortOperator_planeWave]
  push_cast
  ring

/-- Every convex member of the family has a nonnegative exact symbol. -/
theorem mixedRangeSymbol_nonnegative
    (t a : ℝ) (k : Vec3) (u : Fin 12 → Vec3)
    (ht0 : 0 ≤ t) (ht1 : t ≤ 1) (ha : a ≠ 0) :
    0 ≤ mixedRangeSymbol t a k u := by
  have hshort : 0 ≤ cosineSymbol a k u :=
    cosineSymbol_nonnegative a ha k u
  have hlong : 0 ≤ cosineSymbol (2 * a) k u :=
    cosineSymbol_nonnegative (2 * a) (mul_ne_zero (by norm_num) ha) k u
  exact add_nonneg
    (mul_nonneg (sub_nonneg.mpr ht1) hshort)
    (mul_nonneg ht0 hlong)

/-- Port relabeling leaves the two-range symbol unchanged. -/
theorem mixedRangeSymbol_reindex
    (t a : ℝ) (k : Vec3) (u : Fin 12 → Vec3)
    (g : Equiv.Perm (Fin 12)) :
    mixedRangeSymbol t a k (fun i => u (g i)) =
      mixedRangeSymbol t a k u := by
  unfold mixedRangeSymbol
  rw [cosineSymbol_reindex, cosineSymbol_reindex]

/-- A conditional active orthogonal realization of a proper carrier
permutation preserves the two-range symbol. -/
theorem mixedRangeSymbol_active_carrier_covariant
    (t a : ℝ) (k : Vec3) (u : Fin 12 → Vec3)
    (R : Vec3 ≃ₗ[ℝ] Vec3) (g : Equiv.Perm (Fin 12))
    (hOrth : ∀ x y, dot (R x) (R y) = dot x y)
    (hR : ∀ i, R (u i) = u (g i)) :
    mixedRangeSymbol t a (R k) u = mixedRangeSymbol t a k u := by
  unfold mixedRangeSymbol
  rw [cosineSymbol_active_carrier_covariant a k u R g hOrth hR]
  rw [cosineSymbol_active_carrier_covariant (2 * a) k u R g hOrth hR]

/-- Wavevector reversal leaves the two-range symbol unchanged. -/
theorem mixedRangeSymbol_wavevector_neg
    (t a : ℝ) (k : Vec3) (u : Fin 12 → Vec3) :
    mixedRangeSymbol t a (-k) u = mixedRangeSymbol t a k u := by
  unfold mixedRangeSymbol
  rw [cosineSymbol_wavevector_neg, cosineSymbol_wavevector_neg]

/-- Taylor truncation of the exact two-range symbol on a supplied moment
packet. -/
noncomputable def mixedRangeTaylorSix
    (t a k : ℝ) (n : Vec3) (u : Fin 12 → Vec3) : ℝ :=
  (1 - t) * portSymbolTaylorSix a k n u +
    t * portSymbolTaylorSix (2 * a) k n u

/-- Quartic coefficient of the normalized two-range family. -/
noncomputable def mixedC4 (t a : ℝ) : ℝ :=
  (1 - t) * (-a ^ 2 / 20) + t * (-(2 * a) ^ 2 / 20)

/-- Isotropic sixth-order coefficient of the normalized two-range family. -/
noncomputable def mixedB0 (t a : ℝ) : ℝ :=
  (1 - t) * (a ^ 4 / 840) + t * ((2 * a) ^ 4 / 840)

/-- Spin-six coefficient of the normalized two-range family. -/
noncomputable def mixedB6 (t a : ℝ) : ℝ :=
  (1 - t) * (2 * a ^ 4 / 7875) +
    t * (2 * (2 * a) ^ 4 / 7875)

/-- Each separately normalized range contributes the same quadratic term,
while the quartic and sixth-order coefficients mix. -/
theorem mixedRangeTaylorSix_frozen
    (t a k i6 : ℝ) (n : Vec3) (u : Fin 12 → Vec3)
    (ha : a ≠ 0) (hpacket : FrozenMomentPacket n u i6) :
    mixedRangeTaylorSix t a k n u =
      k ^ 2 + mixedC4 t a * k ^ 4 + mixedB0 t a * k ^ 6 +
        (mixedB6 t a * k ^ 6) * i6 := by
  unfold mixedRangeTaylorSix
  rw [frozen_taylor_expansion_of_packet a k i6 n u ha hpacket]
  rw [frozen_taylor_expansion_of_packet (2 * a) k i6 n u
    (mul_ne_zero (by norm_num) ha) hpacket]
  unfold mixedC4 mixedB0 mixedB6
  ring

/-- The two endpoint branches have different quartic coefficients at every
nonzero scale despite sharing the normalized quadratic coefficient. -/
theorem mixedC4_endpoints_distinct (a : ℝ) (ha : a ≠ 0) :
    mixedC4 0 a ≠ mixedC4 1 a := by
  unfold mixedC4
  have ha2 : 0 < a ^ 2 := sq_pos_of_ne_zero ha
  norm_num
  nlinarith

#print axioms stateWeightedFirstHopOperator_of_uniform
#print axioms stateWeightedFirstHopOperator_reindex
#print axioms directedDifference_sum_eq_pairedDifference_sum
#print axioms stateWeightedDirectedFirstHopOperator_of_uniform
#print axioms a3_closes_attached_reciprocal_first_hop
#print axioms a3_closes_attached_direct_first_hop_on_antipodal_frame
#print axioms mixedRangeOperator_planeWave
#print axioms mixedRangeSymbol_nonnegative
#print axioms mixedRangeSymbol_reindex
#print axioms mixedRangeSymbol_active_carrier_covariant
#print axioms mixedRangeSymbol_wavevector_neg
#print axioms mixedRangeTaylorSix_frozen
#print axioms mixedC4_endpoints_distinct

end OPH.PrimitivePortOperatorSelectionBoundary
