import Mathlib

namespace OPH.TraceBalancedKernel

/-! # The trace-balanced cover and its exact kernel, on central parameters

Issue #568.  The compact paper's trace-balanced block integration presents
the cover `(A, B, z) ↦ (z⁻²A, z³B)` from `SU(3) × SU(2) × U(1)` onto
`S(U(3) × U(2))`, with kernel `{(z²I₃, z⁻³I₂, z) : z⁶ = 1} ≅ ℤ/6`, and the
tensor-spin image on `ℂ³ ⊗ ℂ²` with the same six-element kernel
`{(ω₃ᵏI₃, (-1)ˡI₂, ζ₆ʳ) : 2k + 3l + r ≡ 0 mod 6}`.  Every element of both
kernels is central, so the entire calculation lives on the central
parameters `(k, l, r) ∈ ℤ/3 × ℤ/2 × ℤ/6` labelling
`(ω₃ᵏI₃, (-1)ˡI₂, ζ₆ʳ)`.  This file checks that arithmetic exactly.

CONTENT.

* `tensorChar`: the additive character `(k, l, r) ↦ 2k + 3l + r` in `ℤ/6` —
  the scalar by which the central element acts on the tensor carrier
  `ℂ³ ⊗ ℂ²` with unit `U(1)` charge; additivity is kernel-checked.
* `kernel_card`: the kernel has exactly six elements.
* `kernel_cyclic`: the kernel is exactly the set of multiples of
  `gen = (1, 1, 1)`, the paper's generator `(ω₃I₃, -I₂, e^{iπ/3})`.
* `gen_order_six`: the generator has exact order six.
* `kernel_third_coordinate_image_card`, `kernel_third_coordinate_surjective`:
  the `U(1)` coordinate takes six distinct values on the six kernel
  elements and reaches every sixth root — the cover-kernel
  parametrization `z ↦ (z², z⁻³, z)` on sixth roots of unity, since
  `2r mod 3 = k` and `-3r mod 2 = r mod 2 = l` on multiples of `gen`.
* `neg_gen_mem`, `neg_kernel_stable`: negation (complex conjugation) fixes
  the kernel setwise and inverts the generator, matching signed antipodal
  inversion of the screen gluing class in `Z6Exact.lean`.

BOUNDARY.  The identification of these central parameters with unitary
matrix blocks, the determinant-balance selection of the centre slope, the
physical deck class, the spin lift, and the common kernel on realized
matter tensors are the declared remainder (issue #567); no physical receipt
is formalized.  This file is exact finite arithmetic only. -/

/-- Central parameters `(k, l, r)` of `SU(3) × SU(2) × U(1)` at sixth-root
level, labelling `(ω₃ᵏI₃, (-1)ˡI₂, ζ₆ʳ)`. -/
abbrev C := ZMod 3 × ZMod 2 × ZMod 6

/-- The tensor character on central parameters: the central element acts on
`ℂ³ ⊗ ℂ²` with unit `U(1)` charge by the scalar `ζ₆^(2k + 3l + r)`. -/
def tensorCharFun (c : C) : ZMod 6 :=
  ((2 * c.1.val + 3 * c.2.1.val : ℕ) : ZMod 6) + c.2.2

theorem tensorCharFun_zero : tensorCharFun 0 = 0 := by decide

theorem tensorCharFun_add :
    ∀ x y : C, tensorCharFun (x + y) = tensorCharFun x + tensorCharFun y := by
  decide

/-- The tensor character as an additive homomorphism. -/
def tensorChar : C →+ ZMod 6 :=
  ⟨⟨tensorCharFun, tensorCharFun_zero⟩, tensorCharFun_add⟩

/-- The exact kernel of the cover on central parameters. -/
def K : AddSubgroup C := tensorChar.ker

/-- The paper's kernel generator `(ω₃I₃, -I₂, e^{iπ/3})`. -/
def gen : C := (1, 1, 1)

theorem gen_mem : gen ∈ K := by
  rw [K, AddMonoidHom.mem_ker]
  decide

/-- The kernel has exactly six elements. -/
theorem kernel_card :
    (Finset.univ.filter fun c : C => tensorCharFun c = 0).card = 6 := by
  decide

/-- The kernel is exactly the cyclic group generated by `gen`: the
cover-kernel parametrization `z ↦ (z², z⁻³, z)` on sixth roots of unity. -/
theorem kernel_cyclic :
    ∀ c : C, tensorCharFun c = 0 ↔ ∃ n : Fin 6, n.val • gen = c := by
  decide

/-- The generator has exact additive order six. -/
theorem gen_order_six :
    (6 : ℕ) • gen = 0 ∧ ∀ n : Fin 6, 0 < n.val → n.val • gen ≠ 0 := by
  decide

/-- The `U(1)` coordinate takes six distinct values on the six kernel
elements: with `kernel_card`, the coordinate is a bijection from the
kernel onto the sixth roots, so the kernel is `ℤ/6` exactly. -/
theorem kernel_third_coordinate_image_card :
    ((Finset.univ.filter fun c : C => tensorCharFun c = 0).image
      fun c => c.2.2).card = 6 := by
  decide

/-- The `U(1)` coordinate is surjective from the kernel onto the sixth
roots. -/
theorem kernel_third_coordinate_surjective :
    ∀ r : ZMod 6, ∃ c : C, tensorCharFun c = 0 ∧ c.2.2 = r := by
  decide

/-- Negation — complex conjugation on the central parameters — keeps the
generator's inverse in the kernel, matching the signed antipodal sign
reversal of the screen gluing class. -/
theorem neg_gen_mem : tensorCharFun (-gen) = 0 := by decide

/-- Negation fixes the kernel setwise. -/
theorem neg_kernel_stable :
    ∀ c : C, tensorCharFun c = 0 → tensorCharFun (-c) = 0 := by
  decide

end OPH.TraceBalancedKernel

/- Axiom audit: standard axioms only; no native_decide. -/

#print axioms OPH.TraceBalancedKernel.tensorCharFun_add
#print axioms OPH.TraceBalancedKernel.kernel_card
#print axioms OPH.TraceBalancedKernel.kernel_cyclic
#print axioms OPH.TraceBalancedKernel.gen_order_six
#print axioms OPH.TraceBalancedKernel.kernel_third_coordinate_image_card
#print axioms OPH.TraceBalancedKernel.kernel_third_coordinate_surjective
#print axioms OPH.TraceBalancedKernel.neg_gen_mem
#print axioms OPH.TraceBalancedKernel.neg_kernel_stable
