import Mathlib
import Z6Exact
import TraceBalancedKernel

namespace OPH.Z6Descent

open OPH.TraceBalancedKernel

/-! # Axis-centre descent on realized matter weights

Issue #567.  The executable certificate
`code/a5_closure/axis_center_descent_certificate.py` consumes the emitted
action kernel of the matter-lift packet and computes the common central
kernel on every realized matter tensor.  This file checks the same finite
arithmetic in Lean and relates the two abstract `ℤ/6` constructions of the
corpus by an explicit intertwiner.

CONTENT.

* `realizedWeights`: the integer weight table `(q mod 6, triality, duality)`
  of the realized matter fields, both carrier blocks, and the scalar, under
  the convention `q = 6Y`.
* `kernel_on_realized_weights`: the common stabilizer of the realized
  weights inside the 36 central parameters is exactly the tensor-action
  kernel `2k + 3l + r = 0`; with `TraceBalancedKernel.kernel_cyclic` the
  common kernel is the six-element cyclic group generated by
  `(ω₃I₃, -I₂, e^{iπ/3})`.
* `four_admissible_global_forms`: the selected diagonal kernel `ℤ/6` has
  exactly four subgroups.  Every realized local weight descends through all
  four; the local tensor table therefore determines a maximal effective
  quotient but does not select a physical global form.
* `adjoint_only_kernel_is_full_centre` and
  `fractional_singlet_kernel_is_trivial`: the two countermodels — without
  matter every central element survives, and a fractionally charged extra
  tensor kills the whole centre.
* `hCube_trivial_on_realized_weights` and
  `no_universal_fermion_minus_one`: `h^3=(1,-I₂,-1)` is a trivial gauge
  relation, not fermion parity; no central parameter acts by `-1` on all five
  matter multiplets.
* `genPow`, `sixAxisToKernel`: the explicit intertwiner from the six-axis
  screen gluing class of `Z6Exact` onto the tensor-action kernel, carrying
  the axis generator to the kernel generator and antipodal sign reversal
  to conjugation.

BOUNDARY.  The physical identification of the central parameters with
unitary blocks, selection of one physical quotient, a port-loop/deck
holonomy, spacetime Spin attachment, genuine-line category, UV polarization,
instanton sectors, and theta periodicity are not supplied here.  This file is
exact finite arithmetic only. -/

/-- A realized weight: `(q mod 6, triality, duality)` under `q = 6Y`. -/
abbrev W := ZMod 6 × ZMod 3 × ZMod 2

/-- The central phase of `(k, l, r)` on a weight `(q, t, d)`, in sixths of a
turn: `2 k t + 3 l d + r q` modulo six. -/
def phase (c : C) (w : W) : ZMod 6 :=
  ((2 * c.1.val * w.2.1.val + 3 * c.2.1.val * w.2.2.val
      + c.2.2.val * w.1.val : ℕ) : ZMod 6)

/-- The realized weight table: `Q`, `u_c`, `e_c`, `d_c`, `L`, the colour and
weak carrier blocks, and the scalar, with `q mod 6` in the first slot. -/
def realizedWeights : List W :=
  [(1, 1, 1), (2, 2, 0), (0, 0, 0), (2, 2, 0), (3, 0, 1), (4, 1, 0), (3, 0, 1), (3, 0, 1)]

/-- The five matter multiplet weights, excluding carrier blocks and the
optional scalar duplicate. -/
def matterWeights : List W :=
  [(1, 1, 1), (2, 2, 0), (0, 0, 0), (2, 2, 0), (3, 0, 1)]

/-- The common stabilizer of the realized weights is exactly the
tensor-action kernel: the kernel computed on realized matter tensors equals
the `ℤ/6` of `TraceBalancedKernel`. -/
theorem kernel_on_realized_weights :
    ∀ c : C, (∀ w ∈ realizedWeights, phase c w = 0) ↔ tensorCharFun c = 0 := by
  decide

/-- The selected diagonal kernel has exactly four subgroups.  This is not an
enumeration of all subgroups of the full product centre. -/
theorem four_admissible_global_forms :
    (Finset.univ.filter fun s : Finset (ZMod 6) =>
      (0 : ZMod 6) ∈ s ∧ ∀ a ∈ s, ∀ b ∈ s, a + b ∈ s).card = 4 := by
  decide

/-- Without matter, every central element survives: the adjoint-only kernel
is the full 36-element centre. -/
theorem adjoint_only_kernel_is_full_centre :
    (Finset.univ.filter fun c : C => phase c (0, 0, 0) = 0).card = 36 := by
  decide

/-- A fractionally charged colour-singlet extra tensor kills the whole
centre: the larger-cover countermodel. -/
theorem fractional_singlet_kernel_is_trivial :
    (Finset.univ.filter fun c : C =>
      (∀ w ∈ realizedWeights, phase c w = 0) ∧ phase c (1, 0, 0) = 0).card = 1 := by
  decide

/-- The cube of the diagonal generator is `(1,-I₂,-1)` and acts trivially on
every realized weight.  It is a gauge-kernel relation, not fermion parity. -/
theorem hCube_trivial_on_realized_weights :
    ∀ w ∈ realizedWeights, phase (3 • gen) w = 0 := by
  decide

/-- No element of the 36-element central parameter table acts by `-1`
(phase three sixths) on all five matter multiplets.  Hence this finite
central arithmetic does not provide a spacetime Spin/fermion attachment. -/
theorem no_universal_fermion_minus_one :
    ∀ c : C, ¬ (∀ w ∈ matterWeights, phase c w = 3) := by
  decide

/-- The cyclic parametrization of the kernel by `ℤ/6`. -/
def genPow (n : ZMod 6) : C := n.val • gen

theorem genPow_add : ∀ a b : ZMod 6, genPow (a + b) = genPow a + genPow b := by
  decide

theorem genPow_injective : ∀ a b : ZMod 6, genPow a = genPow b → a = b := by
  decide

theorem genPow_mem_kernel : ∀ n : ZMod 6, tensorCharFun (genPow n) = 0 := by
  decide

theorem genPow_kernel_surjective :
    ∀ c : C, tensorCharFun c = 0 → ∃ n : ZMod 6, genPow n = c := by
  decide

/-- Negation intertwines: conjugation on the kernel side is the image of
negation on `ℤ/6`. -/
theorem genPow_neg : ∀ n : ZMod 6, genPow (-n) = -genPow n := by
  decide

/-- The explicit intertwiner from the six-axis screen gluing class onto the
tensor-spin kernel parameters. -/
noncomputable def sixAxisToKernel (x : OPH.Z6Exact.Lattice ⧸ OPH.Z6Exact.gauge) : C :=
  genPow (OPH.Z6Exact.quotientEquivZMod6 x)

/-- The intertwiner sends the six-axis unit generator to the paper's kernel
generator `(ω₃I₃, -I₂, e^{iπ/3})`. -/
theorem sixAxis_generator_maps_to_kernel_generator :
    sixAxisToKernel
        (QuotientAddGroup.mk (fun i => if i = 0 then 1 else 0)) = gen := by
  unfold sixAxisToKernel
  rw [OPH.Z6Exact.representative_formula]
  have hres :
      OPH.Z6Exact.residue (fun i => if i = 0 then (1 : ℤ) else 0) = 1 := by
    simp [OPH.Z6Exact.residue, OPH.Z6Exact.total]
  rw [hres]
  decide

/-- The intertwiner carries antipodal sign reversal of the gluing class to
conjugation of the kernel: the two involutions agree through it. -/
theorem sixAxisToKernel_intertwines_involutions
    (x : OPH.Z6Exact.Lattice ⧸ OPH.Z6Exact.gauge) :
    sixAxisToKernel (-x) = -sixAxisToKernel x := by
  unfold sixAxisToKernel
  rw [map_neg]
  exact genPow_neg _

/-- The intertwiner is injective, so the two abstract `ℤ/6` constructions
are identified, not merely abstractly isomorphic. -/
theorem sixAxisToKernel_injective : Function.Injective sixAxisToKernel := by
  intro a b hab
  have := genPow_injective _ _ hab
  exact (OPH.Z6Exact.quotientEquivZMod6.injective this)

/-- The image of the intertwiner is exactly the tensor-spin kernel. -/
theorem sixAxisToKernel_range :
    ∀ c : C, tensorCharFun c = 0 ↔ ∃ x, sixAxisToKernel x = c := by
  intro c
  constructor
  · intro hc
    obtain ⟨n, hn⟩ := genPow_kernel_surjective c hc
    exact ⟨OPH.Z6Exact.quotientEquivZMod6.symm n, by
      unfold sixAxisToKernel
      rw [AddEquiv.apply_symm_apply]
      exact hn⟩
  · rintro ⟨x, rfl⟩
    exact genPow_mem_kernel _

end OPH.Z6Descent

/- Axiom audit: standard axioms only; no native_decide. -/

#print axioms OPH.Z6Descent.kernel_on_realized_weights
#print axioms OPH.Z6Descent.four_admissible_global_forms
#print axioms OPH.Z6Descent.adjoint_only_kernel_is_full_centre
#print axioms OPH.Z6Descent.fractional_singlet_kernel_is_trivial
#print axioms OPH.Z6Descent.hCube_trivial_on_realized_weights
#print axioms OPH.Z6Descent.no_universal_fermion_minus_one
#print axioms OPH.Z6Descent.sixAxis_generator_maps_to_kernel_generator
#print axioms OPH.Z6Descent.sixAxisToKernel_intertwines_involutions
#print axioms OPH.Z6Descent.sixAxisToKernel_injective
#print axioms OPH.Z6Descent.sixAxisToKernel_range
