import EventAlgebra.TsirelsonSaturation
import QFT.CarrierJoinTransport

set_option autoImplicit false
set_option maxRecDepth 65536

/-!
# Source reachability and the record-diagonal CHSH delimitation

Issue #730 OL-C3, source side of the clause "supply a source-produced
entangled preparation, settings, two-wing instrument, and physical-region
attachment for C3, OR delimit that route without conflating the exact
declared witness with a source result".  This module delivers the
delimitation: an exact, machine-checked closure of the committed
source-production surface under the committed operations, with the
classical CHSH bound on the whole closure and the exact non-diagonal
obstruction separating it from the declared saturating Bell state of
`EventAlgebra.TsirelsonSaturation`.

## The committed source-reachable class, enumerated exactly

`Reachable c M` holds when the state `M` on carrier `c` is generated from
the committed counted data by the committed operations.  The carriers are
the label alphabets and ambient index sets of the committed observer
pairs: `Fin 13` (shared observer-86 alphabet and observer-247 alphabet),
`Fin 14` (observer-88 alphabet), the 86/247 pair carrier
`Fin 13 × Fin 13`, the 86/88 pair carrier `Fin 13 × Fin 14`, the triple
carrier, and the two anchored ambient sets `Fin 169` and `Fin 182`.

Base elements, each a committed source-counted state:

* `OPH.QFT.correlationState` (86/247 pair, `QFT.SourceCorrelationCapstone`);
* `OPH.QFT.correlationState88` (86/88 pair, `QFT.TripleCarrierJoin`);
* `OPH.QFT.tripleCorrelationState` (triple carrier, `QFT.TripleCarrierJoin`).

Closure operations, each cited to its committed definition site:

* the walk-step transports `stepEvolve` (`QFT.PathTimeSliceInterface`;
  index 31 carries the committed declared terminal-to-initial bookkeeping
  closure), `pair88StepEvolve` and `tripleStepEvolve`
  (`QFT.TripleCarrierJoin`, the 31 actual adjacent source transitions);
* the internal slot exchange `slotSwap`
  (`QFT.StructuralNetAdequacySurface`, the constructed internal algebra
  symmetry consumed by the slot-alternating evolution of
  `QFT.CarrierJoinTransport`);
* the ambient anchoring equivalences `ambientEquiv`
  (`QFT.TowerAnchoredDiamond`) and `ambientEquiv247`
  (`QFT.TowerAnchoredCorrelation`);
* the marginalization maps `ptraceSnd` (`QFT.TwoSlotCPNetWitness`),
  `OPH.Locality.ptraceFst` (`ObserverPatchHolography.Locality.NoSignalling`),
  and `ptraceMiddle` (`QFT.TripleCarrierJoin`), on the pair and triple
  carriers where the committed modules apply them;
* the regional conditional expectations `leftSlotExpectation`
  (`QFT.TwoSlotCPNetWitness`), `rightSlotExpectation`
  (`QFT.JointSlotFactorisation`), and the scalar expectation
  `scalarExpectation` (`QFT.TwoSlotCPNetWitness`), the expectation data of
  the committed two-slot diamonds (`twoSlotNet247` in
  `QFT.SourceCorrelationCapstone`);
* marginal-product formation on the 86/247 hinge alphabets, whose
  committed instance is the comparison state
  `marginal86State ⊗ₖ marginal247State` of
  `QFT.SourceCorrelationCapstone.correlationState_ne_product`; the
  constructor generalizes that instance to arbitrary reachable factors,
  and the closure theorem covers the generalization, so it covers the
  committed instance;
* convex mixtures with a weight in `[0,1]`, the committed mixing shape of
  `isState_convexMix` (`QFT.ConvexAffinityBridge`) and of the source
  mixtures of `QFT.SourceConvexFamily`.

Operations NOT included, stated exactly: general Kraus or CPTP channel
application (the committed channel vocabulary of `Dynamics.ChoiCPTP` has
no committed application to the counted states), unitary conjugation by
arbitrary unitaries, the declared Bell-state preparation and the `toFour`
transport of `EventAlgebra.TsirelsonSaturation` (declared data, register
row PR-52), and any operation writing off-diagonal entries.  The class is
exactly the listed arrows and nothing else; `Reachable` is inductively
generated by them.

## Results

1. **Nonvacuity.**  The class contains the committed counted state
   (`correlationState_reachable`) and the committed observer-86 marginal
   (`marginal86State_reachable`).
2. **Closure.**  Every reachable state satisfies the record law
   (`reachable_isRecordLaw`): it is diagonal in the record basis with
   nonnegative real weights summing to one.  In particular it is
   record-diagonal, positive semidefinite, and of trace one
   (`reachable_recordDiagonal`, `reachable_state_certificate`).
3. **Classical bound.**  Via the committed diagonal delimitation
   `EventAlgebra.TsirelsonSaturation.diagonal_state_chsh_le_two`, every
   reachable state on every enumerated carrier obeys the exact CHSH bound
   `2` against every four jointly record-diagonal `[-1,1]`-valued readouts
   (`reachable_diagonal_chsh_le_two`), and the classical bound sits
   strictly below the committed witness value `2√2`
   (`classical_bound_lt_saturation`,
   `reachable_not_tsirelson_saturating`).
4. **The target-specific obstruction.**  The declared saturating state
   `EventAlgebra.TsirelsonSaturation.bellState` has the explicit nonzero
   off-diagonal entry `2⁻¹` at the record pair `((0,0),(1,1))`
   (`bellStateProd_offdiag_entry`), so it is not record-diagonal
   (`bellState_not_recordDiagonal`); every map from a reachable state to
   the saturating state breaks record-diagonality preservation
   (`bellState_target_requires_nondiagonal_production`). The cardinality
   observation `no_committed_carrier_equiv_fin4` records that no
   enumerated carrier is even equinumerous with the witness carrier, so
   the load-bearing obstruction is record-diagonality on the class's own
   carriers, and the transport-form statement is quantified over all
   diagonality-preserving maps rather than over carrier equivalences.
5. **Composed receipt.**  `source_reachability_receipt` conjoins the
   clauses above.  Reaching the one declared Bell-state witness through a
   record-diagonality-preserving state map is impossible.  This does not
   prove that every route to the value `2√2` needs non-diagonal state
   production: non-jointly-diagonal or contextual readouts are outside the
   bound, and a slot-local separability theorem for arbitrary settings has
   not been proved.  These remain viable routes rather than consequences of
   the target-specific state obstruction.

## Hypotheses, falsifier, nonclaims

Hypotheses: the committed counted payloads and the committed definitions
of the enumerated operations; the label conventions and slot assemblies
stay declared postprocessors (premise rows PR-32, PR-33, PR-34 as bundled
in the adequacy surface); the two-slot splits are PR-44 data.

Falsifier: the delimitation's corpus-level reading fails if the corpus
commits an operation on the counted states outside the enumerated class
whose output carries off-diagonal record coherence, or if any state in
the class exceeds CHSH value `2` against jointly record-diagonal
readouts, or if any receipt clause fails.  The Lean theorems quantify
over the enumerated class only.

Nonclaims: this is a delimitation of committed-data reachability under
the enumerated committed operations.  It is not an all-architectures
no-go and not a hidden-variable theorem.  It does not close OL-C3: the
diagonal bound covers one reachable state read against four observables
diagonal in the same record basis, and it says nothing here about
non-jointly-diagonal readouts on reachable states (no separability bound
is committed and none is claimed), nor about context-dependent
operational models.  No implication involving PR-04 or genuinely complex
phase structure is asserted.  Source entangled preparation, physical
regions, spacelike separation, and instruments stay open (PR-52; OL-C3
realization clause); PR-58 content is untouched.

## Tagging convention

As in `EventAlgebra.Basic`: **algebra-only** statements consume no trace
pairing; **trace-dependent** statements pass through `Tr(ρ M)`.
-/

namespace EventAlgebra.SourceReachability

open Matrix
open Kronecker
open OPH.QFT
open scoped ComplexOrder

noncomputable section

/-! ## Record-diagonality and the record law -/

/-- **Algebra-only.**  A matrix is record-diagonal when every off-diagonal
entry vanishes: the record basis carries no coherence. -/
def IsRecordDiagonal {ι : Type*} (M : Matrix ι ι ℂ) : Prop :=
  ∀ i j : ι, i ≠ j → M i j = 0

/-- **Algebra-only.**  The record law: the matrix is the diagonal matrix
of a nonnegative real weight function summing to one.  This is the exact
shape consumed by the committed diagonal CHSH delimitation
`EventAlgebra.TsirelsonSaturation.diagonal_state_chsh_le_two`. -/
def IsRecordLaw {ι : Type*} [Fintype ι] [DecidableEq ι]
    (M : Matrix ι ι ℂ) : Prop :=
  ∃ w : ι → ℝ, (∀ i, 0 ≤ w i) ∧ (∑ i, w i) = 1 ∧
    M = Matrix.diagonal fun i => (w i : ℂ)

variable {ι κ : Type*}

/-- **Algebra-only.**  A record law is record-diagonal. -/
theorem IsRecordLaw.recordDiagonal [Fintype ι] [DecidableEq ι]
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M) : IsRecordDiagonal M := by
  obtain ⟨w, _, _, rfl⟩ := h
  intro i j hij
  exact Matrix.diagonal_apply_ne _ hij

/-- **Trace-dependent.**  A record law has trace one. -/
theorem IsRecordLaw.trace_one [Fintype ι] [DecidableEq ι]
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M) : M.trace = 1 := by
  obtain ⟨w, _, hw1, rfl⟩ := h
  rw [Matrix.trace_diagonal,
    show (∑ i, ((w i : ℝ) : ℂ)) = ((∑ i, w i : ℝ) : ℂ) by push_cast; rfl,
    hw1]
  norm_num

/-- **Algebra-only.**  A record law is positive semidefinite. -/
theorem IsRecordLaw.posSemidef [Fintype ι] [DecidableEq ι]
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M) : M.PosSemidef := by
  obtain ⟨w, hw0, _, rfl⟩ := h
  refine Matrix.posSemidef_diagonal_iff.mpr fun i => ?_
  exact_mod_cast hw0 i

/-- A record law forces a nonempty carrier: the weights sum to one. -/
theorem IsRecordLaw.carrier_nonempty [Fintype ι] [DecidableEq ι]
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M) : Nonempty ι := by
  obtain ⟨w, _, hw1, _⟩ := h
  by_contra hempty
  rw [not_nonempty_iff] at hempty
  rw [Finset.univ_eq_empty, Finset.sum_empty] at hw1
  exact one_ne_zero hw1.symm

/-! ## Preservation of the record law under each committed operation -/

/-- The base shape: the diagonal state of a count table totalling the 32
committed source steps satisfies the record law. -/
theorem isRecordLaw_countDiagonal [Fintype ι] [DecidableEq ι]
    (f : ι → ℕ) (htot : ∑ i, f i = 32) :
    IsRecordLaw (Matrix.diagonal fun i => (f i : ℂ) / 32) := by
  refine ⟨fun i => (f i : ℝ) / 32, fun i => by positivity, ?_, ?_⟩
  · rw [← Finset.sum_div,
      show (∑ i, (f i : ℝ)) = ((∑ i, f i : ℕ) : ℝ) by push_cast; rfl, htot]
    norm_num
  · congr 1
    funext i
    push_cast
    ring

/-- **Algebra-only.**  Reindexing along any equivalence preserves the
record law; this covers every committed transport that acts by
`Matrix.reindex`. -/
theorem IsRecordLaw.reindex [Fintype ι] [DecidableEq ι]
    [Fintype κ] [DecidableEq κ] (e : ι ≃ κ)
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (Matrix.reindex e e M) := by
  obtain ⟨w, hw0, hw1, rfl⟩ := h
  refine ⟨fun k => w (e.symm k), fun k => hw0 _, ?_, ?_⟩
  · rw [← hw1]
    exact Equiv.sum_comp e.symm w
  · rw [Matrix.reindex_apply, Matrix.submatrix_diagonal_equiv]
    rfl

/-- **Algebra-only.**  The committed second-factor marginalization
preserves the record law. -/
theorem IsRecordLaw.ptraceSnd {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β]
    {M : Matrix (α × β) (α × β) ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (ptraceSnd M) := by
  obtain ⟨w, hw0, hw1, rfl⟩ := h
  rw [ptraceSnd_diagonal]
  refine ⟨fun a => ∑ b, w (a, b),
    fun a => Finset.sum_nonneg fun b _ => hw0 _, ?_, ?_⟩
  · rw [← Fintype.sum_prod_type] at *
    exact hw1
  · congr 1
    funext a
    push_cast
    rfl

/-- **Algebra-only.**  The committed first-factor marginalization
preserves the record law. -/
theorem IsRecordLaw.ptraceFst {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β]
    {M : Matrix (α × β) (α × β) ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (OPH.Locality.ptraceFst M) := by
  obtain ⟨w, hw0, hw1, rfl⟩ := h
  rw [ptraceFst_diagonal]
  refine ⟨fun b => ∑ a, w (a, b),
    fun b => Finset.sum_nonneg fun a _ => hw0 _, ?_, ?_⟩
  · rw [← hw1, Fintype.sum_prod_type]
    exact Finset.sum_comm
  · congr 1
    funext b
    push_cast
    rfl

/-- The committed middle marginalization of the triple carrier acts on
diagonal matrices as the fibre sum over the observer-88 alphabet. -/
theorem ptraceMiddle_diagonal (f : TripleCarrier → ℂ) :
    ptraceMiddle (Matrix.diagonal f) =
      Matrix.diagonal fun p : PairIndex247 => ∑ j : Fin 14, f ((p.1, j), p.2) := by
  ext p p'
  by_cases h : p = p'
  · subst h
    show (∑ j : Fin 14, Matrix.diagonal f ((p.1, j), p.2) ((p.1, j), p.2)) = _
    simp [Matrix.diagonal]
  · rw [Matrix.diagonal_apply_ne _ h]
    apply Finset.sum_eq_zero
    intro j _
    apply Matrix.diagonal_apply_ne
    intro hc
    have h1 : p.1 = p'.1 := congrArg (fun q : TripleCarrier => q.1.1) hc
    have h2 : p.2 = p'.2 := congrArg (fun q : TripleCarrier => q.2) hc
    exact h (Prod.ext h1 h2)

/-- **Algebra-only.**  The committed middle marginalization preserves the
record law. -/
theorem IsRecordLaw.ptraceMiddle
    {M : Matrix TripleCarrier TripleCarrier ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (OPH.QFT.ptraceMiddle M) := by
  obtain ⟨w, hw0, hw1, rfl⟩ := h
  rw [ptraceMiddle_diagonal]
  refine ⟨fun p => ∑ j : Fin 14, w ((p.1, j), p.2),
    fun p => Finset.sum_nonneg fun j _ => hw0 _, ?_, ?_⟩
  · rw [← hw1, Fintype.sum_prod_type, Fintype.sum_prod_type,
      Fintype.sum_prod_type]
    refine Finset.sum_congr rfl fun i _ => ?_
    exact Finset.sum_comm
  · congr 1
    funext p
    push_cast
    rfl

/-- **Algebra-only.**  Marginal-product formation preserves the record
law; the committed instance is the comparison state
`marginal86State ⊗ₖ marginal247State`. -/
theorem IsRecordLaw.kronecker {α β : Type*} [Fintype α] [Fintype β]
    [DecidableEq α] [DecidableEq β]
    {M : Matrix α α ℂ} {N : Matrix β β ℂ}
    (hM : IsRecordLaw M) (hN : IsRecordLaw N) :
    IsRecordLaw (M ⊗ₖ N) := by
  obtain ⟨w, hw0, hw1, rfl⟩ := hM
  obtain ⟨v, hv0, hv1, rfl⟩ := hN
  rw [Matrix.diagonal_kronecker_diagonal]
  refine ⟨fun p => w p.1 * v p.2,
    fun p => mul_nonneg (hw0 _) (hv0 _), ?_, ?_⟩
  · rw [Fintype.sum_prod_type, ← Finset.sum_mul_sum, hw1, hv1, one_mul]
  · congr 1
    funext p
    push_cast
    rfl

/-- **Algebra-only.**  The committed left regional conditional
expectation preserves the record law. -/
theorem IsRecordLaw.leftSlotExpectation {α β : Type*} [Fintype α]
    [Fintype β] [DecidableEq α] [DecidableEq β]
    {M : Matrix (α × β) (α × β) ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (OPH.QFT.leftSlotExpectation M) := by
  have hβ : Nonempty β := h.carrier_nonempty.map Prod.snd
  have hcard : (0 : ℝ) < (Fintype.card β : ℝ) := by
    exact_mod_cast Fintype.card_pos
  obtain ⟨wa, ha0, ha1, hPd⟩ := h.ptraceSnd
  have hexp : OPH.QFT.leftSlotExpectation M =
      (Fintype.card β : ℂ)⁻¹ •
        (OPH.QFT.ptraceSnd M ⊗ₖ (1 : Matrix β β ℂ)) := rfl
  refine ⟨fun p => (Fintype.card β : ℝ)⁻¹ * wa p.1,
    fun p => mul_nonneg (by positivity) (ha0 _), ?_, ?_⟩
  · calc ∑ p : α × β, (Fintype.card β : ℝ)⁻¹ * wa p.1
        = ∑ a, ∑ _b : β, (Fintype.card β : ℝ)⁻¹ * wa a :=
          Fintype.sum_prod_type _
      _ = ∑ a, wa a := by
          refine Finset.sum_congr rfl fun a _ => ?_
          rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, ← mul_assoc,
            mul_inv_cancel₀ (ne_of_gt hcard), one_mul]
      _ = 1 := ha1
  · rw [hexp, hPd]
    ext p q
    by_cases hpq : p = q
    · subst hpq
      rw [Matrix.smul_apply, Matrix.kroneckerMap_apply,
        Matrix.diagonal_apply_eq, Matrix.diagonal_apply_eq,
        Matrix.one_apply_eq, smul_eq_mul]
      push_cast
      ring
    · rw [Matrix.diagonal_apply_ne _ hpq, Matrix.smul_apply,
        Matrix.kroneckerMap_apply]
      have hor : p.1 ≠ q.1 ∨ p.2 ≠ q.2 := by
        rcases Decidable.em (p.1 = q.1) with h1 | h1
        · exact Or.inr fun h2 => hpq (Prod.ext h1 h2)
        · exact Or.inl h1
      rcases hor with h1 | h2
      · rw [Matrix.diagonal_apply_ne _ h1, zero_mul, smul_zero]
      · rw [Matrix.one_apply_ne h2, mul_zero, smul_zero]

/-- **Algebra-only.**  The committed right regional conditional
expectation preserves the record law. -/
theorem IsRecordLaw.rightSlotExpectation {α β : Type*} [Fintype α]
    [Fintype β] [DecidableEq α] [DecidableEq β]
    {M : Matrix (α × β) (α × β) ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (OPH.QFT.rightSlotExpectation M) := by
  have hα : Nonempty α := h.carrier_nonempty.map Prod.fst
  have hcard : (0 : ℝ) < (Fintype.card α : ℝ) := by
    exact_mod_cast Fintype.card_pos
  obtain ⟨wb, hb0, hb1, hPd⟩ := h.ptraceFst
  have hexp : OPH.QFT.rightSlotExpectation M =
      (Fintype.card α : ℂ)⁻¹ •
        ((1 : Matrix α α ℂ) ⊗ₖ OPH.Locality.ptraceFst M) := rfl
  refine ⟨fun p => (Fintype.card α : ℝ)⁻¹ * wb p.2,
    fun p => mul_nonneg (by positivity) (hb0 _), ?_, ?_⟩
  · calc ∑ p : α × β, (Fintype.card α : ℝ)⁻¹ * wb p.2
        = ∑ _a : α, ∑ b, (Fintype.card α : ℝ)⁻¹ * wb b :=
          Fintype.sum_prod_type _
      _ = ∑ _a : α, (Fintype.card α : ℝ)⁻¹ * 1 := by
          refine Finset.sum_congr rfl fun a _ => ?_
          rw [← Finset.mul_sum, hb1]
      _ = 1 := by
          rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul, mul_one,
            mul_inv_cancel₀ (ne_of_gt hcard)]
  · rw [hexp, hPd]
    ext p q
    by_cases hpq : p = q
    · subst hpq
      rw [Matrix.smul_apply, Matrix.kroneckerMap_apply,
        Matrix.diagonal_apply_eq, Matrix.diagonal_apply_eq,
        Matrix.one_apply_eq, smul_eq_mul]
      push_cast
      ring
    · rw [Matrix.diagonal_apply_ne _ hpq, Matrix.smul_apply,
        Matrix.kroneckerMap_apply]
      have hor : p.1 ≠ q.1 ∨ p.2 ≠ q.2 := by
        rcases Decidable.em (p.1 = q.1) with h1 | h1
        · exact Or.inr fun h2 => hpq (Prod.ext h1 h2)
        · exact Or.inl h1
      rcases hor with h1 | h2
      · rw [Matrix.one_apply_ne h1, zero_mul, smul_zero]
      · rw [Matrix.diagonal_apply_ne _ h2, mul_zero, smul_zero]

/-- **Trace-dependent.**  The committed scalar conditional expectation
preserves the record law. -/
theorem IsRecordLaw.scalarExpectation [Fintype ι] [DecidableEq ι]
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M) :
    IsRecordLaw (OPH.QFT.scalarExpectation ι M) := by
  have hne : Nonempty ι := h.carrier_nonempty
  have hcard : (0 : ℝ) < (Fintype.card ι : ℝ) := by
    exact_mod_cast Fintype.card_pos
  have hexp : OPH.QFT.scalarExpectation ι M =
      (Fintype.card ι : ℂ)⁻¹ • M.trace • (1 : Matrix ι ι ℂ) := rfl
  refine ⟨fun _ => (Fintype.card ι : ℝ)⁻¹, fun _ => by positivity, ?_, ?_⟩
  · rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
      mul_inv_cancel₀ (ne_of_gt hcard)]
  · rw [hexp, h.trace_one, one_smul]
    ext i j
    by_cases hij : i = j
    · subst hij
      rw [Matrix.smul_apply, Matrix.one_apply_eq, Matrix.diagonal_apply_eq,
        smul_eq_mul, mul_one]
      push_cast
      rfl
    · rw [Matrix.smul_apply, Matrix.one_apply_ne hij, smul_zero,
        Matrix.diagonal_apply_ne _ hij]

/-- **Algebra-only.**  Convex mixture in the committed shape of
`isState_convexMix` preserves the record law. -/
theorem IsRecordLaw.mix [Fintype ι] [DecidableEq ι]
    {M N : Matrix ι ι ℂ} (hM : IsRecordLaw M) (hN : IsRecordLaw N)
    {l : ℝ} (h0 : 0 ≤ l) (h1 : l ≤ 1) :
    IsRecordLaw ((l : ℂ) • M + ((1 - l : ℝ) : ℂ) • N) := by
  obtain ⟨w, hw0, hw1, rfl⟩ := hM
  obtain ⟨v, hv0, hv1, rfl⟩ := hN
  refine ⟨fun i => l * w i + (1 - l) * v i,
    fun i => add_nonneg (mul_nonneg h0 (hw0 i))
      (mul_nonneg (by linarith) (hv0 i)), ?_, ?_⟩
  · rw [Finset.sum_add_distrib, ← Finset.mul_sum, ← Finset.mul_sum,
      hw1, hv1]
    ring
  · ext i j
    by_cases hij : i = j
    · subst hij
      rw [Matrix.add_apply, Matrix.smul_apply, Matrix.smul_apply,
        Matrix.diagonal_apply_eq, Matrix.diagonal_apply_eq,
        Matrix.diagonal_apply_eq, smul_eq_mul, smul_eq_mul]
      push_cast
      ring
    · rw [Matrix.add_apply, Matrix.smul_apply, Matrix.smul_apply,
        Matrix.diagonal_apply_ne _ hij, Matrix.diagonal_apply_ne _ hij,
        Matrix.diagonal_apply_ne _ hij, smul_zero, smul_zero, add_zero]

/-! ## The committed carriers and the reachable class -/

/-- The enumerated committed carriers: the two observer alphabets, the
two committed pair carriers, the triple carrier, and the two anchored
ambient index sets. -/
inductive Carrier : Type
  | hinge13
  | hinge14
  | pair247
  | pair88
  | triple
  | amb169
  | amb182
  deriving DecidableEq

/-- The index type of each enumerated carrier. -/
def Carrier.Index : Carrier → Type
  | .hinge13 => Fin 13
  | .hinge14 => Fin 14
  | .pair247 => PairIndex247
  | .pair88 => PairIndex
  | .triple => TripleCarrier
  | .amb169 => Fin 169
  | .amb182 => Fin 182

instance instFintypeIndex : (c : Carrier) → Fintype c.Index
  | .hinge13 => inferInstanceAs (Fintype (Fin 13))
  | .hinge14 => inferInstanceAs (Fintype (Fin 14))
  | .pair247 => inferInstanceAs (Fintype PairIndex247)
  | .pair88 => inferInstanceAs (Fintype PairIndex)
  | .triple => inferInstanceAs (Fintype TripleCarrier)
  | .amb169 => inferInstanceAs (Fintype (Fin 169))
  | .amb182 => inferInstanceAs (Fintype (Fin 182))

instance instDecEqIndex : (c : Carrier) → DecidableEq c.Index
  | .hinge13 => inferInstanceAs (DecidableEq (Fin 13))
  | .hinge14 => inferInstanceAs (DecidableEq (Fin 14))
  | .pair247 => inferInstanceAs (DecidableEq PairIndex247)
  | .pair88 => inferInstanceAs (DecidableEq PairIndex)
  | .triple => inferInstanceAs (DecidableEq TripleCarrier)
  | .amb169 => inferInstanceAs (DecidableEq (Fin 169))
  | .amb182 => inferInstanceAs (DecidableEq (Fin 182))

/-- **The committed source-reachable class.**  Inductively generated by
the three committed counted states and the enumerated committed
operations, each cited in the module docstring.  No other operation is
included. -/
inductive Reachable : (c : Carrier) → Matrix c.Index c.Index ℂ → Prop
  | base247 : Reachable .pair247 correlationState
  | base88 : Reachable .pair88 correlationState88
  | baseTriple : Reachable .triple tripleCorrelationState
  | step247 (t : Fin 32) (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) : Reachable .pair247 (stepEvolve t M)
  | step88 (t : Fin 31) (M : Matrix PairIndex PairIndex ℂ)
      (h : Reachable .pair88 M) : Reachable .pair88 (pair88StepEvolve t M)
  | stepTriple (t : Fin 31) (M : Matrix TripleCarrier TripleCarrier ℂ)
      (h : Reachable .triple M) : Reachable .triple (tripleStepEvolve t M)
  | swap (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) : Reachable .pair247 (slotSwap M)
  | anchor247 (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) : Reachable .amb169 (ambientEquiv247 M)
  | anchor88 (M : Matrix PairIndex PairIndex ℂ)
      (h : Reachable .pair88 M) : Reachable .amb182 (ambientEquiv M)
  | margSnd247 (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) : Reachable .hinge13 (ptraceSnd M)
  | margFst247 (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) :
      Reachable .hinge13 (OPH.Locality.ptraceFst M)
  | margSnd88 (M : Matrix PairIndex PairIndex ℂ)
      (h : Reachable .pair88 M) : Reachable .hinge13 (ptraceSnd M)
  | margFst88 (M : Matrix PairIndex PairIndex ℂ)
      (h : Reachable .pair88 M) :
      Reachable .hinge14 (OPH.Locality.ptraceFst M)
  | margSndTriple (M : Matrix TripleCarrier TripleCarrier ℂ)
      (h : Reachable .triple M) : Reachable .pair88 (ptraceSnd M)
  | margMiddle (M : Matrix TripleCarrier TripleCarrier ℂ)
      (h : Reachable .triple M) : Reachable .pair247 (ptraceMiddle M)
  | expectL247 (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) :
      Reachable .pair247 (leftSlotExpectation M)
  | expectR247 (M : Matrix PairIndex247 PairIndex247 ℂ)
      (h : Reachable .pair247 M) :
      Reachable .pair247 (rightSlotExpectation M)
  | expectL88 (M : Matrix PairIndex PairIndex ℂ)
      (h : Reachable .pair88 M) :
      Reachable .pair88 (leftSlotExpectation M)
  | expectR88 (M : Matrix PairIndex PairIndex ℂ)
      (h : Reachable .pair88 M) :
      Reachable .pair88 (rightSlotExpectation M)
  | scal (c : Carrier) (M : Matrix c.Index c.Index ℂ)
      (h : Reachable c M) : Reachable c (scalarExpectation c.Index M)
  | prodMarg (M N : Matrix (Fin 13) (Fin 13) ℂ)
      (hM : Reachable .hinge13 M) (hN : Reachable .hinge13 N) :
      Reachable .pair247 (M ⊗ₖ N)
  | mix (c : Carrier) (l : ℝ) (h0 : 0 ≤ l) (h1 : l ≤ 1)
      (M N : Matrix c.Index c.Index ℂ)
      (hM : Reachable c M) (hN : Reachable c N) :
      Reachable c ((l : ℂ) • M + ((1 - l : ℝ) : ℂ) • N)

/-! ## Nonvacuity witnesses -/

/-- **Nonvacuity.**  The committed counted 86/247 state is in the
class. -/
theorem correlationState_reachable :
    Reachable .pair247 correlationState :=
  Reachable.base247

/-- **Nonvacuity.**  The committed observer-86 marginal state is in the
class, through the committed marginalization identity
`correlationState_marginal_left`. -/
theorem marginal86State_reachable :
    Reachable .hinge13 marginal86State := by
  have heq : ptraceSnd correlationState = marginal86State :=
    correlationState_marginal_left
  rw [← heq]
  exact Reachable.margSnd247 correlationState Reachable.base247

/-! ## The closure theorem -/

/-- The committed occupation table of the 86/88 pair totals the 32 source
steps, by marginalizing the committed triple table. -/
theorem jointCount88_total : ∑ p : PairIndex, jointCount88 p = 32 := by
  have h : ∑ q : TripleCarrier, tripleCount q = 32 := tripleCount_total
  rw [Fintype.sum_prod_type] at h
  calc ∑ p : PairIndex, jointCount88 p
      = ∑ p : PairIndex, ∑ k : Fin 13, tripleCount (p, k) :=
        Finset.sum_congr rfl fun p _ => (tripleCount_marginal_88 p).symm
    _ = 32 := h

/-- The committed counted 86/247 state satisfies the record law. -/
theorem isRecordLaw_correlationState : IsRecordLaw correlationState :=
  isRecordLaw_countDiagonal jointCount jointCount_total

/-- The committed counted 86/88 state satisfies the record law. -/
theorem isRecordLaw_correlationState88 : IsRecordLaw correlationState88 :=
  isRecordLaw_countDiagonal jointCount88 jointCount88_total

/-- The committed counted triple state satisfies the record law. -/
theorem isRecordLaw_tripleCorrelationState :
    IsRecordLaw tripleCorrelationState :=
  isRecordLaw_countDiagonal tripleCount tripleCount_total

/-- **The closure theorem.**  Every state in the committed
source-reachable class satisfies the record law: each committed base
state does, and each enumerated committed operation preserves it. -/
theorem reachable_isRecordLaw {c : Carrier}
    {M : Matrix c.Index c.Index ℂ} (h : Reachable c M) :
    IsRecordLaw M := by
  induction h with
  | base247 => exact isRecordLaw_correlationState
  | base88 => exact isRecordLaw_correlationState88
  | baseTriple => exact isRecordLaw_tripleCorrelationState
  | step247 t M h ih =>
      rw [stepEvolve_apply]
      exact ih.reindex (walkStepEquiv t)
  | step88 t M h ih =>
      have happ : pair88StepEvolve t M =
          Matrix.reindex (walkStepEquiv88 t) (walkStepEquiv88 t) M := rfl
      rw [happ]
      exact ih.reindex (walkStepEquiv88 t)
  | stepTriple t M h ih =>
      have happ : tripleStepEvolve t M =
          Matrix.reindex (tripleStepEquiv t) (tripleStepEquiv t) M := rfl
      rw [happ]
      exact ih.reindex (tripleStepEquiv t)
  | swap M h ih =>
      have happ : slotSwap M =
          Matrix.reindex (Equiv.prodComm (Fin 13) (Fin 13))
            (Equiv.prodComm (Fin 13) (Fin 13)) M := rfl
      rw [happ]
      exact ih.reindex (Equiv.prodComm (Fin 13) (Fin 13))
  | anchor247 M h ih =>
      rw [ambientEquiv247_apply]
      exact ih.reindex pairFin247
  | anchor88 M h ih =>
      rw [ambientEquiv_apply]
      exact ih.reindex pairFin
  | margSnd247 M h ih => exact ih.ptraceSnd
  | margFst247 M h ih => exact ih.ptraceFst
  | margSnd88 M h ih => exact ih.ptraceSnd
  | margFst88 M h ih => exact ih.ptraceFst
  | margSndTriple M h ih => exact ih.ptraceSnd
  | margMiddle M h ih => exact ih.ptraceMiddle
  | expectL247 M h ih => exact ih.leftSlotExpectation
  | expectR247 M h ih => exact ih.rightSlotExpectation
  | expectL88 M h ih => exact ih.leftSlotExpectation
  | expectR88 M h ih => exact ih.rightSlotExpectation
  | scal c M h ih => exact ih.scalarExpectation
  | prodMarg M N hM hN ihM ihN => exact ihM.kronecker ihN
  | mix c l h0 h1 M N hM hN ihM ihN => exact ihM.mix ihN h0 h1

/-- Every reachable state is record-diagonal. -/
theorem reachable_recordDiagonal {c : Carrier}
    {M : Matrix c.Index c.Index ℂ} (h : Reachable c M) :
    IsRecordDiagonal M :=
  (reachable_isRecordLaw h).recordDiagonal

/-- Every reachable state is a state: positive semidefinite with trace
one. -/
theorem reachable_state_certificate {c : Carrier}
    {M : Matrix c.Index c.Index ℂ} (h : Reachable c M) :
    M.PosSemidef ∧ M.trace = 1 :=
  ⟨(reachable_isRecordLaw h).posSemidef,
    (reachable_isRecordLaw h).trace_one⟩

/-! ## The classical CHSH bound on the reachable class -/

/-- The CHSH combination of four record-diagonal readouts, in the exact
operator shape of the committed delimitation
`EventAlgebra.TsirelsonSaturation.diagonal_state_chsh_le_two`. -/
def diagonalChsh [Fintype ι] [DecidableEq ι]
    (a₀ a₁ b₀ b₁ : ι → ℝ) : Matrix ι ι ℂ :=
  Matrix.diagonal (fun i => (a₀ i : ℂ)) *
      Matrix.diagonal (fun i => (b₀ i : ℂ)) +
    Matrix.diagonal (fun i => (a₀ i : ℂ)) *
      Matrix.diagonal (fun i => (b₁ i : ℂ)) +
    Matrix.diagonal (fun i => (a₁ i : ℂ)) *
      Matrix.diagonal (fun i => (b₀ i : ℂ)) -
    Matrix.diagonal (fun i => (a₁ i : ℂ)) *
      Matrix.diagonal (fun i => (b₁ i : ℂ))

/-- **Trace-dependent.**  A record law obeys the classical CHSH bound
against every four jointly record-diagonal `[-1,1]`-valued readouts, by
the committed diagonal delimitation. -/
theorem IsRecordLaw.chsh_le_two [Fintype ι] [DecidableEq ι]
    {M : Matrix ι ι ℂ} (h : IsRecordLaw M)
    (a₀ a₁ b₀ b₁ : ι → ℝ)
    (ha₀ : ∀ i, |a₀ i| ≤ 1) (ha₁ : ∀ i, |a₁ i| ≤ 1)
    (hb₀ : ∀ i, |b₀ i| ≤ 1) (hb₁ : ∀ i, |b₁ i| ≤ 1) :
    ‖(M * diagonalChsh a₀ a₁ b₀ b₁).trace‖ ≤ 2 := by
  obtain ⟨w, hw0, hw1, rfl⟩ := h
  exact EventAlgebra.TsirelsonSaturation.diagonal_state_chsh_le_two
    w a₀ a₁ b₀ b₁ hw0 hw1 ha₀ ha₁ hb₀ hb₁

/-- **Trace-dependent.**  **The source-reachability delimitation.**
Every state in the committed source-reachable class, on every enumerated
carrier, obeys the classical CHSH bound `2` exactly against every four
jointly record-diagonal `[-1,1]`-valued readouts. -/
theorem reachable_diagonal_chsh_le_two {c : Carrier}
    {M : Matrix c.Index c.Index ℂ} (h : Reachable c M)
    (a₀ a₁ b₀ b₁ : c.Index → ℝ)
    (ha₀ : ∀ i, |a₀ i| ≤ 1) (ha₁ : ∀ i, |a₁ i| ≤ 1)
    (hb₀ : ∀ i, |b₀ i| ≤ 1) (hb₁ : ∀ i, |b₁ i| ≤ 1) :
    ‖(M * diagonalChsh a₀ a₁ b₀ b₁).trace‖ ≤ 2 :=
  (reachable_isRecordLaw h).chsh_le_two a₀ a₁ b₀ b₁ ha₀ ha₁ hb₀ hb₁

/-- **Premise-free real arithmetic.**  The classical bound sits strictly
below the committed witness value. -/
theorem classical_bound_lt_saturation : (2 : ℝ) < 2 * Real.sqrt 2 := by
  have h1 : (1 : ℝ) < Real.sqrt 2 := by
    rw [show (1 : ℝ) = Real.sqrt 1 from Real.sqrt_one.symm]
    exact Real.sqrt_lt_sqrt (by norm_num) (by norm_num)
  linarith

/-- **Trace-dependent.**  No reachable state attains the committed
saturation value `2√2` through jointly record-diagonal readouts. -/
theorem reachable_not_tsirelson_saturating {c : Carrier}
    {M : Matrix c.Index c.Index ℂ} (h : Reachable c M)
    (a₀ a₁ b₀ b₁ : c.Index → ℝ)
    (ha₀ : ∀ i, |a₀ i| ≤ 1) (ha₁ : ∀ i, |a₁ i| ≤ 1)
    (hb₀ : ∀ i, |b₀ i| ≤ 1) (hb₁ : ∀ i, |b₁ i| ≤ 1) :
    ‖(M * diagonalChsh a₀ a₁ b₀ b₁).trace‖ ≠ 2 * Real.sqrt 2 := by
  intro heq
  have hle := reachable_diagonal_chsh_le_two h a₀ a₁ b₀ b₁ ha₀ ha₁ hb₀ hb₁
  rw [heq] at hle
  exact absurd hle (not_le.mpr classical_bound_lt_saturation)

/-! ## The exact non-diagonal obstruction -/

/-- The declared saturating state carries the explicit off-diagonal
record entry `2⁻¹` at the pair `((0,0), (1,1))` of the product
carrier. -/
theorem bellStateProd_offdiag_entry :
    EventAlgebra.TsirelsonSaturation.bellStateProd
      ((0 : Fin 2), (0 : Fin 2)) ((1 : Fin 2), (1 : Fin 2)) = 2⁻¹ := by
  norm_num [EventAlgebra.TsirelsonSaturation.bellStateProd,
    OPH.Dynamics.maxEntangled, Matrix.smul_apply, Matrix.vecMulVec_apply,
    Pi.star_apply]

/-- The declared saturating state on the product carrier is not
record-diagonal. -/
theorem bellStateProd_not_recordDiagonal :
    ¬ IsRecordDiagonal EventAlgebra.TsirelsonSaturation.bellStateProd := by
  intro h
  have hne : ((0, 0) : Fin 2 × Fin 2) ≠ (1, 1) := by decide
  have h0 := h _ _ hne
  rw [bellStateProd_offdiag_entry] at h0
  norm_num at h0

/-- **The obstruction.**  The declared saturating state
`EventAlgebra.TsirelsonSaturation.bellState` is not record-diagonal: the
transported off-diagonal entry `2⁻¹` survives the fixed carrier
equivalence. -/
theorem bellState_not_recordDiagonal :
    ¬ IsRecordDiagonal EventAlgebra.TsirelsonSaturation.bellState := by
  intro h
  apply bellStateProd_not_recordDiagonal
  intro p q hpq
  have hne : EventAlgebra.TsirelsonSaturation.carrierEquiv p ≠
      EventAlgebra.TsirelsonSaturation.carrierEquiv q :=
    fun hc => hpq (EventAlgebra.TsirelsonSaturation.carrierEquiv.injective hc)
  have hval := h _ _ hne
  rwa [show EventAlgebra.TsirelsonSaturation.bellState
        (EventAlgebra.TsirelsonSaturation.carrierEquiv p)
        (EventAlgebra.TsirelsonSaturation.carrierEquiv q) =
      EventAlgebra.TsirelsonSaturation.bellStateProd p q from by
    show (Matrix.reindex EventAlgebra.TsirelsonSaturation.carrierEquiv
        EventAlgebra.TsirelsonSaturation.carrierEquiv
        EventAlgebra.TsirelsonSaturation.bellStateProd) _ _ = _
    rw [Matrix.reindex_apply, Matrix.submatrix_apply,
      Equiv.symm_apply_apply, Equiv.symm_apply_apply]] at hval

/-- No enumerated committed carrier is equinumerous with the four-point
witness carrier; this records that the transport-form obstruction below
is quantified over diagonality-preserving maps, and the load-bearing
content is the record-diagonality closure on the class's own carriers. -/
theorem no_committed_carrier_equiv_fin4 (c : Carrier) :
    IsEmpty (c.Index ≃ Fin 4) := by
  cases c with
  | hinge13 =>
      constructor; intro e
      exact absurd (Fin.equiv_iff_eq.mp ⟨e⟩) (by norm_num)
  | hinge14 =>
      constructor; intro e
      exact absurd (Fin.equiv_iff_eq.mp ⟨e⟩) (by norm_num)
  | pair247 =>
      constructor; intro e
      exact absurd (Fin.equiv_iff_eq.mp ⟨pairFin247.symm.trans e⟩)
        (by norm_num)
  | pair88 =>
      constructor; intro e
      exact absurd (Fin.equiv_iff_eq.mp ⟨pairFin.symm.trans e⟩)
        (by norm_num)
  | triple =>
      constructor; intro e
      have etriple : TripleCarrier ≃ Fin (182 * 13) :=
        (pairFin.prodCongr (Equiv.refl (Fin 13))).trans finProdFinEquiv
      exact absurd (Fin.equiv_iff_eq.mp ⟨etriple.symm.trans e⟩)
        (by norm_num)
  | amb169 =>
      constructor; intro e
      exact absurd (Fin.equiv_iff_eq.mp ⟨e⟩) (by norm_num)
  | amb182 =>
      constructor; intro e
      exact absurd (Fin.equiv_iff_eq.mp ⟨e⟩) (by norm_num)

/-- **The target-specific obstruction.**  Producing the declared Bell-state
witness from any reachable state requires a map that breaks
record-diagonality: every record-diagonality-preserving map sends every
reachable state away from `bellState`.  The enumerated committed
operations all preserve record-diagonality (the closure theorem).  The
theorem does not say that every state/readout realization of the same CHSH
value requires non-diagonal preparation; arbitrary non-jointly-diagonal or
contextual readouts are outside its hypotheses. -/
theorem bellState_target_requires_nondiagonal_production {c : Carrier}
    {M : Matrix c.Index c.Index ℂ} (h : Reachable c M)
    (T : Matrix c.Index c.Index ℂ → Matrix (Fin 4) (Fin 4) ℂ)
    (hT : ∀ N, IsRecordDiagonal N → IsRecordDiagonal (T N)) :
    T M ≠ EventAlgebra.TsirelsonSaturation.bellState := by
  intro heq
  exact bellState_not_recordDiagonal
    (heq ▸ hT M (reachable_recordDiagonal h))

/-! ## The composed receipt -/

/-- **The source-reachability delimitation receipt.**  One conjunction:

1. **Nonvacuity**: the class contains the committed counted state and
   the committed observer-86 marginal;
2. **Closure**: every reachable state is record-diagonal, positive
   semidefinite, and of trace one;
3. **Classical bound**: every reachable state on every enumerated
   carrier obeys CHSH `≤ 2` against every four jointly record-diagonal
   `[-1,1]`-valued readouts, and `2 < 2√2`;
4. **Obstruction**: the declared saturating state is not
   record-diagonal, and every record-diagonality-preserving map sends
   every reachable state away from it.

Boundary, stated exactly: the class is the enumerated committed class
and nothing else; the bound covers jointly record-diagonal readouts
only; non-jointly-diagonal readouts on reachable states are not covered
by this module; the declared witness of
`EventAlgebra.TsirelsonSaturation` stays a declared result, and source
entangled preparation stays open (PR-52; OL-C3 realization clause). -/
theorem source_reachability_receipt :
    Reachable .pair247 correlationState ∧
    Reachable .hinge13 marginal86State ∧
    (∀ (c : Carrier) (M : Matrix c.Index c.Index ℂ), Reachable c M →
      IsRecordDiagonal M ∧ M.PosSemidef ∧ M.trace = 1) ∧
    (∀ (c : Carrier) (M : Matrix c.Index c.Index ℂ), Reachable c M →
      ∀ a₀ a₁ b₀ b₁ : c.Index → ℝ,
        (∀ i, |a₀ i| ≤ 1) → (∀ i, |a₁ i| ≤ 1) →
        (∀ i, |b₀ i| ≤ 1) → (∀ i, |b₁ i| ≤ 1) →
        ‖(M * diagonalChsh a₀ a₁ b₀ b₁).trace‖ ≤ 2) ∧
    (2 : ℝ) < 2 * Real.sqrt 2 ∧
    ¬ IsRecordDiagonal EventAlgebra.TsirelsonSaturation.bellState ∧
    (∀ (c : Carrier) (M : Matrix c.Index c.Index ℂ), Reachable c M →
      ∀ T : Matrix c.Index c.Index ℂ → Matrix (Fin 4) (Fin 4) ℂ,
        (∀ N, IsRecordDiagonal N → IsRecordDiagonal (T N)) →
        T M ≠ EventAlgebra.TsirelsonSaturation.bellState) :=
  ⟨correlationState_reachable, marginal86State_reachable,
    fun _ _ h => ⟨reachable_recordDiagonal h,
      (reachable_state_certificate h).1, (reachable_state_certificate h).2⟩,
    fun _ _ h a₀ a₁ b₀ b₁ ha₀ ha₁ hb₀ hb₁ =>
      reachable_diagonal_chsh_le_two h a₀ a₁ b₀ b₁ ha₀ ha₁ hb₀ hb₁,
    classical_bound_lt_saturation, bellState_not_recordDiagonal,
    fun _ _ h T hT => bellState_target_requires_nondiagonal_production h T hT⟩

end

end EventAlgebra.SourceReachability

-- Axiom audit: each must report only `[propext, Classical.choice, Quot.sound]`.
-- No native_decide is used anywhere in this module.
#print axioms EventAlgebra.SourceReachability.isRecordLaw_countDiagonal
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.recordDiagonal
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.trace_one
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.posSemidef
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.reindex
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.ptraceSnd
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.ptraceFst
#print axioms EventAlgebra.SourceReachability.ptraceMiddle_diagonal
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.ptraceMiddle
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.kronecker
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.leftSlotExpectation
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.rightSlotExpectation
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.scalarExpectation
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.mix
#print axioms EventAlgebra.SourceReachability.correlationState_reachable
#print axioms EventAlgebra.SourceReachability.marginal86State_reachable
#print axioms EventAlgebra.SourceReachability.jointCount88_total
#print axioms EventAlgebra.SourceReachability.isRecordLaw_correlationState
#print axioms EventAlgebra.SourceReachability.isRecordLaw_correlationState88
#print axioms EventAlgebra.SourceReachability.isRecordLaw_tripleCorrelationState
#print axioms EventAlgebra.SourceReachability.reachable_isRecordLaw
#print axioms EventAlgebra.SourceReachability.reachable_recordDiagonal
#print axioms EventAlgebra.SourceReachability.reachable_state_certificate
#print axioms EventAlgebra.SourceReachability.IsRecordLaw.chsh_le_two
#print axioms EventAlgebra.SourceReachability.reachable_diagonal_chsh_le_two
#print axioms EventAlgebra.SourceReachability.classical_bound_lt_saturation
#print axioms EventAlgebra.SourceReachability.reachable_not_tsirelson_saturating
#print axioms EventAlgebra.SourceReachability.bellStateProd_offdiag_entry
#print axioms EventAlgebra.SourceReachability.bellStateProd_not_recordDiagonal
#print axioms EventAlgebra.SourceReachability.bellState_not_recordDiagonal
#print axioms EventAlgebra.SourceReachability.no_committed_carrier_equiv_fin4
#print axioms EventAlgebra.SourceReachability.bellState_target_requires_nondiagonal_production
#print axioms EventAlgebra.SourceReachability.source_reachability_receipt
