import Mathlib.Analysis.Normed.Operator.ContinuousAlgEquiv
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.Deriv.Mul

/-!
# Finite private dynamics on a full matrix block

This module records the private counterpart to finite public stochasticity.
On a finite-dimensional complex Hilbert space, every star-algebra
automorphism of the full continuous-endomorphism algebra is implemented by a
unitary linear isometry.  Exponential conjugation has its exact commutator
derivative, and a self-adjoint Hamiltonian gives a unitary real-parameter
propagator.  The statements concern one simple full-matrix block.  A
classification of arbitrary finite direct sums by central blocks is a
separate obligation.
-/

namespace OPH.Dynamics

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H] [FiniteDimensional ℂ H]

abbrev PrivateEnd := H →L[ℂ] H

/-- Every star-algebra automorphism of a finite full private matrix block is
unitarily inner. -/
theorem finitePrivateStarAutomorphism_inner
    (F : PrivateEnd (H := H) ≃⋆ₐ[ℂ] PrivateEnd (H := H)) :
    ∃ U : H ≃ₗᵢ[ℂ] H, F = U.conjStarAlgEquiv := by
  apply StarAlgEquiv.eq_linearIsometryEquivConjStarAlgEquiv F
  exact LinearMap.continuous_of_finiteDimensional
    F.toAlgEquiv.toLinearEquiv.toLinearMap

/-! ## Exponential inner flow and the von Neumann equation -/

/-- The inner exponential flow generated by `A`.  Complex time is used for
the derivative statement; the Hamiltonian specialization below identifies
the unitary real-parameter slice. -/
noncomputable def innerExponentialFlow
    (A rho : PrivateEnd (H := H)) (t : ℂ) : PrivateEnd (H := H) :=
  NormedSpace.exp (t • A) * rho * NormedSpace.exp (t • (-A))

omit [FiniteDimensional ℂ H] in
/-- Exponential conjugation differentiates to the commutator with its fixed
generator. -/
theorem hasDerivAt_innerExponentialFlow
    (A rho : PrivateEnd (H := H)) (t : ℂ) :
    HasDerivAt (innerExponentialFlow A rho)
      (A * innerExponentialFlow A rho t -
        innerExponentialFlow A rho t * A) t := by
  have hleft := (hasDerivAt_exp_smul_const A t).mul_const rho
  have hright := hasDerivAt_exp_smul_const (-A) t
  have hprod := hleft.mul hright
  convert hprod using 1
  have hcommLeft :
      Commute (NormedSpace.exp (t • A)) A :=
    ((Commute.refl A).smul_left t).exp_left
  simp only [innerExponentialFlow]
  rw [hcommLeft.eq]
  noncomm_ring

omit [FiniteDimensional ℂ H] in
/-- The Hamiltonian specialization of the commutator derivative.  In the
usual notation this is `d rho / dt = -i [H, rho]`. -/
theorem hasDerivAt_vonNeumannFlow
    (ham rho : PrivateEnd (H := H)) (t : ℂ) :
    HasDerivAt (innerExponentialFlow ((-Complex.I) • ham) rho)
      ((-Complex.I) •
        (ham * innerExponentialFlow ((-Complex.I) • ham) rho t -
          innerExponentialFlow ((-Complex.I) • ham) rho t * ham)) t := by
  convert hasDerivAt_innerExponentialFlow ((-Complex.I) • ham) rho t using 1
  simp [smul_sub]

/-- The real-parameter inner exponential flow. -/
noncomputable def realInnerExponentialFlow
    (A rho : PrivateEnd (H := H)) (t : ℝ) : PrivateEnd (H := H) :=
  NormedSpace.exp (t • A) * rho * NormedSpace.exp (t • (-A))

omit [FiniteDimensional ℂ H] in
/-- Real-parameter exponential conjugation has the same exact commutator
derivative. -/
theorem hasDerivAt_realInnerExponentialFlow
    (A rho : PrivateEnd (H := H)) (t : ℝ) :
    HasDerivAt (realInnerExponentialFlow A rho)
      (A * realInnerExponentialFlow A rho t -
        realInnerExponentialFlow A rho t * A) t := by
  have hleft := (hasDerivAt_exp_smul_const A t).mul_const rho
  have hright := hasDerivAt_exp_smul_const (-A) t
  have hprod := hleft.mul hright
  convert hprod using 1
  have hcommLeft :
      Commute (NormedSpace.exp (t • A)) A :=
    ((Commute.refl A).smul_left t).exp_left
  simp only [realInnerExponentialFlow]
  rw [hcommLeft.eq]
  noncomm_ring

omit [FiniteDimensional ℂ H] in
/-- The von Neumann equation on a real parameter, with no physical-clock claim. -/
theorem hasDerivAt_realVonNeumannFlow
    (ham rho : PrivateEnd (H := H)) (t : ℝ) :
    HasDerivAt (realInnerExponentialFlow ((-Complex.I) • ham) rho)
      ((-Complex.I) •
        (ham * realInnerExponentialFlow ((-Complex.I) • ham) rho t -
          realInnerExponentialFlow ((-Complex.I) • ham) rho t * ham)) t := by
  convert hasDerivAt_realInnerExponentialFlow
    ((-Complex.I) • ham) rho t using 1
  simp [smul_sub]

omit [FiniteDimensional ℂ H] in
/-- A self-adjoint finite Hamiltonian gives a unitary propagator on every
real-parameter slice. -/
theorem hamiltonianPropagator_mem_unitary
    (ham : PrivateEnd (H := H)) (hham : IsSelfAdjoint ham) (t : ℝ) :
    NormedSpace.exp (t • ((-Complex.I) • ham)) ∈
      unitary (PrivateEnd (H := H)) := by
  let +nondep : NormedAlgebra ℚ (PrivateEnd (H := H)) :=
    .restrictScalars ℚ ℂ (PrivateEnd (H := H))
  apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
  apply skewAdjoint.smul_mem t
  apply hham.smul_mem_skewAdjoint
  rw [skewAdjoint.mem_iff]
  simp

#print axioms OPH.Dynamics.finitePrivateStarAutomorphism_inner
#print axioms OPH.Dynamics.hasDerivAt_innerExponentialFlow
#print axioms OPH.Dynamics.hasDerivAt_vonNeumannFlow
#print axioms OPH.Dynamics.hasDerivAt_realVonNeumannFlow
#print axioms OPH.Dynamics.hamiltonianPropagator_mem_unitary

end OPH.Dynamics
