import Mathlib.LinearAlgebra.Matrix.DotProduct
import Mathlib.LinearAlgebra.Matrix.Trace
import Mathlib.LinearAlgebra.Dimension.Free
import Mathlib.Algebra.GroupWithZero.Pi
import Mathlib.Algebra.Star.Pi
import Mathlib.Algebra.BigOperators.Pi
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.List.OfFn
import Dynamics.CenterSpectral

/-!
# Star Wedderburn classification and the finite-block Stone converse

`CenterSpectral.lean` resolves the identity of a star subalgebra of a finite
complex matrix algebra into minimal orthogonal central projections.  This
module carries steps 2 and 3 of the remaining gap of issue 679: the
classification of each minimal central corner as one full matrix block, and
the Stone converse on an arbitrary finite direct sum of full matrix blocks.

1. Projection order inside a star subalgebra: star projections of `S`
   (`IsProjectionIn`), minimal star projections of `S`
   (`IsMinimalProjectionIn`), the corner submodule cut by a projection
   (`projCorner`), and strict corner descent.  Every nonzero star
   projection of `S` splits into a finite orthogonal family of minimal
   projections of `S` (`IsProjectionIn.exists_minimal_decomposition`).
2. Scalar corners: against a minimal projection of `S` the corner of every
   element of `S` is scalar (`IsMinimalProjectionIn.corner_smul`), by
   cutting the spectral projections of the self-adjoint parts.
3. Partial isometries: between two minimal projections of `S` joined by a
   nonzero element of `S`, a partial isometry of `S` exists
   (`exists_partial_isometry`), by trace normalization.
4. The connecting ideal: inside a minimal central corner every two minimal
   projections are joined (`exists_connecting_element`), because the
   two-sided ideal generated by a subordinate projection carries a support
   projection that is central in `S` and is forced to be the whole central
   corner unit.
5. Star Wedderburn for one corner: every minimal central corner of `S` is
   star-isomorphic to one full matrix block
   (`minimalCentralCorner_starEquiv_matrix`), through a matrix-unit system
   built from a maximal orthogonal family of minimal projections.  The
   relative center of the corner is scalar
   (`IsMinimalCentralProjectionIn.corner_center_scalar`).
6. Star Wedderburn for `S`: the iterated cut along a minimal central
   resolution factors `S` as a finite direct product of its corners
   (`centralResolutionEquiv`), so `S` is star-isomorphic to a finite
   direct sum of full matrix blocks (`starSubalgebra_starEquiv_pi_matrix`).
7. The finite-block Stone converse: on an arbitrary finite direct sum of
   full matrix blocks, every pointwise-continuous real-parameter
   star-automorphism group fixes every block projection
   (`continuousFlow_fixes_piBlockProjection`), acts blockwise, and is
   blockwise conjugation by the coherent unitary family of one
   time-independent self-adjoint Hamiltonian per block
   (`piBlockStoneConverse_of_continuous`).
8. Flow rigidity on the subalgebra: every minimal central projection of
   `S` is a member of every minimal central resolution
   (`IsMinimalCentralProjectionIn.mem_resolution`), star automorphisms of
   `S` permute the minimal central projections
   (`IsMinimalCentralProjectionIn.map_subtype`), and every
   pointwise-continuous star-automorphism family of `S` through the
   identity fixes each minimal central projection
   (`continuousFlow_fixes_minimalCentralProjection`) and acts on every
   minimal central corner (`continuousFlow_maps_relativeCorner`).
9. The composed closure statement of the gap
   (`starWedderburn_stone_closure`,
   `starSubalgebraStoneConverse_of_continuous`): every star subalgebra of
   a finite complex matrix algebra is star-isomorphic to a finite direct
   sum of full matrix blocks, and every pointwise-continuous
   real-parameter star-automorphism group, on the block model or on the
   subalgebra itself, is blockwise conjugation by the coherent unitary
   family of one time-independent self-adjoint Hamiltonian per Wedderburn
   block.

No physical clock, source-selected Hamiltonian, or physical time
identification is claimed; the parameter is a real number.
-/

namespace OPH.Dynamics

universe u v w

open Polynomial

/-! ## Star projections of a star subalgebra and corner descent -/

section ProjectionOrder

variable {A : Type u} [Ring A] [StarRing A] [Algebra ℂ A] [StarModule ℂ A]

/-- A star projection lying in a star subalgebra. -/
structure IsProjectionIn (S : StarSubalgebra ℂ A) (p : A) : Prop
    extends IsStarProjection p where
  mem : p ∈ S

/-- A minimal star projection of a star subalgebra: a nonzero star
projection of the subalgebra whose only subprojections inside the
subalgebra are zero and itself. -/
structure IsMinimalProjectionIn (S : StarSubalgebra ℂ A) (p : A) :
    Prop extends IsProjectionIn S p where
  ne_zero : p ≠ 0
  minimal : ∀ q, IsProjectionIn S q → q * p = q → q = 0 ∨ q = p

variable {S : StarSubalgebra ℂ A}

/-- A central projection of the subalgebra is a projection of the
subalgebra. -/
theorem IsCentralProjectionIn.isProjectionIn {p : A}
    (hp : IsCentralProjectionIn S p) : IsProjectionIn S p where
  toIsStarProjection := hp.toIsStarProjection
  mem := hp.centralIn.mem

/-- Subordination between star projections is two-sided. -/
theorem IsProjectionIn.absorb_left {p q : A} (hp : IsProjectionIn S p)
    (hq : IsProjectionIn S q) (hle : q * p = q) : p * q = q := by
  have h1 := congrArg star hle
  rwa [star_mul, hp.isSelfAdjoint.star_eq, hq.isSelfAdjoint.star_eq] at h1

/-- The difference of a star projection and a subordinate star projection
is a star projection of the subalgebra. -/
theorem IsProjectionIn.sub {p q : A} (hp : IsProjectionIn S p)
    (hq : IsProjectionIn S q) (hle : q * p = q) :
    IsProjectionIn S (p - q) where
  isIdempotentElem := by
    have hpq : p * q = q := hp.absorb_left hq hle
    show (p - q) * (p - q) = p - q
    rw [sub_mul, mul_sub, mul_sub, hp.isIdempotentElem.eq, hpq, hle,
      hq.isIdempotentElem.eq]
    abel
  isSelfAdjoint := hp.isSelfAdjoint.sub hq.isSelfAdjoint
  mem := sub_mem hp.mem hq.mem

/-- The two-sided corner of the subalgebra cut by an element, as a complex
submodule of the ambient algebra. -/
def projCorner (S : StarSubalgebra ℂ A) (p : A) : Submodule ℂ A :=
  Submodule.map ((LinearMap.mulLeft ℂ p).comp (LinearMap.mulRight ℂ p))
    (Subalgebra.toSubmodule S.toSubalgebra)

/-- Corner membership for a star projection: membership in the subalgebra
together with two-sided absorption. -/
theorem mem_projCorner_iff {p x : A} (hp : IsProjectionIn S p) :
    x ∈ projCorner S p ↔ x ∈ S ∧ p * x = x ∧ x * p = x := by
  constructor
  · rintro ⟨z, hz, rfl⟩
    have hzS : z ∈ S := hz
    refine ⟨mul_mem hp.mem (mul_mem hzS hp.mem), ?_, ?_⟩
    · show p * (p * (z * p)) = p * (z * p)
      rw [← mul_assoc, hp.isIdempotentElem.eq]
    · show p * (z * p) * p = p * (z * p)
      rw [mul_assoc, mul_assoc, hp.isIdempotentElem.eq]
  · rintro ⟨hxS, hpx, hxp⟩
    refine ⟨x, hxS, ?_⟩
    show p * (x * p) = x
    rw [hxp, hpx]

/-- A star projection lies in its own corner. -/
theorem self_mem_projCorner {p : A} (hp : IsProjectionIn S p) :
    p ∈ projCorner S p :=
  (mem_projCorner_iff hp).mpr
    ⟨hp.mem, hp.isIdempotentElem.eq, hp.isIdempotentElem.eq⟩

/-- The corner of a subordinate projection is contained in the corner of
the projection. -/
theorem projCorner_le {p q : A} (hp : IsProjectionIn S p)
    (hq : IsProjectionIn S q) (hle : q * p = q) :
    projCorner S q ≤ projCorner S p := by
  intro x hx
  obtain ⟨hxS, hqx, hxq⟩ := (mem_projCorner_iff hq).mp hx
  have hpq : p * q = q := hp.absorb_left hq hle
  refine (mem_projCorner_iff hp).mpr ⟨hxS, ?_, ?_⟩
  · rw [← hqx, ← mul_assoc, hpq]
  · rw [← hxq, mul_assoc, hle]

/-- A projection is outside the corner of any proper subordinate
projection. -/
theorem notMem_projCorner {p q : A} (hq : IsProjectionIn S q)
    (hle : q * p = q) (hne : q ≠ p) : p ∉ projCorner S q := by
  intro hmem
  obtain ⟨_, hqp, _⟩ := (mem_projCorner_iff hq).mp hmem
  exact hne (hle.symm.trans hqp)

/-- Strict corner descent for proper subordinate projections. -/
theorem projCorner_lt {p q : A} (hp : IsProjectionIn S p)
    (hq : IsProjectionIn S q) (hle : q * p = q) (hne : q ≠ p) :
    projCorner S q < projCorner S p := by
  refine lt_of_le_of_ne (projCorner_le hp hq hle) (fun h => ?_)
  exact notMem_projCorner hq hle hne (h ▸ self_mem_projCorner hp)

/-- Every nonzero star projection of a star subalgebra of a
finite-dimensional complex star algebra dominates a minimal star
projection of the subalgebra. -/
theorem IsProjectionIn.exists_minimal_le [FiniteDimensional ℂ A] {p : A}
    (hp : IsProjectionIn S p) (hp0 : p ≠ 0) :
    ∃ r : A, IsMinimalProjectionIn S r ∧ r * p = r := by
  suffices H : ∀ N : ℕ, ∀ p : A, IsProjectionIn S p → p ≠ 0 →
      Module.finrank ℂ (projCorner S p) ≤ N →
      ∃ r : A, IsMinimalProjectionIn S r ∧ r * p = r by
    exact H (Module.finrank ℂ (projCorner S p)) p hp hp0 le_rfl
  intro N
  induction N with
  | zero =>
    intro p hp hp0 hrank
    exfalso
    have hbot : projCorner S p = ⊥ :=
      Submodule.finrank_eq_zero.mp (Nat.le_zero.mp hrank)
    have := self_mem_projCorner hp
    rw [hbot, Submodule.mem_bot] at this
    exact hp0 this
  | succ N IH =>
    intro p hp hp0 hrank
    by_cases hmin : ∀ q, IsProjectionIn S q → q * p = q → q = 0 ∨ q = p
    · exact ⟨p, ⟨hp, hp0, hmin⟩, hp.isIdempotentElem.eq⟩
    · push Not at hmin
      obtain ⟨q, hq, hqle, hq0, hqne⟩ := hmin
      have hqrank : Module.finrank ℂ (projCorner S q) ≤ N :=
        Nat.lt_succ_iff.mp (lt_of_lt_of_le
          (Submodule.finrank_lt_finrank_of_lt
            (projCorner_lt hp hq hqle hqne)) hrank)
      obtain ⟨r, hr, hrq⟩ := IH q hq hq0 hqrank
      exact ⟨r, hr, by rw [← hrq, mul_assoc, hqle]⟩

/-- Every star projection of a star subalgebra of a finite-dimensional
complex star algebra decomposes into a finite orthogonal family of
minimal star projections of the subalgebra summing to it. -/
theorem IsProjectionIn.exists_minimal_decomposition
    [FiniteDimensional ℂ A] {p : A} (hp : IsProjectionIn S p) :
    ∃ l : List A, (∀ e ∈ l, IsMinimalProjectionIn S e) ∧
      l.Pairwise (fun a b => a * b = 0) ∧ (∀ e ∈ l, e * p = e) ∧
      l.sum = p := by
  suffices H : ∀ N : ℕ, ∀ p : A, IsProjectionIn S p →
      Module.finrank ℂ (projCorner S p) ≤ N →
      ∃ l : List A, (∀ e ∈ l, IsMinimalProjectionIn S e) ∧
        l.Pairwise (fun a b => a * b = 0) ∧ (∀ e ∈ l, e * p = e) ∧
        l.sum = p by
    exact H (Module.finrank ℂ (projCorner S p)) p hp le_rfl
  intro N
  induction N with
  | zero =>
    intro p hp hrank
    have hbot : projCorner S p = ⊥ :=
      Submodule.finrank_eq_zero.mp (Nat.le_zero.mp hrank)
    have hp0 : p = 0 := by
      have := self_mem_projCorner hp
      rw [hbot, Submodule.mem_bot] at this
      exact this
    exact ⟨[], by simp, by simp, by simp, by rw [List.sum_nil, hp0]⟩
  | succ N IH =>
    intro p hp hrank
    by_cases hp0 : p = 0
    · exact ⟨[], by simp, by simp, by simp, by rw [List.sum_nil, hp0]⟩
    by_cases hmin : ∀ q, IsProjectionIn S q → q * p = q → q = 0 ∨ q = p
    · refine ⟨[p], ?_, List.pairwise_singleton _ p, ?_, List.sum_singleton⟩
      · intro e he
        rw [List.mem_singleton] at he
        subst he
        exact ⟨hp, hp0, hmin⟩
      · intro e he
        rw [List.mem_singleton] at he
        subst he
        exact hp.isIdempotentElem.eq
    · push Not at hmin
      obtain ⟨q, hq, hqle, hq0, hqne⟩ := hmin
      have hpq : IsProjectionIn S (p - q) := hp.sub hq hqle
      have hsuble : (p - q) * p = p - q := by
        rw [sub_mul, hp.isIdempotentElem.eq, hqle]
      have hsubne : p - q ≠ p := by
        intro h1
        apply hq0
        have h2 : p - (p - q) = p - p := by rw [h1]
        simpa using h2
      have hqrank : Module.finrank ℂ (projCorner S q) ≤ N :=
        Nat.lt_succ_iff.mp (lt_of_lt_of_le
          (Submodule.finrank_lt_finrank_of_lt
            (projCorner_lt hp hq hqle hqne)) hrank)
      have hsubrank : Module.finrank ℂ (projCorner S (p - q)) ≤ N :=
        Nat.lt_succ_iff.mp (lt_of_lt_of_le
          (Submodule.finrank_lt_finrank_of_lt
            (projCorner_lt hp hpq hsuble hsubne)) hrank)
      obtain ⟨l₁, h₁min, h₁orth, h₁le, h₁sum⟩ := IH q hq hqrank
      obtain ⟨l₂, h₂min, h₂orth, h₂le, h₂sum⟩ := IH (p - q) hpq hsubrank
      have hqsub : q * (p - q) = 0 := by
        rw [mul_sub, hqle, hq.isIdempotentElem.eq, sub_self]
      have hcross : ∀ a ∈ l₁, ∀ b ∈ l₂, a * b = 0 := by
        intro a ha b hb
        have hb' : (p - q) * b = b :=
          hpq.absorb_left (h₂min b hb).toIsProjectionIn (h₂le b hb)
        calc a * b = (a * q) * ((p - q) * b) := by rw [h₁le a ha, hb']
          _ = a * (q * ((p - q) * b)) := by rw [mul_assoc]
          _ = a * ((q * (p - q)) * b) := by rw [← mul_assoc q _ b]
          _ = 0 := by rw [hqsub, zero_mul, mul_zero]
      refine ⟨l₁ ++ l₂, ?_, ?_, ?_, ?_⟩
      · intro e he
        rcases List.mem_append.mp he with h1 | h2
        · exact h₁min e h1
        · exact h₂min e h2
      · exact List.pairwise_append.mpr ⟨h₁orth, h₂orth, hcross⟩
      · intro e he
        rcases List.mem_append.mp he with h1 | h2
        · rw [← h₁le e h1, mul_assoc, hqle]
        · rw [← h₂le e h2, mul_assoc, hsuble]
      · rw [List.sum_append, h₁sum, h₂sum, add_comm, sub_add_cancel]

end ProjectionOrder

/-! ## Scalar corners against a minimal projection -/

section ScalarCorner

variable {A : Type u} [Ring A] [StarRing A] [Algebra ℂ A] [StarModule ℂ A]
  {S : StarSubalgebra ℂ A}

/-- Polynomial functional calculus stays inside a star subalgebra
containing the element. -/
theorem aeval_mem_of_mem {h : A} (hh : h ∈ S) (q : Polynomial ℂ) :
    Polynomial.aeval h q ∈ S := by
  have hle : Algebra.adjoin ℂ ({h} : Set A) ≤ S.toSubalgebra :=
    Algebra.adjoin_le (Set.singleton_subset_iff.mpr
      (StarSubalgebra.mem_toSubalgebra.mpr hh))
  exact StarSubalgebra.mem_toSubalgebra.mp
    (hle (Polynomial.aeval_mem_adjoin_singleton ℂ h))

omit [StarRing A] [StarModule ℂ A] in
/-- An element commuting with the argument commutes with every polynomial
in the argument. -/
theorem commute_aeval_of_commute {p h : A} (hcomm : p * h = h * p)
    (q : Polynomial ℂ) :
    p * Polynomial.aeval h q = Polynomial.aeval h q * p := by
  have hmem : h ∈ Subalgebra.centralizer ℂ ({p} : Set A) :=
    (Subalgebra.mem_centralizer_iff ℂ).mpr
      (fun g hg => by rw [Set.mem_singleton_iff] at hg; rw [hg]; exact hcomm)
  have hle : Algebra.adjoin ℂ ({h} : Set A) ≤
      Subalgebra.centralizer ℂ ({p} : Set A) :=
    Algebra.adjoin_le (Set.singleton_subset_iff.mpr hmem)
  exact (Subalgebra.mem_centralizer_iff ℂ).mp
    (hle (Polynomial.aeval_mem_adjoin_singleton ℂ h (p := q))) p rfl

end ScalarCorner

section MatrixScalarCorner

variable {n : Type u} [Fintype n] [DecidableEq n]
  {S : StarSubalgebra ℂ (Matrix n n ℂ)}

omit [Fintype n] [DecidableEq n] in
/-- A nonzero matrix forces a nonempty index type. -/
theorem nonempty_of_matrix_ne_zero {M : Matrix n n ℂ} (hM : M ≠ 0) :
    Nonempty n := by
  by_contra hn
  rw [not_nonempty_iff] at hn
  exact hM (Matrix.ext fun i _ => (hn.false i).elim)

/-- Against a minimal projection of the subalgebra, every self-adjoint
element of the two-sided corner is a real multiple of the projection:
each spectral projection of the element is cut to a subprojection of the
minimal projection and survives as zero or the whole projection. -/
theorem IsMinimalProjectionIn.selfAdjoint_corner_smul
    {p h : Matrix n n ℂ} (hp : IsMinimalProjectionIn S p)
    (hh : h ∈ S) (hsa : IsSelfAdjoint h)
    (hph : p * h = h) (hhp : h * p = h) :
    ∃ c : ℂ, h = c • p := by
  classical
  haveI : Nonempty n := nonempty_of_matrix_ne_zero hp.ne_zero
  have hcommph : p * h = h * p := by rw [hph, hhp]
  set T := spectralSupport hsa.isHermitian with hT
  set π : ℂ → Matrix n n ℂ := spectralProjection hsa.isHermitian with hπ
  have hπcomm : ∀ a : ℂ, p * π a = π a * p := fun a =>
    commute_aeval_of_commute hcommph _
  have hπproj : ∀ a ∈ T, IsProjectionIn S (π a * p) := by
    intro a ha
    refine ⟨⟨?_, ?_⟩, mul_mem (aeval_mem_of_mem hh _) hp.mem⟩
    · show π a * p * (π a * p) = π a * p
      calc π a * p * (π a * p)
          = π a * ((p * π a) * p) := by rw [mul_assoc, ← mul_assoc p (π a) p]
        _ = π a * ((π a * p) * p) := by rw [hπcomm a]
        _ = (π a * π a) * (p * p) := by rw [mul_assoc, ← mul_assoc,
            ← mul_assoc]
        _ = π a * p := by
            rw [hp.isIdempotentElem.eq,
              (isIdempotentElem_spectralProjection _ ha).eq]
    · show star (π a * p) = π a * p
      rw [star_mul, hp.isSelfAdjoint.star_eq,
        (isSelfAdjoint_spectralProjection _ ha).star_eq]
      exact hπcomm a
  have hπle : ∀ a : ℂ, (π a * p) * p = π a * p := by
    intro a
    rw [mul_assoc, hp.isIdempotentElem.eq]
  have hcases : ∀ a ∈ T, π a * p = 0 ∨ π a * p = p := fun a ha =>
    hp.minimal _ (hπproj a ha) (hπle a)
  have hrec : h = ∑ a ∈ T, a • (π a * p) := by
    conv_lhs => rw [← hhp, eq_sum_smul_spectralProjection hsa.isHermitian,
      Finset.sum_mul]
    exact Finset.sum_congr rfl (fun a _ => smul_mul_assoc a (π a) p)
  set F := T.filter (fun a => π a * p ≠ 0) with hF
  have hfilter : ∑ a ∈ F, a • (π a * p) = ∑ a ∈ T, a • (π a * p) := by
    refine Finset.sum_filter_of_ne (fun a _ hne => ?_)
    intro hzero
    exact hne (by rw [hzero, smul_zero])
  have hFp : ∀ a ∈ F, π a * p = p := by
    intro a ha
    rw [hF, Finset.mem_filter] at ha
    exact (hcases a ha.1).resolve_left ha.2
  refine ⟨∑ a ∈ F, a, ?_⟩
  rw [hrec, ← hfilter, Finset.sum_smul]
  exact Finset.sum_congr rfl (fun a ha => by rw [hFp a ha])

/-- Scalar corner theorem: against a minimal projection of the
subalgebra, the two-sided corner of every element of the subalgebra is a
complex multiple of the projection. -/
theorem IsMinimalProjectionIn.corner_smul {p x : Matrix n n ℂ}
    (hp : IsMinimalProjectionIn S p) (hx : x ∈ S) :
    ∃ c : ℂ, p * x * p = c • p := by
  set y := p * x * p with hy
  have hyS : y ∈ S := mul_mem (mul_mem hp.mem hx) hp.mem
  have hpy : p * y = y := by
    rw [hy, ← mul_assoc, ← mul_assoc, hp.isIdempotentElem.eq]
  have hyp : y * p = y := by
    rw [hy, mul_assoc, mul_assoc, hp.isIdempotentElem.eq, ← mul_assoc]
  have hystar : star y ∈ S := star_mem hyS
  have hpystar : p * star y = star y := by
    have h1 := congrArg star hyp
    rwa [star_mul, hp.isSelfAdjoint.star_eq] at h1
  have hystarp : star y * p = star y := by
    have h1 := congrArg star hpy
    rwa [star_mul, hp.isSelfAdjoint.star_eq] at h1
  have hsa₁ : IsSelfAdjoint (((2 : ℂ)⁻¹) • (y + star y)) := by
    show star _ = _
    rw [star_smul, star_add, star_star, star_inv₀, star_ofNat,
      add_comm (star y) y]
  have hsa₂ : IsSelfAdjoint (((2 : ℂ)⁻¹ * Complex.I) • (star y - y)) := by
    show star _ = _
    rw [star_smul, star_sub, star_star, star_mul', star_inv₀, star_ofNat,
      Complex.star_def, Complex.conj_I]
    rw [show (2 : ℂ)⁻¹ * -Complex.I = -((2 : ℂ)⁻¹ * Complex.I) by ring]
    rw [neg_smul, ← smul_neg, neg_sub]
  obtain ⟨c₁, hc₁⟩ := hp.selfAdjoint_corner_smul
    (SMulMemClass.smul_mem _ (add_mem hyS hystar)) hsa₁
    (by rw [mul_smul_comm, mul_add, hpy, hpystar])
    (by rw [smul_mul_assoc, add_mul, hyp, hystarp])
  obtain ⟨c₂, hc₂⟩ := hp.selfAdjoint_corner_smul
    (SMulMemClass.smul_mem _ (sub_mem hystar hyS)) hsa₂
    (by rw [mul_smul_comm, mul_sub, hpy, hpystar])
    (by rw [smul_mul_assoc, sub_mul, hyp, hystarp])
  have hdecomp : y = ((2 : ℂ)⁻¹) • (y + star y) +
      Complex.I • (((2 : ℂ)⁻¹ * Complex.I) • (star y - y)) := by
    rw [smul_smul, smul_add, smul_sub]
    rw [show Complex.I * ((2 : ℂ)⁻¹ * Complex.I) = -(2 : ℂ)⁻¹ by
      rw [mul_comm (2 : ℂ)⁻¹ Complex.I, ← mul_assoc, Complex.I_mul_I]; ring]
    rw [neg_smul, neg_smul, neg_sub_neg]
    rw [show ((2 : ℂ)⁻¹ • y + (2 : ℂ)⁻¹ • star y +
        ((2 : ℂ)⁻¹ • y - (2 : ℂ)⁻¹ • star y)) =
        ((2 : ℂ)⁻¹ + (2 : ℂ)⁻¹) • y by
      rw [add_smul]; abel]
    rw [show ((2 : ℂ)⁻¹ + (2 : ℂ)⁻¹ : ℂ) = 1 by norm_num, one_smul]
  refine ⟨c₁ + Complex.I * c₂, ?_⟩
  rw [hdecomp, hc₁, hc₂, smul_smul, add_smul]

end MatrixScalarCorner

/-! ## Traces and partial isometries -/

section Trace

variable {n : Type u} [Fintype n] [DecidableEq n]

omit [DecidableEq n] in
/-- The trace of `star m * m` is a nonnegative real that vanishes only at
zero: it is the sum of the squared moduli of the entries. -/
theorem exists_trace_star_mul_self (m : Matrix n n ℂ) :
    ∃ r : ℝ, 0 ≤ r ∧ (star m * m).trace = (r : ℂ) ∧ (r = 0 → m = 0) := by
  refine ⟨∑ j : n, ∑ i : n, Complex.normSq (m i j), ?_, ?_, ?_⟩
  · exact Finset.sum_nonneg fun j _ =>
      Finset.sum_nonneg fun i _ => Complex.normSq_nonneg _
  · have hentry : ∀ j : n, (star m * m) j j =
        ∑ i : n, (Complex.normSq (m i j) : ℂ) := by
      intro j
      rw [Matrix.mul_apply]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [Matrix.star_apply, Complex.star_def,
        ← Complex.normSq_eq_conj_mul_self]
    have htr : (star m * m).trace = ∑ j : n, (star m * m) j j := rfl
    rw [htr]
    push_cast
    exact Finset.sum_congr rfl fun j _ => hentry j
  · intro hzero
    have hall : ∀ j ∈ Finset.univ (α := n),
        ∑ i : n, Complex.normSq (m i j) = 0 :=
      (Finset.sum_eq_zero_iff_of_nonneg fun j _ =>
        Finset.sum_nonneg fun i _ => Complex.normSq_nonneg _).mp hzero
    ext i j
    have hij : Complex.normSq (m i j) = 0 :=
      (Finset.sum_eq_zero_iff_of_nonneg fun i _ =>
        Complex.normSq_nonneg _).mp (hall j (Finset.mem_univ j))
        i (Finset.mem_univ i)
    rw [Matrix.zero_apply]
    exact Complex.normSq_eq_zero.mp hij

omit [DecidableEq n] in
/-- The trace of a nonzero star projection is a positive real. -/
theorem exists_trace_pos_of_projection {p : Matrix n n ℂ}
    (hidem : IsIdempotentElem p) (hsa : IsSelfAdjoint p) (hp0 : p ≠ 0) :
    ∃ r : ℝ, 0 < r ∧ p.trace = (r : ℂ) := by
  obtain ⟨r, hr0, htr, hz⟩ := exists_trace_star_mul_self p
  rw [hsa.star_eq, hidem.eq] at htr
  refine ⟨r, lt_of_le_of_ne hr0 ?_, htr⟩
  intro h
  exact hp0 (hz h.symm)

omit [DecidableEq n] in
open scoped ComplexOrder in
/-- Zero detection for `star`-squares of complex matrices. -/
theorem eq_zero_of_star_mul_self_eq_zero {m : Matrix n n ℂ}
    (h : star m * m = 0) : m = 0 := by
  rw [Matrix.star_eq_conjTranspose] at h
  exact Matrix.conjTranspose_mul_self_eq_zero.mp h

variable {S : StarSubalgebra ℂ (Matrix n n ℂ)}

/-- Partial isometry between minimal projections: a nonzero element of
the subalgebra carried by two minimal projections normalizes to a partial
isometry of the subalgebra joining them.  The normalization scalar is the
positive square root of a trace quotient. -/
theorem exists_partial_isometry {p q x : Matrix n n ℂ}
    (hp : IsMinimalProjectionIn S p) (hq : IsMinimalProjectionIn S q)
    (hx : x ∈ S) (hx0 : x ≠ 0) (hqx : q * x = x) (hxp : x * p = x) :
    ∃ v : Matrix n n ℂ, v ∈ S ∧ star v * v = p ∧ v * star v = q ∧
      q * v = v ∧ v * p = v := by
  have hxstarp : p * star x = star x := by
    have h1 := congrArg star hxp
    rwa [star_mul, hp.isSelfAdjoint.star_eq] at h1
  have hxstarq : star x * q = star x := by
    have h1 := congrArg star hqx
    rwa [star_mul, hq.isSelfAdjoint.star_eq] at h1
  -- the star square lands in the scalar corner of `p`
  obtain ⟨c, hc⟩ := hp.corner_smul (mul_mem (star_mem hx) hx)
  have hcorner : star x * x = c • p := by
    have h1 : p * (star x * x) * p = star x * x := by
      rw [← mul_assoc, hxstarp, mul_assoc, hxp]
    rwa [h1] at hc
  -- trace evaluation of the corner scalar
  obtain ⟨rx, hrx0, hrxtr, hrxz⟩ := exists_trace_star_mul_self x
  obtain ⟨rp, hrp0, hrptr⟩ :=
    exists_trace_pos_of_projection hp.isIdempotentElem hp.isSelfAdjoint
      hp.ne_zero
  have hrxpos : 0 < rx :=
    lt_of_le_of_ne hrx0 (fun h => hx0 (hrxz h.symm))
  have hctr : (rx : ℂ) = c * rp := by
    have h1 := congrArg Matrix.trace hcorner
    rwa [Matrix.trace_smul, smul_eq_mul, hrxtr, hrptr] at h1
  have hcval : c = ((rx / rp : ℝ) : ℂ) := by
    rw [Complex.ofReal_div, eq_div_iff (by
      exact_mod_cast hrp0.ne')]
    exact hctr.symm
  set s : ℝ := Real.sqrt (rx / rp) with hs
  have hspos : 0 < s := Real.sqrt_pos.mpr (div_pos hrxpos hrp0)
  have hssq : (s : ℂ) * s = ((rx / rp : ℝ) : ℂ) := by
    rw [← Complex.ofReal_mul, Real.mul_self_sqrt (div_pos hrxpos hrp0).le]
  set σ : ℂ := ((s : ℂ))⁻¹ with hσ
  have hσreal : star σ = σ := by
    rw [hσ, star_inv₀, Complex.star_def, Complex.conj_ofReal]
  have hσσc : σ * σ * c = 1 := by
    have hne : ((s : ℝ) : ℂ) ≠ 0 := by exact_mod_cast hspos.ne'
    rw [hσ, hcval, ← hssq, ← mul_inv, inv_mul_cancel₀ (mul_ne_zero hne hne)]
  refine ⟨σ • x, SMulMemClass.smul_mem σ hx, ?_, ?_, ?_, ?_⟩
  · -- star square of the normalized element
    rw [star_smul, hσreal, smul_mul_smul_comm, hcorner, smul_smul, hσσc,
      one_smul]
  · -- the reflected square is a projection under the minimal `q`
    have hxxstarq : q * (x * star x) * q = x * star x := by
      rw [← mul_assoc, hqx, mul_assoc, hxstarq]
    obtain ⟨d, hd⟩ := hq.corner_smul (mul_mem hx (star_mem hx))
    have hdcorner : x * star x = d • q := by rwa [hxxstarq] at hd
    have hvv : (σ • x) * star (σ • x) = (σ * σ * d) • q := by
      rw [star_smul, hσreal, smul_mul_smul_comm, hdcorner, smul_smul,
        mul_assoc]
    have hvp : (σ • x) * p = σ • x := by rw [smul_mul_assoc, hxp]
    have hidem : ((σ • x) * star (σ • x)) * ((σ • x) * star (σ • x)) =
        (σ • x) * star (σ • x) := by
      have h1 : star (σ • x) * (σ • x) = p := by
        rw [star_smul, hσreal, smul_mul_smul_comm, hcorner, smul_smul,
          hσσc, one_smul]
      calc ((σ • x) * star (σ • x)) * ((σ • x) * star (σ • x))
          = (σ • x) * (star (σ • x) * (σ • x)) * star (σ • x) := by
            rw [mul_assoc, mul_assoc, mul_assoc]
        _ = (σ • x) * star (σ • x) := by rw [h1, hvp]
    set d' : ℂ := σ * σ * d with hd'
    have hd'idem : (d' * d') • q = d' • q := by
      have h2 : ((d' • q) : Matrix n n ℂ) * (d' • q) = d' • q := by
        rw [← hvv]; exact hidem
      rwa [smul_mul_smul_comm, hq.isIdempotentElem.eq] at h2
    have hd'cases : d' = 0 ∨ d' = 1 := by
      have h3 : (d' * d' - d') • q = 0 := by
        rw [sub_smul, hd'idem, sub_self]
      have h4 : d' * d' - d' = 0 := by
        rcases smul_eq_zero.mp h3 with h5 | h5
        · exact h5
        · exact absurd h5 hq.ne_zero
      exact IsIdempotentElem.iff_eq_zero_or_one.mp (by
        rwa [sub_eq_zero] at h4)
    rcases hd'cases with h5 | h5
    · exfalso
      have hvzero : (σ • x) * star (σ • x) = 0 := by
        rw [hvv, h5, zero_smul]
      have hstarv : star (σ • x) = 0 := by
        refine eq_zero_of_star_mul_self_eq_zero (m := star (σ • x)) ?_
        rwa [star_star]
      have hv0 : σ • x = 0 := by
        have := congrArg star hstarv
        rwa [star_star, star_zero] at this
      have hp0 : p = 0 := by
        have h6 : star (σ • x) * (σ • x) = p := by
          rw [star_smul, hσreal, smul_mul_smul_comm, hcorner, smul_smul,
            hσσc, one_smul]
        rw [← h6, hv0, mul_zero]
      exact hp.ne_zero hp0
    · rw [hvv, h5, one_smul]
  · rw [mul_smul_comm, hqx]
  · rw [smul_mul_assoc, hxp]

end Trace

/-! ## The connecting ideal of a subordinate projection -/

section ConnectingIdeal

variable {n : Type u} [Fintype n] [DecidableEq n]
  {S : StarSubalgebra ℂ (Matrix n n ℂ)}

/-- The two-sided ideal of the subalgebra generated by an element, as a
complex submodule of the matrix algebra. -/
noncomputable def connectingIdeal (S : StarSubalgebra ℂ (Matrix n n ℂ))
    (p : Matrix n n ℂ) : Submodule ℂ (Matrix n n ℂ) :=
  Submodule.span ℂ {y | ∃ a ∈ S, ∃ b ∈ S, y = a * p * b}

theorem mem_connectingIdeal_of {p a b : Matrix n n ℂ} (ha : a ∈ S)
    (hb : b ∈ S) : a * p * b ∈ connectingIdeal S p :=
  Submodule.subset_span ⟨a, ha, b, hb, rfl⟩

theorem self_mem_connectingIdeal {p : Matrix n n ℂ} :
    p ∈ connectingIdeal S p := by
  have h1 := mem_connectingIdeal_of (p := p) (one_mem S) (one_mem S)
  rwa [one_mul, mul_one] at h1

theorem mem_of_mem_connectingIdeal {p x : Matrix n n ℂ} (hp : p ∈ S)
    (hx : x ∈ connectingIdeal S p) : x ∈ S := by
  have hle : connectingIdeal S p ≤
      Subalgebra.toSubmodule S.toSubalgebra := by
    rw [connectingIdeal, Submodule.span_le]
    rintro y ⟨a, ha, b, hb, rfl⟩
    exact (show a * p * b ∈ S from mul_mem (mul_mem ha hp) hb)
  exact hle hx

theorem connectingIdeal_mul_left {p s x : Matrix n n ℂ} (hs : s ∈ S)
    (hx : x ∈ connectingIdeal S p) : s * x ∈ connectingIdeal S p := by
  have hmap : Submodule.map (LinearMap.mulLeft ℂ s)
      (connectingIdeal S p) ≤ connectingIdeal S p := by
    rw [connectingIdeal, Submodule.map_span, Submodule.span_le]
    rintro y ⟨z, ⟨a, ha, b, hb, rfl⟩, rfl⟩
    have h1 : LinearMap.mulLeft ℂ s (a * p * b) = (s * a) * p * b := by
      rw [LinearMap.mulLeft_apply, ← mul_assoc, ← mul_assoc]
    rw [h1]
    exact mem_connectingIdeal_of (mul_mem hs ha) hb
  exact hmap ⟨x, hx, rfl⟩

theorem connectingIdeal_mul_right {p s x : Matrix n n ℂ} (hs : s ∈ S)
    (hx : x ∈ connectingIdeal S p) : x * s ∈ connectingIdeal S p := by
  have hmap : Submodule.map (LinearMap.mulRight ℂ s)
      (connectingIdeal S p) ≤ connectingIdeal S p := by
    rw [connectingIdeal, Submodule.map_span, Submodule.span_le]
    rintro y ⟨z, ⟨a, ha, b, hb, rfl⟩, rfl⟩
    have h1 : LinearMap.mulRight ℂ s (a * p * b) = a * p * (b * s) := by
      rw [LinearMap.mulRight_apply, mul_assoc (a * p) b s]
    rw [h1]
    exact mem_connectingIdeal_of ha (mul_mem hb hs)
  exact hmap ⟨x, hx, rfl⟩

theorem connectingIdeal_star {p x : Matrix n n ℂ} (hpsa : star p = p)
    (hx : x ∈ connectingIdeal S p) : star x ∈ connectingIdeal S p := by
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨a, ha, b, hb, rfl⟩ := hy
    have h1 : star (a * p * b) = (star b) * p * (star a) := by
      rw [star_mul, star_mul, hpsa, mul_assoc]
    rw [h1]
    exact mem_connectingIdeal_of (star_mem hb) (star_mem ha)
  | zero => rw [star_zero]; exact zero_mem _
  | add y z _ _ hy hz => rw [star_add]; exact add_mem hy hz
  | smul c y _ hy => rw [star_smul]; exact SMulMemClass.smul_mem _ hy

/-- A projection of the subalgebra central against the subalgebra absorbs
the connecting ideal of any element it dominates. -/
theorem connectingIdeal_central_absorb {p e x : Matrix n n ℂ}
    (he : IsCentralIn S e) (hep : e * p = p)
    (hx : x ∈ connectingIdeal S p) : e * x = x := by
  have hker : connectingIdeal S p ≤
      LinearMap.ker (LinearMap.mulLeft ℂ e - LinearMap.id) := by
    rw [connectingIdeal, Submodule.span_le]
    rintro y ⟨a, ha, b, hb, rfl⟩
    rw [SetLike.mem_coe, LinearMap.mem_ker, LinearMap.sub_apply,
      LinearMap.mulLeft_apply, LinearMap.id_apply, sub_eq_zero]
    calc e * (a * p * b) = (e * a) * p * b := by
          rw [← mul_assoc, ← mul_assoc]
      _ = (a * e) * p * b := by rw [he.commutes ha]
      _ = a * (e * p) * b := by rw [mul_assoc a e p]
      _ = a * p * b := by rw [hep]
  have h1 := hker hx
  rw [LinearMap.mem_ker, LinearMap.sub_apply, LinearMap.mulLeft_apply,
    LinearMap.id_apply, sub_eq_zero] at h1
  exact h1

/-- Support of the connecting ideal: inside a minimal central corner, the
connecting ideal of a nonzero subordinate projection contains the central
corner unit.  The support projection of a trace-positive combination of
an ideal basis is a central projection of the subalgebra dominated by the
corner unit, and minimality forces equality. -/
theorem central_unit_mem_connectingIdeal {e p : Matrix n n ℂ}
    (he : IsMinimalCentralProjectionIn S e) (hp : IsProjectionIn S p)
    (hp0 : p ≠ 0) (hpe : p * e = p) :
    e ∈ connectingIdeal S p := by
  classical
  haveI : Nonempty n := nonempty_of_matrix_ne_zero hp0
  set J := connectingIdeal S p with hJdef
  -- a trace-positive self-adjoint combination of an ideal basis
  set bJ := Module.finBasis ℂ ↥J with hbJ
  set m : Fin (Module.finrank ℂ ↥J) → Matrix n n ℂ :=
    fun i => J.subtype (bJ i) with hm
  have hmJ : ∀ i, m i ∈ J := fun i => (bJ i).2
  have hmS : ∀ i, m i ∈ S := fun i => mem_of_mem_connectingIdeal hp.mem
    (hmJ i)
  set h : Matrix n n ℂ := ∑ i, star (m i) * m i with hh
  have hhJ : h ∈ J := sum_mem fun i _ =>
    connectingIdeal_mul_left (star_mem (hmS i)) (hmJ i)
  have hhS : h ∈ S := mem_of_mem_connectingIdeal hp.mem hhJ
  have hhsa : IsSelfAdjoint h := by
    show star h = h
    rw [hh, star_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [star_mul, star_star]
  -- the support projection of `h` through its spectral resolution
  set T := spectralSupport hhsa.isHermitian with hT
  set π : ℂ → Matrix n n ℂ := spectralProjection hhsa.isHermitian with hπ
  set F := T.filter (fun a => a ≠ 0) with hF
  have hFsub : F ⊆ T := Finset.filter_subset _ _
  have hFne : ∀ a ∈ F, a ≠ 0 := fun a ha => (Finset.mem_filter.mp ha).2
  set u : Matrix n n ℂ := ∑ a ∈ F, π a with hu
  set g : Matrix n n ℂ := ∑ a ∈ F, a⁻¹ • π a with hg
  have hrec : h = ∑ a ∈ T, a • π a :=
    eq_sum_smul_spectralProjection hhsa.isHermitian
  have hπu : ∀ a ∈ F, π a * u = π a := by
    intro a ha
    rw [hu, Finset.mul_sum]
    have hterm : ∀ b ∈ F, π a * π b = if b = a then π b else 0 := by
      intro b hb
      by_cases hba : b = a
      · subst hba
        rw [if_pos rfl, (isIdempotentElem_spectralProjection _
          (hFsub hb)).eq]
      · rw [if_neg hba]
        exact spectralProjection_mul_of_ne _ (hFsub ha) (hFsub hb)
          (fun h1 => hba h1.symm)
    rw [Finset.sum_congr rfl hterm, Finset.sum_ite_eq' F a (fun b => π b),
      if_pos ha]
  have hug : h * g = u := by
    rw [hrec, Finset.sum_mul]
    have hterm : ∀ a ∈ T, (a • π a) * g =
        if a ≠ 0 then π a else 0 := by
      intro a ha
      rw [hg, Finset.mul_sum]
      have hterm2 : ∀ b ∈ F, (a • π a) * (b⁻¹ • π b) =
          if b = a then (a * a⁻¹) • π b else 0 := by
        intro b hb
        by_cases hba : b = a
        · subst hba
          rw [if_pos rfl, smul_mul_smul_comm,
            (isIdempotentElem_spectralProjection _ (hFsub hb)).eq]
        · rw [if_neg hba, smul_mul_smul_comm,
            spectralProjection_mul_of_ne _ ha (hFsub hb)
              (fun h1 => hba h1.symm), smul_zero]
      rw [Finset.sum_congr rfl hterm2,
        Finset.sum_ite_eq' F a (fun b => (a * a⁻¹) • π b)]
      by_cases ha0 : a = 0
      · subst ha0
        have hnot : (0 : ℂ) ∉ F := by
          intro hmem
          exact hFne 0 hmem rfl
        rw [if_neg hnot, if_neg (by simp)]
      · have hmem : a ∈ F := Finset.mem_filter.mpr ⟨ha, ha0⟩
        rw [if_pos hmem, if_pos ha0, mul_inv_cancel₀ ha0, one_smul]
    rw [Finset.sum_congr rfl hterm, ← Finset.sum_filter]
  have hgS : g ∈ S := sum_mem fun a _ =>
    SMulMemClass.smul_mem _ (aeval_mem_of_mem hhS _)
  have huJ : u ∈ J := by
    rw [← hug]
    exact connectingIdeal_mul_right hgS hhJ
  have huS : u ∈ S := mem_of_mem_connectingIdeal hp.mem huJ
  have huidem : IsIdempotentElem u := by
    show u * u = u
    conv_lhs => rw [hu, Finset.sum_mul]
    exact Finset.sum_congr rfl fun a ha => hπu a ha
  have husa : IsSelfAdjoint u := by
    show star u = u
    rw [hu, star_sum]
    exact Finset.sum_congr rfl fun a ha =>
      (isSelfAdjoint_spectralProjection _ (hFsub ha)).star_eq
  -- the ideal is absorbed by its support projection
  have hhu : h * u = h := by
    conv_lhs => rw [hrec, Finset.sum_mul]
    conv_rhs => rw [hrec]
    refine Finset.sum_congr rfl fun a ha => ?_
    by_cases ha0 : a = 0
    · subst ha0
      rw [zero_smul, zero_mul]
    · rw [smul_mul_assoc, hπu a (Finset.mem_filter.mpr ⟨ha, ha0⟩)]
  set X : Matrix n n ℂ := 1 - u with hX
  have hXsa : star X = X := by
    rw [hX, star_sub, star_one, husa.star_eq]
  have hhX : h * X = 0 := by
    rw [hX, mul_sub, mul_one, hhu, sub_self]
  have hXh : X * h = 0 := by
    have h1 := congrArg star hhX
    rwa [star_mul, hXsa, hhsa.star_eq, star_zero] at h1
  have hsumzero : ∑ i, star (m i * X) * (m i * X) = 0 := by
    have hterm : ∀ i, star (m i * X) * (m i * X) =
        X * (star (m i) * m i) * X := by
      intro i
      rw [star_mul, hXsa]
      noncomm_ring
    rw [Finset.sum_congr rfl fun i _ => hterm i]
    have h1 : ∑ i, X * (star (m i) * m i) * X =
        X * h * X := by
      rw [hh, Finset.mul_sum, Finset.sum_mul]
    rw [h1, hXh, zero_mul]
  have hmX : ∀ i, m i * X = 0 := by
    have htr := fun i => exists_trace_star_mul_self (m i * X)
    choose r hr0 hrtr hrz using htr
    have hsumtr : ((∑ i, r i : ℝ) : ℂ) = 0 := by
      have h1 := congrArg Matrix.trace hsumzero
      rw [Matrix.trace_sum, Matrix.trace_zero] at h1
      rw [Complex.ofReal_sum]
      rw [Finset.sum_congr rfl fun i _ => (hrtr i).symm]
      exact h1
    have hsumr : ∑ i, r i = 0 := by exact_mod_cast hsumtr
    intro i
    exact hrz i ((Finset.sum_eq_zero_iff_of_nonneg
      (fun j _ => hr0 j)).mp hsumr i (Finset.mem_univ i))
  have hmu : ∀ i, m i * u = m i := by
    intro i
    have h1 := hmX i
    rw [hX, mul_sub, mul_one, sub_eq_zero] at h1
    exact h1.symm
  have hJu : ∀ x ∈ J, x * u = x := by
    intro x hx
    have h2 := congrArg J.subtype (bJ.sum_repr ⟨x, hx⟩)
    rw [map_sum] at h2
    simp only [map_smul] at h2
    have h3 : ∑ i, bJ.repr ⟨x, hx⟩ i • m i = x := h2
    calc x * u = (∑ i, bJ.repr ⟨x, hx⟩ i • m i) * u := by rw [h3]
      _ = ∑ i, bJ.repr ⟨x, hx⟩ i • (m i * u) := by
          rw [Finset.sum_mul]
          exact Finset.sum_congr rfl fun i _ => smul_mul_assoc _ _ _
      _ = ∑ i, bJ.repr ⟨x, hx⟩ i • m i := by
          exact Finset.sum_congr rfl fun i _ => by rw [hmu i]
      _ = x := h3
  have huJ' : ∀ x ∈ J, u * x = x := by
    intro x hx
    have hstar : star x ∈ J :=
      connectingIdeal_star hp.isSelfAdjoint.star_eq hx
    have h1 := hJu (star x) hstar
    have h2 := congrArg star h1
    rwa [star_mul, husa.star_eq, star_star] at h2
  have hucentral : ∀ s ∈ S, u * s = s * u := by
    intro s hs
    have h1 : s * u ∈ J := connectingIdeal_mul_left hs huJ
    have h2 : u * s ∈ J := connectingIdeal_mul_right hs huJ
    calc u * s = (u * s) * u := (hJu _ h2).symm
      _ = u * (s * u) := by rw [mul_assoc]
      _ = s * u := huJ' _ h1
  -- the support is a central projection of `S` below the corner unit
  have hep : e * p = p :=
    he.toIsCentralProjectionIn.isProjectionIn.absorb_left hp hpe
  have hue : u * e = u := by
    have h1 : e * u = u :=
      connectingIdeal_central_absorb he.centralIn hep huJ
    have h2 := congrArg star h1
    rwa [star_mul, husa.star_eq, he.isSelfAdjoint.star_eq] at h2
  have hu0 : u ≠ 0 := by
    intro h0
    have h1 := hJu p self_mem_connectingIdeal
    rw [h0, mul_zero] at h1
    exact hp0 h1.symm
  have hucp : IsCentralProjectionIn S u :=
    { isIdempotentElem := huidem
      isSelfAdjoint := husa
      centralIn := ⟨huS, fun s hs => hucentral s hs⟩ }
  rcases he.minimal u hucp hue with h0 | hue'
  · exact absurd h0 hu0
  · rw [← hue']
    exact huJ

/-- Inside a minimal central corner every two subordinate minimal
projections are joined by a nonzero element of the subalgebra. -/
theorem exists_connecting_element {e p q : Matrix n n ℂ}
    (he : IsMinimalCentralProjectionIn S e)
    (hp : IsMinimalProjectionIn S p) (hpe : p * e = p)
    (hq : IsMinimalProjectionIn S q) (hqe : q * e = q) :
    ∃ x : Matrix n n ℂ, x ∈ S ∧ x ≠ 0 ∧ q * x = x ∧ x * p = x := by
  by_cases hvanish : ∀ s ∈ S, q * s * p = 0
  · exfalso
    -- the corner cut kills the whole ideal, including the corner unit
    have hcut : ∀ x ∈ connectingIdeal S p, q * x * q = 0 := by
      intro x hx
      have hker : connectingIdeal S p ≤
          LinearMap.ker ((LinearMap.mulLeft ℂ q).comp
            (LinearMap.mulRight ℂ q)) := by
        rw [connectingIdeal, Submodule.span_le]
        rintro y ⟨a, ha, b, hb, rfl⟩
        rw [SetLike.mem_coe, LinearMap.mem_ker, LinearMap.comp_apply,
          LinearMap.mulRight_apply, LinearMap.mulLeft_apply]
        have h1 : q * (a * p * b * q) = (q * a * p) * (b * q) := by
          noncomm_ring
        rw [h1, hvanish a ha, zero_mul]
      have h1 := hker hx
      rw [LinearMap.mem_ker, LinearMap.comp_apply,
        LinearMap.mulRight_apply, LinearMap.mulLeft_apply] at h1
      rwa [← mul_assoc] at h1
    have hqe' : q * e * q = q := by
      rw [hqe, hq.isIdempotentElem.eq]
    have h1 := hcut e (central_unit_mem_connectingIdeal he
      hp.toIsProjectionIn hp.ne_zero hpe)
    rw [hqe'] at h1
    exact hq.ne_zero h1
  · push Not at hvanish
    obtain ⟨s, hs, hsne⟩ := hvanish
    refine ⟨q * s * p, mul_mem (mul_mem hq.mem hs) hp.mem, hsne, ?_, ?_⟩
    · rw [← mul_assoc, ← mul_assoc, hq.isIdempotentElem.eq]
    · rw [mul_assoc, hp.isIdempotentElem.eq]

end ConnectingIdeal

/-! ## The relative corner of a central projection -/

section RelativeCorner

variable {A : Type u} [Ring A] [StarRing A] [Algebra ℂ A] [StarModule ℂ A]

/-- The corner of a star subalgebra cut by a central projection of the
subalgebra, as a non-unital star subalgebra of the ambient algebra.  Its
multiplicative unit is the projection itself. -/
def relativeCorner (S : StarSubalgebra ℂ A) {e : A}
    (he : IsCentralProjectionIn S e) : NonUnitalStarSubalgebra ℂ A where
  carrier := {x : A | x ∈ S ∧ e * x = x}
  add_mem' := fun {a b} ha hb =>
    ⟨add_mem ha.1 hb.1, by rw [mul_add, ha.2, hb.2]⟩
  zero_mem' := ⟨zero_mem S, mul_zero e⟩
  mul_mem' := fun {a b} ha hb =>
    ⟨mul_mem ha.1 hb.1, by rw [← mul_assoc, ha.2]⟩
  smul_mem' := fun c {x} hx =>
    ⟨SMulMemClass.smul_mem c hx.1, by rw [mul_smul_comm, hx.2]⟩
  star_mem' := fun {a} ha => by
    refine ⟨star_mem ha.1, ?_⟩
    have h1 : a * e = a := by
      rw [← he.centralIn.commutes ha.1, ha.2]
    have h2 := congrArg star h1
    rwa [star_mul, he.isSelfAdjoint.star_eq] at h2

@[simp] theorem mem_relativeCorner_iff {S : StarSubalgebra ℂ A} {e : A}
    (he : IsCentralProjectionIn S e) {x : A} :
    x ∈ relativeCorner S he ↔ x ∈ S ∧ e * x = x := Iff.rfl

/-- Corner members are absorbed on both sides. -/
theorem mul_unit_of_mem_relativeCorner {S : StarSubalgebra ℂ A} {e : A}
    (he : IsCentralProjectionIn S e) {x : A}
    (hx : x ∈ relativeCorner S he) : x * e = x := by
  rw [← he.centralIn.commutes hx.1, hx.2]

end RelativeCorner

/-! ## Matrix units and the corner classification -/

section MatrixUnits

variable {n : Type u} [Fintype n] [DecidableEq n]
  {S : StarSubalgebra ℂ (Matrix n n ℂ)}

/-- Star Wedderburn step for one corner: every minimal central corner of
a star subalgebra of a finite complex matrix algebra is star-isomorphic
to one full matrix block.  A maximal orthogonal family of minimal
projections refines the corner unit, partial isometries join the family
through the connecting ideal, and the resulting matrix-unit system spans
the corner with full matrix relations. -/
theorem minimalCentralCorner_starEquiv_matrix
    (S : StarSubalgebra ℂ (Matrix n n ℂ)) {e : Matrix n n ℂ}
    (he : IsMinimalCentralProjectionIn S e) :
    ∃ k : ℕ, 0 < k ∧
      Nonempty (↥(relativeCorner S he.toIsCentralProjectionIn) ≃⋆ₐ[ℂ]
        Matrix (Fin k) (Fin k) ℂ) := by
  classical
  obtain ⟨l, hlmin, hlorth, hlle, hlsum⟩ :=
    he.toIsCentralProjectionIn.isProjectionIn.exists_minimal_decomposition
  have hlne : l ≠ [] := by
    intro h1
    rw [h1, List.sum_nil] at hlsum
    exact he.ne_zero hlsum.symm
  have hk : 0 < l.length := List.length_pos_of_ne_nil hlne
  refine ⟨l.length, hk, ?_⟩
  set P : Fin l.length → Matrix n n ℂ := l.get with hP
  have hPmin : ∀ i, IsMinimalProjectionIn S (P i) :=
    fun i => hlmin _ (List.get_mem l i)
  have hPle : ∀ i, P i * e = P i := fun i => hlle _ (List.get_mem l i)
  have hPorth : ∀ i j, i ≠ j → P i * P j = 0 := by
    intro i j hij
    have hpair := List.pairwise_iff_get.mp hlorth
    rcases lt_or_gt_of_ne hij with h1 | h1
    · exact hpair i j h1
    · have h0 := hpair j i h1
      have h2 := congrArg star h0
      rwa [star_mul, (hPmin i).isSelfAdjoint.star_eq,
        (hPmin j).isSelfAdjoint.star_eq, star_zero] at h2
  have hPsum : ∑ i, P i = e := by
    rw [← hlsum]
    conv_rhs => rw [← List.ofFn_get l]
    rw [List.sum_ofFn]
  set i₀ : Fin l.length := ⟨0, hk⟩ with hi₀
  -- partial isometries joining every block to the reference block
  have hWex : ∀ i : Fin l.length, ∃ w : Matrix n n ℂ, w ∈ S ∧
      star w * w = P i₀ ∧ w * star w = P i ∧ P i * w = w ∧
      w * P i₀ = w := by
    intro i
    obtain ⟨x, hxS, hx0, hqx, hxp⟩ := exists_connecting_element he
      (hPmin i₀) (hPle i₀) (hPmin i) (hPle i)
    exact exists_partial_isometry (hPmin i₀) (hPmin i) hxS hx0 hqx hxp
  choose w hwS hwsq hwq hPw hwP using hWex
  have hstarwP : ∀ i, star (w i) * P i = star (w i) := by
    intro i
    have h1 := congrArg star (hPw i)
    rwa [star_mul, (hPmin i).isSelfAdjoint.star_eq] at h1
  have hP0starw : ∀ i, P i₀ * star (w i) = star (w i) := by
    intro i
    have h1 := congrArg star (hwP i)
    rwa [star_mul, (hPmin i₀).isSelfAdjoint.star_eq] at h1
  -- the matrix-unit system
  set E : Fin l.length → Fin l.length → Matrix n n ℂ :=
    fun i j => w i * star (w j) with hE
  have hEmem : ∀ i j, E i j ∈ S := fun i j =>
    mul_mem (hwS i) (star_mem (hwS j))
  have hEstar : ∀ i j, star (E i j) = E j i := by
    intro i j
    rw [hE, star_mul, star_star]
  have hEdiag : ∀ i, E i i = P i := fun i => hwq i
  have hEmul : ∀ i j a b, E i j * E a b =
      if j = a then E i b else 0 := by
    intro i j a b
    by_cases hja : j = a
    · subst hja
      rw [if_pos rfl]
      calc w i * star (w j) * (w j * star (w b))
          = w i * (star (w j) * w j) * star (w b) := by noncomm_ring
        _ = w i * star (w b) := by rw [hwsq j, hwP i]
    · rw [if_neg hja]
      have h1 : star (w j) * w a = 0 := by
        calc star (w j) * w a
            = (star (w j) * P j) * (P a * w a) := by rw [hstarwP, hPw]
          _ = star (w j) * (P j * P a) * w a := by noncomm_ring
          _ = 0 := by rw [hPorth j a hja, mul_zero, zero_mul]
      calc w i * star (w j) * (w a * star (w b))
          = w i * (star (w j) * w a) * star (w b) := by noncomm_ring
        _ = 0 := by rw [h1, mul_zero, zero_mul]
  have hPE : ∀ a i j, P a * E i j = if a = i then E i j else 0 := by
    intro a i j
    by_cases hai : a = i
    · subst hai
      rw [if_pos rfl]
      show P a * (w a * star (w j)) = w a * star (w j)
      rw [← mul_assoc, hPw]
    · rw [if_neg hai]
      show P a * (w i * star (w j)) = 0
      have h1 : P a * w i = 0 := by
        rw [← hPw i, ← mul_assoc, hPorth a i hai, zero_mul]
      rw [← mul_assoc, h1, zero_mul]
  have hEP : ∀ i j b, E i j * P b = if b = j then E i j else 0 := by
    intro i j b
    by_cases hbj : b = j
    · subst hbj
      rw [if_pos rfl]
      show (w i * star (w b)) * P b = w i * star (w b)
      rw [mul_assoc, hstarwP]
    · rw [if_neg hbj]
      show (w i * star (w j)) * P b = 0
      have h1 : star (w j) * P b = 0 := by
        rw [← hstarwP j, mul_assoc, hPorth j b (fun h2 => hbj h2.symm),
          mul_zero]
      rw [mul_assoc, h1, mul_zero]
  have hEne : ∀ i j, E i j ≠ 0 := by
    intro i j h0
    have h1 : E i j * E j i = P i := by
      rw [hEmul, if_pos rfl, hEdiag]
    rw [h0, zero_mul] at h1
    exact (hPmin i).ne_zero h1.symm
  have heE : ∀ i j, e * E i j = E i j := by
    intro i j
    have h1 : e * P i = P i :=
      he.toIsCentralProjectionIn.isProjectionIn.absorb_left
        (hPmin i).toIsProjectionIn (hPle i)
    have h2 : e * w i = w i := by
      rw [← hPw i, ← mul_assoc, h1]
    show e * (w i * star (w j)) = w i * star (w j)
    rw [← mul_assoc, h2]
  -- scalar coefficients against the reference corner
  have hcoef : ∀ x ∈ S, ∀ i j, ∃ c : ℂ, P i * x * P j = c • E i j := by
    intro x hx i j
    obtain ⟨c, hc⟩ := (hPmin i₀).corner_smul
      (mul_mem (mul_mem (star_mem (hwS i)) hx) (hwS j))
    have habs : P i₀ * (star (w i) * x * w j) * P i₀ =
        star (w i) * x * w j := by
      calc P i₀ * (star (w i) * x * w j) * P i₀
          = (P i₀ * star (w i)) * x * (w j * P i₀) := by noncomm_ring
        _ = star (w i) * x * w j := by rw [hP0starw i, hwP j]
    have hy : star (w i) * x * w j = c • P i₀ := by rw [← habs, hc]
    refine ⟨c, ?_⟩
    calc P i * x * P j
        = (w i * star (w i)) * x * (w j * star (w j)) := by
          rw [hwq i, hwq j]
      _ = w i * (star (w i) * x * w j) * star (w j) := by noncomm_ring
      _ = w i * (c • P i₀) * star (w j) := by rw [hy]
      _ = c • (w i * P i₀ * star (w j)) := by
          rw [mul_smul_comm, smul_mul_assoc]
      _ = c • E i j := by rw [hwP i]
  -- block decomposition of corner elements
  have hdecomp : ∀ x ∈ S, e * x = x →
      x = ∑ i, ∑ j, P i * x * P j := by
    intro x hx hex
    have hxe : x * e = x := by
      rw [← he.centralIn.commutes hx, hex]
    have h1 : x = e * x * e := by rw [hex, hxe]
    conv_lhs => rw [h1, ← hPsum]
    rw [Finset.sum_mul, Finset.sum_mul]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Finset.mul_sum]
  -- the candidate homomorphism from the full matrix block
  set corner := relativeCorner S he.toIsCentralProjectionIn with hcorner
  have hmemΦ : ∀ M : Matrix (Fin l.length) (Fin l.length) ℂ,
      (∑ i, ∑ j, M i j • E i j) ∈ corner := by
    intro M
    refine ⟨sum_mem fun i _ => sum_mem fun j _ =>
      SMulMemClass.smul_mem _ (hEmem i j), ?_⟩
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [mul_smul_comm, heE]
  have hmul : ∀ M N : Matrix (Fin l.length) (Fin l.length) ℂ,
      (∑ i, ∑ j, M i j • E i j) * (∑ i, ∑ j, N i j • E i j) =
        ∑ i, ∑ j, (M * N) i j • E i j := by
    intro M N
    have hexp : (∑ i, ∑ j, M i j • E i j) * (∑ i, ∑ j, N i j • E i j) =
        ∑ i, ∑ j, ∑ a, ∑ b, (M i j * N a b) • (E i j * E a b) := by
      rw [Finset.sum_mul]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [Finset.sum_mul]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl fun a _ => ?_
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl fun b _ => ?_
      rw [smul_mul_smul_comm]
    rw [hexp]
    refine Finset.sum_congr rfl fun i _ => ?_
    have hcollapse : ∀ j, (∑ a, ∑ b, (M i j * N a b) • (E i j * E a b)) =
        ∑ b, (M i j * N j b) • E i b := by
      intro j
      have h1 : ∀ a, (∑ b, (M i j * N a b) • (E i j * E a b)) =
          if j = a then ∑ b, (M i j * N a b) • E i b else 0 := by
        intro a
        by_cases hja : j = a
        · rw [if_pos hja]
          refine Finset.sum_congr rfl fun b _ => ?_
          rw [hEmul, if_pos hja]
        · rw [if_neg hja]
          refine Finset.sum_eq_zero fun b _ => ?_
          rw [hEmul, if_neg hja, smul_zero]
      rw [Finset.sum_congr rfl fun a _ => h1 a, Finset.sum_ite_eq,
        if_pos (Finset.mem_univ j)]
    rw [Finset.sum_congr rfl fun j _ => hcollapse j, Finset.sum_comm]
    refine Finset.sum_congr rfl fun b _ => ?_
    rw [← Finset.sum_smul, Matrix.mul_apply]
  have hstarmap : ∀ M : Matrix (Fin l.length) (Fin l.length) ℂ,
      star (∑ i, ∑ j, M i j • E i j) =
        ∑ i, ∑ j, (star M) i j • E i j := by
    intro M
    rw [star_sum]
    have h1 : ∀ i, star (∑ j, M i j • E i j) =
        ∑ j, star (M i j) • E j i := by
      intro i
      rw [star_sum]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [star_smul, hEstar]
    rw [Finset.sum_congr rfl fun i _ => h1 i, Finset.sum_comm]
    refine Finset.sum_congr rfl fun i _ => ?_
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [Matrix.star_eq_conjTranspose, Matrix.conjTranspose_apply]
  have hPab : ∀ (M : Matrix (Fin l.length) (Fin l.length) ℂ) (a b),
      P a * (∑ i, ∑ j, M i j • E i j) * P b = M a b • E a b := by
    intro M a b
    have hexp : P a * (∑ i, ∑ j, M i j • E i j) * P b =
        ∑ i, ∑ j, M i j • (P a * E i j * P b) := by
      rw [Finset.mul_sum, Finset.sum_mul]
      refine Finset.sum_congr rfl fun i _ => ?_
      rw [Finset.mul_sum, Finset.sum_mul]
      refine Finset.sum_congr rfl fun j _ => ?_
      rw [mul_smul_comm, smul_mul_assoc]
    rw [hexp]
    have hterm : ∀ i j, M i j • (P a * E i j * P b) =
        if a = i then (if b = j then M i j • E i j else 0) else 0 := by
      intro i j
      by_cases hai : a = i
      · by_cases hbj : b = j
        · rw [if_pos hai, if_pos hbj, hPE, if_pos hai, hEP, if_pos hbj]
        · rw [if_pos hai, if_neg hbj, hPE, if_pos hai, hEP, if_neg hbj,
            smul_zero]
      · rw [if_neg hai, hPE, if_neg hai, zero_mul, smul_zero]
    rw [Finset.sum_congr rfl fun i _ =>
      Finset.sum_congr rfl fun j _ => hterm i j]
    have hinner : ∀ i, (∑ j, if a = i then
        (if b = j then M i j • E i j else 0) else 0) =
        if a = i then M i b • E i b else 0 := by
      intro i
      by_cases hai : a = i
      · rw [if_pos hai]
        rw [Finset.sum_congr rfl fun j _ => if_pos hai,
          Finset.sum_ite_eq, if_pos (Finset.mem_univ b)]
      · rw [if_neg hai]
        exact Finset.sum_eq_zero fun j _ => if_neg hai
    rw [Finset.sum_congr rfl fun i _ => hinner i, Finset.sum_ite_eq,
      if_pos (Finset.mem_univ a)]
  -- the bundled non-unital star homomorphism
  let Φ : Matrix (Fin l.length) (Fin l.length) ℂ →⋆ₙₐ[ℂ] ↥corner :=
    { toFun := fun M => ⟨∑ i, ∑ j, M i j • E i j, hmemΦ M⟩
      map_smul' := fun c M => Subtype.ext (by
        show (∑ i, ∑ j, (c • M) i j • E i j) =
          c • ∑ i, ∑ j, M i j • E i j
        rw [Finset.smul_sum]
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [Finset.smul_sum]
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [Matrix.smul_apply, smul_eq_mul, mul_smul])
      map_zero' := Subtype.ext (by
        show (∑ i, ∑ j, (0 : Matrix (Fin l.length) (Fin l.length) ℂ) i j
          • E i j) = 0
        refine Finset.sum_eq_zero fun i _ => Finset.sum_eq_zero
          fun j _ => ?_
        rw [Matrix.zero_apply, zero_smul])
      map_add' := fun M N => Subtype.ext (by
        show (∑ i, ∑ j, (M + N) i j • E i j) =
          (∑ i, ∑ j, M i j • E i j) + ∑ i, ∑ j, N i j • E i j
        rw [← Finset.sum_add_distrib]
        refine Finset.sum_congr rfl fun i _ => ?_
        rw [← Finset.sum_add_distrib]
        refine Finset.sum_congr rfl fun j _ => ?_
        rw [Matrix.add_apply, add_smul])
      map_mul' := fun M N => Subtype.ext (by
        show (∑ i, ∑ j, (M * N) i j • E i j) = _
        exact (hmul M N).symm)
      map_star' := fun M => Subtype.ext (by
        show (∑ i, ∑ j, (star M) i j • E i j) =
          star (∑ i, ∑ j, M i j • E i j)
        exact (hstarmap M).symm) }
  have hinj : Function.Injective Φ := by
    intro M N hMN
    have hzero : (∑ i, ∑ j, (M - N) i j • E i j) = 0 := by
      have h1 : Φ (M - N) = 0 := by rw [map_sub, hMN, sub_self]
      exact congrArg Subtype.val h1
    ext a b
    have h2 : (M - N) a b • E a b = 0 := by
      rw [← hPab (M - N) a b, hzero, mul_zero, zero_mul]
    rcases smul_eq_zero.mp h2 with h3 | h3
    · rw [Matrix.sub_apply] at h3
      exact sub_eq_zero.mp h3
    · exact absurd h3 (hEne a b)
  have hsurj : Function.Surjective Φ := by
    rintro ⟨x, hxS, hex⟩
    choose c hc using hcoef x hxS
    refine ⟨Matrix.of c, Subtype.ext ?_⟩
    show (∑ i, ∑ j, (Matrix.of c) i j • E i j) = x
    have h1 : ∀ i j, (Matrix.of c) i j • E i j = P i * x * P j := by
      intro i j
      rw [Matrix.of_apply, ← hc i j]
    rw [Finset.sum_congr rfl fun i _ =>
      Finset.sum_congr rfl fun j _ => h1 i j]
    exact (hdecomp x hxS hex).symm
  exact ⟨(StarAlgEquiv.ofBijective Φ ⟨hinj, hsurj⟩).symm⟩

end MatrixUnits

/-! ## The relative center of a minimal central corner is scalar -/

section CornerCenter

variable {n : Type u} [Fintype n] [DecidableEq n]
  {S : StarSubalgebra ℂ (Matrix n n ℂ)}

/-- Trivial relative center: an element of a minimal central corner
commuting with the whole corner is a complex multiple of the corner unit.
Commuting with the corner forces centrality in the subalgebra, and the
self-adjoint parts cut against the minimal central projection. -/
theorem IsMinimalCentralProjectionIn.corner_center_scalar
    {e : Matrix n n ℂ} (he : IsMinimalCentralProjectionIn S e)
    {z : Matrix n n ℂ}
    (hz : z ∈ relativeCorner S he.toIsCentralProjectionIn)
    (hcomm : ∀ x ∈ relativeCorner S he.toIsCentralProjectionIn,
      z * x = x * z) :
    ∃ c : ℂ, z = c • e := by
  haveI : Nonempty n := nonempty_of_matrix_ne_zero he.ne_zero
  obtain ⟨hzS, hez⟩ := hz
  have hze : z * e = z :=
    mul_unit_of_mem_relativeCorner he.toIsCentralProjectionIn ⟨hzS, hez⟩
  -- commuting with the corner forces centrality in the subalgebra
  have hcentral : IsCentralIn S z := by
    refine ⟨hzS, fun x hx => ?_⟩
    have hex : e * (e * x) = e * x := by
      rw [← mul_assoc, he.isIdempotentElem.eq]
    have h1 : z * (e * x) = (e * x) * z :=
      hcomm (e * x) ⟨mul_mem he.centralIn.mem hx, hex⟩
    calc z * x = (z * e) * x := by rw [hze]
      _ = z * (e * x) := by rw [mul_assoc]
      _ = (e * x) * z := h1
      _ = (x * e) * z := by rw [he.centralIn.commutes hx]
      _ = x * (e * z) := by rw [mul_assoc]
      _ = x * z := by rw [hez]
  -- cut the self-adjoint parts against the minimal central projection
  have hsa₁ : IsSelfAdjoint (((2 : ℂ)⁻¹) • (z + star z)) := by
    show star _ = _
    rw [star_smul, star_add, star_star, star_inv₀, star_ofNat,
      add_comm (star z) z]
  have hsa₂ : IsSelfAdjoint (((2 : ℂ)⁻¹ * Complex.I) • (star z - z)) := by
    show star _ = _
    rw [star_smul, star_sub, star_star, star_mul', star_inv₀, star_ofNat,
      Complex.star_def, Complex.conj_I]
    rw [show (2 : ℂ)⁻¹ * -Complex.I = -((2 : ℂ)⁻¹ * Complex.I) by ring]
    rw [neg_smul, ← smul_neg, neg_sub]
  have hc₁ : IsCentralIn S (((2 : ℂ)⁻¹) • (z + star z)) :=
    (hcentral.add hcentral.star).smul _
  have hc₂ : IsCentralIn S (((2 : ℂ)⁻¹ * Complex.I) • (star z - z)) :=
    (hcentral.star.sub hcentral).smul _
  obtain ⟨c₁, hcc₁⟩ := hc₁.mul_minimal_eq_smul hsa₁ he
  obtain ⟨c₂, hcc₂⟩ := hc₂.mul_minimal_eq_smul hsa₂ he
  have hstarze : star z * e = star z := by
    have h1 := congrArg star hez
    rwa [star_mul, he.isSelfAdjoint.star_eq] at h1
  have habs₁ : (((2 : ℂ)⁻¹) • (z + star z)) * e =
      ((2 : ℂ)⁻¹) • (z + star z) := by
    rw [smul_mul_assoc, add_mul, hze, hstarze]
  have habs₂ : (((2 : ℂ)⁻¹ * Complex.I) • (star z - z)) * e =
      ((2 : ℂ)⁻¹ * Complex.I) • (star z - z) := by
    rw [smul_mul_assoc, sub_mul, hze, hstarze]
  rw [habs₁] at hcc₁
  rw [habs₂] at hcc₂
  have hdecomp : z = ((2 : ℂ)⁻¹) • (z + star z) +
      Complex.I • (((2 : ℂ)⁻¹ * Complex.I) • (star z - z)) := by
    rw [smul_smul, smul_add, smul_sub]
    rw [show Complex.I * ((2 : ℂ)⁻¹ * Complex.I) = -(2 : ℂ)⁻¹ by
      rw [mul_comm (2 : ℂ)⁻¹ Complex.I, ← mul_assoc, Complex.I_mul_I]; ring]
    rw [neg_smul, neg_smul, neg_sub_neg]
    rw [show ((2 : ℂ)⁻¹ • z + (2 : ℂ)⁻¹ • star z +
        ((2 : ℂ)⁻¹ • z - (2 : ℂ)⁻¹ • star z)) =
        ((2 : ℂ)⁻¹ + (2 : ℂ)⁻¹) • z by
      rw [add_smul]; abel]
    rw [show ((2 : ℂ)⁻¹ + (2 : ℂ)⁻¹ : ℂ) = 1 by norm_num, one_smul]
  refine ⟨c₁ + Complex.I * c₂, ?_⟩
  rw [hdecomp, hcc₁, hcc₂, smul_smul, add_smul]

end CornerCenter

/-! ## The iterated cut and star Wedderburn for the subalgebra -/

section PiCongr

variable {ι : Type u} {A : ι → Type v} {B : ι → Type w}
  [∀ i, Add (A i)] [∀ i, Mul (A i)] [∀ i, SMul ℂ (A i)] [∀ i, Star (A i)]
  [∀ i, Add (B i)] [∀ i, Mul (B i)] [∀ i, SMul ℂ (B i)] [∀ i, Star (B i)]

/-- Componentwise congruence of star-algebra equivalences on dependent
products. -/
def starAlgEquivPiCongr (F : ∀ i, A i ≃⋆ₐ[ℂ] B i) :
    ((i : ι) → A i) ≃⋆ₐ[ℂ] ((i : ι) → B i) where
  toFun x i := F i (x i)
  invFun y i := (F i).symm (y i)
  left_inv x := funext fun i => (F i).symm_apply_apply (x i)
  right_inv y := funext fun i => (F i).apply_symm_apply (y i)
  map_mul' x y := funext fun i => map_mul (F i) (x i) (y i)
  map_add' x y := funext fun i => map_add (F i) (x i) (y i)
  map_smul' c x := funext fun i => map_smul (F i) c (x i)
  map_star' x := funext fun i => map_star (F i) (x i)

end PiCongr

section IteratedCut

variable {n : Type u} [Fintype n] [DecidableEq n]

/-- Star Wedderburn for a star subalgebra of a finite complex matrix
algebra: the subalgebra is star-isomorphic to a finite direct sum of
full matrix blocks.  The identity resolves into minimal orthogonal
central projections, the cut along the resolution factors the subalgebra
into its corners, and each corner is one full matrix block. -/
theorem starSubalgebra_starEquiv_pi_matrix
    (S : StarSubalgebra ℂ (Matrix n n ℂ)) :
    ∃ (k : ℕ) (d : Fin k → ℕ), (∀ i, 0 < d i) ∧
      Nonempty (↥S ≃⋆ₐ[ℂ]
        ((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ)) := by
  classical
  obtain ⟨l, hlmin, hlorth, hlsum⟩ := exists_minimal_central_resolution S
  set E : Fin l.length → Matrix n n ℂ := l.get with hE
  have hEmin : ∀ i, IsMinimalCentralProjectionIn S (E i) :=
    fun i => hlmin _ (List.get_mem l i)
  have hEorth : ∀ i j, i ≠ j → E i * E j = 0 := by
    intro i j hij
    have hpair := List.pairwise_iff_get.mp hlorth
    rcases lt_or_gt_of_ne hij with h1 | h1
    · exact hpair i j h1
    · have h0 := hpair j i h1
      have h2 := congrArg star h0
      rwa [star_mul, (hEmin i).isSelfAdjoint.star_eq,
        (hEmin j).isSelfAdjoint.star_eq, star_zero] at h2
  have hEsum : ∑ i, E i = 1 := by
    rw [← hlsum]
    conv_rhs => rw [← List.ofFn_get l]
    rw [List.sum_ofFn]
  -- the cut along the resolution
  have hcut : ∀ (x : Matrix n n ℂ), x ∈ S → ∀ i,
      E i * x ∈ relativeCorner S (hEmin i).toIsCentralProjectionIn := by
    intro x hx i
    exact ⟨mul_mem (hEmin i).centralIn.mem hx,
      by rw [← mul_assoc, (hEmin i).isIdempotentElem.eq]⟩
  let cutEquiv : ↥S ≃⋆ₐ[ℂ]
      ((i : Fin l.length) →
        ↥(relativeCorner S (hEmin i).toIsCentralProjectionIn)) :=
    { toFun := fun x i => ⟨E i * (x : Matrix n n ℂ), hcut _ x.2 i⟩
      invFun := fun y =>
        ⟨∑ i, ((y i : Matrix n n ℂ)), sum_mem fun i _ => (y i).2.1⟩
      left_inv := fun x => Subtype.ext (by
        show ∑ i, E i * (x : Matrix n n ℂ) = (x : Matrix n n ℂ)
        rw [← Finset.sum_mul, hEsum, one_mul])
      right_inv := fun y => funext fun i => Subtype.ext (by
        show E i * (∑ j, ((y j : Matrix n n ℂ))) = ((y i : Matrix n n ℂ))
        rw [Finset.mul_sum]
        have hterm : ∀ j, E i * ((y j : Matrix n n ℂ)) =
            if j = i then ((y j : Matrix n n ℂ)) else 0 := by
          intro j
          by_cases hji : j = i
          · subst hji
            rw [if_pos rfl]
            exact (y j).2.2
          · rw [if_neg hji, ← (y j).2.2, ← mul_assoc,
              hEorth i j (fun h1 => hji h1.symm), zero_mul]
        rw [Finset.sum_congr rfl fun j _ => hterm j,
          Finset.sum_ite_eq' Finset.univ i
            (fun j => ((y j : Matrix n n ℂ))),
          if_pos (Finset.mem_univ i)])
      map_mul' := fun x y => funext fun i => Subtype.ext (by
        show E i * ((x : Matrix n n ℂ) * (y : Matrix n n ℂ)) =
          (E i * (x : Matrix n n ℂ)) * (E i * (y : Matrix n n ℂ))
        calc E i * ((x : Matrix n n ℂ) * (y : Matrix n n ℂ))
            = (E i * E i) * ((x : Matrix n n ℂ) * (y : Matrix n n ℂ)) := by
              rw [(hEmin i).isIdempotentElem.eq]
          _ = E i * ((E i * (x : Matrix n n ℂ)) * (y : Matrix n n ℂ)) := by
              noncomm_ring
          _ = E i * (((x : Matrix n n ℂ) * E i) * (y : Matrix n n ℂ)) := by
              rw [(hEmin i).centralIn.commutes x.2]
          _ = (E i * (x : Matrix n n ℂ)) * (E i * (y : Matrix n n ℂ)) := by
              noncomm_ring)
      map_add' := fun x y => funext fun i => Subtype.ext (by
        show E i * ((x : Matrix n n ℂ) + (y : Matrix n n ℂ)) =
          E i * (x : Matrix n n ℂ) + E i * (y : Matrix n n ℂ)
        rw [mul_add])
      map_smul' := fun c x => funext fun i => Subtype.ext (by
        show E i * (c • (x : Matrix n n ℂ)) = c • (E i * (x : Matrix n n ℂ))
        rw [mul_smul_comm])
      map_star' := fun x => funext fun i => Subtype.ext (by
        show E i * star (x : Matrix n n ℂ) =
          star (E i * (x : Matrix n n ℂ))
        rw [star_mul, (hEmin i).isSelfAdjoint.star_eq]
        exact (hEmin i).centralIn.commutes (star_mem x.2)) }
  -- classify each corner
  have hblocks := fun i => minimalCentralCorner_starEquiv_matrix S (hEmin i)
  choose d hd hEquiv using hblocks
  exact ⟨l.length, d, hd,
    ⟨cutEquiv.trans (starAlgEquivPiCongr
      (fun i => Classical.choice (hEquiv i)))⟩⟩

end IteratedCut

/-! ## Central idempotents of a finite direct sum of full matrix blocks -/

section PiBlockCenter

variable {J : Type u} [Fintype J] [DecidableEq J]
variable {n : J → Type v} [∀ j, Fintype (n j)] [∀ j, DecidableEq (n j)]

/-- The finite direct sum of full matrix blocks indexed by `J`. -/
abbrev PiBlockAlgebra (n : J → Type v) :=
  (j : J) → Matrix (n j) (n j) ℂ

/-- The indicator central idempotent of a set of blocks. -/
def piBlockIndicator (T : Finset J) : PiBlockAlgebra n :=
  fun j => if j ∈ T then 1 else 0

omit [Fintype J] [∀ j, Fintype (n j)] in
theorem piBlockIndicator_apply (T : Finset J) (i : J) :
    piBlockIndicator (n := n) T i = if i ∈ T then 1 else 0 := rfl

/-- The minimal central projection carried by one block. -/
def piBlockProjection (j : J) : PiBlockAlgebra n :=
  fun i => if i = j then 1 else 0

omit [Fintype J] [∀ j, Fintype (n j)] in
theorem piBlockProjection_apply (j i : J) :
    piBlockProjection (n := n) j i = if i = j then 1 else 0 := rfl

omit [Fintype J] in
theorem piBlockProjection_mul_self (j : J) :
    piBlockProjection (n := n) j * piBlockProjection (n := n) j =
      piBlockProjection (n := n) j := by
  funext i
  show (if i = j then (1 : Matrix (n i) (n i) ℂ) else 0) *
      (if i = j then 1 else 0) = if i = j then 1 else 0
  by_cases h : i = j
  · rw [if_pos h, one_mul]
  · rw [if_neg h, zero_mul]

omit [Fintype J] in
theorem piBlockProjection_central (j : J) (x : PiBlockAlgebra n) :
    piBlockProjection (n := n) j * x = x * piBlockProjection (n := n) j := by
  funext i
  show (if i = j then (1 : Matrix (n i) (n i) ℂ) else 0) * x i =
    x i * (if i = j then 1 else 0)
  by_cases h : i = j
  · rw [if_pos h, one_mul, mul_one]
  · rw [if_neg h, zero_mul, mul_zero]

/-- Every central idempotent of the finite direct sum of full matrix
blocks is the indicator of a set of blocks: each component is central in
its own full block, hence scalar, and idempotency forces each scalar to
be zero or one. -/
theorem piBlock_central_idempotent_indicator [∀ j, Nonempty (n j)]
    {z : PiBlockAlgebra n} (hcentral : ∀ x, z * x = x * z)
    (hidem : z * z = z) :
    ∃ T : Finset J, z = piBlockIndicator (n := n) T := by
  classical
  have hscalar : ∀ i, z i ∈ Set.range (Matrix.scalar (n i)) := by
    intro i
    refine Matrix.mem_range_scalar_of_commute_single (fun p q _ => ?_)
    have h := congrArg (fun w : PiBlockAlgebra n => w i)
      (hcentral (Pi.single i (Matrix.single p q 1)))
    have h' : z i * Matrix.single p q 1 = Matrix.single p q 1 * z i := by
      simpa using h
    exact h'.symm
  choose c hc using hscalar
  have hidemc : ∀ i, c i * c i = c i := by
    intro i
    obtain ⟨p⟩ := (inferInstance : Nonempty (n i))
    have h : z i * z i = z i :=
      congrArg (fun w : PiBlockAlgebra n => w i) hidem
    rw [← hc i, ← map_mul] at h
    have h2 := congrArg (fun M : Matrix (n i) (n i) ℂ => M p p) h
    simpa [Matrix.scalar_apply, Matrix.diagonal_apply_eq] using h2
  have hcases : ∀ i, c i = 0 ∨ c i = 1 := by
    intro i
    have h : c i * (c i - 1) = 0 := by linear_combination hidemc i
    rcases mul_eq_zero.mp h with h0 | h1
    · exact Or.inl h0
    · exact Or.inr (sub_eq_zero.mp h1)
  refine ⟨Finset.univ.filter fun i => c i = 1, funext fun i => ?_⟩
  rcases hcases i with h0 | h1
  · have hnot : i ∉ Finset.univ.filter fun i' => c i' = 1 := by
      simp [Finset.mem_filter, h0]
    rw [piBlockIndicator_apply, if_neg hnot, ← hc i, h0, map_zero]
  · have hmem : i ∈ Finset.univ.filter fun i' => c i' = 1 := by
      simp [Finset.mem_filter, h1]
    rw [piBlockIndicator_apply, if_pos hmem, ← hc i, h1, map_one]

/-- A star automorphism of the finite direct sum carries each block
projection to an indicator of blocks. -/
theorem starAutomorphism_piBlockProjection_indicator [∀ j, Nonempty (n j)]
    (F : PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n) (j : J) :
    ∃ T : Finset J, F (piBlockProjection (n := n) j) =
      piBlockIndicator (n := n) T := by
  refine piBlock_central_idempotent_indicator (fun y => ?_) ?_
  · conv_lhs => rw [← F.apply_symm_apply y]
    conv_rhs => rw [← F.apply_symm_apply y]
    rw [← map_mul, ← map_mul, piBlockProjection_central j (F.symm y)]
  · rw [← map_mul, piBlockProjection_mul_self]

end PiBlockCenter

/-! ## Continuous block fixing and the finite-block Stone converse -/

section PiBlockControl

variable {J : Type u} [Fintype J] [DecidableEq J]
variable {n : J → Type v} [∀ j, Fintype (n j)] [∀ j, DecidableEq (n j)]

/-- A continuous path with values in a finite subset of a T1 space is
constant: each fiber is closed, the complement of one fiber is the finite
union of the others, and the real line is connected. -/
private theorem continuous_finiteRange_apply_eq {X : Type w}
    [TopologicalSpace X] [T1Space X] {f : ℝ → X} (hf : Continuous f)
    {F : Set X} (hF : F.Finite) (hmem : ∀ s, f s ∈ F) (t : ℝ) :
    f t = f 0 := by
  have hclosed : IsClosed (f ⁻¹' {f 0}) := isClosed_singleton.preimage hf
  have hcompl : (f ⁻¹' {f 0})ᶜ = f ⁻¹' (F \ {f 0}) := by
    ext s
    simp only [Set.mem_compl_iff, Set.mem_preimage, Set.mem_singleton_iff,
      Set.mem_diff]
    exact ⟨fun hne => ⟨hmem s, hne⟩, fun hs => hs.2⟩
  have hopen : IsOpen (f ⁻¹' {f 0}) := by
    have hcl : IsClosed (f ⁻¹' (F \ {f 0})) :=
      ((hF.subset Set.diff_subset).isClosed).preimage hf
    rw [← hcompl] at hcl
    exact isClosed_compl_iff.mp hcl
  obtain hempty | huniv := isClopen_iff.mp ⟨hclosed, hopen⟩
  · exfalso
    have h0 : (0 : ℝ) ∈ f ⁻¹' {f 0} := by
      rw [Set.mem_preimage, Set.mem_singleton_iff]
    rw [hempty] at h0
    exact Set.notMem_empty 0 h0
  · have ht : t ∈ f ⁻¹' {f 0} := huniv ▸ Set.mem_univ t
    rwa [Set.mem_preimage, Set.mem_singleton_iff] at ht

/-- A pointwise-continuous family of star automorphisms through the
identity fixes every block projection of the finite direct sum: the orbit
is a continuous path inside the finite set of block indicators, and the
parameter line is connected. -/
theorem continuousFlow_fixes_piBlockProjection [∀ j, Nonempty (n j)]
    (α : ℝ → (PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n))
    (hzero : ∀ x, α 0 x = x)
    (hcont : ∀ x, Continuous fun t : ℝ => α t x) (j : J) :
    ∀ t : ℝ, α t (piBlockProjection (n := n) j) =
      piBlockProjection (n := n) j := by
  intro t
  have hmem : ∀ s : ℝ, α s (piBlockProjection (n := n) j) ∈
      Set.range (piBlockIndicator (n := n)) := by
    intro s
    obtain ⟨T, hT⟩ := starAutomorphism_piBlockProjection_indicator (α s) j
    exact ⟨T, hT.symm⟩
  have hconst := continuous_finiteRange_apply_eq
    (hcont (piBlockProjection (n := n) j))
    (Set.finite_range (piBlockIndicator (n := n))) hmem t
  rw [hconst, hzero]

omit [Fintype J] in
theorem mul_piBlockProjection_eq_single (y : PiBlockAlgebra n) (j : J) :
    y * piBlockProjection (n := n) j = Pi.single j (y j) := by
  funext i
  rw [Pi.mul_apply, piBlockProjection_apply]
  by_cases h : i = j
  · subst h
    rw [if_pos rfl, mul_one, Pi.single_eq_same]
  · rw [if_neg h, mul_zero, Pi.single_eq_of_ne h]

omit [Fintype J] in
theorem single_mul_piBlockProjection (j : J) (x : Matrix (n j) (n j) ℂ) :
    Pi.single j x * piBlockProjection (n := n) j = Pi.single j x := by
  rw [mul_piBlockProjection_eq_single, Pi.single_eq_same]

omit [Fintype J] in
/-- A block-fixing star automorphism carries the block into itself. -/
theorem apply_single_of_fixes
    (F : PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n) (j : J)
    (hF : F (piBlockProjection (n := n) j) = piBlockProjection (n := n) j)
    (x : Matrix (n j) (n j) ℂ) :
    F (Pi.single j x) = Pi.single j (F (Pi.single j x) j) := by
  conv_lhs => rw [← single_mul_piBlockProjection j x, map_mul, hF,
    mul_piBlockProjection_eq_single]

omit [Fintype J] in
/-- Fixing a block projection passes to the inverse automorphism. -/
theorem symm_fixes_piBlockProjection
    (F : PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n) (j : J)
    (hF : F (piBlockProjection (n := n) j) = piBlockProjection (n := n) j) :
    F.symm (piBlockProjection (n := n) j) = piBlockProjection (n := n) j := by
  conv_lhs => rw [← hF]
  rw [F.symm_apply_apply]

/-- The one-block restriction of a block-fixing star automorphism of the
finite direct sum. -/
def piBlockRestriction
    (F : PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n) (j : J)
    (hF : F (piBlockProjection (n := n) j) = piBlockProjection (n := n) j) :
    Matrix (n j) (n j) ℂ ≃⋆ₐ[ℂ] Matrix (n j) (n j) ℂ where
  toFun x := F (Pi.single j x) j
  invFun x := F.symm (Pi.single j x) j
  left_inv x := by
    show F.symm (Pi.single j (F (Pi.single j x) j)) j = x
    rw [← apply_single_of_fixes F j hF x, F.symm_apply_apply,
      Pi.single_eq_same]
  right_inv x := by
    show F (Pi.single j (F.symm (Pi.single j x) j)) j = x
    rw [← apply_single_of_fixes F.symm j
        (symm_fixes_piBlockProjection F j hF) x,
      F.apply_symm_apply, Pi.single_eq_same]
  map_mul' x y := by
    show F (Pi.single j (x * y)) j = F (Pi.single j x) j * F (Pi.single j y) j
    rw [Pi.single_mul, map_mul]
    rfl
  map_add' x y := by
    show F (Pi.single j (x + y)) j = F (Pi.single j x) j + F (Pi.single j y) j
    rw [Pi.single_add, map_add]
    rfl
  map_smul' c x := by
    show F (Pi.single j (c • x)) j = c • F (Pi.single j x) j
    rw [Pi.single_smul, map_smul]
    rfl
  map_star' x := by
    show F (Pi.single j (star x)) j = star (F (Pi.single j x) j)
    rw [Pi.single_star, map_star]
    rfl

omit [Fintype J] in
theorem piBlockRestriction_apply
    (F : PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n) (j : J)
    (hF : F (piBlockProjection (n := n) j) = piBlockProjection (n := n) j)
    (x : Matrix (n j) (n j) ℂ) :
    piBlockRestriction F j hF x = F (Pi.single j x) j := rfl

/-- Finite-block Stone converse from pointwise continuity alone.  Every
pointwise-continuous real-parameter star-automorphism group of a finite
direct sum of full matrix blocks fixes every block projection and is
blockwise conjugation by the coherent unitary family of one
time-independent self-adjoint Hamiltonian per block.  Block fixing is
derived, so no block-preservation hypothesis is taken. -/
theorem piBlockStoneConverse_of_continuous [∀ j, Nonempty (n j)]
    (α : ℝ → (PiBlockAlgebra n ≃⋆ₐ[ℂ] PiBlockAlgebra n))
    (hzero : ∀ x, α 0 x = x)
    (hgroup : ∀ s t : ℝ, ∀ x, α (s + t) x = α s (α t x))
    (hcont : ∀ x, Continuous fun t : ℝ => α t x) :
    ∃ Ham : (j : J) → Matrix (n j) (n j) ℂ,
      (∀ j, IsSelfAdjoint (Ham j)) ∧
        ∀ (t : ℝ) (x : PiBlockAlgebra n) (j : J),
          α t x j = stonePropagator (Ham j) t * x j *
            stonePropagator (Ham j) (-t) := by
  classical
  have hfix : ∀ (j : J) (t : ℝ),
      α t (piBlockProjection (n := n) j) = piBlockProjection (n := n) j :=
    fun j => continuousFlow_fixes_piBlockProjection α hzero hcont j
  have hblock : ∀ j : J, ∃ Ham : Matrix (n j) (n j) ℂ,
      IsSelfAdjoint Ham ∧ ∀ (t : ℝ) (x : Matrix (n j) (n j) ℂ),
        piBlockRestriction (α t) j (hfix j t) x =
          stonePropagator Ham t * x * stonePropagator Ham (-t) := by
    intro j
    exact finiteStoneConverse_of_continuous
      (fun t => piBlockRestriction (α t) j (hfix j t))
      (fun x => by
        show α 0 (Pi.single j x) j = x
        rw [hzero, Pi.single_eq_same])
      (fun s t x => by
        show α (s + t) (Pi.single j x) j =
          α s (Pi.single j (α t (Pi.single j x) j)) j
        conv_lhs => rw [hgroup s t, apply_single_of_fixes (α t) j (hfix j t) x])
      (fun x => (continuous_apply j).comp (hcont (Pi.single j x)))
  choose Ham hsa hconj using hblock
  refine ⟨Ham, hsa, ?_⟩
  intro t x j
  have hx : x = ∑ i, Pi.single i (x i) := (Finset.univ_sum_single x).symm
  conv_lhs => rw [hx]
  rw [map_sum, Finset.sum_apply]
  have hterm : ∀ i, α t (Pi.single i (x i)) j =
      if i = j then
        stonePropagator (Ham j) t * x j * stonePropagator (Ham j) (-t)
      else 0 := by
    intro i
    by_cases hij : i = j
    · subst hij
      rw [if_pos rfl]
      have h := hconj i t (x i)
      rw [piBlockRestriction_apply] at h
      exact h
    · rw [if_neg hij, apply_single_of_fixes (α t) i (hfix i t) (x i)]
      exact Pi.single_eq_of_ne (fun h => hij h.symm) _
  rw [Finset.sum_congr rfl fun i _ => hterm i,
    Finset.sum_ite_eq' Finset.univ j
      (fun _ => stonePropagator (Ham j) t * x j * stonePropagator (Ham j) (-t)),
    if_pos (Finset.mem_univ j)]

end PiBlockControl

/-! ## Continuous flows on a star subalgebra fix its minimal center -/

section SubalgebraFlow

variable {n : Type u} [Fintype n] [DecidableEq n]
  {S : StarSubalgebra ℂ (Matrix n n ℂ)}

private theorem mul_list_sum' {M : Type u} [NonUnitalNonAssocSemiring M]
    (a : M) (l : List M) : a * l.sum = (l.map (fun x => a * x)).sum := by
  induction l with
  | nil => simp
  | cons b l ih => simp [List.sum_cons, mul_add, ih]

/-- Rigidity of minimal central projections: every minimal central
projection of the subalgebra is a member of every minimal orthogonal
central resolution of the identity. -/
theorem IsMinimalCentralProjectionIn.mem_resolution
    {q : Matrix n n ℂ} (hq : IsMinimalCentralProjectionIn S q)
    {l : List (Matrix n n ℂ)}
    (hl : ∀ e ∈ l, IsMinimalCentralProjectionIn S e) (hsum : l.sum = 1) :
    q ∈ l := by
  have hqsum : q = (l.map (fun f => q * f)).sum := by
    rw [← mul_list_sum', hsum, mul_one]
  have hex : ∃ f ∈ l, q * f ≠ 0 := by
    by_contra hall
    push Not at hall
    refine hq.ne_zero (hqsum.trans (List.sum_eq_zero ?_))
    intro y hy
    rw [List.mem_map] at hy
    obtain ⟨f, hf, rfl⟩ := hy
    exact hall f hf
  obtain ⟨f, hfl, hqf⟩ := hex
  have hff := hl f hfl
  have hprod : IsCentralProjectionIn S (q * f) :=
    hq.toIsCentralProjectionIn.mul hff.toIsCentralProjectionIn
  have hcomm : q * f = f * q := hq.centralIn.commute hff.centralIn
  have hle_q : (q * f) * q = q * f := by
    rw [hcomm, mul_assoc, hq.isIdempotentElem.eq, ← hcomm]
  have hle_f : (q * f) * f = q * f := by
    rw [mul_assoc, hff.isIdempotentElem.eq]
  have hq_eq : q * f = q := (hq.minimal _ hprod hle_q).resolve_left hqf
  have hf_eq : q * f = f := (hff.minimal _ hprod hle_f).resolve_left hqf
  rw [hq_eq.symm.trans hf_eq]
  exact hfl

/-- Star automorphisms of the subalgebra carry central star projections of
the subalgebra to central star projections of the subalgebra. -/
theorem IsCentralProjectionIn.map_subtype {p : Matrix n n ℂ}
    (hp : IsCentralProjectionIn S p) (F : ↥S ≃⋆ₐ[ℂ] ↥S) :
    IsCentralProjectionIn S
      ((F ⟨p, hp.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) := by
  have haidem : (⟨p, hp.centralIn.mem⟩ : ↥S) * ⟨p, hp.centralIn.mem⟩ =
      ⟨p, hp.centralIn.mem⟩ := Subtype.ext hp.isIdempotentElem.eq
  have hastar : star (⟨p, hp.centralIn.mem⟩ : ↥S) =
      ⟨p, hp.centralIn.mem⟩ := Subtype.ext hp.isSelfAdjoint.star_eq
  refine { isIdempotentElem := ?_, isSelfAdjoint := ?_,
           centralIn := ⟨(F ⟨p, hp.centralIn.mem⟩).2, ?_⟩ }
  · have h1 : F ⟨p, hp.centralIn.mem⟩ * F ⟨p, hp.centralIn.mem⟩ =
        F ⟨p, hp.centralIn.mem⟩ := by rw [← map_mul, haidem]
    exact congrArg Subtype.val h1
  · have h1 : star (F ⟨p, hp.centralIn.mem⟩) = F ⟨p, hp.centralIn.mem⟩ := by
      rw [← map_star, hastar]
    exact congrArg Subtype.val h1
  · intro x hx
    have hx' : F (F.symm ⟨x, hx⟩) = ⟨x, hx⟩ := F.apply_symm_apply _
    have hxa : (⟨p, hp.centralIn.mem⟩ : ↥S) * F.symm ⟨x, hx⟩ =
        F.symm ⟨x, hx⟩ * ⟨p, hp.centralIn.mem⟩ :=
      Subtype.ext (hp.centralIn.commutes (F.symm ⟨x, hx⟩).2)
    have h1 : F ⟨p, hp.centralIn.mem⟩ * ⟨x, hx⟩ =
        ⟨x, hx⟩ * F ⟨p, hp.centralIn.mem⟩ := by
      rw [← hx', ← map_mul, ← map_mul, hxa]
    exact congrArg Subtype.val h1

/-- Star automorphisms of the subalgebra carry minimal central projections
of the subalgebra to minimal central projections. -/
theorem IsMinimalCentralProjectionIn.map_subtype {q : Matrix n n ℂ}
    (hq : IsMinimalCentralProjectionIn S q) (F : ↥S ≃⋆ₐ[ℂ] ↥S) :
    IsMinimalCentralProjectionIn S
      ((F ⟨q, hq.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) := by
  refine ⟨hq.toIsCentralProjectionIn.map_subtype F, ?_, ?_⟩
  · intro h0
    have h1 : F ⟨q, hq.centralIn.mem⟩ = 0 := Subtype.ext h0
    have h2 : (⟨q, hq.centralIn.mem⟩ : ↥S) = 0 := by
      have h3 := congrArg F.symm h1
      rwa [F.symm_apply_apply, map_zero] at h3
    exact hq.ne_zero (congrArg Subtype.val h2)
  · intro r hr hle
    have hcproj : IsCentralProjectionIn S
        ((F.symm ⟨r, hr.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) :=
      hr.map_subtype F.symm
    have himg : F (F.symm ⟨r, hr.centralIn.mem⟩ * ⟨q, hq.centralIn.mem⟩) =
        F (F.symm ⟨r, hr.centralIn.mem⟩) := by
      rw [map_mul, F.apply_symm_apply]
      exact Subtype.ext hle
    have hle' : F.symm ⟨r, hr.centralIn.mem⟩ * ⟨q, hq.centralIn.mem⟩ =
        F.symm ⟨r, hr.centralIn.mem⟩ := F.injective himg
    have hleq : ((F.symm ⟨r, hr.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) * q =
        ((F.symm ⟨r, hr.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) :=
      congrArg Subtype.val hle'
    rcases hq.minimal _ hcproj hleq with h0 | hqe
    · left
      have hc0 : (F.symm ⟨r, hr.centralIn.mem⟩ : ↥S) = 0 := Subtype.ext h0
      have hr0 : (⟨r, hr.centralIn.mem⟩ : ↥S) = 0 := by
        rw [← F.apply_symm_apply ⟨r, hr.centralIn.mem⟩, hc0, map_zero]
      exact congrArg Subtype.val hr0
    · right
      have hca : (F.symm ⟨r, hr.centralIn.mem⟩ : ↥S) =
          ⟨q, hq.centralIn.mem⟩ := Subtype.ext hqe
      have hrF : (⟨r, hr.centralIn.mem⟩ : ↥S) = F ⟨q, hq.centralIn.mem⟩ := by
        rw [← F.apply_symm_apply ⟨r, hr.centralIn.mem⟩, hca]
      exact congrArg Subtype.val hrF

/-- A pointwise-continuous family of star automorphisms of the subalgebra
through the identity fixes every minimal central projection of the
subalgebra at every parameter: the orbit is a continuous path inside the
finite member set of one minimal central resolution. -/
theorem continuousFlow_fixes_minimalCentralProjection
    (α : ℝ → (↥S ≃⋆ₐ[ℂ] ↥S)) (hzero : ∀ x, α 0 x = x)
    (hcont : ∀ x : ↥S, Continuous fun t : ℝ =>
      ((α t x : ↥S) : Matrix n n ℂ))
    {e : Matrix n n ℂ} (he : IsMinimalCentralProjectionIn S e) (t : ℝ) :
    ((α t ⟨e, he.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) = e := by
  obtain ⟨l, hlmin, _, hlsum⟩ := exists_minimal_central_resolution S
  have hmem : ∀ s : ℝ,
      ((α s ⟨e, he.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) ∈
        {x : Matrix n n ℂ | x ∈ l} := fun s =>
    (he.map_subtype (α s)).mem_resolution hlmin hlsum
  have h1 := continuous_finiteRange_apply_eq (hcont _)
    l.finite_toSet hmem t
  rw [h1, hzero]

/-- A pointwise-continuous identity-based family of star automorphisms of
the subalgebra acts on every minimal central corner. -/
theorem continuousFlow_maps_relativeCorner
    (α : ℝ → (↥S ≃⋆ₐ[ℂ] ↥S)) (hzero : ∀ x, α 0 x = x)
    (hcont : ∀ x : ↥S, Continuous fun t : ℝ =>
      ((α t x : ↥S) : Matrix n n ℂ))
    {e : Matrix n n ℂ} (he : IsMinimalCentralProjectionIn S e)
    {x : ↥S} (hx : (x : Matrix n n ℂ) ∈
      relativeCorner S he.toIsCentralProjectionIn) (t : ℝ) :
    ((α t x : ↥S) : Matrix n n ℂ) ∈
      relativeCorner S he.toIsCentralProjectionIn := by
  refine ⟨(α t x).2, ?_⟩
  have hfix := continuousFlow_fixes_minimalCentralProjection α hzero hcont
    he t
  have hex : (⟨e, he.centralIn.mem⟩ : ↥S) * x = x := Subtype.ext hx.2
  have h1 : α t ⟨e, he.centralIn.mem⟩ * α t x = α t x := by
    rw [← map_mul, hex]
  calc e * ((α t x : ↥S) : Matrix n n ℂ)
      = ((α t ⟨e, he.centralIn.mem⟩ : ↥S) : Matrix n n ℂ) *
          ((α t x : ↥S) : Matrix n n ℂ) := by rw [hfix]
    _ = ((α t x : ↥S) : Matrix n n ℂ) := congrArg Subtype.val h1

end SubalgebraFlow

/-! ## The composed closure statement -/

section Closure

variable {N : Type u} [Fintype N] [DecidableEq N]

/-- Composed closure of the star Wedderburn classification and the
finite-block Stone converse: every star subalgebra of a finite complex
matrix algebra is star-isomorphic to a finite direct sum of full matrix
blocks of positive dimensions, and on that block model every
pointwise-continuous real-parameter star-automorphism group is blockwise
conjugation by the coherent unitary family of one time-independent
self-adjoint Hamiltonian per block. -/
theorem starWedderburn_stone_closure (S : StarSubalgebra ℂ (Matrix N N ℂ)) :
    ∃ (k : ℕ) (d : Fin k → ℕ), (∀ i, 0 < d i) ∧
      Nonempty (↥S ≃⋆ₐ[ℂ]
        ((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ)) ∧
      ∀ α : ℝ → (((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ) ≃⋆ₐ[ℂ]
          ((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ)),
        (∀ x, α 0 x = x) →
        (∀ s t : ℝ, ∀ x, α (s + t) x = α s (α t x)) →
        (∀ x, Continuous fun t : ℝ => α t x) →
        ∃ Ham : (i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ,
          (∀ i, IsSelfAdjoint (Ham i)) ∧
            ∀ (t : ℝ) (x : (i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ)
              (i : Fin k),
              α t x i = stonePropagator (Ham i) t * x i *
                stonePropagator (Ham i) (-t) := by
  obtain ⟨k, d, hd, hequiv⟩ := starSubalgebra_starEquiv_pi_matrix S
  refine ⟨k, d, hd, hequiv, ?_⟩
  intro α hzero hgroup hcont
  haveI : ∀ i, Nonempty (Fin (d i)) := fun i => Fin.pos_iff_nonempty.mp (hd i)
  exact piBlockStoneConverse_of_continuous α hzero hgroup hcont

/-- Full composed form of the closure: a pointwise-continuous
real-parameter star-automorphism group of a star subalgebra of a finite
complex matrix algebra is, through one star Wedderburn block model,
blockwise conjugation by the coherent unitary families of one
time-independent self-adjoint Hamiltonian per block.  Pointwise
continuity is taken in the ambient matrix algebra; the transported flow
on the block model is pointwise continuous because every linear map from
the finite-dimensional carrier submodule is continuous. -/
theorem starSubalgebraStoneConverse_of_continuous
    (S : StarSubalgebra ℂ (Matrix N N ℂ))
    (α : ℝ → (↥S ≃⋆ₐ[ℂ] ↥S))
    (hzero : ∀ x, α 0 x = x)
    (hgroup : ∀ s t : ℝ, ∀ x, α (s + t) x = α s (α t x))
    (hcont : ∀ x : ↥S, Continuous fun t : ℝ =>
      ((α t x : ↥S) : Matrix N N ℂ)) :
    ∃ (k : ℕ) (d : Fin k → ℕ)
      (Φ : ↥S ≃⋆ₐ[ℂ] ((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ))
      (Ham : (i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ),
      (∀ i, 0 < d i) ∧ (∀ i, IsSelfAdjoint (Ham i)) ∧
      ∀ (t : ℝ) (x : ↥S) (i : Fin k),
        Φ (α t x) i =
          stonePropagator (Ham i) t * Φ x i *
            stonePropagator (Ham i) (-t) := by
  classical
  obtain ⟨k, d, hd, hΦne⟩ := starSubalgebra_starEquiv_pi_matrix S
  obtain ⟨Φ⟩ := hΦne
  haveI : ∀ i, Nonempty (Fin (d i)) := fun i =>
    Fin.pos_iff_nonempty.mp (hd i)
  set β : ℝ → (((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ) ≃⋆ₐ[ℂ]
      ((i : Fin k) → Matrix (Fin (d i)) (Fin (d i)) ℂ)) :=
    fun t => (Φ.symm.trans (α t)).trans Φ with hβ
  have hβapply : ∀ (t : ℝ) y, β t y = Φ (α t (Φ.symm y)) := fun t y => rfl
  have hβzero : ∀ y, β 0 y = y := by
    intro y
    rw [hβapply, hzero, Φ.apply_symm_apply]
  have hβgroup : ∀ s t : ℝ, ∀ y, β (s + t) y = β s (β t y) := by
    intro s t y
    rw [hβapply, hβapply, hβapply, hgroup, Φ.symm_apply_apply]
  have hβcont : ∀ y, Continuous fun t : ℝ => β t y := by
    intro y
    show Continuous fun t : ℝ => Φ (α t (Φ.symm y))
    apply continuous_pi
    intro i
    have hmemS : ∀ v : ↥(Subalgebra.toSubmodule S.toSubalgebra),
        (v : Matrix N N ℂ) ∈ S := fun v => v.2
    let L : ↥(Subalgebra.toSubmodule S.toSubalgebra) →ₗ[ℂ]
        Matrix (Fin (d i)) (Fin (d i)) ℂ :=
      { toFun := fun v => Φ ⟨(v : Matrix N N ℂ), hmemS v⟩ i
        map_add' := fun v w => by
          have h1 : (⟨((v + w : _) : Matrix N N ℂ), hmemS _⟩ : ↥S) =
              ⟨(v : Matrix N N ℂ), hmemS v⟩ +
                ⟨(w : Matrix N N ℂ), hmemS w⟩ :=
            Subtype.ext rfl
          show Φ ⟨((v + w : _) : Matrix N N ℂ), hmemS _⟩ i = _
          rw [h1, map_add]
          rfl
        map_smul' := fun c v => by
          have h1 : (⟨((c • v : _) : Matrix N N ℂ), hmemS _⟩ : ↥S) =
              c • ⟨(v : Matrix N N ℂ), hmemS v⟩ :=
            Subtype.ext rfl
          show Φ ⟨((c • v : _) : Matrix N N ℂ), hmemS _⟩ i = _
          rw [h1, map_smul]
          rfl }
    have hLcont : Continuous L := L.continuous_of_finiteDimensional
    have hsub : Continuous fun t : ℝ =>
        (⟨((α t (Φ.symm y) : ↥S) : Matrix N N ℂ),
          (α t (Φ.symm y)).2⟩ :
          ↥(Subalgebra.toSubmodule S.toSubalgebra)) :=
      (hcont (Φ.symm y)).subtype_mk _
    have hfun : (fun t : ℝ => Φ (α t (Φ.symm y)) i) =
        fun t : ℝ => L ⟨((α t (Φ.symm y) : ↥S) : Matrix N N ℂ),
          (α t (Φ.symm y)).2⟩ := by
      funext t
      show Φ (α t (Φ.symm y)) i =
        Φ ⟨((α t (Φ.symm y) : ↥S) : Matrix N N ℂ), _⟩ i
      rw [Subtype.coe_eta]
    rw [hfun]
    exact hLcont.comp hsub
  obtain ⟨Ham, hsa, hconj⟩ :=
    piBlockStoneConverse_of_continuous β hβzero hβgroup hβcont
  refine ⟨k, d, Φ, Ham, hd, hsa, ?_⟩
  intro t x i
  have h1 : β t (Φ x) = Φ (α t x) := by
    rw [hβapply, Φ.symm_apply_apply]
  rw [← h1]
  exact hconj t (Φ x) i

end Closure

#print axioms OPH.Dynamics.IsProjectionIn.exists_minimal_decomposition
#print axioms OPH.Dynamics.IsMinimalProjectionIn.corner_smul
#print axioms OPH.Dynamics.exists_partial_isometry
#print axioms OPH.Dynamics.exists_connecting_element
#print axioms OPH.Dynamics.minimalCentralCorner_starEquiv_matrix
#print axioms OPH.Dynamics.IsMinimalCentralProjectionIn.corner_center_scalar
#print axioms OPH.Dynamics.starSubalgebra_starEquiv_pi_matrix
#print axioms OPH.Dynamics.piBlock_central_idempotent_indicator
#print axioms OPH.Dynamics.continuousFlow_fixes_piBlockProjection
#print axioms OPH.Dynamics.piBlockStoneConverse_of_continuous
#print axioms OPH.Dynamics.IsMinimalCentralProjectionIn.mem_resolution
#print axioms OPH.Dynamics.IsMinimalCentralProjectionIn.map_subtype
#print axioms OPH.Dynamics.continuousFlow_fixes_minimalCentralProjection
#print axioms OPH.Dynamics.continuousFlow_maps_relativeCorner
#print axioms OPH.Dynamics.starWedderburn_stone_closure
#print axioms OPH.Dynamics.starSubalgebraStoneConverse_of_continuous

end OPH.Dynamics
