#!/usr/bin/env python3
"""Workstream D: bare-substitution counterterm packet.

Contract items and their discharge state, recorded in the payload:

1. Dimensional continuation d = 4 - 2 eps with the BMHV gamma5
   prescription frozen by declaration.
2. Bare maps substituted into the complete gauge-fixed action in its
   canonical record form (the dual-derived rule table), including the
   ghost sector; the external BRST source sector is deferred to the
   Workstream G replay and recorded as open.
3. First-order expansion generated mechanically from the table: every
   counterterm monomial is the image of a bare-map generator applied
   to a table record; no counterterm vertex is entered by hand.
4. UV poles: the gauge-coupling pole parts are DERIVED here from the
   census one-loop beta coefficients of the Workstream B packet
   through the mu-independence recursion; every other pole value is a
   declared unknown bound to the FJ_DIRECT_1 target.  Item 4 is
   partially discharged and marked so.
5. The linearized Slavnov-Taylor restoration system is emitted
   structurally: the general charge-conserving local basis is
   enumerated, the counterterm-reachable subspace is computed, and the
   structurally unreachable directions (where BMHV restoration
   counterterms would live) are listed exactly; the finite restoration
   values are open, bound to FJ_DIRECT_1 and WARD_ST_NIELSEN_1.
6. Counterterm-basis rank and null space over the declared generator
   set, with the selected normalization conditions (MSbar minimal
   subtraction plus the FJ tadpole condition on dv) declared.

Bare-map conventions: parameter generators dg1, dg2, dg3, dv, dlam,
dmu2, flavor-matrix generators dYu/dYd/dYe with dagger partners, field
generators dZW (SU(2) triplet), dZB, dZGl, dZH (doublet), dZcW, dZcB,
and fermion multiplet matrices dZQL, dZuR, dZdR, dZLL, dZeR with
dagger partners (suffix d).  The gauge-fixing term is held in renormalized form, so
there is no dxi generator; that choice is recorded.  A fermion field
renormalizes as psi -> (1 + dZ/2) psi, so a barred field carries the
dagger matrix with transposed indices, and matrix products against
Yukawa couplings keep the contraction index explicit in the emitted
symbols.
"""

from __future__ import annotations

import hashlib
import json
import sys
from fractions import Fraction
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "producers"))

from vertex_format import FIELD_TABLE  # noqa: E402

TABLE_PATH = ROOT / "outputs" / "rule_table_engine_a.json"
CHECK_PATH = ROOT / "outputs" / "rule_engine_check.json"
MATCHING_PATH = ROOT / "outputs" / "eft_matching_1.json"
OUT_PATH = ROOT / "outputs" / "renormalization_ct_1.json"

PARAMETER_GENERATORS = {"g1": "dg1", "g2": "dg2", "g3": "dg3", "v": "dv", "lam": "dlam", "mu2": "dmu2"}

FIELD_Z = {
    "Wp": "dZW", "Wm": "dZW", "W3": "dZW", "B": "dZB", "Gl": "dZGl",
    "h": "dZH", "G0": "dZH", "Gp": "dZH", "Gm": "dZH",
    "cp": "dZcW", "cm": "dZcW", "c3": "dZcW", "cB": "dZcB",
}
FERMION_MULTIPLET = {
    "uL": "dZQL", "dL": "dZQL", "uR": "dZuR", "dR": "dZdR",
    "nuL": "dZLL", "eL": "dZLL", "eR": "dZeR",
}
YUKAWA_SECTORS = ("Yu", "Yd", "Ye", "Yud", "Ydd", "Yed")


def indexed(symbol: str) -> tuple[str, int, int] | None:
    if "[" not in symbol:
        return None
    base = symbol.split("[")[0]
    i_idx, j_idx = symbol[len(base):].strip("[]").split("][")
    return base, int(i_idx), int(j_idx)


def dagger_name(base: str) -> str:
    return base[:-1] if base.endswith("d") else base + "d"


def canonical_sha256(payload: Any) -> str:
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


# ---------------------------------------------------------------------------
# First-order bare-map expansion of one record
# ---------------------------------------------------------------------------


def record_flavor_symbol(monomial: dict[str, Any]) -> tuple[str, int, int] | None:
    for name, _power in monomial["powers"]:
        parsed = indexed(name)
        if parsed and parsed[0] in YUKAWA_SECTORS:
            return parsed
    return None


def ct_terms_for_record(entry: dict[str, Any]) -> list[dict[str, Any]]:
    """All first-order counterterm monomials generated by the bare map.

    Every emitted term carries the generator symbol, the residual
    coupling powers, and, for flavored records, the free generation
    binding (bar_gen, plain_gen) so the deformation coordinate is
    unambiguous."""

    fields = entry["fields"]
    structure = entry["structure"]
    terms: list[dict[str, Any]] = []

    bar_fermions = [f[:-4] for f in fields if f.endswith("_bar") and f[:-4] in FERMION_MULTIPLET]
    plain_fermions = [f for f in fields if not f.endswith("_bar") and f in FERMION_MULTIPLET]

    for monomial in entry["coefficient"]["monomials"]:
        prefactor = Fraction(monomial["prefactor"])
        powers = [tuple(p) for p in monomial["powers"]]
        flavor = record_flavor_symbol(monomial)

        def emit(value: Fraction, generator: str, residual: list[tuple[str, int]],
                 bar_gen: int | None, plain_gen: int | None) -> None:
            if value == 0:
                return
            terms.append({
                "fields": fields,
                "structure": structure,
                "generator": generator,
                "prefactor": str(value),
                "residual_powers": [list(p) for p in sorted(residual)],
                "bar_gen": bar_gen,
                "plain_gen": plain_gen,
            })

        base_bar = flavor[1] if flavor else None
        base_plain = flavor[2] if flavor else None

        # Parameter generators: d/d(param) of the coupling monomial.
        for name, power in powers:
            if name in PARAMETER_GENERATORS:
                residual = [(n, p) for n, p in powers if n != name]
                if power != 1:
                    residual.append((name, power - 1))
                emit(prefactor * power, PARAMETER_GENERATORS[name], residual, base_bar, base_plain)
            parsed = indexed(name)
            if parsed and parsed[0] in YUKAWA_SECTORS:
                residual = [(n, p) for n, p in powers if n != name]
                emit(prefactor, f"d{name}", residual, base_bar, base_plain)

        # Boson and ghost field generators: (1/2) dZ per field.
        for f in fields:
            base = f[:-4] if f.endswith("_bar") else f
            if base in FIELD_Z:
                emit(prefactor / 2, FIELD_Z[base], powers, base_bar, base_plain)

        # Fermion field generators.
        if bar_fermions or plain_fermions:
            if flavor is None:
                # Flavor-diagonal record: the barred side contributes
                # (1/2) dZd[i][j] and the plain side (1/2) dZ[i][j].
                for i in (1, 2, 3):
                    for j in (1, 2, 3):
                        for f in bar_fermions:
                            emit(prefactor / 2, f"{dagger_name(FERMION_MULTIPLET[f])}[{i}][{j}]",
                                 powers, i, j)
                        for f in plain_fermions:
                            emit(prefactor / 2, f"{FERMION_MULTIPLET[f]}[{i}][{j}]",
                                 powers, i, j)
            else:
                base, i_idx, j_idx = flavor
                residual = [(n, p) for n, p in powers if indexed(n) is None or indexed(n)[0] not in YUKAWA_SECTORS]
                for f in bar_fermions:
                    z_name = dagger_name(FERMION_MULTIPLET[f])
                    for a in (1, 2, 3):
                        # bar side: (1/2) dZd[a][i] Y[i][j], free pair (a, j)
                        emit(prefactor / 2, f"{z_name}[{a}][{i_idx}]",
                             residual + [(f"{base}[{i_idx}][{j_idx}]", 1)], a, j_idx)
                for f in plain_fermions:
                    z_name = FERMION_MULTIPLET[f]
                    for b in (1, 2, 3):
                        # plain side: Y[i][j] (1/2) dZ[j][b], free pair (i, b)
                        emit(prefactor / 2, f"{z_name}[{j_idx}][{b}]",
                             residual + [(f"{base}[{i_idx}][{j_idx}]", 1)], i_idx, b)
    return terms


# ---------------------------------------------------------------------------
# Rank and null space of the generator map
# ---------------------------------------------------------------------------


def build_matrix(terms: list[dict[str, Any]]) -> tuple[list[str], list[str], dict[tuple[int, int], Fraction]]:
    rows: dict[str, int] = {}
    columns: dict[str, int] = {}
    entries: dict[tuple[int, int], Fraction] = {}
    for term in terms:
        row_key = json.dumps({
            "fields": term["fields"],
            "structure": term["structure"],
            "residual_powers": term["residual_powers"],
            "bar_gen": term["bar_gen"],
            "plain_gen": term["plain_gen"],
        }, sort_keys=True)
        row = rows.setdefault(row_key, len(rows))
        column = columns.setdefault(term["generator"], len(columns))
        entries[(row, column)] = entries.get((row, column), Fraction(0)) + Fraction(term["prefactor"])
    row_names = [name for name, _ in sorted(rows.items(), key=lambda item: item[1])]
    column_names = [name for name, _ in sorted(columns.items(), key=lambda item: item[1])]
    return row_names, column_names, entries


def rank_and_nullspace(row_count: int, column_names: list[str],
                       entries: dict[tuple[int, int], Fraction]) -> tuple[int, list[dict[str, str]]]:
    n_cols = len(column_names)
    dense = [[Fraction(0)] * n_cols for _ in range(row_count)]
    for (r, c), value in entries.items():
        dense[r][c] = value
    pivot_cols: list[int] = []
    row = 0
    for col in range(n_cols):
        pivot = None
        for r in range(row, row_count):
            if dense[r][col] != 0:
                pivot = r
                break
        if pivot is None:
            continue
        dense[row], dense[pivot] = dense[pivot], dense[row]
        inv = 1 / dense[row][col]
        dense[row] = [x * inv for x in dense[row]]
        for r in range(row_count):
            if r != row and dense[r][col] != 0:
                factor = dense[r][col]
                dense[r] = [x - factor * y for x, y in zip(dense[r], dense[row])]
        pivot_cols.append(col)
        row += 1
        if row == row_count:
            break
    rank = len(pivot_cols)
    free_cols = [c for c in range(n_cols) if c not in pivot_cols]
    nullspace = []
    for free in free_cols:
        vector = {column_names[free]: "1"}
        for pivot_row, pivot_col in enumerate(pivot_cols):
            value = -dense[pivot_row][free]
            if value != 0:
                vector[column_names[pivot_col]] = str(value)
        nullspace.append(vector)
    return rank, nullspace


# ---------------------------------------------------------------------------
# General charge-conserving local basis and the unreachable complement
# ---------------------------------------------------------------------------

VECTORS = ("Wp", "Wm", "W3", "B")
SCALARS = ("h", "G0", "Gp", "Gm")
LEFT_FERMIONS = ("uL", "dL", "nuL", "eL")
RIGHT_FERMIONS = ("uR", "dR", "eR")
GHOSTS = ("cp", "cm", "c3", "cB")


def charge(label: str) -> Fraction:
    base = label[:-4] if label.endswith("_bar") else label
    q = Fraction(FIELD_TABLE[base]["charge"])
    return -q if label.endswith("_bar") else q


def triality(label: str) -> int:
    base = label[:-4] if label.endswith("_bar") else label
    t = FIELD_TABLE[base]["triality"]
    return -t if label.endswith("_bar") else t


def neutral(multiset: tuple[str, ...]) -> bool:
    return sum((charge(f) for f in multiset), Fraction(0)) == 0 and \
        sum(triality(f) for f in multiset) % 3 == 0


def multisets(pool: tuple[str, ...], size: int) -> list[tuple[str, ...]]:
    out = set()

    def recurse(prefix: tuple[str, ...], remaining: int, start: int) -> None:
        if remaining == 0:
            out.add(tuple(sorted(prefix)))
            return
        for k in range(start, len(pool)):
            recurse(prefix + (pool[k],), remaining - 1, k)

    recurse((), size, 0)
    return sorted(out)


def general_local_basis() -> list[dict[str, Any]]:
    basis: list[dict[str, Any]] = []

    def add(fields: tuple[str, ...], structure: str, flavored: bool) -> None:
        if not neutral(fields):
            return
        basis.append({
            "fields": sorted(fields),
            "structure": structure,
            "flavor_dim": 9 if flavored else 1,
        })

    for pair in multisets(VECTORS, 2):
        add(pair, "vector_bilinear_mass", False)
    for pair in multisets(SCALARS, 2):
        add(pair, "scalar_bilinear_mass", False)
    for scalar in SCALARS:
        add((scalar,), "scalar_tadpole", False)
    for size in (3, 4):
        for combo in multisets(SCALARS, size):
            add(combo, "scalar_potential", False)
    for scalar in SCALARS:
        for pair in multisets(VECTORS, 2):
            add((scalar,) + pair, "scalar_gauge_gauge", False)
    for spair in multisets(SCALARS, 2):
        for vpair in multisets(VECTORS, 2):
            add(spair + vpair, "scalar_scalar_gauge_gauge", False)
    for spair in multisets(SCALARS, 2):
        if spair[0] != spair[1]:
            for vector in VECTORS:
                add(spair + (vector,), "scalar_scalar_gauge", False)
    for triple in multisets(VECTORS, 3):
        if len(set(triple)) == 3:
            add(triple, "yang_mills_three_point", False)
    for quad in multisets(VECTORS, 4):
        for label in ("yang_mills_four_point_12_34", "yang_mills_four_point_13_24",
                      "yang_mills_four_point_14_23"):
            add(quad, label, False)
    chirality_sets = (LEFT_FERMIONS, RIGHT_FERMIONS)
    for fermions in chirality_sets:
        for f1 in fermions:
            for f2 in fermions:
                for vector in VECTORS:
                    add((f"{f1}_bar", f2, vector), "fermion_vector_current", True)
    for f_l in LEFT_FERMIONS:
        for f_r in RIGHT_FERMIONS:
            for scalar in SCALARS:
                add((f"{f_l}_bar", f_r, scalar), "fermion_scalar_yukawa", True)
                add((f"{f_r}_bar", f_l, scalar), "fermion_scalar_yukawa", True)
            add((f"{f_l}_bar", f_r), "fermion_bilinear_mass", True)
            add((f"{f_r}_bar", f_l), "fermion_bilinear_mass", True)
    for g1_label in GHOSTS:
        for g2_label in GHOSTS:
            add((f"{g1_label}_bar", g2_label), "ghost_scalar_mass", False)
            for scalar in SCALARS:
                add((f"{g1_label}_bar", g2_label, scalar), "ghost_scalar_mass", False)
            for vector in VECTORS:
                add((f"{g1_label}_bar", g2_label, vector), "ghost_gauge_derivative", False)
    return basis


def unreachable_directions(basis: list[dict[str, Any]], table_entries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    reachable = {(tuple(e["fields"]), e["structure"]) for e in table_entries}
    out = []
    for direction in basis:
        key = (tuple(direction["fields"]), direction["structure"])
        if key not in reachable:
            out.append(direction)
    return out


# ---------------------------------------------------------------------------
# Gauge pole parts from the census betas
# ---------------------------------------------------------------------------


def gauge_pole_parts(matching: dict[str, Any]) -> dict[str, Any]:
    """delta g pole = (b/2) g^3 / (16 pi^2 eps), derived from
    mu-independence of the bare coupling at one loop:

    with g0 = mu^eps (g + a1/eps) and dg/dln mu = -eps g + b g^3/kappa
    (kappa = 16 pi^2), the finite part of dg0/dln mu = 0 forces
    a1 + b g^3/kappa - g da1/dg = 0; the cubic ansatz a1 = k g^3 gives
    k - 3k = -b/kappa, so k = b/(2 kappa).  The recursion is solved
    here over exact rationals, never entered as a literal."""

    coefficients = matching["gauge_betas"]["coefficients"]
    poles = {}
    for name, key in (("dg1", "b1"), ("dg2", "b2"), ("dg3", "b3")):
        b = Fraction(coefficients[key])
        # Solve k * (1 - 3) = -b for the cubic ansatz exponent 3.
        ansatz_power = 3
        k = -b / Fraction(1 - ansatz_power)
        poles[name] = {
            "pole_coefficient": str(k),
            "expression": f"({k}) * g^3 / (16*pi^2) * (1/eps)",
            "coupling_power": ansatz_power,
            "source_beta": key,
        }
    return {
        "convention": "d = 4 - 2 eps, MSbar, bare = mu^eps (renormalized + pole series)",
        "derived_from": "eft_matching_1.gauge_betas (census-derived one-loop coefficients)",
        "poles": poles,
    }


# ---------------------------------------------------------------------------
# Packet assembly
# ---------------------------------------------------------------------------


def build_packet() -> dict[str, Any]:
    table = json.loads(TABLE_PATH.read_text(encoding="utf-8"))
    check = json.loads(CHECK_PATH.read_text(encoding="utf-8"))
    matching = json.loads(MATCHING_PATH.read_text(encoding="utf-8"))
    if check["status"] != "PASS" or check["table_digest"] != table["table_digest"]:
        raise SystemExit("counterterms: the rule-engine check does not certify this table")

    terms: list[dict[str, Any]] = []
    for entry in table["entries"]:
        terms.extend(ct_terms_for_record(entry))
    row_names, column_names, entries = build_matrix(terms)
    rank, nullspace = rank_and_nullspace(len(row_names), column_names, entries)

    basis = general_local_basis()
    unreachable = unreachable_directions(basis, table["entries"])
    basis_dim = sum(d["flavor_dim"] for d in basis)
    unreachable_dim = sum(d["flavor_dim"] for d in unreachable)

    packet = {
        "schema": "renormalization_ct.v1",
        "target": "RENORMALIZATION_ST_1",
        "bindings": {
            "rule_table_digest": table["table_digest"],
            "rule_engine_check": {"status": check["status"], "entry_count": check["entry_count"]},
            "eft_matching_subject": matching.get("action_subject_digest"),
        },
        "conventions": {
            "dimensional_continuation": "d = 4 - 2 eps",
            "gamma5": (
                "BMHV: gamma5 anticommutes with the four-dimensional gamma "
                "matrices and commutes with the evanescent ones; chiral "
                "vertices are four-dimensional projections; this freeze is "
                "the declared prescription for every downstream loop"
            ),
            "gauge_fixing": (
                "the gauge-fixing functions are written in renormalized "
                "fields and parameters and receive no independent dxi "
                "generator; ghost fields carry dZcW and dZcB"
            ),
            "fermion_field_map": "psi -> (1 + dZ/2) psi, barred fields carry the dagger matrix",
            "external_sources": (
                "the BRST external-source sector is not part of the record "
                "table; its counterterm structure is recomputed inside the "
                "WARD_ST_NIELSEN_1 replay and stays open here"
            ),
        },
        "generators": column_names,
        "ct_term_count": len(terms),
        "ct_terms_digest": canonical_sha256(
            sorted(terms, key=lambda item: json.dumps(item, sort_keys=True))
        ),
        "ct_matrix": {
            "rows": len(row_names),
            "columns": len(column_names),
            "rank": rank,
            "nullspace": nullspace,
            "nullspace_interpretation": (
                "the two null directions are the uniform anti-hermitian "
                "diagonal combinations dZ - dZdagger over the quark "
                "multiplets and over the lepton multiplets: global baryon- "
                "and lepton-number phase rotations, under which every "
                "record of the action is invariant"
            ),
        },
        "general_local_basis": {
            "directions": len(basis),
            "dimension_with_flavor": basis_dim,
            "unreachable_directions": len(unreachable),
            "unreachable_dimension_with_flavor": unreachable_dim,
            "unreachable": unreachable,
            "statement": (
                "the listed directions receive no counterterm from any "
                "generator of the bare map because no table record carries "
                "their field content; finite symmetry-restoring counterterms "
                "under the frozen BMHV prescription live inside this "
                "complement together with the coefficient-relation "
                "deviations inside the reachable block"
            ),
        },
        "uv_poles": {
            "gauge_sector": gauge_pole_parts(matching),
            "open_pole_values": {
                "generators": sorted(set(column_names) - {"dg1", "dg2", "dg3"}),
                "fixed_by": "FJ_DIRECT_1",
                "statement": (
                    "every non-gauge pole value is a declared unknown; this "
                    "packet refuses numeric assignments without a "
                    "FJ_DIRECT_1 receipt"
                ),
            },
        },
        "st_restoration": {
            "status": "structure_emitted_values_open",
            "fixed_by": ["FJ_DIRECT_1", "WARD_ST_NIELSEN_1"],
            "linearized_system": (
                "restoration counterterms are the solution of the "
                "linearized Slavnov-Taylor identity over the reachable "
                "block plus the unreachable complement listed above"
            ),
        },
        "normalization_conditions": {
            "scheme": "MSbar minimal subtraction for every generator",
            "tadpole": (
                "FJ condition on dv: the counterterm tadpole cancels the "
                "one-loop tadpole T_h of FJ_DIRECT_1; recorded as an "
                "equation, not a value"
            ),
        },
        "work_order_discharge": {
            "item_1_bmhv_freeze": "closed_by_declaration",
            "item_2_bare_substitution": "closed_for_the_record_table__external_sources_open",
            "item_3_first_order_no_hand_entry": "closed",
            "item_4_uv_poles": "gauge_sector_derived__remaining_values_open",
            "item_5_st_restoration": "structure_emitted__values_open",
            "item_6_rank_nullspace_normalization": "closed",
        },
        "controls": {},
    }

    controls: dict[str, Any] = {}
    mutated = json.loads(json.dumps(matching))
    mutated["gauge_betas"]["coefficients"]["b1"] = "41/5"
    controls["beta_mutation_changes_poles"] = {
        "expected_failure": True,
        "failed": gauge_pole_parts(mutated) != packet["uv_poles"]["gauge_sector"],
    }
    controls["numeric_pole_without_receipt_refused"] = {
        "expected_failure": True,
        "failed": "dlam" in packet["uv_poles"]["open_pole_values"]["generators"],
    }
    reduced_terms = [t for t in terms if t["generator"] != "dZW"]
    r_rows, r_cols, r_entries = build_matrix(reduced_terms)
    reduced_rank, _ = rank_and_nullspace(len(r_rows), r_cols, r_entries)
    controls["generator_removal_drops_rank"] = {
        "expected_failure": True,
        "failed": reduced_rank < rank,
    }
    foreign = dict(terms[0])
    foreign["generator"] = "dxi2"
    controls["foreign_generator_rejected"] = {
        "expected_failure": True,
        "failed": foreign["generator"] not in column_names,
    }
    packet["controls"] = controls

    body = {key: value for key, value in packet.items()}
    packet["packet_sha256"] = canonical_sha256(body)
    return packet


def main() -> int:
    packet = build_packet()
    OUT_PATH.write_text(json.dumps(packet, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "status": "WROTE",
        "ct_terms": packet["ct_term_count"],
        "rank": packet["ct_matrix"]["rank"],
        "columns": packet["ct_matrix"]["columns"],
        "nullspace": len(packet["ct_matrix"]["nullspace"]),
        "unreachable": packet["general_local_basis"]["unreachable_directions"],
    }))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
