#!/usr/bin/env python3
"""Workstream F core: converted tadpole-free chart and the exact
FJ-equivalence receipts.

The converted chart removes the explicit tadpoles of the direct FJ
engine by shifting the vacuum parameter,

    v_F = v + hbar Delta_v,   Delta_v = - T_h / m_h^2,

with three distinct markers kept separate throughout: ``h`` the Higgs
fluctuation field label, ``hbar`` the loop-counting unit of the chart
map, and the loop order of an emitted quantity tracked by its block
payload.  T_h is consumed from the emitted one-point artifact of the
direct engine (a hashed receipt, not an engine call), and m_h^2 is
the FJ-chart Higgs mass from the certified table.

Equivalence statement, checked exactly per block: expanding every
v-dependent tree record to first order in hbar,

    record(v_F) = record(v) + hbar (d record/d v) Delta_v + O(hbar^2),

reproduces the direct engine's tadpole-insertion diagram of that block
if and only if the insertion equals

    (d/dv of the tree two-point record) x Delta_v,

because the insertion head coupling is the v-derivative of the mass
record for every block generated by the spontaneously broken action.
This module recomputes both sides with its OWN expansion code (the
head couplings are differentiated from the certified records, never
read from the direct engine), re-expands before truncation, and emits
a per-block equivalence receipt; a mismatch in any block is fatal.

The scalar-integral content of the receipts stays symbolic in the
A0/B0 basis; the ball-arithmetic evaluation layer is a separate
module with its own implementation, per the workstream contract.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "producers"))

import fj_spectrum  # noqa: E402

VECTOR_PATH = ROOT / "outputs" / "fj_direct_vector_blocks.json"
SCALAR_PATH = ROOT / "outputs" / "fj_direct_scalar_blocks.json"
OUT_PATH = ROOT / "outputs" / "fj_converted_equivalence.json"

g1, g2, v = fj_spectrum.g1, fj_spectrum.g2, fj_spectrum.v
lam, mu2, xi = fj_spectrum.lam, fj_spectrum.mu2, fj_spectrum.xi
hbar = sp.Symbol("hbar")


def sympify_env() -> dict[str, sp.Expr]:
    ns = {"g1": g1, "g2": g2, "v": v, "lam": lam, "mu2": mu2, "xi": xi,
          "p2": sp.Symbol("p2"), "d": sp.Symbol("d")}
    for i in (1, 2, 3):
        for name in (f"mfu{i}", f"mfd{i}", f"mfe{i}"):
            ns[name] = sp.Symbol(name)
        for j in (1, 2, 3):
            ns[f"V{i}{j}"] = sp.Symbol(f"V{i}{j}")
            ns[f"Vc{i}{j}"] = sp.Symbol(f"Vc{i}{j}")
    return ns


def parse_value(text: str, ns: dict[str, sp.Expr]) -> sp.Expr:
    """Parse an emitted block value; instantiated loop symbols like
    A0[...] survive as opaque symbols."""

    import re
    opaque = {}
    def hide(match):
        token = f"OPAQUE{len(opaque)}"
        opaque[token] = match.group(0)
        return token
    hidden = re.sub(r"[ABC][0-9]*[0p]*\[[^\]]*\]", hide, text)
    local = dict(ns)
    for token, original in opaque.items():
        local[token] = sp.Symbol(original)
    return sp.sympify(hidden, locals=local)


def build_receipts() -> dict[str, Any]:
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    scalar = json.loads(SCALAR_PATH.read_text(encoding="utf-8"))
    ns = sympify_env()

    records = fj_spectrum.specialized_records()
    spectrum, checks = fj_spectrum.spectrum_and_checks(records)
    if checks:
        raise SystemExit("converted engine: specialization checks failed")
    mh_sq = spectrum["h"]

    def tree_bilinear(fields: list[str], structure: str) -> sp.Expr:
        for record in records:
            if record["fields"] == sorted(fields) and record["structure"] == structure:
                return record["coefficient"]
        return sp.Integer(0)

    # T_h from the emitted one-point contributions, summed here.
    t_total = sp.Integer(0)
    for name, value in vector["one_point_h"]["contributions"].items():
        t_total += parse_value(value, ns)

    # Delta_v solves the tadpole-free condition T(v_F) = 0 to first
    # order in hbar: T + (dT_tree/dv) Delta_v = 0, with the tree slope
    # differentiated from the certified tadpole record (its value is
    # -m_h^2 identically, so no sign is entered by hand).
    tree_tadpole = tree_bilinear(["h"], "scalar_tadpole")
    tree_slope = sp.diff(tree_tadpole, v)
    if sp.simplify(tree_slope + mh_sq) != 0:
        raise SystemExit("converted engine: tree tadpole slope is not -m_h^2")
    delta_v = sp.simplify(-t_total / tree_slope)

    # Tree two-point coefficients whose v-shift must reproduce the
    # tadpole insertions.  For a vector pair the record equals the mass
    # term coefficient of the block; for W+W- the full Pi convention
    # carries the record directly, for ZZ the (1/2) Z Z record enters
    # the propagator as 2c, matching the multiplicity factor of the
    # insertion head, so both sides are compared through the same
    # d/dv route: head = d(record x mult)/dv.
    blocks = {
        "ZZ": (vector, ["Z", "Z"], "vector_bilinear_mass"),
        "WpWm": (vector, ["Wm", "Wp"], "vector_bilinear_mass"),
        "hh": (scalar, ["h", "h"], "scalar_bilinear_mass"),
        "G0G0": (scalar, ["G0", "G0"], "scalar_bilinear_mass"),
        "GpGm": (scalar, ["Gm", "Gp"], "scalar_bilinear_mass"),
    }
    receipts = {}
    problems = []
    for name, (payload, fields, structure) in blocks.items():
        insertion = sp.Integer(0)
        for diagram in payload["blocks"][name]["diagrams"]:
            if diagram["kind"] != "tadpole_insertion":
                continue
            key = "g" if "g" in diagram else "value"
            if key == "g":
                # vector blocks store projections; the insertion is
                # C g_munu with g-projection d C: recover C at d = 4
                # exactly since the insertion carries no d dependence
                # beyond the projector.
                c_expr = parse_value(diagram["g"], ns) / ns["d"]
                insertion += sp.simplify(c_expr.subs(ns["d"], sp.Symbol("d")))
                insertion = sp.simplify(insertion)
            else:
                insertion += parse_value(diagram["value"], ns)
        mult = 1
        seen = set()
        for f in fields:
            if f in seen:
                mult *= 2
            seen.add(f)
        record_value = tree_bilinear(fields, structure) * mult
        # Chart declaration: the hbar shift acts on the invariant
        # action only; the gauge-fixing functions keep the unshifted
        # v, so the xi-weighted gauge-fixing parts of a record carry
        # no transported v-dependence.  The records are linear in xi
        # (gauge fixing and ghosts are the only xi sources), which is
        # asserted before the split.
        if sp.simplify(sp.diff(record_value, xi, 2)) != 0:
            raise SystemExit(f"converted engine: record for {name} is not linear in xi")
        invariant_part = sp.expand(record_value).subs(xi, 0)
        expected = sp.expand(sp.diff(invariant_part, v) * delta_v)
        difference = sp.simplify(sp.expand(insertion - expected))
        receipts[name] = {
            "insertion": str(sp.simplify(insertion)),
            "v_shift_of_tree_record": str(sp.simplify(expected)),
            "difference": str(difference),
            "passed": difference == 0,
        }
        if difference != 0:
            problems.append(name)

    payload_out = {
        "schema": "fj_converted_equivalence.v1",
        "target": "FJ_CONVERTED_1",
        "chart": {
            "map": "v_F = v + hbar Delta_v with Delta_v solving T + (dT_tree/dv) Delta_v = 0; dT_tree/dv = -m_h^2 from the certified record",
            "markers": {
                "h": "Higgs fluctuation field label",
                "hbar": "loop-counting unit of the chart map",
                "loop_order": "tracked per emitted block payload",
            },
            "Delta_v": str(delta_v),
            "gauge_fixing_v": (
                "frozen: the shift acts on the invariant action; the "
                "R_xi functions keep the unshifted v, so xi-weighted "
                "record parts are excluded from the transported "
                "v-dependence"
            ),
            "re_expansion": (
                "every v-dependent record expands to first order in hbar "
                "before truncation; O(hbar^2) terms are dropped after the "
                "expansion, never before"
            ),
        },
        "equivalence_receipts": receipts,
        "statement": (
            "the tadpole-free chart reproduces the direct FJ blocks "
            "exactly at one loop: each explicit tadpole insertion equals "
            "the hbar-linear v-shift of its tree two-point record under "
            "the derived Delta_v, with the head couplings obtained by "
            "differentiating the certified records"
        ),
        "problems": problems,
    }
    return payload_out


def main() -> int:
    payload = build_receipts()
    OUT_PATH.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({
        "status": "PASS" if not payload["problems"] else "FAIL",
        "receipts": {k: r["passed"] for k, r in payload["equivalence_receipts"].items()},
    }))
    return 0 if not payload["problems"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
