#!/usr/bin/env python3
"""Non-certifying W and Z boundary diagnostic on a synthetic fixture.

The one-loop inverse-propagator functions are assembled from the emitted
transverse blocks and sampled on a declared target-free rational fixture.
The contour walk uses binary64 point coordinates and mpmath midpoint
evaluation with heuristic roundoff radii.  It does not provide directed
complex-ball arithmetic, a holomorphic second-sheet chart, an analytic
derivative bound, or an interval argument-principle proof.  Every root,
Laurent, physical-current, precision-enclosure, and promotion flag in the
output is therefore fixed to false.

The evaluator compiles exact rational polynomial coefficients in ``p2`` and
adds the exact finite term generated by ``d = 4 - 2 eps`` prefactors
multiplying the emitted scalar-integral UV poles.  This repairs one finite
arithmetic omission in the earlier diagnostic.  It does not supply the
remaining BMHV restoration, second-sheet, or physical-amplitude work.

Conventions, recorded in the payload:

* Inverse propagator, strict one-loop mask: D(s) = s - m_tree^2 -
  Pi_T(s) for the W block, and for the neutral system the masked
  determinant reduces to s - mZ^2 - Pi_ZZ(s) because the Pi_AZ^2 term
  is second order in the loop counting; the AZ block is recorded once
  at the contour center for the receipt.
* One common sign convention is used.  The loop implementation samples a
  precision-dependent finite ``-i eps`` prescription.  No continuation path
  or analytic sheet is certified.
* The sampled winding and sampled-point nonzero checks are diagnostics only.
  No root count, derivative, null vector, or Laurent denominator is emitted.
* xi = 1 on the fixture (the strict-one-loop electroweak grid point
  with xiS = 1); the symbolic identities of the replay checkers carry
  the general-xi content.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from fractions import Fraction
from pathlib import Path
from typing import Any

import mpmath as mp
import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "producers"))

import ball_arithmetic as ba  # noqa: E402

VECTOR_PATH = ROOT / "outputs" / "fj_direct_vector_blocks.json"
OUT_PATH = ROOT / "outputs" / "wz_pole_receipts.json"
SCHEMA = "wz_pole_boundary_diagnostic.v3"
STATUS = "SAMPLED_BOUNDARY_DIAGNOSTIC__NO_ROOT_CERTIFICATE"

SUBDIVISIONS = 64
EXCLUSION_SAMPLES = 32

# Declared synthetic admissible fixture: exact rationals, couplings
# small enough for contour containment, xi = 1, no relation to
# measured targets.
FIXTURE: dict[str, Fraction] = {
    "g1": Fraction(1, 4), "g2": Fraction(1, 3), "v": Fraction(2),
    "lam": Fraction(1, 8), "xi": Fraction(1),
    "mu2": Fraction(1, 2),
    "mfu1": Fraction(1, 50), "mfu2": Fraction(1, 20), "mfu3": Fraction(1, 5),
    "mfd1": Fraction(1, 60), "mfd2": Fraction(1, 25), "mfd3": Fraction(1, 10),
    "mfe1": Fraction(1, 80), "mfe2": Fraction(1, 30), "mfe3": Fraction(1, 15),
    "mu_ren2": Fraction(1),
}
CKM_FIXTURE = {(i, j): Fraction(1 if i == j else 0) for i in (1, 2, 3) for j in (1, 2, 3)}


def canonical_json_bytes(value: Any) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")


def canonical_sha256(value: Any) -> str:
    return hashlib.sha256(canonical_json_bytes(value)).hexdigest()


def sympy_namespace() -> dict[str, sp.Expr]:
    ns: dict[str, sp.Expr] = {}
    for name in ("g1", "g2", "v", "lam", "mu2", "xi", "p2", "d"):
        ns[name] = sp.Symbol(name)
    for i in (1, 2, 3):
        for name in (f"mfu{i}", f"mfd{i}", f"mfe{i}"):
            ns[name] = sp.Symbol(name)
        for j in (1, 2, 3):
            ns[f"V{i}{j}"] = sp.Symbol(f"V{i}{j}")
            ns[f"Vc{i}{j}"] = sp.Symbol(f"Vc{i}{j}")
    return ns


NS = sympy_namespace()


def parse_emitted(text: str) -> sp.Expr:
    """Parse an emitted expression, hiding every loop symbol
    HEAD[args] behind an opaque sympy symbol whose name keeps the
    encoded arguments for later evaluation."""

    opaque: dict[str, str] = {}

    def hide(match: re.Match) -> str:
        token = f"OPQ{len(opaque)}"
        opaque[token] = match.group(0)
        return token

    hidden = re.sub(r"[ABC][0-9]*[0p]*\[[^\]]*\]", hide, text)
    local = dict(NS)
    for token, original in opaque.items():
        encoded = original.replace("[", "__LB__").replace("]", "__RB__").replace("|", "__BAR__")
        local[token] = sp.Symbol(encoded)
    return sp.sympify(hidden, locals=local)


def block_transverse(payload: dict[str, Any], name: str) -> sp.Expr:
    """g and p projections combined into the exact transverse function;
    the loop symbols stay opaque with encoded arguments."""

    total_g = sp.Integer(0)
    total_p = sp.Integer(0)
    for diagram in payload["blocks"][name]["diagrams"]:
        total_g += parse_emitted(diagram["g"])
        total_p += parse_emitted(diagram["p"])
    transverse = sp.expand((total_g - total_p / NS["p2"]) / (NS["d"] - 1))
    return transverse


def compile_block(expression: sp.Expr) -> list[dict[str, Any]]:
    """Substitute the fixture once and compile every term.

    Each compiled term carries the exact rational coefficients of the
    numerator and denominator polynomials in p2 together with the loop
    head and its exact mass arguments; per-point evaluation is then
    polynomial arithmetic plus a cached loop ball.  Mapping every loop
    symbol to its MSbar finite part implements the subtraction convention
    on the solvable counterterm slice.  The separate finite
    dimensional-prefactor correction is added by ``build_receipts``.
    This evaluator does not discharge the open scalar-xi obstruction or
    the missing BMHV finite restoration."""

    fixture_subs = {NS[k]: sp.Rational(f) for k, f in FIXTURE.items() if k in NS}
    for (i, j), val in CKM_FIXTURE.items():
        fixture_subs[NS[f"V{i}{j}"]] = sp.Rational(val)
        fixture_subs[NS[f"Vc{i}{j}"]] = sp.Rational(val)
    fixture_subs[NS["d"]] = sp.Integer(4)
    expr = sp.expand(expression.subs(fixture_subs))

    def poly_coefficients(poly_expr: sp.Expr) -> list[tuple[int, Fraction]]:
        poly = sp.Poly(sp.expand(poly_expr), NS["p2"])
        return [
            (int(power), Fraction(int(sp.Rational(coeff).p), int(sp.Rational(coeff).q)))
            for (power,), coeff in poly.terms()
        ]

    compiled: list[dict[str, Any]] = []
    for term in expr.as_ordered_terms():
        loop_head = None
        loop_args: tuple[Fraction, ...] = ()
        coefficient = term
        for symbol in term.free_symbols:
            name = str(symbol)
            if "__LB__" not in name:
                continue
            if loop_head is not None:
                raise SystemExit("two loop symbols in one monomial")
            head, args_text = name.split("__LB__", 1)
            args_text = args_text.replace("__RB__", "").replace("__BAR__", "|")
            arg_values = []
            for part in args_text.split("|"):
                value = sp.sympify(part, locals=NS).subs(fixture_subs)
                arg_values.append(Fraction(str(sp.nsimplify(value))))
            loop_head = head
            loop_args = tuple(arg_values)
            coefficient = coefficient / symbol
        numerator, denominator = sp.fraction(sp.together(coefficient))
        compiled.append(
            {
                "num": poly_coefficients(numerator),
                "den": poly_coefficients(denominator),
                "head": loop_head,
                "args": loop_args,
            }
        )
    return compiled


def fixture_substitutions() -> dict[sp.Symbol, sp.Expr]:
    substitutions = {
        NS[key]: sp.Rational(value)
        for key, value in FIXTURE.items()
        if key in NS and key != "d"
    }
    for (i, j), value in CKM_FIXTURE.items():
        substitutions[NS[f"V{i}{j}"]] = sp.Rational(value)
        substitutions[NS[f"Vc{i}{j}"]] = sp.Rational(value)
    return substitutions


def loop_symbol_parts(symbol: sp.Symbol) -> tuple[str, list[sp.Expr]]:
    name = str(symbol)
    if "__LB__" not in name:
        raise ValueError(f"not an encoded loop symbol: {name}")
    head, args_text = name.split("__LB__", 1)
    args_text = args_text.replace("__RB__", "").replace("__BAR__", "|")
    args = [sp.sympify(part, locals=NS) for part in args_text.split("|")]
    return head, args


def dimensional_prefactor_finite_correction(expression: sp.Expr) -> sp.Expr:
    """Exact ``eps * UV-pole`` finite term of the emitted block.

    The current emitted basis has UV-pole coefficients
    ``A0[m2] -> m2/eps``, ``A0p[m2] -> 1/eps`` and
    ``B0[m1|m2] -> 1/eps``.  Higher denominator powers have zero simple
    pole in the declared reduction basis.  Expanding the complete
    transverse expression at ``d = 4 - 2 eps`` and removing its
    ``1/eps`` residue leaves the finite dimensional-prefactor term.
    """

    eps = sp.Symbol("eps_diagnostic", positive=True)
    substituted = sp.together(expression.subs(fixture_substitutions()))
    pole_replacements: dict[sp.Symbol, sp.Expr] = {}
    for symbol in substituted.free_symbols:
        if "__LB__" not in str(symbol):
            continue
        head, args = loop_symbol_parts(symbol)
        evaluated_args = [
            sp.simplify(arg.subs(fixture_substitutions()))
            for arg in args
        ]
        if head == "A0":
            pole = evaluated_args[0]
        elif head in {"A0p", "B0"}:
            pole = sp.Integer(1)
        elif head.startswith("C"):
            pole = sp.Integer(0)
        else:
            raise ValueError(f"unknown UV-pole coefficient for {head}")
        pole_replacements[symbol] = pole / eps

    pole_only = sp.together(
        substituted.xreplace(pole_replacements).subs(NS["d"], 4 - 2 * eps)
    )
    residue = sp.simplify(sp.limit(eps * pole_only, eps, 0))
    finite = sp.simplify(sp.limit(pole_only - residue / eps, eps, 0))
    if finite.has(eps):
        raise ValueError("dimensional-prefactor correction retains eps")
    return sp.factor(finite)


def boundary_sample_points(
    lower_left: complex,
    upper_right: complex,
    samples_per_edge: int,
) -> list[tuple[str, complex]]:
    """Return a four-edge counter-clockwise point walk.

    Endpoints are represented once: each edge includes its first point and
    excludes its last point, which is the next edge's first point.
    """

    if samples_per_edge < 2:
        raise ValueError("samples_per_edge must be at least two")
    lo = lower_left
    hi = upper_right
    points: list[tuple[str, complex]] = []
    for k in range(samples_per_edge):
        t = k / samples_per_edge
        points.append(("bottom", complex(lo.real + (hi.real - lo.real) * t, lo.imag)))
    for k in range(samples_per_edge):
        t = k / samples_per_edge
        points.append(("right", complex(hi.real, lo.imag + (hi.imag - lo.imag) * t)))
    for k in range(samples_per_edge):
        t = k / samples_per_edge
        points.append(("top", complex(hi.real - (hi.real - lo.real) * t, hi.imag)))
    for k in range(samples_per_edge):
        t = k / samples_per_edge
        points.append(("left", complex(lo.real, hi.imag - (hi.imag - lo.imag) * t)))
    return points


def _poly_eval(coefficients: list[tuple[int, Fraction]], s: mp.mpc) -> mp.mpc:
    value = mp.mpc(0)
    for power, fraction in coefficients:
        exact = mp.mpf(fraction.numerator) / mp.mpf(fraction.denominator)
        value += exact * s ** power
    return value


class CompiledEvaluator:
    """Per-precision evaluator over compiled terms with a loop cache."""

    def __init__(self, compiled: list[dict[str, Any]], precision: int) -> None:
        self.compiled = compiled
        self.precision = precision
        self.cache: dict[
            tuple[str, tuple[Fraction, ...], complex],
            ba.DiagnosticEstimate,
        ] = {}

    def loop_estimate(
        self,
        head: str,
        args: tuple[Fraction, ...],
        s_value: complex,
    ) -> ba.DiagnosticEstimate:
        key = (head, args, s_value if head == "B0" else 0j)
        cached = self.cache.get(key)
        if cached is not None:
            return cached
        with mp.workprec(self.precision):
            mu_ren = (
                mp.mpf(FIXTURE["mu_ren2"].numerator)
                / mp.mpf(FIXTURE["mu_ren2"].denominator)
            )
            ulp = mp.mpf(2) ** (8 - self.precision)
            values = [mp.mpf(a.numerator) / mp.mpf(a.denominator) for a in args]
            if head == "A0":
                estimate = ba.a0_fin(
                    values[0],
                    mu_ren,
                    precision=self.precision,
                )
            elif head == "B0":
                estimate = ba.b0_fin(
                    complex(s_value),
                    values[0],
                    values[1],
                    mu_ren,
                    precision=self.precision,
                )
            elif head == "A0p":
                if values[0] == 0:
                    estimate = ba.DiagnosticEstimate(
                        mp.mpf(0),
                        mp.mpf(0),
                        mp.mpf(0),
                    )
                else:
                    value = mp.mpc(-mp.log(values[0] / mu_ren))
                    estimate = ba.DiagnosticEstimate(
                        value.real,
                        value.imag,
                        abs(value) * ulp,
                    )
            else:
                raise SystemExit(f"unexpected loop symbol {head}")
        self.cache[key] = estimate
        return estimate

    def evaluate(self, s_value: complex) -> ba.DiagnosticEstimate:
        with mp.workprec(self.precision):
            s = mp.mpc(s_value)
            ulp = mp.mpf(2) ** (8 - self.precision)
            total_mid = mp.mpc(0)
            total_rad = mp.mpf(0)
            for term in self.compiled:
                den_value = _poly_eval(term["den"], s)
                if den_value == 0:
                    raise SystemExit("coefficient denominator vanishes on the contour")
                c_value = _poly_eval(term["num"], s) / den_value
                if term["head"] is None:
                    total_mid += c_value
                    total_rad += abs(c_value) * ulp
                else:
                    estimate = self.loop_estimate(
                        term["head"],
                        term["args"],
                        s_value,
                    )
                    mid = mp.mpc(estimate.mid_re, estimate.mid_im)
                    total_mid += c_value * mid
                    total_rad += (
                        abs(c_value) * estimate.rad
                        + abs(c_value * mid) * ulp
                    )
            loop_factor = mp.mpc(1) / (16 * mp.pi ** 2)
            total_mid *= loop_factor
            total_rad = total_rad * abs(loop_factor) + abs(total_mid) * ulp
            return ba.DiagnosticEstimate(
                total_mid.real,
                total_mid.imag,
                total_rad,
            )


def build_receipts() -> tuple[dict[str, Any], dict[str, str]]:
    vector = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    g1 = Fraction(FIXTURE["g1"])
    g2 = Fraction(FIXTURE["g2"])
    v = Fraction(FIXTURE["v"])
    mw2 = Fraction(g2 ** 2 * v ** 2, 4)
    mz2 = Fraction((g1 ** 2 + g2 ** 2) * v ** 2, 4)

    expression_ww = block_transverse(vector, "WpWm")
    expression_zz = block_transverse(vector, "ZZ")
    expression_az = block_transverse(vector, "AZ")
    correction_ww = dimensional_prefactor_finite_correction(expression_ww)
    correction_zz = dimensional_prefactor_finite_correction(expression_zz)
    correction_az = dimensional_prefactor_finite_correction(expression_az)
    compiled_ww = compile_block(expression_ww) + compile_block(correction_ww)
    compiled_zz = compile_block(expression_zz) + compile_block(correction_zz)
    compiled_az = compile_block(expression_az) + compile_block(correction_az)

    receipts: dict[str, Any] = {}
    corrections = {
        "W": str(correction_ww),
        "Z": str(correction_zz),
        "AZ": str(correction_az),
    }
    for name, tree_mass, compiled in (
        ("W", mw2, compiled_ww),
        ("Z", mz2, compiled_zz),
    ):
        for precision in ba.PRECISIONS:
            evaluator = CompiledEvaluator(compiled, precision)

            def inverse_propagator(s: complex) -> complex:
                pi = evaluator.evaluate(s)
                return complex(s - complex(float(tree_mass))
                               - complex(float(pi.mid_re), float(pi.mid_im)))

            radius_exact = tree_mass / 8
            center = complex(float(tree_mass), 0.0)
            lo = complex(
                float(tree_mass - radius_exact),
                float(-radius_exact),
            )
            hi = complex(
                float(tree_mass + radius_exact),
                float(radius_exact),
            )
            sampled_winding = ba.sample_winding(
                inverse_propagator, (lo, hi),
                subdivisions=SUBDIVISIONS, precision=precision,
            )
            min_mod = None
            max_rad = mp.mpf(0)
            edge_counts = {
                "bottom": 0,
                "right": 0,
                "top": 0,
                "left": 0,
            }
            for edge_name, point in boundary_sample_points(
                lo,
                hi,
                EXCLUSION_SAMPLES,
            ):
                edge_counts[edge_name] += 1
                pi_estimate = evaluator.evaluate(point)
                mid = complex(point) - complex(float(tree_mass)) - complex(
                    float(pi_estimate.mid_re),
                    float(pi_estimate.mid_im),
                )
                if min_mod is None or abs(mid) < min_mod:
                    min_mod = abs(mid)
                if pi_estimate.rad > max_rad:
                    max_rad = pi_estimate.rad
            sampled_points_exclude_zero = bool(min_mod > 8 * float(max_rad))
            az_center = CompiledEvaluator(compiled_az, precision).evaluate(center)
            receipts[f"{name}_{precision}"] = {
                "boson": name,
                "precision_bits": precision,
                "tree_mass_sq": str(tree_mass),
                "contour_exact": {
                    "lower_left": [
                        str(tree_mass - radius_exact),
                        str(-radius_exact),
                    ],
                    "upper_right": [
                        str(tree_mass + radius_exact),
                        str(radius_exact),
                    ],
                },
                "contour_binary64": {
                    "lower_left": [lo.real, lo.imag],
                    "upper_right": [hi.real, hi.imag],
                },
                "sampled_boundary_winding": sampled_winding,
                "sampled_boundary_min_modulus": float(min_mod),
                "roundoff_heuristic_max_radius": float(max_rad),
                "sampled_points_exclude_zero": sampled_points_exclude_zero,
                "samples_per_edge": EXCLUSION_SAMPLES,
                "edge_sample_counts": edge_counts,
                "az_block_at_center": [float(az_center.mid_re),
                                       float(az_center.mid_im),
                                       float(az_center.rad)],
                "dimensional_prefactor_finite_correction": corrections[name],
                "diagnostic_checks_passed": bool(
                    sampled_winding == 1 and sampled_points_exclude_zero
                ),
                "root_count_certified": False,
                "simple_root_certified": False,
                "analytic_sheet_certified": False,
                "precision_enclosure_certified": False,
                "laurent_data_certified": False,
                "physical_current_pole_certified": False,
            }
    return receipts, corrections


def build_payload() -> dict[str, Any]:
    vector_raw = VECTOR_PATH.read_bytes()
    vector = json.loads(vector_raw)
    receipts, corrections = build_receipts()
    diagnostic_ok = all(r["diagnostic_checks_passed"] for r in receipts.values())
    payload = {
        "schema": SCHEMA,
        "type": "EXTERNAL_SM_EFT_DIAGNOSTIC",
        "status": STATUS,
        "diagnostic_checks_passed": diagnostic_ok,
        "acceptance_row_discharged": False,
        "promotion": {"oph_native": False, "unit_claim": False},
        "certification": {
            "root_count": False,
            "simple_root": False,
            "analytic_sheet": False,
            "precision_enclosure": False,
            "laurent_data": False,
            "physical_current_pole": False,
        },
        "input": {
            "path": "outputs/fj_direct_vector_blocks.json",
            "bytes": len(vector_raw),
            "sha256": hashlib.sha256(vector_raw).hexdigest(),
            "schema": vector.get("schema"),
            "target": vector.get("target"),
        },
        "fixture": {k: str(f) for k, f in FIXTURE.items()},
        "ckm_fixture": {
            f"V{i}{j}": str(CKM_FIXTURE[(i, j)])
            for i in (1, 2, 3)
            for j in (1, 2, 3)
        },
        "fixture_statement": (
            "declared synthetic admissible rationals; not the measured "
            "Standard-Model point; no target mounts anywhere; xi = 1; "
            "V is the exact identity matrix and Vc equals V"
        ),
        "arithmetic_scope": (
            "binary64 contour coordinates with mpmath midpoint evaluation "
            "and heuristic roundoff radii; no directed interval arithmetic"
        ),
        "conventions": {
            "mask": ("strict one loop: Pi enters once; the AZ^2 determinant "
                     "term is second loop order and dropped; the AZ block is "
                     "recorded at the contour center"),
            "sheet": (
                "precision-dependent finite -i eps principal-log sampling; "
                "no second-sheet continuation path or holomorphic contour "
                "domain is certified"
            ),
            "dimensional_prefactor_finite_correction": corrections,
        },
        "receipts": receipts,
    }
    payload["artifact_sha256"] = "sha256:" + canonical_sha256(payload)
    return payload


def render_payload(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check-byte-exact", action="store_true")
    args = parser.parse_args()
    payload = build_payload()
    rendered = render_payload(payload)
    if args.check_byte_exact:
        if not OUT_PATH.is_file() or OUT_PATH.read_bytes() != rendered.encode("utf-8"):
            raise SystemExit("stored W/Z boundary diagnostic is not byte-exact")
    else:
        OUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(json.dumps({
        "status": payload["status"],
        "diagnostic_checks_passed": payload["diagnostic_checks_passed"],
        "root_count_certified": payload["certification"]["root_count"],
        "sampled_windings": {
            key: receipt["sampled_boundary_winding"]
            for key, receipt in payload["receipts"].items()
        },
    }))
    return 0 if payload["diagnostic_checks_passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
