#!/usr/bin/env python3
"""Regenerate the runtime-kernel Lean harness from the checked-in capture.

The capture `runtime_kernel_capture.json` records the exact schema object the
oph-physics-sim fractional surface passes to its `quotient_lumpability` check
at runtime, obtained by intercepting that call inside a live
`demo_fractional_report()` run.  This script deterministically renders the
capture into `Lean/ObserverPatchHolography/QuotientLumpabilityRuntimeHarness.lean`,
whose `#guard_msgs`-pinned `#eval`s run all four certified checkers on the
captured data and pin its pointwise equality with the transcribed
`fractionalSandbox*` instance.  If either the capture or the Lean file is
edited by hand, `--check` (and the pytest that wraps it) fails.

Modes:
  --check              compare rendered text against the checked-in Lean file
  --write              rewrite the checked-in Lean file from the capture
  --capture SIM_REPO   re-run the simulator at SIM_REPO and refresh the capture
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from fractions import Fraction
from pathlib import Path

HERE = Path(__file__).resolve().parent
CAPTURE_PATH = HERE / "runtime_kernel_capture.json"
LEAN_PATH = (
    HERE.parents[2]
    / "Lean"
    / "ObserverPatchHolography"
    / "QuotientLumpabilityRuntimeHarness.lean"
)

STATE_IDS = {"a0": ".a0", "a1": ".a1", "vac": ".vac"}
SECTOR_IDS = {"anyon_e_over_3": ".anyonEOver3", "vacuum": ".vacuum"}


def capture(sim_repo: Path) -> dict:
    sys.path.insert(0, str(sim_repo))
    import oph_fractional.compare as compare
    import oph_fractional.quotient as quotient

    captured: dict = {}
    orig_lump = quotient.quotient_lumpability
    orig_bias = quotient.no_orbit_size_bias

    def cap_lump(schema, **kw):
        captured["schema"] = schema
        return orig_lump(schema, **kw)

    def cap_bias(schema, weights, **kw):
        captured["weights"] = dict(weights)
        return orig_bias(schema, weights, **kw)

    compare.quotient_lumpability = cap_lump
    compare.no_orbit_size_bias = cap_bias
    compare.demo_fractional_report()
    schema = captured["schema"]

    def frac(value: float) -> list[int]:
        exact = Fraction(value)
        return [exact.numerator, exact.denominator]

    head = None
    git_head = sim_repo / ".git" / "HEAD"
    if git_head.is_file():
        ref = git_head.read_text(encoding="utf-8").strip()
        if ref.startswith("ref: "):
            ref_file = sim_repo / ".git" / ref[len("ref: "):]
            head = ref_file.read_text(encoding="utf-8").strip() if ref_file.is_file() else None
        else:
            head = ref
    return {
        "artifact": "fractional_runtime_kernel_capture",
        "source_repo": "https://github.com/muellerberndt/oph-physics-sim",
        "captured_at_commit": head,
        "pinned_transcription_commit": "877675938812e26417bb006d5bf3752301f8a3f8",
        "capture_method": (
            "interception of the quotient_lumpability and no_orbit_size_bias "
            "calls inside a live demo_fractional_report() run"
        ),
        "captured_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "states": list(schema.states),
        "sectors": list(schema.sectors),
        "canonical": dict(schema.canonical),
        "kernel": {
            state: {
                target: frac(value)
                for target, value in schema.transition_kernel.get(state, {}).items()
            }
            for state in schema.states
        },
        "orbit_sizes": dict(schema.orbit_sizes),
        "weights": {key: frac(value) for key, value in captured["weights"].items()},
    }


def render(cap: dict) -> str:
    kernel_lines = []
    for state in cap["states"]:
        for target, (num, den) in cap["kernel"].get(state, {}).items():
            kernel_lines.append(
                f"  | {STATE_IDS[state]}, {STATE_IDS[target]} => {num} / {den}"
            )
    kernel_lines.append("  | _, _ => 0")
    quotient_lines = [
        f"  | {STATE_IDS[state]} => {SECTOR_IDS[cap['canonical'][state]]}"
        for state in cap["states"]
    ]
    orbit_lines = [
        f"  | {SECTOR_IDS[sector]} => {cap['orbit_sizes'][sector]}"
        for sector in cap["sectors"]
    ]
    weight_lines = [
        f"  | {SECTOR_IDS[sector]} => "
        f"{cap['weights'][sector][0]} / {cap['weights'][sector][1]}"
        for sector in cap["sectors"]
    ]
    newline = "\n"
    return f"""import ObserverPatchHolography.QuotientLumpability

/-! # Runtime-kernel regression harness

Machine-generated by
`code/particles/fractional/generate_runtime_kernel_harness.py` from
`code/particles/fractional/runtime_kernel_capture.json`; do not edit by hand
(regenerate with `--write`).  The capture records the exact schema object the
simulator's fractional surface passes to its `quotient_lumpability` check at
runtime ({cap["source_repo"]}
at `{cap["captured_at_commit"]}`, transcription pinned at
`{cap["pinned_transcription_commit"]}`).  The pinned `#eval`s run all four
certified checkers on the captured runtime data and pin its pointwise
equality with the transcribed `fractionalSandbox*` instance, so drift in
either the checkers or the capture fails this build. -/

namespace OPH.QuotientLumpability

/-- The transition kernel the simulator ran, exact binary-float rationals. -/
@[reducible] def runtimeKernel :
    FractionalSandboxState → FractionalSandboxState → ℚ
{newline.join(kernel_lines)}

/-- The quotient map the simulator ran. -/
@[reducible] def runtimeQuotient :
    FractionalSandboxState → FractionalSandboxSector
{newline.join(quotient_lines)}

/-- The orbit sizes the simulator ran. -/
@[reducible] def runtimeOrbitSize : FractionalSandboxSector → ℤ
{newline.join(orbit_lines)}

/-- The sector weights the simulator ran. -/
@[reducible] def runtimeSectorWeight : FractionalSandboxSector → ℚ
{newline.join(weight_lines)}

/-- info: true -/
#guard_msgs in
#eval checkLumpable runtimeKernel runtimeQuotient
  fractionalSandboxStates fractionalSandboxSectors

/-- info: true -/
#guard_msgs in
#eval checkCanonicalizerIdempotent
  (fun x => fractionalSandboxRep (runtimeQuotient x)) fractionalSandboxStates

/-- info: true -/
#guard_msgs in
#eval checkRepresentativeInvariant runtimeQuotient runtimeQuotient
  fractionalSandboxStates

/-- info: true -/
#guard_msgs in
#eval checkNoOrbitSizeBias runtimeOrbitSize runtimeSectorWeight
  fractionalSandboxSectors

/- The captured runtime data is pointwise the transcribed instance. -/

/-- info: true -/
#guard_msgs in
#eval decide (∀ x y, runtimeKernel x y = fractionalSandboxKernel x y)

/-- info: true -/
#guard_msgs in
#eval decide (∀ x, runtimeQuotient x = fractionalSandboxQuotient x)

/-- info: true -/
#guard_msgs in
#eval decide ((∀ c, runtimeOrbitSize c = fractionalSandboxOrbitSize c) ∧
  (∀ c, runtimeSectorWeight c = fractionalSandboxSectorWeight c))

end OPH.QuotientLumpability
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--capture", metavar="SIM_REPO")
    args = parser.parse_args()

    if args.capture:
        payload = capture(Path(args.capture).resolve())
        CAPTURE_PATH.write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        print(f"wrote {CAPTURE_PATH}")
        return 0

    cap = json.loads(CAPTURE_PATH.read_text(encoding="utf-8"))
    rendered = render(cap)
    if args.write:
        LEAN_PATH.write_text(rendered, encoding="utf-8")
        print(f"wrote {LEAN_PATH}")
        return 0
    if not LEAN_PATH.is_file():
        print(f"MISSING {LEAN_PATH}")
        return 1
    if LEAN_PATH.read_text(encoding="utf-8") != rendered:
        print(f"STALE {LEAN_PATH}: does not match render of {CAPTURE_PATH}")
        return 1
    print("in sync")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
