import ObservableNormalForms.Exact
import ObservableNormalForms.ObserverConfluence
import ObservableNormalForms.Stability
import ObservableNormalForms.Refinement
import ObservableNormalForms.Repair
import ObservableNormalForms.MechanismVariants
import ObservableNormalForms.Examples.AmdA2A5Conditional
import ObservableNormalForms.Functional
import ObservableNormalForms.Stochastic
import ObservableNormalForms.ConditionalResampling
import ObservableNormalForms.ProtectedObstructions
import ObservableNormalForms.Examples.ProtectedObstructions
import ObservableNormalForms.Examples.Rule90
import ObservableNormalForms.Moduli

/-!
# Axiom audit

The build output of this module is the theorem-level axiom receipt for the
submission artifact.  None of the declarations below should report
`sorryAx`.
-/

open ObservableNormalForms

#print axioms ProtectedObstructions.endpointHitProbability_pos_iff
#print axioms ProtectedObstructions.hitProbability_eq_one_iff_no_reachableClosedTrap
#print axioms ProtectedObstructions.hitProbability_least_nonnegative_fixedPoint
#print axioms ProtectedObstructions.Scheduler.support_to_rewrite
#print axioms ProtectedObstructions.Scheduler.rewrite_to_support
#print axioms ProtectedObstructions.NonidentityExactness.StructuralMorphism.fiber_nonempty_exact_derived
#print axioms ProtectedObstructions.NonidentityExactness.StructuralMorphism.endpointHitProbability_pushforward_derived
#print axioms ProtectedObstructions.NonidentityExactness.StructuralMorphism.layer3_exact
#print axioms ProtectedObstructions.NamedFixtures.m2_not_almostSure
#print axioms ProtectedObstructions.NamedFixtures.m3_two_positive_distinct_endpoints
#print axioms ProtectedObstructions.NonidentityExactness.Fixture.nonidentity_layer3_exact

#print axioms ProtectedObstructions.PublicAdapter.Profile.t0_partition
#print axioms ProtectedObstructions.PublicAdapter.Profile.t0_pairwise_disjoint
#print axioms ProtectedObstructions.PublicAdapter.Profile.t1_fiber_empty_iff
#print axioms ProtectedObstructions.PublicAdapter.Profile.t2_positive_reach_iff
#print axioms ProtectedObstructions.PublicAdapter.Profile.t3_almostSure_iff_noClosedTrap
#print axioms ProtectedObstructions.PublicAdapter.Profile.t4_selection_iff_endpointUnionCert
#print axioms ProtectedObstructions.PublicAdapter.Profile.t5_observableDetermination_collapse
#print axioms ProtectedObstructions.PublicAdapter.Profile.t6_support_to_rewrite
#print axioms ProtectedObstructions.PublicAdapter.Profile.t6_rewrite_to_support
#print axioms ProtectedObstructions.PublicAdapter.Profile.target_is_normal
#print axioms ProtectedObstructions.PublicAdapter.Profile.t7_behaviorCut0
#print axioms ProtectedObstructions.PublicAdapter.Profile.t7_behaviorCut1
#print axioms ProtectedObstructions.PublicAdapter.Profile.t7_behaviorCut2
#print axioms ProtectedObstructions.PublicAdapter.Profile.t7_behaviorCut3
#print axioms ProtectedObstructions.PublicAdapter.t8_coordinate_strict_iff
#print axioms ProtectedObstructions.PublicAdapter.CoreStructuralMorphism.id
#print axioms ProtectedObstructions.PublicAdapter.CoreStructuralMorphism.comp

#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Profile.cut0_subset_cut1
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Profile.cut1_subset_cut2
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Profile.cut2_subset_cut3
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Profile.delta1_eq_cut1_diff_cut0
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Profile.delta2_eq_cut2_diff_cut1
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Profile.delta3_eq_cut3_diff_cut2
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.profile_protected_rfl
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.cutAt_zero
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.cutAt_one
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.cutAt_two
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.cutAt_three
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.le_refl
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.VariantFamily.le_trans
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.FrozenMorphism.toObservationCompatibility
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.FrozenMorphism.carrier_map_bijective
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.FrozenMorphism.id
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.FrozenMorphism.comp
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.InitialLaw.pooledHit_pos_iff
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.InitialLaw.pooledEndpoint_pos_iff
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.InitialLaw.pooledEndpointUnique_iff
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.InitialLaw.pooledHit_eq_one_iff
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Quantitative.pooledHit_exact_derived
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.Quantitative.pooledEndpoint_pushforward_derived

#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.StrictReversal.strict_forward
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.StrictReversal.strict_reverse
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.StrictReversal.not_profileLE_false_true
#print axioms ProtectedObstructions.PublicAdapter.GenericCompletion.StrictReversal.not_profileLE_true_false
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.M0.protected_in_delta0
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.TwoBit.fine_survivor
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.TwoBit.fine_scheduler_activation
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.TwoBit.coarse_in_delta3
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.C4.full_L0_iff_strongRepair
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.C4.missing_K0_iff_noStrongRepair
#print axioms ProtectedObstructions.PublicAdapter.NativeTwoBitC4.C4.filled_relation_not_staticK0
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.source_equality_does_not_imply_support
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m2_t6_support_to_rewrite
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m2_t6_rewrite_to_support
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m3_t6_both_directions
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m2_delta2
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m3_delta3
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m2_t7_level2_rejects
#print axioms ProtectedObstructions.PublicAdapter.NativeC6.m3_t7_level3_rejects

#print axioms observableDetermined_iff_unique_partialNormalizer
#print axioms reachable_normalForm_mem_fiber
#print axioms singleton_fiber_weakNormalization_confluent
#print axioms existsUnique_auditedTerminal
#print axioms ObservationLeakCounterexample.singleton_fiber_insufficient_without_observation_preservation
#print axioms boundaryIdentifiesModulo_iff_observerEndpointUniqueModulo
#print axioms exists_equivalent_observer_endpoints
#print axioms TwoBitRepair.observerEndpointUnique
#print axioms TwoBitRepair.coarse_confluent
#print axioms TwoBitRepair.coarse_observerEndpointUnique_fails
#print axioms heterogeneous_two_output_estimate
#print axioms approximate_schedule_independence
#print axioms one_step_approximate_naturality
#print axioms telescoping_refinement_bound
#print axioms same_level_implementation_agreement
#print axioms anchored_cross_level_metric_core
#print axioms nested_compatible_levels_metric_core
#print axioms two_implementations_bound_from_tower_receipts
#print axioms strongRepair_exists_iff_collarProjection_surjective
#print axioms observation_eq_of_reflTransGen
#print axioms collar_projection_surjective_of_strongRepair
#print axioms no_strongRepair_of_missing_collar
#print axioms empty_write_space_counterexample
#print axioms robust_no_repair_margin
#print axioms empty_relation_repairMargin_zero
#print axioms RankedSynchronousSystem.synchronous_depth_settling
#print axioms FiniteMarkovKernel.finite_markov_drift_iteration
#print axioms finite_markov_tail_bound
#print axioms FiniteMarkovKernel.finiteExpectation_endpointDistribution
#print axioms FiniteMarkovKernel.endpointDistribution_eq_pathWeight_sum
#print axioms FiniteMarkovKernel.pathWeight_sum_one
#print axioms FiniteMarkovKernel.exists_supportedPath_of_endpointDistribution_pos
#print axioms FiniteMarkovKernel.observation_eq_of_mem_supportedPath
#print axioms FiniteMarkovKernel.observation_eq_of_endpointDistribution_pos
#print axioms FiniteMarkovKernel.endpointDistribution_tail_bound
#print axioms FiniteMarkovKernel.finite_markov_endpoint_receipt
#print axioms FiniteMarkovKernel.stationary_expectation_bound
#print axioms FiniteMarkovKernel.stationary_tail_bound
#print axioms FiniteMarkovKernel.occupation_tail_bound
#print axioms FiniteMarkovKernel.occupation_tail_bound_average
#print axioms FiniteMarkovKernel.confinedMass_eq_pathWeight_sum
#print axioms PersistentNoiseControl.noisy_drift
#print axioms PersistentNoiseControl.noisy_endpoint_tail_const
#print axioms PersistentNoiseControl.noisy_confinedMass
#print axioms PersistentNoiseControl.noisy_confinement_vanishes
#print axioms SupportAudit.empty_support_declaration_fails
#print axioms SupportAudit.disconnected_support_declaration_fails
#print axioms SupportAudit.stutter_support_declaration_holds
#print axioms FiniteWeightedObservation.resample_eq_self_iff_observationMeasurable
#print axioms FiniteWeightedObservation.resample_idempotent
#print axioms FiniteWeightedObservation.resample_weighted_self_adjoint
#print axioms FiniteWeightedObservation.resample_weighted_energy_identity
#print axioms FiniteWeightedObservation.resample_weighted_energy_le
#print axioms FiniteWeightedObservation.kernel_eq_conditionalResamplingKernel_iff_recognition
#print axioms Rule90.kernel_exact
#print axioms Rule90.image_exact
#print axioms Rule90.read01_injective_on_image
#print axioms Rule90.read02_not_injective_on_image
#print axioms Rule90.no_total_reverse_repair
#print axioms residualModulus_mono
#print axioms residualModulus_zero
#print axioms residualModulus_le_of_errorBoundWitness
#print axioms errorBoundWitness_residualModulus
#print axioms inverseModulus_mono
#print axioms inverseModulus_le_of_inverseObservationBound
#print axioms inverseObservationBound_inverseModulus
#print axioms inverseModulus_zero_iff_injOn
#print axioms exists_separation_radius
#print axioms intrinsic_two_output_estimate
#print axioms settledModulus_le_symmetric_bound
#print axioms rate_transfer
#print axioms settledModulus_zero_residual
#print axioms SharpnessWitness.symmetric_bound_attained
#print axioms SharpnessWitness.coefficient_two_sharp
#print axioms NegativeControl.bound_not_attained
#print axioms MechanismVariants.behaviorLT_of_subset_of_witness
#print axioms MechanismVariants.trace_to_reflTransGen
#print axioms MechanismVariants.stateObservation_eq_of_trace
#print axioms MechanismVariants.collarProjectionSurjective_iff_full_admissibleCollar
#print axioms MechanismVariants.admissibleCollar_iff_encodedCollarSurjective
#print axioms MechanismVariants.strongRepair_exists_iff_full_admissibleCollar
#print axioms MechanismVariants.strongRepair_exists_iff_encodedCollarSurjective
#print axioms MechanismVariants.no_strongRepair_of_missing_admissibleCollar

#print axioms Examples.AmdA2A5Conditional.trace_starts_initial
#print axioms Examples.AmdA2A5Conditional.trace_reachable
#print axioms Examples.AmdA2A5Conditional.a2_ownerDeclines_premises_activate
#print axioms Examples.AmdA2A5Conditional.a2_broad_target_eliminated
#print axioms Examples.AmdA2A5Conditional.a5_flash_target_eliminated
#print axioms Examples.AmdA2A5Conditional.a5_broad_target_failure
#print axioms Examples.AmdA2A5Conditional.baseline_broad_and_flash_targets_activate
#print axioms Examples.AmdA2A5Conditional.each_variant_has_initial_state
#print axioms Examples.AmdA2A5Conditional.each_variant_has_nontrivial_step
#print axioms Examples.AmdA2A5Conditional.a5_eoa_premises_activate
#print axioms Examples.AmdA2A5Conditional.a2_broad_outcome_preserving
#print axioms Examples.AmdA2A5Conditional.a2_buyer_not_cut
#print axioms Examples.AmdA2A5Conditional.a5_buyer_cut
#print axioms Examples.AmdA2A5Conditional.a2_pairwise_lt_a5_outcome_broad
#print axioms Examples.AmdA2A5Conditional.a2_immediate_eoa_cut_full
#print axioms Examples.AmdA2A5Conditional.a5_immediate_eoa_cut_broad
#print axioms Examples.AmdA2A5Conditional.a5_contract_wallet_cut_flash
#print axioms Examples.AmdA2A5Conditional.a2_flash_hybrid_preserving
#print axioms Examples.AmdA2A5Conditional.a5_contract_hybrid_cut_flash
#print axioms Examples.AmdA2A5Conditional.a2_pairwise_lt_a5_hybrid_flash
#print axioms Examples.AmdA2A5Conditional.outcome_equal_immediate_pending
#print axioms Examples.AmdA2A5Conditional.full_distinguishes_immediate_pending
#print axioms Examples.AmdA2A5Conditional.hybrid_forgets_pending_but_retains_caller
#print axioms Examples.AmdA2A5Conditional.observation_profile_changes_behavior_judgment
#print axioms Examples.AmdA2A5Conditional.a2_zero_new_raw_capability_fails
#print axioms Examples.AmdA2A5Conditional.a2_zero_new_authority_class
#print axioms Examples.AmdA2A5Conditional.a5_zero_new_authority_class
#print axioms Examples.AmdA2A5Conditional.observation_preservation_does_not_supply_strategy
#print axioms Examples.AmdA2A5Conditional.strategic_choice_changes_under_delay_cost
#print axioms Examples.AmdA2A5Conditional.outcomeCollar_injective
#print axioms Examples.AmdA2A5Conditional.a2FullEncode_outcomeCollar
#print axioms Examples.AmdA2A5Conditional.a2FullRelationEncoding_exactRange
#print axioms Examples.AmdA2A5Conditional.declared_support_is_active
#print axioms Examples.AmdA2A5Conditional.declared_missing_support_is_active
#print axioms Examples.AmdA2A5Conditional.broadOutcomePolicy_a2_eligible
#print axioms Examples.AmdA2A5Conditional.broadOutcomePolicy_a5_eligible
#print axioms Examples.AmdA2A5Conditional.flashHybridPolicy_a2_eligible
#print axioms Examples.AmdA2A5Conditional.flashHybridPolicy_a5_eligible
#print axioms Examples.AmdA2A5Conditional.broadOutcomePolicy_a2_lt_a5
#print axioms Examples.AmdA2A5Conditional.flashHybridPolicy_a2_lt_a5
#print axioms Examples.AmdA2A5Conditional.support_costs_are_nontrivial
#print axioms Examples.AmdA2A5Conditional.support_relations_are_distinct
#print axioms Examples.AmdA2A5Conditional.fixed_relation_positive_repairability
#print axioms Examples.AmdA2A5Conditional.fixed_relation_full_collar_covered
#print axioms Examples.AmdA2A5Conditional.a2_full_repair_iff_protected_outcome_representatives
#print axioms Examples.AmdA2A5Conditional.missing_collar_no_repair
#print axioms Examples.AmdA2A5Conditional.protected_sets_are_nonempty
#print axioms Examples.AmdA2A5Conditional.variants_are_distinct
#print axioms Examples.AmdA2A5Conditional.finite_control_premises_satisfiable
#print axioms Examples.AmdA2A5Conditional.a2_pairwise_lt_a5_in_declared_family
#print axioms Examples.AmdA2A5Conditional.pairwise_does_not_establish_family_minimum
#print axioms Examples.AmdA2A5Conditional.full_control_activation_satisfiable
