import ObservableNormalForms.Exact
import ObservableNormalForms.ObserverConfluence
import ObservableNormalForms.Stability
import ObservableNormalForms.Refinement
import ObservableNormalForms.Repair
import ObservableNormalForms.Functional
import ObservableNormalForms.Stochastic
import ObservableNormalForms.ConditionalResampling
import ObservableNormalForms.Examples.Rule90
import ObservableNormalForms.Moduli

/-!
# Axiom audit

The build output of this module is the theorem-level axiom receipt for the
submission artifact.  None of the declarations below should report
`sorryAx`.
-/

open ObservableNormalForms

#print axioms observableDetermined_iff_unique_partialNormalizer
#print axioms reachable_normalForm_mem_fiber
#print axioms singleton_fiber_weakNormalization_confluent
#print axioms existsUnique_auditedTerminal
#print axioms ObservationLeakCounterexample.singleton_fiber_insufficient_without_observation_preservation
#print axioms boundaryIdentifiesModulo_iff_observerEndpointUniqueModulo
#print axioms exists_equivalent_observer_endpoints
#print axioms TwoBitRepair.observerEndpointUnique
#print axioms TwoBitRepair.coarse_confluent
#print axioms TwoBitRepair.coarse_observerEndpointUnique_fails
#print axioms heterogeneous_two_output_estimate
#print axioms approximate_schedule_independence
#print axioms one_step_approximate_naturality
#print axioms telescoping_refinement_bound
#print axioms same_level_implementation_agreement
#print axioms anchored_cross_level_metric_core
#print axioms nested_compatible_levels_metric_core
#print axioms two_implementations_bound_from_tower_receipts
#print axioms strongRepair_exists_iff_collarProjection_surjective
#print axioms empty_write_space_counterexample
#print axioms robust_no_repair_margin
#print axioms empty_relation_repairMargin_zero
#print axioms RankedSynchronousSystem.synchronous_depth_settling
#print axioms FiniteMarkovKernel.finite_markov_drift_iteration
#print axioms finite_markov_tail_bound
#print axioms FiniteMarkovKernel.finiteExpectation_endpointDistribution
#print axioms FiniteMarkovKernel.endpointDistribution_eq_pathWeight_sum
#print axioms FiniteMarkovKernel.pathWeight_sum_one
#print axioms FiniteMarkovKernel.exists_supportedPath_of_endpointDistribution_pos
#print axioms FiniteMarkovKernel.observation_eq_of_mem_supportedPath
#print axioms FiniteMarkovKernel.observation_eq_of_endpointDistribution_pos
#print axioms FiniteMarkovKernel.endpointDistribution_tail_bound
#print axioms FiniteMarkovKernel.finite_markov_endpoint_receipt
#print axioms FiniteMarkovKernel.stationary_expectation_bound
#print axioms FiniteMarkovKernel.stationary_tail_bound
#print axioms FiniteMarkovKernel.occupation_tail_bound
#print axioms FiniteMarkovKernel.occupation_tail_bound_average
#print axioms FiniteMarkovKernel.confinedMass_eq_pathWeight_sum
#print axioms PersistentNoiseControl.noisy_drift
#print axioms PersistentNoiseControl.noisy_endpoint_tail_const
#print axioms PersistentNoiseControl.noisy_confinedMass
#print axioms PersistentNoiseControl.noisy_confinement_vanishes
#print axioms SupportAudit.empty_support_declaration_fails
#print axioms SupportAudit.disconnected_support_declaration_fails
#print axioms SupportAudit.stutter_support_declaration_holds
#print axioms FiniteWeightedObservation.resample_eq_self_iff_observationMeasurable
#print axioms FiniteWeightedObservation.resample_idempotent
#print axioms FiniteWeightedObservation.resample_weighted_self_adjoint
#print axioms FiniteWeightedObservation.resample_weighted_energy_identity
#print axioms FiniteWeightedObservation.resample_weighted_energy_le
#print axioms FiniteWeightedObservation.kernel_eq_conditionalResamplingKernel_iff_recognition
#print axioms Rule90.kernel_exact
#print axioms Rule90.image_exact
#print axioms Rule90.read01_injective_on_image
#print axioms Rule90.read02_not_injective_on_image
#print axioms Rule90.no_total_reverse_repair
#print axioms residualModulus_mono
#print axioms residualModulus_zero
#print axioms residualModulus_le_of_errorBoundWitness
#print axioms errorBoundWitness_residualModulus
#print axioms inverseModulus_mono
#print axioms inverseModulus_le_of_inverseObservationBound
#print axioms inverseObservationBound_inverseModulus
#print axioms inverseModulus_zero_iff_injOn
#print axioms exists_separation_radius
#print axioms intrinsic_two_output_estimate
#print axioms settledModulus_le_symmetric_bound
#print axioms rate_transfer
#print axioms settledModulus_zero_residual
#print axioms SharpnessWitness.symmetric_bound_attained
#print axioms SharpnessWitness.coefficient_two_sharp
#print axioms NegativeControl.bound_not_attained
