#!/usr/bin/env python3
"""Emit the direct public sigma-datum descent theorem for the quark lane."""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[2]
SECTOR_ATTACHED_JSON = (
    ROOT / "particles" / "runs" / "flavor" / "quark_current_family_transport_frame_sector_attached_lift.json"
)
STRENGTHENED_LOCAL_JSON = (
    ROOT / "particles" / "runs" / "flavor" / "quark_current_family_transport_frame_strengthened_physical_sigma_lift_theorem.json"
)
LINE_LIFT_JSON = ROOT / "particles" / "runs" / "flavor" / "overlap_edge_line_lift.json"
SOURCE_SIGMA_REQUIRED_JSON = (
    ROOT / "particles" / "runs" / "flavor" / "quark_sigma_source_datum_no_target_leak_required.json"
)
DEFAULT_OUT = ROOT / "particles" / "runs" / "flavor" / "quark_public_physical_sigma_datum_descent.json"

MISSING_FOR_PROMOTION = [
    "QUARK_SIGMA_SOURCE_QUOTIENT",
    "QUARK_SIGMA_SOURCE_SELECTOR",
    "QUARK_EDGE_STATISTICS_CORRECTION_THEOREM",
    "QUARK_SIGMA_REFINEMENT_COMPATIBILITY",
    "NO_TARGET_LEAK_DAG_QUARK_SIGMA_SOURCE",
]


def _timestamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_optional_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return _load_json(path)


def _source_sigma_closed(source_sigma_required: dict[str, Any] | None) -> bool:
    if not source_sigma_required:
        return False
    return (
        source_sigma_required.get("status") == "theorem_grade"
        and source_sigma_required.get("no_target_leak") is True
        and source_sigma_required.get("identity") == "P_to_selected_public_quark_sigma_datum"
    )


def build_artifact(
    sector_attached_lift: dict[str, Any],
    strengthened_local: dict[str, Any],
    line_lift: dict[str, Any],
    source_sigma_required: dict[str, Any] | None = None,
) -> dict[str, Any]:
    selected_class = dict(sector_attached_lift["common_refinement_frame_class"])
    sigma_element = dict(strengthened_local["restricted_sigma_ud_phys_element"])
    sigma_datum = dict(strengthened_local["theorem_grade_physical_sigma_datum"])
    overlap_certificate = dict(line_lift["common_refinement_overlap_certificate"])
    supporting_artifacts = dict(strengthened_local.get("supporting_artifacts") or {})
    target_derived_sigma_datum_used = "exact_sigma_target" in supporting_artifacts
    source_sigma_closed = _source_sigma_closed(source_sigma_required)
    promotion_allowed = source_sigma_closed and not target_derived_sigma_datum_used
    proof_status = (
        "closed_source_only_public_physical_sigma_datum_descent"
        if promotion_allowed
        else "blocked_target_derived_sigma_datum_descent"
    )
    declared_fiber_statement = (
        "Let R_decl(f_P) be the set of declared current-family/common-refinement transport-frame realizations "
        "generated by the same-label line lift and projecting to the selected public quark frame class f_P. "
        "For any r,r' in R_decl(f_P), the ordered same-label projectors carry the same labels "
        f"{list(line_lift['object_labels'])}, the same-label transport partial isometries fix the same phase-locked "
        "source/target frame columns up to independent per-label phases, and refinement functoriality plus "
        "current-family common-refinement invariance identify every declared presentation with that same labeled "
        "transport-frame class. Therefore there exist diagonal D_u,D_d in U(1)^3 such that "
        "(U_u^L(r'),U_d^L(r'),V_CKM(r')) = (U_u^L(r) D_u, U_d^L(r) D_d, D_u^dagger V_CKM(r) D_d), so "
        "[sigma_id(r'),canonical_token(r'),U_u^L(r'),U_d^L(r'),V_CKM(r'),I_CKM(r')] = "
        "[sigma_id(r),canonical_token(r),U_u^L(r) D_u,U_d^L(r) D_d,D_u^dagger V_CKM(r) D_d,I_CKM(r)] "
        "in Sigma_ud^phys. Since the strengthened restricted lift attaches one exact sigma datum to that declared "
        "same-label class, (sigma_seed_ud, eta_ud, sigma_u, sigma_d)(r') = "
        "(sigma_seed_ud, eta_ud, sigma_u, sigma_d)(r)."
    )
    return {
        "artifact": "oph_quark_public_physical_sigma_datum_descent",
        "generated_utc": _timestamp(),
        "proof_status": proof_status,
        "theorem_id": (
            "source_only_public_physical_sigma_datum_descent"
            if promotion_allowed
            else "selected_bridge_fiber_sigma_descent_not_source_selection"
        ),
        "theorem_scope": "selected_public_physical_quark_frame_class_only",
        "claim_tier": (
            "source_only_public_sigma_datum"
            if promotion_allowed
            else "selected_class_conditional_on_source_sigma"
        ),
        "public_promotion_allowed": promotion_allowed,
        "source_only_sigma_emitted": promotion_allowed,
        "downstream_algebra_closed": True,
        "sigma_descent_is_sigma_selection": False,
        "display_allowed_as_selected_class_witness": True,
        "non_circularity_status": {
            "promotion_allowed": promotion_allowed,
            "target_derived_sigma_datum_used": target_derived_sigma_datum_used,
            "source_sigma_selector_closed": source_sigma_closed,
            "missing_source_object": None
            if promotion_allowed
            else "quark_sigma_source_datum_no_target_leak_required",
            "strict_audit_label": "source_only_public_sigma_datum"
            if promotion_allowed
            else "selected_class_conditional_on_source_sigma",
        },
        "missing_for_promotion": [] if promotion_allowed else MISSING_FOR_PROMOTION,
        "source_sigma_selector_required_artifact": (
            None if promotion_allowed else "particles/runs/flavor/quark_sigma_source_datum_no_target_leak_required.json"
        ),
        "supporting_artifacts": {
            "restricted_sector_attached_lift": sector_attached_lift["artifact"],
            "restricted_strengthened_physical_sigma_lift": strengthened_local["artifact"],
            "restricted_strengthened_physical_sigma_lift_supports": supporting_artifacts,
            "same_label_line_lift": line_lift["artifact"],
            "source_sigma_required_gate": None
            if source_sigma_required is None
            else source_sigma_required.get("artifact"),
        },
        "theorem_statement": (
            "Let f_P be the physical quark frame class selected by P, represented on the realized quark lane by the "
            "explicit same-label common-refinement transport-frame class [F0^dagger F1]. For any two declared "
            "current-family/common-refinement transport-frame realizations r,r' in the selected same-label bridge "
            "fiber R_decl(f_P), the emitted Sigma_ud^phys element and attached exact physical sigma datum "
            "(sigma_seed_ud, eta_ud, sigma_u, sigma_d) agree. Equivalently, the exact sigma readout is constant on "
            "R_decl(f_P) and descends uniquely to a representative-independent datum on the selected physical quark "
            "frame class. This descent proves constancy on the selected bridge fiber only; it does not select the "
            "sigma value from P. If the attached sigma value is inherited from the current-family exact target "
            "surface, the descended public value remains target-derived."
        ),
        "selected_public_physical_frame_class": {
            "symbol": selected_class["symbol"],
            "representative": selected_class["representative"],
            "representative_abs_matrix": selected_class["representative_abs_matrix"],
            "selected_by": "P",
        },
        "realized_transport_frame_section_uniqueness": {
            "section_domain": sector_attached_lift["section_property"]["section_domain"],
            "object_labels": list(line_lift["object_labels"]),
            "common_refinement_level": int(line_lift["common_refinement_level"]),
            "refinement_functoriality_closed": bool(line_lift["refinement_functoriality_closed"]),
            "cocycle_identity_closed": bool(line_lift["cocycle_identity_closed"]),
            "common_refinement_invariance_closed_on_current_family": bool(
                overlap_certificate["common_refinement_invariance_closed_on_current_family"]
            ),
            "refinement_intertwiners": line_lift["refinement_intertwiners"],
            "uniqueness_reason": (
                "On the selected public class, the declared same-label bridge fiber is generated by one labeled "
                "common-refinement transport-frame class from the same-label line lift. Ordered labels and canonical "
                "phase-locking leave only independent diagonal rephasing on the source and target frames."
            ),
        },
        "declared_bridge_fiber": {
            "name": "R_decl(f_P)",
            "definition": (
                "Declared current-family/common-refinement transport-frame realizations generated by the same-label "
                "line lift and projecting to the selected public quark frame class f_P."
            ),
            "selected_public_class_symbol": selected_class["symbol"],
            "realized_section_is_singleton_mod_diagonal_phase": True,
            "phase_quotient": "(U_uL,U_dL,V) ~ (U_uL D_u,U_dL D_d,D_u^dagger V D_d)",
        },
        "declared_bridge_fiber_invariance_theorem": {
            "id": "declared_selected_public_bridge_fiber_sigma_constancy",
            "statement": declared_fiber_statement,
            "must_emit_sigma_datum": sigma_datum,
        },
        "phase_quotient_argument": sector_attached_lift["quotient_well_definedness"],
        "descended_sigma_ud_phys_element": sigma_element,
        "descended_physical_sigma_datum": sigma_datum,
        "induces_global_contract": {
            "id": "strengthened_quark_physical_sigma_ud_lift",
            "role": "public_same_label_left_handed_sigma_datum_on_selected_physical_frame_class",
        },
        "proof_skeleton": [
            {
                "step": 1,
                "statement": (
                    "The restricted sector-attached lift already provides a section over the explicit same-label "
                    "common-refinement transport-frame class generated by the line lift."
                ),
            },
            {
                "step": 2,
                "statement": (
                    "Changing unit eigenvector representatives multiplies the source and target frames on the right by "
                    "diagonal phases only, and this is exactly the defining quotient relation of Sigma_ud^phys."
                ),
            },
            {
                "step": 3,
                "statement": (
                    "The restricted strengthened lift already attaches the unique exact sigma datum to that emitted "
                    "Sigma_ud^phys class on the realized section."
                ),
            },
            {
                "step": 4,
                "statement": (
                    "Any declared realization in the selected same-label bridge fiber is reconstructed from the same "
                    "ordered labels and same-label transport partial isometries, so any two declared realizations "
                    "differ only by diagonal rephasing."
                ),
            },
            {
                "step": 5,
                "statement": (
                    "The defining quotient of Sigma_ud^phys kills that rephasing freedom, so the sigma element and the "
                    "attached exact sigma datum are constant on the selected declared bridge fiber and factor through f_P."
                ),
            },
            {
                "step": 6,
                "statement": (
                    "Factoring through f_P is not a selector theorem: any constant sigma map on R_decl(f_P) would "
                    "descend. Promotion therefore still requires a no-target source theorem emitting the physical "
                    "sigma datum before the affine readout can be counted as a public quark-mass prediction."
                ),
            },
        ],
        "why_sufficient": (
            "Once a source-only sigma selector is supplied and this descent holds, the physical sigma datum is "
            "intrinsic public data on the selected physical quark frame class. The affine mean law then emits the "
            "absolute sector scales algebraically, and the already-closed exact forward construction lifts from the "
            "local transport-frame representative to the public selected class. In the current artifact the descent "
            "is only an audit/support witness because the descended sigma datum is target-derived."
        ),
        "notes": [
            "This theorem closes representative independence on the selected bridge fiber, not source selection of the sigma datum.",
            "It is a descent theorem on the selected public frame class only; it does not claim a global classification of all quark frame classes.",
            "The selected exact sigma datum is the same target-derived one already emitted on the closed local transport-frame chain.",
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the public quark sigma-datum descent theorem artifact.")
    parser.add_argument("--sector-attached-lift", default=str(SECTOR_ATTACHED_JSON))
    parser.add_argument("--strengthened-local", default=str(STRENGTHENED_LOCAL_JSON))
    parser.add_argument("--line-lift", default=str(LINE_LIFT_JSON))
    parser.add_argument("--source-sigma-required", default=str(SOURCE_SIGMA_REQUIRED_JSON))
    parser.add_argument("--output", default=str(DEFAULT_OUT))
    args = parser.parse_args()

    payload = build_artifact(
        _load_json(Path(args.sector_attached_lift)),
        _load_json(Path(args.strengthened_local)),
        _load_json(Path(args.line_lift)),
        _load_optional_json(Path(args.source_sigma_required)),
    )
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"saved: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
