import ObserverPatchHolography.QuotientLumpability

/-! # Runtime-kernel regression harness

Machine-generated by
`code/particles/fractional/generate_runtime_kernel_harness.py` from
`code/particles/fractional/runtime_kernel_capture.json`; do not edit by hand
(regenerate with `--write`).  The capture records the exact schema object the
simulator's fractional surface passes to its `quotient_lumpability` check at
runtime (https://github.com/muellerberndt/oph-physics-sim
at commit `52dc7355a657b7fd0ab413d9aa5321c5f37e2145` (tree `4ddf19b45ead9b68ea19a98de115fbb2e1ffdd6a`),
transcription pinned at
`877675938812e26417bb006d5bf3752301f8a3f8`).  The pinned `#eval`s run all four
certified checkers on the captured runtime data and pin its pointwise
equality with the transcribed `fractionalSandbox*` instance, so drift in
either the checkers or the capture fails this build. -/

namespace OPH.QuotientLumpability

/-- The transition kernel the simulator ran, exact binary-float rationals. -/
@[reducible] def runtimeKernel :
    FractionalSandboxState → FractionalSandboxState → ℚ
  | .a0, .a1 => 1 / 2
  | .a0, .vac => 1 / 2
  | .a1, .a0 => 1 / 2
  | .a1, .vac => 1 / 2
  | .vac, .vac => 1 / 1
  | _, _ => 0

/-- The quotient map the simulator ran. -/
@[reducible] def runtimeQuotient :
    FractionalSandboxState → FractionalSandboxSector
  | .a0 => .anyonEOver3
  | .a1 => .anyonEOver3
  | .vac => .vacuum

/-- The orbit sizes the simulator ran. -/
@[reducible] def runtimeOrbitSize : FractionalSandboxSector → ℤ
  | .anyonEOver3 => 1
  | .vacuum => 1

/-- The sector weights the simulator ran. -/
@[reducible] def runtimeSectorWeight : FractionalSandboxSector → ℚ
  | .anyonEOver3 => 1 / 1
  | .vacuum => 1 / 1

/-- info: true -/
#guard_msgs in
#eval checkLumpable runtimeKernel runtimeQuotient
  fractionalSandboxStates fractionalSandboxSectors

/-- info: true -/
#guard_msgs in
#eval checkCanonicalizerIdempotent
  (fun x => fractionalSandboxRep (runtimeQuotient x)) fractionalSandboxStates

/-- info: true -/
#guard_msgs in
#eval checkRepresentativeInvariant runtimeQuotient runtimeQuotient
  fractionalSandboxStates

/-- info: true -/
#guard_msgs in
#eval checkNoOrbitSizeBias runtimeOrbitSize runtimeSectorWeight
  fractionalSandboxSectors

/- The captured runtime data is pointwise the transcribed instance. -/

/-- info: true -/
#guard_msgs in
#eval decide (∀ x y, runtimeKernel x y = fractionalSandboxKernel x y)

/-- info: true -/
#guard_msgs in
#eval decide (∀ x, runtimeQuotient x = fractionalSandboxQuotient x)

/-- info: true -/
#guard_msgs in
#eval decide ((∀ c, runtimeOrbitSize c = fractionalSandboxOrbitSize c) ∧
  (∀ c, runtimeSectorWeight c = fractionalSandboxSectorWeight c))

end OPH.QuotientLumpability
