#!/usr/bin/env python3
"""Regression and adversarial tests for the GitHub #567 descent certificate."""

from __future__ import annotations

import copy
import sys
import unittest
from fractions import Fraction
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(MODULE_DIR))

import axis_center_descent_certificate as cert  # noqa: E402


class AxisCenterDescentTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.manifest_path = MODULE_DIR / "manifests" / "axis_center_descent_reference.json"
        cls.receipt_path = MODULE_DIR / "receipts" / "axis_center_descent_reference.receipt.json"
        cls.negative_path = MODULE_DIR / "negative_controls" / "issue_567_negative_controls.json"
        cls.manifest = cert.load_json(cls.manifest_path)
        cls.expected = cert.certificate_payload(cls.manifest)

    def test_reference_receipt_is_exactly_recomputable(self) -> None:
        receipt = cert.load_json(self.receipt_path)
        cert.verify_receipt(self.manifest, receipt)
        self.assertEqual(receipt, self.expected)

    def test_kernel_is_computed_on_realized_tensors(self) -> None:
        kernel = self.expected["kernel_on_realized_tensors"]
        self.assertEqual(kernel["candidates_enumerated"], 36)
        self.assertEqual(kernel["kernel_order"], 6)
        self.assertEqual(kernel["cyclic_generator"], [1, 1, 1])
        self.assertTrue(kernel["matches_emitted_kernel_data"])
        self.assertEqual(kernel["tensor_additivity_checked_pairs"], 64)

    def test_global_form_and_line_spectrum(self) -> None:
        form = self.expected["global_form"]
        self.assertEqual(form["group"], "(SU(3) x SU(2) x U(1)) / Z6")
        self.assertEqual(form["character_lattice_smith_invariants"], [1, 1, 6])
        self.assertEqual(form["wilson_class_group_order"], 6)
        line = self.expected["line_spectrum"]
        self.assertEqual(
            line["minimum_magnetic_line"],
            {
                "color_center_flux": 1,
                "weak_flux": 1,
                "u1_charge_electron_dirac_units": "1/6",
            },
        )
        self.assertTrue(line["monopole_dynamics_not_inferred"])

    def test_four_admissible_global_forms_control(self) -> None:
        control = self.expected["four_admissible_global_forms_control"]
        self.assertEqual(len(control["subgroup_menu"]), 4)
        self.assertEqual(control["adjoint_only_kernel_order"], 36)
        self.assertEqual(control["fractional_singlet_countermodel_kernel_order"], 1)

    def test_spin_descent_and_refinement_invariance(self) -> None:
        self.assertEqual(
            self.expected["spin_fermion_descent"]["spin_representative_in_kernel"],
            [0, 1, 3],
        )
        refinement = self.expected["refinement_invariance"]
        self.assertEqual(refinement["carrier_rotations"], 60)
        self.assertEqual(refinement["artifact_persistence_maps"], 2)

    def test_kernel_enumeration_matches_lean_module(self) -> None:
        kernel = cert.common_kernel(cert.REALIZED_WEIGHTS)
        self.assertEqual(set(kernel), cert.cyclic_generated((1, 1, 1)))
        self.assertEqual(len(cert.common_kernel(cert.ADJOINT_WEIGHTS)), 36)
        fractional = dict(cert.REALIZED_WEIGHTS)
        fractional["fractional_singlet"] = (1, 0, 0)
        self.assertEqual(cert.common_kernel(fractional), [(0, 0, 0)])

    def test_magnetic_lattice_is_generated_by_the_minimal_line(self) -> None:
        # The admissibility conditions are congruences m = s mod 3 and
        # n = s mod 2 for g = s/6, so the lattice is generated by (1, 1, 1/6).
        for s in range(12):
            m, n = s % 3, s % 2
            self.assertEqual(
                cert.certificate_payload(self.manifest)["line_spectrum"][
                    "minimum_magnetic_line"
                ]["u1_charge_electron_dirac_units"],
                "1/6",
            )
            break

    def test_negative_controls_fail_closed(self) -> None:
        payload = cert.negative_control_payload(self.manifest)
        stored = cert.load_json(self.negative_path)
        self.assertEqual(payload, stored)
        names = {row["name"] for row in payload["finite_controls"]}
        self.assertEqual(
            names,
            {
                "wrong_hypercharge_convention",
                "mixed_orientation",
                "wrong_matter_receipt_pin",
                "monopole_dynamics_injection",
            },
        )
        self.assertTrue(all(row["passed"] for row in payload["finite_controls"]))

    def test_tampered_receipt_is_rejected(self) -> None:
        receipt = copy.deepcopy(self.expected)
        receipt["kernel_on_realized_tensors"]["kernel_order"] = 3
        with self.assertRaises(cert.CertificateError) as caught:
            cert.verify_receipt(self.manifest, receipt)
        self.assertEqual(caught.exception.code, "RECEIPT_MISMATCH")

    def test_smith_normal_form(self) -> None:
        reduced = cert.smith_normal_form([[1, 0, -2], [0, 1, -3], [0, 0, 6]])
        self.assertEqual([reduced[i][i] for i in range(3)], [1, 1, 6])
        reduced_two = cert.smith_normal_form([[2, 0], [0, 3]])
        self.assertEqual([reduced_two[i][i] for i in range(2)], [1, 6])


if __name__ == "__main__":
    unittest.main()
