#!/usr/bin/env python3
"""Regression and adversarial tests for the GitHub #565 certificate."""

from __future__ import annotations

import copy
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(MODULE_DIR))

import echosahedral_selector_certificate as cert  # noqa: E402


class EchosahedralSelectorCertificateTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.manifest_path = MODULE_DIR / "manifests" / "echosahedral_federation_reference.json"
        cls.receipt_path = MODULE_DIR / "receipts" / "echosahedral_federation_reference.receipt.json"
        cls.negative_path = MODULE_DIR / "negative_controls" / "issue_565_negative_controls.json"
        cls.manifest = cert.load_json(cls.manifest_path)
        cls.expected = cert.certificate_payload(cls.manifest)

    def test_reference_receipt_is_exactly_recomputable(self) -> None:
        receipt = cert.load_json(self.receipt_path)
        cert.verify_receipt(self.manifest, receipt)
        self.assertEqual(receipt, self.expected)

    def test_unit_split_has_unique_integer_floor_and_gap(self) -> None:
        row = self.expected["unit_split"]
        self.assertEqual(row["unique_minimizer"], [1] * 12)
        self.assertEqual(row["minimum"], 12)
        self.assertEqual(row["strict_gap"], 2)
        self.assertEqual(row["next_integer_floor"], 14)
        self.assertEqual(len(row["unit_lines"]), 12)

    def test_inverse_pairing_is_unique_and_fixed_point_free(self) -> None:
        row = self.expected["inverse_pairing"]
        self.assertTrue(row["unique"])
        self.assertTrue(row["fixed_point_free"])
        self.assertTrue(row["involutive"])
        flattened = [port for pair in row["pairs"] for port in pair]
        self.assertEqual(len(row["pairs"]), 6)
        self.assertEqual(set(flattened), set(self.manifest["carrier"]["ports"]))

    def test_group_and_frame_certificate(self) -> None:
        row = self.expected["icosahedral_selector"]
        self.assertEqual(row["full_incidence_automorphism_order"], 120)
        self.assertEqual(row["full_incidence_group"], "A5 x C2, with central C2 generated by the antipode")
        self.assertEqual(row["orientation_preserving_order"], 60)
        self.assertEqual(row["direct_a5_identification"]["klein_four_subgroups"], 5)
        self.assertTrue(row["direct_a5_identification"]["conjugation_action_faithful"])
        self.assertEqual(row["orientation_character_counts"], {"+1": 60, "-1": 60})
        self.assertEqual(row["element_order_histogram"], {"1": 1, "2": 15, "3": 20, "5": 24})
        self.assertEqual(row["canonical_gram_rank"], 3)
        self.assertEqual(row["canonical_gram_trace"], 12)
        self.assertEqual(row["canonical_gram_identity"], "G^2=4G")
        self.assertTrue(row["port_action_faithful"])
        self.assertTrue(row["axis_action_faithful"])
        self.assertTrue(row["port_frame_equivariance"])
        self.assertTrue(row["frame_orientation_certificate"]["combinatorial_orientation_equals_frame_determinant"])
        self.assertEqual(row["frame_orientation_certificate"]["orientation_preserving_determinants"], {"+1": 60})
        self.assertEqual(row["frame_orientation_certificate"]["orientation_reversing_determinants"], {"-1": 60})
        self.assertEqual(row["axis_count"], 6)

    def test_refinement_naturality_and_cocycle(self) -> None:
        row = self.expected["refinement"]
        self.assertTrue(row["all_maps_in_A5"])
        self.assertTrue(row["unit_lines_natural"])
        self.assertTrue(row["antipode_natural"])
        self.assertTrue(row["frame_gram_natural"])
        self.assertEqual(row["checked_cocycle_triangles"], 1)

    def test_arbitrary_port_relabeling_preserves_canonical_class(self) -> None:
        sigma = (7, 2, 10, 4, 0, 11, 5, 9, 1, 6, 3, 8)
        relabeled = cert.relabel_manifest(self.manifest, sigma)
        receipt = cert.certificate_payload(relabeled)
        self.assertEqual(
            receipt["carrier"]["canonical_oriented_incidence_sha256"],
            self.expected["carrier"]["canonical_oriented_incidence_sha256"],
        )
        for key in (
            "orientation_preserving_order",
            "full_incidence_automorphism_order",
            "element_order_histogram",
            "canonical_gram_rank",
            "six_axis_squared_cross_inner_product",
        ):
            self.assertEqual(receipt["icosahedral_selector"][key], self.expected["icosahedral_selector"][key])
        self.assertEqual(receipt["refinement"], self.expected["refinement"])

    def test_all_finite_negative_controls_fail_closed(self) -> None:
        payload = cert.negative_control_payload(self.manifest)
        stored = cert.load_json(self.negative_path)
        self.assertEqual(payload, stored)
        self.assertGreaterEqual(len(payload["finite_controls"]), 9)
        self.assertTrue(all(row["passed"] for row in payload["finite_controls"]))

    def test_forbidden_downstream_data_is_rejected(self) -> None:
        mutant = copy.deepcopy(self.manifest)
        mutant["selector_hint"] = {"standard_model_representation": "adjoint"}
        with self.assertRaises(cert.CertificateError) as caught:
            cert.certificate_payload(mutant)
        self.assertEqual(caught.exception.code, "FORBIDDEN_DEPENDENCY")

    def test_tampered_receipt_is_rejected(self) -> None:
        receipt = copy.deepcopy(self.expected)
        receipt["icosahedral_selector"]["orientation_preserving_order"] = 59
        with self.assertRaises(cert.CertificateError) as caught:
            cert.verify_receipt(self.manifest, receipt)
        self.assertEqual(caught.exception.code, "RECEIPT_MISMATCH")

    def test_cli_certify_verify_and_negative_controls(self) -> None:
        script = MODULE_DIR / "echosahedral_selector_certificate.py"
        with tempfile.TemporaryDirectory() as tmp:
            tmpdir = Path(tmp)
            receipt = tmpdir / "receipt.json"
            controls = tmpdir / "negative.json"
            subprocess.run(
                [sys.executable, str(script), "certify", "--manifest", str(self.manifest_path), "--output", str(receipt)],
                check=True,
                capture_output=True,
                text=True,
            )
            subprocess.run(
                [sys.executable, str(script), "verify", "--manifest", str(self.manifest_path), "--receipt", str(receipt)],
                check=True,
                capture_output=True,
                text=True,
            )
            subprocess.run(
                [sys.executable, str(script), "negative-controls", "--manifest", str(self.manifest_path), "--output", str(controls)],
                check=True,
                capture_output=True,
                text=True,
            )
            self.assertEqual(cert.load_json(receipt), self.expected)
            self.assertEqual(cert.load_json(controls), cert.negative_control_payload(self.manifest))


if __name__ == "__main__":
    unittest.main()

