import Dynamics.ProtectedCharge
import Dynamics.WardLimitManifest
import Dynamics.ConditionalExpectationGenerator
import Dynamics.PublicMarkov
import Dynamics.PublicAutomorphism
import Dynamics.PrivateInner
import Dynamics.StoneConverse
import Dynamics.CentralBlocks
import Dynamics.CenterSpectral
import Dynamics.StarWedderburn
import Dynamics.ChoiCPTP

/-!
# OPH construction dynamics umbrella

Cross-track dynamical interfaces live under `OPH.Dynamics`. Concrete finite
realizations remain in their issue-owned libraries and import these interfaces
when needed.

`ConditionalExpectationGenerator.lean` contains the finite matrix identity
for the generator of partition pinching, its projector-rate GKSL expression,
the single-collar fixed algebra, and the multi-collar intersection under an
explicit no-cancellation premise. It supplies no formal channel object or
physical rate attachment.

`PublicMarkov.lean`, `PublicAutomorphism.lean`, and `PrivateInner.lean` carry
the bounded B3 dichotomy:
positive unital maps of finite record functions are row-stochastic, continuous
public star-automorphism groups are trivial because every finite public star
automorphism is uniquely a label permutation, full private matrix-block
automorphisms are unitarily inner, and a fixed self-adjoint Hamiltonian
generates a unitary real-parameter von Neumann flow.
`Dynamics.StoneConverse` proves the converse on one full finite matrix
block: derivations are inner, star derivations carry self-adjoint
generators unique up to a real scalar, and every pointwise-continuous
real-parameter star-automorphism group is conjugation by a coherent
unitary one-parameter family generated by one time-independent
self-adjoint Hamiltonian. Arbitrary central-block algebras remain
outside this result.
`Dynamics.CentralBlocks` adds central star projections, the
two-sided corner factorization, the center and central-idempotent
classification of the two-block algebra, the automorphism block
dichotomy with the swap countermodel, and the two-block Stone converse
in which block fixing is derived from continuity through the identity.
`Dynamics.CenterSpectral` proves the center of a star
subalgebra of a matrix algebra is spanned by a finite orthogonal family
of minimal central projections summing to one, by finite descent plus
Lagrange functional calculus, with uniqueness up to permutation.
`Dynamics.StarWedderburn` completes the ladder: every
finite-dimensional star subalgebra of a matrix algebra is star-isomorphic
to a finite product of full matrix blocks, and every pointwise-continuous
one-parameter star-automorphism group is blockwise unitary conjugation
with one time-independent self-adjoint Hamiltonian per block, with block
fixing derived from continuity.
`Dynamics.ChoiCPTP` defines finite complete positivity through
amplified positivity with the Kraus criterion, proves the partition
average, partition pinching, and every nonnegative-time relaxation
channel CPTP, and refutes the transpose map through an exact Choi
computation.
-/
