import QFT.NoncommutativeWitness

/-!
# Coverage receipts for finite causal observer nets

The committed `FiniteCover` in `QFT/ObserverNetDescent.lean` names a
nonempty finite family of declared subregions; the abstract region
preorder has no join operation, so the name carries no union semantics.
This module supplies the missing joint-coverage law for completion-plan
issue `#692` as a separate receipt.  `familyJoin` is the star-subalgebra
join of the family's local algebras inside the private matrix algebra,
and a `CoverageLaw` declares that the covered region's local algebra is
contained in that join.  Isotony supplies the reverse containment
(`familyJoin_le_covered`), so the receipt is equivalent to the equality
`CoverageLaw.join_eq`: the covered local algebra is generated by the
family's local algebras.  Monotonicity under family enlargement and
refinement naturality along the regulator preorder are derivable, so
they are theorems (`CoverageLaw.mono`, `CoverageLaw.refine_mem`) rather
than declared fields.  A coverage law for the refined family at the
finer regulator is not derivable from the committed interface and is not
claimed.

Reconstruction: a coverage law together with a declared
`ObserverNetDescent` packet yields the exact statement that every
compatible family on the declared cover has exactly one globalization in
the covered local algebra and that the globalization lies in the
family-generated join (`CoverageLaw.reconstruction`).  The pointwise
form `CoverageLaw.determined_by_restrictions` states that an element of
the covered algebra is determined by its declared restrictions to the
family and lies in the join.  The determination clause consumes only the
descent packet, through `jointly_injective_of_unique_descent`; the
coverage law contributes the generation membership, so both hypotheses
are load-bearing in the conjunction.

Witness receipts on the noncommutative `characterCausalNet`.  The
star-subalgebra join of the two block algebras is computed exactly: it
is the block-diagonal algebra with two free two-by-two corner blocks
(`leftBlock_sup_rightBlock`), and that algebra is a proper subalgebra of
`M₄` (`blockDiagonalAlgebra_lt_top`), since the mixed matrix unit
`|0><2|` is outside it.  The join of all three regional algebras is the
same block-diagonal algebra (`characterCausalNet_join_all_regions`), so
the witness net does not cover its ambient private algebra
(`characterCausalNet_not_ambient_covering`).  The two maximal regions
have no common region above them, so no declared subregion family of any
region contains both
(`characterCausalNet_no_family_contains_left_and_right`); the
`{bot, left}` family covers the left region
(`characterLeftCover_coverageLaw`), the `{bot}` family does not
(`characterBotCover_not_coverageLaw`), and reconstruction is
instantiated on the covering family through the self-membered descent
packet (`characterLeftCover_reconstruction`).

The commutative witness that does cover: in the diagonal-algebra witness
net of `QFT/ObserverAccessCut.lean`, the two-region family `{{0}, {1}}`
of the full two-label region joins to the full diagonal algebra
(`witnessTwoRegionCover_familyJoin`), satisfies the coverage law
(`witnessTwoRegionCover_coverageLaw`), and reconstruction is
instantiated over the all-families descent packet
(`witnessTwoRegionCover_reconstruction`).

Claim boundary: every statement here is finite algebraic coverage over
the committed E1 interface.  No physical spacetime cover, no geometric
union of regions, no continuum limit, no instrument semantics, and no
source realization is claimed.
-/

namespace OPH.QFT

open Matrix
open OPH.Tower

universe u

variable {ι : Type u} [Preorder ι]

namespace FiniteCausalObserverNet

variable {T : ConsensusTower ι} (N : FiniteCausalObserverNet T)

/-! ## The family join and the coverage law -/

/-- The star-subalgebra join of the local algebras of one declared
subregion family, taken inside the A3 private matrix algebra at the
family's regulator. -/
noncomputable def familyJoin {r : ι} {W : N.Region r}
    (C : N.FiniteCover r W) :
    StarSubalgebra ℂ (ConsensusTower.PrivateAlgebra T r) :=
  ⨆ U ∈ C.regions, N.localAlgebra r U

/-- Every family member's local algebra is below the family join. -/
theorem le_familyJoin {r : ι} {W : N.Region r} (C : N.FiniteCover r W)
    {U : N.Region r} (hU : U ∈ C.regions) :
    N.localAlgebra r U ≤ N.familyJoin C :=
  le_iSup₂ (f := fun U (_ : U ∈ C.regions) => N.localAlgebra r U) U hU

/-- The family join is the least upper bound of the member algebras. -/
theorem familyJoin_le {r : ι} {W : N.Region r} {C : N.FiniteCover r W}
    {S : StarSubalgebra ℂ (ConsensusTower.PrivateAlgebra T r)}
    (h : ∀ U ∈ C.regions, N.localAlgebra r U ≤ S) :
    N.familyJoin C ≤ S :=
  iSup₂_le h

/-- Monotone direction from isotony alone: the family join is contained
in the covered region's local algebra.  This half needs no declared
receipt. -/
theorem familyJoin_le_covered {r : ι} {W : N.Region r}
    (C : N.FiniteCover r W) :
    N.familyJoin C ≤ N.localAlgebra r W :=
  N.familyJoin_le fun U hU => N.isotony r (C.subregion U hU)

/-- The joint-coverage receipt for one declared subregion family: the
covered region's local algebra is contained in the star-subalgebra join
of the family's local algebras.  Isotony gives the reverse containment,
so the receipt is equivalent to generation of the covered algebra by the
family (`CoverageLaw.join_eq`).  Coverage is not derivable from isotony,
locality, finiteness, or descent; it is a separate declared law, and
`characterBotCover_not_coverageLaw` below exhibits a declared family
without it. -/
structure CoverageLaw {r : ι} {W : N.Region r}
    (C : N.FiniteCover r W) : Prop where
  covered_le_join :
    N.localAlgebra r W ≤ N.familyJoin C

namespace CoverageLaw

variable {N}
variable {r : ι} {W : N.Region r} {C : N.FiniteCover r W}

/-- Coverage upgraded to the generation equality: the covered local
algebra equals the star-subalgebra join of the family's local
algebras. -/
theorem join_eq (hcov : N.CoverageLaw C) :
    N.familyJoin C = N.localAlgebra r W :=
  le_antisymm (N.familyJoin_le_covered C) hcov.covered_le_join

/-- Every element of the covered algebra lies in the family join. -/
theorem mem_join (hcov : N.CoverageLaw C) (X : N.localAlgebra r W) :
    (X : ConsensusTower.PrivateAlgebra T r) ∈ N.familyJoin C :=
  hcov.covered_le_join X.2

/-- Monotonicity: enlarging the declared family preserves the coverage
law.  This is a theorem rather than a field because it follows from the
lattice structure alone. -/
theorem mono {C' : N.FiniteCover r W} (hcov : N.CoverageLaw C)
    (hsub : C.regions ⊆ C'.regions) : N.CoverageLaw C' :=
  ⟨hcov.covered_le_join.trans
    (N.familyJoin_le fun _U hU => N.le_familyJoin C' (hsub hU))⟩

/-- Refinement naturality: the A3 refinement of any element of the
covered algebra lies in the join of the refined family algebras.  This
is the derivable direction; a full coverage law for the refined family
at the finer regulator would need surjectivity data the committed
interface does not carry, and it is not claimed. -/
theorem refine_mem {s : ι} (hrs : r ≤ s) (hcov : N.CoverageLaw C)
    {X : ConsensusTower.PrivateAlgebra T r}
    (hX : X ∈ N.localAlgebra r W) :
    T.algebraRefine hrs X ∈
      ⨆ U ∈ C.regions, N.localAlgebra s (N.regionRefine hrs U) := by
  have hle : N.familyJoin C ≤
      StarSubalgebra.comap (T.algebraRefine hrs)
        (⨆ U ∈ C.regions, N.localAlgebra s (N.regionRefine hrs U)) := by
    refine N.familyJoin_le fun U hU => ?_
    intro Y hY
    rw [StarSubalgebra.mem_comap]
    exact le_iSup₂ (f := fun U (_ : U ∈ C.regions) =>
        N.localAlgebra s (N.regionRefine hrs U)) U hU
      (N.localAlgebra_natural hrs U Y hY)
  exact hle (hcov.covered_le_join hX)

/-- **Reconstruction.**  A coverage law together with a declared descent
packet gives, for every compatible family on the cover, exactly one
globalization in the covered local algebra, and that globalization lies
in the family-generated join.  Existence and uniqueness come from the
descent packet; the join membership comes from the coverage law. -/
theorem reconstruction (hcov : N.CoverageLaw C)
    (D : N.ObserverNetDescent) (hC : D.declaredCover C)
    (F : C.CompatibleFamily) :
    ∃! X : N.localAlgebra r W, C.Globalizes F X ∧
      (X : ConsensusTower.PrivateAlgebra T r) ∈ N.familyJoin C := by
  obtain ⟨X, hX, huniq⟩ := D.unique_descent C hC F
  exact ⟨X, ⟨hX, hcov.mem_join X⟩, fun Y hY => huniq Y hY.1⟩

/-- Pointwise reconstruction: an element of the covered algebra lies in
the family-generated join and is determined by its declared restrictions
to the family.  The determination clause consumes only the descent
packet; the membership clause consumes only the coverage law. -/
theorem determined_by_restrictions (hcov : N.CoverageLaw C)
    (D : N.ObserverNetDescent) (hC : D.declaredCover C)
    (X : N.localAlgebra r W) :
    (X : ConsensusTower.PrivateAlgebra T r) ∈ N.familyJoin C ∧
      ∀ Y : N.localAlgebra r W,
        (∀ U (hU : U ∈ C.regions),
          N.restrict r (C.subregion U hU) Y =
            N.restrict r (C.subregion U hU) X) → Y = X :=
  ⟨hcov.mem_join X, fun _Y hY =>
    C.jointly_injective_of_unique_descent (D.unique_descent C hC) hY⟩

end CoverageLaw

end FiniteCausalObserverNet

/-! ## The exact join of the two block algebras inside `M₄(ℂ)`

The generated star subalgebra of the two witness block algebras is
computed rather than declared: products and sums of `diag(a, a, A)` and
`diag(B, b, b)` never leave the block-diagonal algebra with vanishing
mixed blocks, and every block-diagonal matrix splits as a sum of one
element of each block algebra. -/

/-- The block-diagonal star subalgebra of `M₄(ℂ)`: two free two-by-two
corner blocks and vanishing mixed blocks. -/
def blockDiagonalAlgebra : StarSubalgebra ℂ (Matrix (Fin 4) (Fin 4) ℂ) where
  carrier := {X | X 0 2 = 0 ∧ X 0 3 = 0 ∧ X 1 2 = 0 ∧ X 1 3 = 0 ∧
    X 2 0 = 0 ∧ X 2 1 = 0 ∧ X 3 0 = 0 ∧ X 3 1 = 0}
  zero_mem' := by simp [Set.mem_setOf_eq]
  one_mem' := by simp [Set.mem_setOf_eq]
  add_mem' := by
    intro X Y hX hY
    obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := hX
    obtain ⟨g1, g2, g3, g4, g5, g6, g7, g8⟩ := hY
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
      simp [Matrix.add_apply, h1, h2, h3, h4, h5, h6, h7, h8,
        g1, g2, g3, g4, g5, g6, g7, g8]
  mul_mem' := by
    intro X Y hX hY
    obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := hX
    obtain ⟨g1, g2, g3, g4, g5, g6, g7, g8⟩ := hY
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
      simp [Matrix.mul_apply, Fin.sum_univ_four, h1, h2, h3, h4, h5, h6,
        h7, h8, g1, g2, g3, g4, g5, g6, g7, g8]
  algebraMap_mem' := by
    intro c
    simp [Set.mem_setOf_eq, Algebra.algebraMap_eq_smul_one,
      Matrix.smul_apply]
  star_mem' := by
    intro X hX
    obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ := hX
    refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
      simp [h1, h2, h3, h4, h5, h6, h7, h8]

theorem mem_blockDiagonalAlgebra_iff {X : Matrix (Fin 4) (Fin 4) ℂ} :
    X ∈ blockDiagonalAlgebra ↔
      (X 0 2 = 0 ∧ X 0 3 = 0 ∧ X 1 2 = 0 ∧ X 1 3 = 0 ∧
        X 2 0 = 0 ∧ X 2 1 = 0 ∧ X 3 0 = 0 ∧ X 3 1 = 0) :=
  Iff.rfl

/-- The left witness block algebra sits inside the block-diagonal
algebra: its eight mixed-block constraints are shared. -/
theorem leftBlockAlgebra_le_blockDiagonal :
    leftBlockAlgebra ≤ blockDiagonalAlgebra := by
  intro X hX
  obtain ⟨_, _, _, h4, h5, h6, h7, h8, h9, h10, h11⟩ :=
    mem_leftBlockAlgebra_iff.mp hX
  exact ⟨h4, h5, h6, h7, h8, h9, h10, h11⟩

/-- The right witness block algebra sits inside the block-diagonal
algebra. -/
theorem rightBlockAlgebra_le_blockDiagonal :
    rightBlockAlgebra ≤ blockDiagonalAlgebra := by
  intro X hX
  obtain ⟨_, _, _, h4, h5, h6, h7, h8, h9, h10, h11⟩ :=
    mem_rightBlockAlgebra_iff.mp hX
  exact ⟨h4, h5, h6, h7, h8, h9, h10, h11⟩

/-- The upper two-by-two corner truncation of a dimension-four matrix. -/
def upperCorner (X : Matrix (Fin 4) (Fin 4) ℂ) :
    Matrix (Fin 4) (Fin 4) ℂ :=
  fun i j => if (i = 0 ∨ i = 1) ∧ (j = 0 ∨ j = 1) then X i j else 0

/-- The lower two-by-two corner truncation of a dimension-four matrix. -/
def lowerCorner (X : Matrix (Fin 4) (Fin 4) ℂ) :
    Matrix (Fin 4) (Fin 4) ℂ :=
  fun i j => if (i = 2 ∨ i = 3) ∧ (j = 2 ∨ j = 3) then X i j else 0

/-- The upper corner of any matrix is a right-block element with
vanishing scalar block. -/
theorem upperCorner_mem_rightBlock (X : Matrix (Fin 4) (Fin 4) ℂ) :
    upperCorner X ∈ rightBlockAlgebra := by
  refine mem_rightBlockAlgebra_iff.mpr
    ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    simp [upperCorner]

/-- The lower corner of any matrix is a left-block element with
vanishing scalar block. -/
theorem lowerCorner_mem_leftBlock (X : Matrix (Fin 4) (Fin 4) ℂ) :
    lowerCorner X ∈ leftBlockAlgebra := by
  refine mem_leftBlockAlgebra_iff.mpr
    ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩ <;>
    simp [lowerCorner]

/-- Every block-diagonal matrix is the sum of its two corner
truncations. -/
theorem eq_upperCorner_add_lowerCorner {X : Matrix (Fin 4) (Fin 4) ℂ}
    (hX : X ∈ blockDiagonalAlgebra) :
    X = upperCorner X + lowerCorner X := by
  obtain ⟨h1, h2, h3, h4, h5, h6, h7, h8⟩ :=
    mem_blockDiagonalAlgebra_iff.mp hX
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [upperCorner, lowerCorner, Matrix.add_apply,
      h1, h2, h3, h4, h5, h6, h7, h8]

/-- **The exact generated algebra.**  The star-subalgebra join of the
two witness block algebras is the block-diagonal algebra: the join is
squeezed between the two containments above and the corner
decomposition. -/
theorem leftBlock_sup_rightBlock :
    leftBlockAlgebra ⊔ rightBlockAlgebra = blockDiagonalAlgebra := by
  refine le_antisymm
    (sup_le leftBlockAlgebra_le_blockDiagonal
      rightBlockAlgebra_le_blockDiagonal) ?_
  intro X hX
  rw [eq_upperCorner_add_lowerCorner hX]
  exact add_mem
    ((le_sup_right :
        rightBlockAlgebra ≤ leftBlockAlgebra ⊔ rightBlockAlgebra)
      (upperCorner_mem_rightBlock X))
    ((le_sup_left :
        leftBlockAlgebra ≤ leftBlockAlgebra ⊔ rightBlockAlgebra)
      (lowerCorner_mem_leftBlock X))

/-- The mixed matrix unit `|0><2|` is outside the block-diagonal
algebra. -/
theorem blockUnit_zero_two_not_mem_blockDiagonal :
    blockUnit 0 2 ∉ blockDiagonalAlgebra := by
  intro h
  have h02 := (mem_blockDiagonalAlgebra_iff.mp h).1
  simp [blockUnit] at h02

/-- The generated algebra is proper: the two block algebras do not
generate all of `M₄(ℂ)`. -/
theorem blockDiagonalAlgebra_lt_top :
    blockDiagonalAlgebra <
      (⊤ : StarSubalgebra ℂ (Matrix (Fin 4) (Fin 4) ℂ)) := by
  rw [SetLike.lt_iff_le_and_exists]
  exact ⟨le_top, blockUnit 0 2, StarSubalgebra.mem_top,
    blockUnit_zero_two_not_mem_blockDiagonal⟩

/-! ## Coverage receipts on the noncommutative witness net -/

/-- The join receipt restated on the witness net's regional algebras. -/
theorem characterCausalNet_left_sup_right :
    characterCausalNet.localAlgebra () CharacterRegion.left ⊔
        characterCausalNet.localAlgebra () CharacterRegion.right =
      blockDiagonalAlgebra :=
  leftBlock_sup_rightBlock

/-- The join of all three regional algebras of the witness net is the
block-diagonal algebra: the scalar bottom algebra is absorbed. -/
theorem characterCausalNet_join_all_regions :
    (⨆ U : CharacterRegion, characterCausalNet.localAlgebra () U) =
      blockDiagonalAlgebra := by
  refine le_antisymm (iSup_le fun U => ?_) ?_
  · cases U with
    | bot => exact oneBlockPartition_publicSubalgebra_le blockDiagonalAlgebra
    | left => exact leftBlockAlgebra_le_blockDiagonal
    | right => exact rightBlockAlgebra_le_blockDiagonal
  · rw [← leftBlock_sup_rightBlock]
    exact sup_le
      (le_iSup (fun U : CharacterRegion =>
        characterCausalNet.localAlgebra () U) CharacterRegion.left)
      (le_iSup (fun U : CharacterRegion =>
        characterCausalNet.localAlgebra () U) CharacterRegion.right)

/-- **Negative coverage finding.**  The witness net does not cover its
ambient private algebra: the join of every regional algebra is strictly
below `M₄(ℂ)`.  The declared regions of this net can generate at most
the block-diagonal algebra. -/
theorem characterCausalNet_not_ambient_covering :
    (⨆ U : CharacterRegion, characterCausalNet.localAlgebra () U) <
      (⊤ : StarSubalgebra ℂ
        (ConsensusTower.PrivateAlgebra characterTower ())) := by
  rw [characterCausalNet_join_all_regions]
  exact blockDiagonalAlgebra_lt_top

/-- The two maximal witness regions have no common region above them. -/
theorem CharacterRegion.left_right_no_upper_bound :
    ¬ ∃ W : CharacterRegion,
        CharacterRegion.le CharacterRegion.left W ∧
          CharacterRegion.le CharacterRegion.right W := by
  decide

/-- Consequently no declared subregion family of any witness region
contains both maximal regions: the `{bot, left, right}` family is not a
`FiniteCover` of any region of this net. -/
theorem characterCausalNet_no_family_contains_left_and_right
    {W : CharacterRegion}
    (C : characterCausalNet.FiniteCover () W) :
    ¬ (CharacterRegion.left ∈ C.regions ∧
        CharacterRegion.right ∈ C.regions) := by
  rintro ⟨hl, hr⟩
  exact CharacterRegion.left_right_no_upper_bound
    ⟨W, C.subregion CharacterRegion.left hl,
      C.subregion CharacterRegion.right hr⟩

/-- The two-member family `{bot, left}` under the left region. -/
noncomputable def characterLeftCover :
    characterCausalNet.FiniteCover () CharacterRegion.left where
  regions :=
    ({CharacterRegion.bot, CharacterRegion.left} : Finset CharacterRegion)
  nonempty := by
    refine ⟨CharacterRegion.bot, ?_⟩
    change CharacterRegion.bot ∈
      ({CharacterRegion.bot, CharacterRegion.left} :
        Finset CharacterRegion)
    simp
  subregion (U : CharacterRegion) hU := by
    change U ∈ ({CharacterRegion.bot, CharacterRegion.left} :
      Finset CharacterRegion) at hU
    have h : U = CharacterRegion.bot ∨ U = CharacterRegion.left := by
      simpa using hU
    rcases h with rfl | rfl
    · exact Or.inr rfl
    · exact Or.inl rfl

/-- The left region is a member of its own two-member family. -/
theorem characterLeftCover_mem_left :
    CharacterRegion.left ∈ characterLeftCover.regions := by
  change CharacterRegion.left ∈
    ({CharacterRegion.bot, CharacterRegion.left} : Finset CharacterRegion)
  simp

/-- The family join of `{bot, left}` is exactly the left block algebra:
the scalar bottom algebra is absorbed. -/
theorem characterLeftCover_familyJoin :
    characterCausalNet.familyJoin characterLeftCover =
      leftBlockAlgebra := by
  refine le_antisymm
    (characterCausalNet.familyJoin_le fun (U : CharacterRegion) hU => ?_)
    (characterCausalNet.le_familyJoin characterLeftCover
      (U := CharacterRegion.left) characterLeftCover_mem_left)
  change U ∈ ({CharacterRegion.bot, CharacterRegion.left} :
    Finset CharacterRegion) at hU
  have h : U = CharacterRegion.bot ∨ U = CharacterRegion.left := by
    simpa using hU
  rcases h with rfl | rfl
  · exact oneBlockPartition_publicSubalgebra_le leftBlockAlgebra
  · exact le_rfl

/-- The `{bot, left}` family satisfies the coverage law for the left
region: the covered algebra is one of the family algebras. -/
theorem characterLeftCover_coverageLaw :
    characterCausalNet.CoverageLaw characterLeftCover :=
  ⟨characterCausalNet.le_familyJoin characterLeftCover
    (U := CharacterRegion.left) characterLeftCover_mem_left⟩

/-- The singleton family `{bot}` under the left region. -/
noncomputable def characterBotCover :
    characterCausalNet.FiniteCover () CharacterRegion.left where
  regions := ({CharacterRegion.bot} : Finset CharacterRegion)
  nonempty := by
    refine ⟨CharacterRegion.bot, ?_⟩
    change CharacterRegion.bot ∈
      ({CharacterRegion.bot} : Finset CharacterRegion)
    simp
  subregion (U : CharacterRegion) hU := by
    change U ∈ ({CharacterRegion.bot} : Finset CharacterRegion) at hU
    have h : U = CharacterRegion.bot := by simpa using hU
    subst h
    exact Or.inr rfl

/-- **Negative control.**  The `{bot}` family does not satisfy the
coverage law for the left region: its join is the scalar algebra, and
the left block algebra contains the nonscalar unit `|2><3|`.  Coverage
is therefore a genuine declared receipt, separate from the `FiniteCover`
data. -/
theorem characterBotCover_not_coverageLaw :
    ¬ characterCausalNet.CoverageLaw characterBotCover := by
  intro hcov
  have hjoin : characterCausalNet.familyJoin characterBotCover ≤
      (oneBlockPartition 4).publicSubalgebra := by
    refine characterCausalNet.familyJoin_le
      fun (U : CharacterRegion) hU => ?_
    change U ∈ ({CharacterRegion.bot} : Finset CharacterRegion) at hU
    have h : U = CharacterRegion.bot := by simpa using hU
    subst h
    exact le_rfl
  have hmem : blockUnit 2 3 ∈ (oneBlockPartition 4).publicSubalgebra :=
    hjoin (hcov.covered_le_join blockUnit_two_three_mem_left)
  obtain ⟨c, hc⟩ := (oneBlockPartition_mem_iff _).mp hmem
  have h23 := congrFun (congrFun hc 2) 3
  simp [blockUnit, Matrix.smul_apply] at h23

/-! ## A descent packet for self-membered families on the witness net -/

/-- Every subregion family of the witness net that contains its own
covered region has unique descent: the section at the covered region is
the glue, and the character restrictions to the bottom region are pinned
by overlap compatibility. -/
theorem characterCausalNet_hasUniqueDescent_of_mem
    {W : CharacterRegion}
    (C : characterCausalNet.FiniteCover () W)
    (hW : W ∈ C.regions) : C.HasUniqueDescent := by
  cases W with
  | bot =>
      intro F
      refine ⟨F.localSection CharacterRegion.bot hW, ?_, ?_⟩
      · intro U hU
        have hle : CharacterRegion.le U CharacterRegion.bot :=
          C.subregion U hU
        have h : U = CharacterRegion.bot := by
          rcases hle with h | h <;> exact h
        subst h
        rfl
      · intro X hX
        exact hX CharacterRegion.bot hW
  | left =>
      intro F
      refine ⟨F.localSection CharacterRegion.left hW, ?_, ?_⟩
      · intro U hU
        have hle : CharacterRegion.le U CharacterRegion.left :=
          C.subregion U hU
        rcases hle with h | h
        · subst h
          rfl
        · subst h
          exact (F.overlap_compatible CharacterRegion.bot hU
            CharacterRegion.left hW).symm
      · intro X hX
        exact hX CharacterRegion.left hW
  | right =>
      intro F
      refine ⟨F.localSection CharacterRegion.right hW, ?_, ?_⟩
      · intro U hU
        have hle : CharacterRegion.le U CharacterRegion.right :=
          C.subregion U hU
        rcases hle with h | h
        · subst h
          rfl
        · subst h
          exact (F.overlap_compatible CharacterRegion.bot hU
            CharacterRegion.right hW).symm
      · intro X hX
        exact hX CharacterRegion.right hW

/-- The declared descent packet of the witness net: exactly the families
that contain their own covered region.  It contains every singleton
identity family, so the nonvacuity obligation is met, and it contains
`characterLeftCover`. -/
noncomputable def characterSelfDescent :
    characterCausalNet.ObserverNetDescent where
  declaredCover := fun {_r} {W} C => W ∈ C.regions
  cover_exists := fun r W =>
    ⟨characterCausalNet.singletonCover r W, by
      simp [FiniteCausalObserverNet.singletonCover]⟩
  unique_descent := fun {_r} {_W} C hC =>
    characterCausalNet_hasUniqueDescent_of_mem C hC

/-- Reconstruction instantiated on the noncommutative witness: every
compatible family on `{bot, left}` has exactly one globalization in the
left block algebra, and the globalization lies in the family join. -/
theorem characterLeftCover_reconstruction
    (F : characterLeftCover.CompatibleFamily) :
    ∃! X : characterCausalNet.localAlgebra () CharacterRegion.left,
      characterLeftCover.Globalizes F X ∧
        (X : ConsensusTower.PrivateAlgebra characterTower ()) ∈
          characterCausalNet.familyJoin characterLeftCover :=
  characterLeftCover_coverageLaw.reconstruction characterSelfDescent
    characterLeftCover_mem_left F

/-! ## A commutative inhabitant that does cover -/

/-- The two-region family `{{0}, {1}}` of the full two-label region in
the diagonal-algebra witness net of `QFT/ObserverAccessCut.lean`. -/
noncomputable def witnessTwoRegionCover :
    witnessNet.FiniteCover () ({0, 1} : Finset (Fin 2)) where
  regions :=
    ({({0} : Finset (Fin 2)), ({1} : Finset (Fin 2))} :
      Finset (Finset (Fin 2)))
  nonempty := by
    refine ⟨({0} : Finset (Fin 2)), ?_⟩
    change ({0} : Finset (Fin 2)) ∈
      ({({0} : Finset (Fin 2)), ({1} : Finset (Fin 2))} :
        Finset (Finset (Fin 2)))
    simp
  subregion (U : Finset (Fin 2)) _ := by
    change U ⊆ ({0, 1} : Finset (Fin 2))
    intro x hx
    fin_cases x <;> simp

theorem witnessTwoRegionCover_mem_left :
    ({0} : Finset (Fin 2)) ∈ witnessTwoRegionCover.regions := by
  change ({0} : Finset (Fin 2)) ∈
    ({({0} : Finset (Fin 2)), ({1} : Finset (Fin 2))} :
      Finset (Finset (Fin 2)))
  simp

/-- The witness family joins to the full diagonal algebra: every member
algebra and the covered algebra are the same commutative diagonal
algebra, so the join receipt holds with equality. -/
theorem witnessTwoRegionCover_familyJoin :
    witnessNet.familyJoin witnessTwoRegionCover =
      (diagonalPartition 2).publicSubalgebra := by
  refine le_antisymm
    (witnessNet.familyJoin_le fun U hU => le_rfl) ?_
  exact witnessNet.le_familyJoin witnessTwoRegionCover
    witnessTwoRegionCover_mem_left

/-- The commutative witness family satisfies the coverage law. -/
theorem witnessTwoRegionCover_coverageLaw :
    witnessNet.CoverageLaw witnessTwoRegionCover :=
  ⟨witnessTwoRegionCover_familyJoin.ge⟩

/-- Reconstruction instantiated end to end on the commutative witness,
over the all-families descent packet of `QFT/ObserverAccessCut.lean`. -/
theorem witnessTwoRegionCover_reconstruction
    (F : witnessTwoRegionCover.CompatibleFamily) :
    ∃! X : witnessNet.localAlgebra () ({0, 1} : Finset (Fin 2)),
      witnessTwoRegionCover.Globalizes F X ∧
        (X : ConsensusTower.PrivateAlgebra witnessTower ()) ∈
          witnessNet.familyJoin witnessTwoRegionCover :=
  witnessTwoRegionCover_coverageLaw.reconstruction
    witnessAllCoversDescent trivial F

end OPH.QFT

-- Axiom audit: no project-specific axiom or admission is permitted here.
#print axioms OPH.QFT.FiniteCausalObserverNet.familyJoin_le_covered
#print axioms OPH.QFT.FiniteCausalObserverNet.CoverageLaw.join_eq
#print axioms OPH.QFT.FiniteCausalObserverNet.CoverageLaw.mono
#print axioms OPH.QFT.FiniteCausalObserverNet.CoverageLaw.refine_mem
#print axioms OPH.QFT.FiniteCausalObserverNet.CoverageLaw.reconstruction
#print axioms OPH.QFT.FiniteCausalObserverNet.CoverageLaw.determined_by_restrictions
#print axioms OPH.QFT.leftBlock_sup_rightBlock
#print axioms OPH.QFT.blockDiagonalAlgebra_lt_top
#print axioms OPH.QFT.characterCausalNet_left_sup_right
#print axioms OPH.QFT.characterCausalNet_join_all_regions
#print axioms OPH.QFT.characterCausalNet_not_ambient_covering
#print axioms OPH.QFT.CharacterRegion.left_right_no_upper_bound
#print axioms OPH.QFT.characterCausalNet_no_family_contains_left_and_right
#print axioms OPH.QFT.characterLeftCover_familyJoin
#print axioms OPH.QFT.characterLeftCover_coverageLaw
#print axioms OPH.QFT.characterBotCover_not_coverageLaw
#print axioms OPH.QFT.characterCausalNet_hasUniqueDescent_of_mem
#print axioms OPH.QFT.characterLeftCover_reconstruction
#print axioms OPH.QFT.witnessTwoRegionCover_familyJoin
#print axioms OPH.QFT.witnessTwoRegionCover_coverageLaw
#print axioms OPH.QFT.witnessTwoRegionCover_reconstruction
