import QFT.SourceHistoryExpectationNet

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# An enlarged-target record embedding for the source-history carrier

The committed matrix no-go of `QFT.SourceHistoryExpectationNet` has a fixed
and narrow scope: on the eight-history carrier there is no complex-linear
map with range in the slot-`(0,1)` interval algebra `algebra01` that obeys
the `algebra01`-bimodule law and preserves the committed source state.  The
audited scope names enlarged targets, ancillas, generalized or non-bimodule
maps, and alternate states as live alternatives.  This module takes the
enlarged-target path and constructs it.

Construction.  The enlarged carrier is `M₈(ℂ) ⊗ M₂(ℂ)`, indexed by
`Fin 8 × Spin`; the enlarged target is the star subalgebra generated by the
ampliated interval algebra `algebra01 ⊗ 1` and the ancilla factor
`1 ⊗ M₂(ℂ)`.  The record embedding `M₈(ℂ) → M₈(ℂ) ⊗ M₂(ℂ)` reads the
slot-two record bit of each history into the ancilla: it relabels the three
history slots, adjoins the ancilla factor, and swaps the slot-two tensor
factor with the ancilla factor.  It is a unital injective star-algebra
homomorphism whose range is exactly the enlarged target.

Clause comparison with the committed obstruction, clause for clause:
* range: the committed clause `E X ∈ algebra01` becomes
  `E X ∈ enlargedTarget`; this is the single enlarged clause;
* bimodule: the clause quantifies over the same committed `algebra01`,
  acting through the canonical ampliation `B ↦ B ⊗ 1`; on `algebra01` the
  record embedding coincides with the ampliation, so the transported clause
  holds with the same interval algebra on both sides;
* state: the exhibited enlarged state is the diagonal density pairing each
  history with a copy of its own slot-two bit in the ancilla; its
  restriction along the ampliation is exactly the committed source state,
  and the record embedding preserves it.

Two delimiting theorems establish two necessary features of this escape.
First, for every
ancilla matrix `σ` the product functional `Tr((ρ ⊗ σ) · )` admits no map
satisfying the three transported clauses: enlarging the target while
keeping a product-form state extension keeps the obstruction.  Second, a
map whose range lies in the ampliated copy `algebra01 ⊗ 1` is obstructed
even against the exhibited correlated state: the ancilla factor must be
used.  Within this clause family, target enlargement and some non-product
state extension are therefore necessary.  The exhibited record-correlated
extension is one witness; it is not proved to be the unique such extension.

The ancilla dimension is two.  The ancilla-free instance of the clause
list is the committed fixed-target obstruction, reading the dimension-one
instance `M₈(ℂ) ⊗ M₁(ℂ)` through the canonical identification with
`M₈(ℂ)`; that identification is stated here as prose, without a
formalized transport.  Dimension two is therefore the least ancilla
dimension in this tensor-factor family for which the clause list is
inhabited; a minimality statement quantifying over arbitrary enlarged
targets is left open.

Boundary.  This is a finite-matrix existence statement on the committed
eight-history packet.  Slots are retained-window positions.  No region
system, no ordered family of algebra embeddings, no time-slice statement,
no locality axiom, no AQFT net claim, no dynamics, no continuum limit, and
no physical detector or clock is constructed here.  The enlarged state is
one exhibited extension; uniqueness of the extension is neither claimed
nor proved.
-/

namespace OPH.QFT.EnlargedTargetRecordEmbedding

open Matrix
open Kronecker
open OPH.QFT
open OPH.InformationProjection
open OPH.QFT.FiniteTwoSiteIsingField
open OPH.QFT.SourceHistoryGNSDynamics
open OPH.QFT.SourceHistoryThreeSlotLocalGNS
open OPH.QFT.SourceHistoryExpectationNet

open scoped ComplexOrder

noncomputable section

/-! ## The enlarged carrier and its two canonical factor embeddings -/

/-- The enlarged index: a retained history together with one ancilla bit. -/
abbrev EnlargedIndex := Fin 8 × Spin

/-- The enlarged carrier `M₈(ℂ) ⊗ M₂(ℂ)`. -/
abbrev EnlargedHistoryMatrix := Matrix EnlargedIndex EnlargedIndex ℂ

/-- The ancilla dimension of the enlargement is two. -/
theorem ancilla_dimension_two : Fintype.card Spin = 2 := rfl

/-- The canonical ampliation `X ↦ X ⊗ 1` of the source carrier into the
enlarged carrier. -/
def ampliation : HistoryMatrix →⋆ₐ[ℂ] EnlargedHistoryMatrix :=
  slotLeft Spin (α := Fin 8)

/-- The ancilla factor embedding `C ↦ 1 ⊗ C`. -/
def ancillaSlot : SpinMatrix →⋆ₐ[ℂ] EnlargedHistoryMatrix :=
  slotRight (Fin 8) (β := Spin)

theorem ampliation_apply (X : HistoryMatrix) :
    ampliation X = X ⊗ₖ (1 : SpinMatrix) := rfl

theorem ancillaSlot_apply (C : SpinMatrix) :
    ancillaSlot C = (1 : HistoryMatrix) ⊗ₖ C := rfl

/-! ## The record embedding -/

/-- The index involution exchanging the slot-two coordinate with the
ancilla coordinate. -/
def slotSwap : (ThreeSlotIndex × Spin) ≃ (ThreeSlotIndex × Spin) where
  toFun z := ((z.1.1, z.2), z.1.2)
  invFun z := ((z.1.1, z.2), z.1.2)
  left_inv _ := rfl
  right_inv _ := rfl

/-- The slot-two/ancilla swap on the four-factor matrix algebra. -/
def swapStageEquiv :
    Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ ≃⋆ₐ[ℂ]
      Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ :=
  StarAlgEquiv.ofAlgEquiv (Matrix.reindexAlgEquiv ℂ ℂ slotSwap)
    (fun M => by
      simp only [Matrix.reindexAlgEquiv_apply, Matrix.star_eq_conjTranspose]
      exact reindex_conjTranspose slotSwap M)

@[simp]
theorem swapStageEquiv_apply
    (M : Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ) :
    swapStageEquiv M = Matrix.reindex slotSwap slotSwap M := rfl

/-- The index identification collapsing the three history slots back onto
the `Fin 8` carrier, with the ancilla coordinate carried along. -/
def enlargedIndexEquiv : (ThreeSlotIndex × Spin) ≃ EnlargedIndex :=
  Equiv.prodCongr historyEquiv (Equiv.refl Spin)

/-- The reindexing star equivalence for the enlarged carrier. -/
def enlargedStageEquiv :
    Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ ≃⋆ₐ[ℂ]
      EnlargedHistoryMatrix :=
  StarAlgEquiv.ofAlgEquiv (Matrix.reindexAlgEquiv ℂ ℂ enlargedIndexEquiv)
    (fun M => by
      simp only [Matrix.reindexAlgEquiv_apply, Matrix.star_eq_conjTranspose]
      exact reindex_conjTranspose enlargedIndexEquiv M)

@[simp]
theorem enlargedStageEquiv_apply
    (M : Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ) :
    enlargedStageEquiv M = Matrix.reindex enlargedIndexEquiv enlargedIndexEquiv M :=
  rfl

/-- **The record embedding.**  Relabel the three history slots, adjoin the
ancilla factor on the right, swap the slot-two factor with the ancilla
factor, and read the first three coordinates back as the source carrier.
The slot-two record bit of each history is thereby carried by the ancilla
factor. -/
def recordEmbedding : HistoryMatrix →⋆ₐ[ℂ] EnlargedHistoryMatrix :=
  ((enlargedStageEquiv :
      Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ →⋆ₐ[ℂ]
        EnlargedHistoryMatrix).comp
    ((swapStageEquiv :
        Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ →⋆ₐ[ℂ]
          Matrix (ThreeSlotIndex × Spin) (ThreeSlotIndex × Spin) ℂ).comp
      (slotLeft Spin (α := ThreeSlotIndex)))).comp
    (historyStageEquiv.symm : HistoryMatrix →⋆ₐ[ℂ] ThreeSlotMatrix)

/-! ## The enlarged target `algebra01 ⊗ M₂(ℂ)` -/

/-- The enlarged target: the star subalgebra generated by the ampliated
interval algebra and the ancilla factor. -/
def enlargedTarget : StarSubalgebra ℂ EnlargedHistoryMatrix :=
  (algebra01.map ampliation) ⊔ ancillaSlot.range

theorem ampliation_map_le_enlargedTarget :
    algebra01.map ampliation ≤ enlargedTarget := le_sup_left

theorem ancillaSlot_range_le_enlargedTarget :
    ancillaSlot.range ≤ enlargedTarget := le_sup_right

/-! ## The kronecker factorization of the record embedding -/

/-- Swapping the last two tensor factors of `(P ⊗ C) ⊗ 1` produces
`(P ⊗ 1) ⊗ C`. -/
theorem swap_pair_kronecker (P : Matrix (Spin × Spin) (Spin × Spin) ℂ)
    (C : SpinMatrix) :
    swapStageEquiv ((P ⊗ₖ C) ⊗ₖ (1 : SpinMatrix))
      = (P ⊗ₖ (1 : SpinMatrix)) ⊗ₖ C := by
  ext z z'
  obtain ⟨⟨p, t⟩, s⟩ := z
  obtain ⟨⟨p', t'⟩, s'⟩ := z'
  rw [swapStageEquiv_apply, Matrix.reindex_apply, Matrix.submatrix_apply]
  have hz : slotSwap.symm ((p, t), s) = ((p, s), t) := rfl
  have hz' : slotSwap.symm ((p', t'), s') = ((p', s'), t') := rfl
  rw [hz, hz']
  simp only [Matrix.kroneckerMap_apply]
  ring

/-- **Master factorization.**  On a slot-pair/slot-two kronecker product the
record embedding is the product of the ampliated interval element and the
ancilla element: the slot-two factor moves into the ancilla. -/
theorem recordEmbedding_stage_kronecker
    (P : Matrix (Spin × Spin) (Spin × Spin) ℂ) (C : SpinMatrix) :
    recordEmbedding (historyStageEquiv (P ⊗ₖ C))
      = ampliation (pair01 P) * ancillaSlot C := by
  have h1 : recordEmbedding (historyStageEquiv (P ⊗ₖ C))
      = enlargedStageEquiv (swapStageEquiv ((P ⊗ₖ C) ⊗ₖ (1 : SpinMatrix))) := by
    show enlargedStageEquiv (swapStageEquiv (slotLeft Spin
      (historyStageEquiv.symm (historyStageEquiv (P ⊗ₖ C))))) = _
    rw [StarAlgEquiv.symm_apply_apply]
    rfl
  have h4 : ampliation (pair01 P) * ancillaSlot C = pair01 P ⊗ₖ C := by
    rw [ampliation_apply, ancillaSlot_apply, ← Matrix.mul_kronecker_mul,
      mul_one, one_mul]
  have hp : pair01 P = historyStageEquiv (P ⊗ₖ (1 : SpinMatrix)) := rfl
  rw [h1, swap_pair_kronecker, h4, hp]
  ext z z'
  obtain ⟨g, b⟩ := z
  obtain ⟨g', b'⟩ := z'
  rw [enlargedStageEquiv_apply, Matrix.reindex_apply, Matrix.submatrix_apply]
  have hz : enlargedIndexEquiv.symm (g, b) = (historyEquiv.symm g, b) := rfl
  have hz' : enlargedIndexEquiv.symm (g', b') = (historyEquiv.symm g', b') := rfl
  rw [hz, hz']
  simp only [Matrix.kroneckerMap_apply, historyStageEquiv_apply,
    Matrix.reindex_apply, Matrix.submatrix_apply]

/-- The record embedding coincides with the ampliation on every slot-pair
element. -/
theorem recordEmbedding_pair01 (P : Matrix (Spin × Spin) (Spin × Spin) ℂ) :
    recordEmbedding (pair01 P) = ampliation (pair01 P) := by
  have hp : pair01 P = historyStageEquiv (P ⊗ₖ (1 : SpinMatrix)) := rfl
  conv_lhs => rw [hp]
  rw [recordEmbedding_stage_kronecker, map_one, mul_one]

/-- The ancilla factor lies in the range of the record embedding. -/
theorem ancillaSlot_eq_recordEmbedding (C : SpinMatrix) :
    recordEmbedding (historyStageEquiv
      ((1 : Matrix (Spin × Spin) (Spin × Spin) ℂ) ⊗ₖ C)) = ancillaSlot C := by
  rw [recordEmbedding_stage_kronecker, map_one, map_one, one_mul]

/-! ## The interval algebra is exactly the slot-pair range -/

/-- A kronecker product of one-slot elements maps to the product of the two
site embeddings. -/
theorem pair01_kronecker (A B : SpinMatrix) :
    pair01 (A ⊗ₖ B) = slot0 A * slot1 B := by
  rw [slot0_eq_pair01, slot1_eq_pair01, ← map_mul]
  congr 1
  show A ⊗ₖ B = A ⊗ₖ (1 : SpinMatrix) * ((1 : SpinMatrix) ⊗ₖ B)
  rw [← Matrix.mul_kronecker_mul, mul_one, one_mul]

/-- Every slot-pair element lies in the interval algebra: the converse of
the committed `algebra01_le_pair01_range`. -/
theorem pair01_mem_algebra01 (M : Matrix (Spin × Spin) (Spin × Spin) ℂ) :
    pair01 M ∈ algebra01 := by
  rw [Matrix.matrix_eq_sum_single M]
  simp only [map_sum]
  refine sum_mem fun z _ => sum_mem fun z' _ => ?_
  obtain ⟨u, v⟩ := z
  obtain ⟨u', v'⟩ := z'
  have hfac : Matrix.single ((u, v) : Spin × Spin) (u', v') (M (u, v) (u', v'))
      = Matrix.single u u' (M (u, v) (u', v')) ⊗ₖ Matrix.single v v' (1 : ℂ) := by
    rw [Matrix.single_kronecker_single, mul_one]
  rw [hfac, pair01_kronecker]
  exact mul_mem (algebra0_le_algebra01 ⟨_, rfl⟩) (algebra1_le_algebra01 ⟨_, rfl⟩)

/-- The interval algebra is exactly the slot-pair range. -/
theorem algebra01_eq_pair01_range : algebra01 = pair01.range := by
  refine le_antisymm algebra01_le_pair01_range ?_
  rintro X ⟨M, rfl⟩
  exact pair01_mem_algebra01 M

/-- On the committed interval algebra the record embedding is the canonical
ampliation. -/
theorem recordEmbedding_agrees_on_algebra01 :
    ∀ B ∈ algebra01, recordEmbedding B = ampliation B := by
  intro B hB
  obtain ⟨P, rfl⟩ := algebra01_le_pair01_range hB
  exact recordEmbedding_pair01 P

/-! ## Range and bimodule clauses -/

/-- **Range clause.**  The record embedding lands in the enlarged target. -/
theorem recordEmbedding_mem_enlargedTarget (X : HistoryMatrix) :
    recordEmbedding X ∈ enlargedTarget := by
  obtain ⟨T, rfl⟩ : ∃ T, X = historyStageEquiv T :=
    ⟨historyStageEquiv.symm X,
      (StarAlgEquiv.apply_symm_apply historyStageEquiv X).symm⟩
  rw [Matrix.matrix_eq_sum_single T]
  simp only [map_sum]
  refine sum_mem fun z _ => sum_mem fun z' _ => ?_
  obtain ⟨p, s⟩ := z
  obtain ⟨p', s'⟩ := z'
  have hfac : Matrix.single ((p, s) : ThreeSlotIndex) (p', s') (T (p, s) (p', s'))
      = Matrix.single p p' (T (p, s) (p', s')) ⊗ₖ Matrix.single s s' (1 : ℂ) := by
    rw [Matrix.single_kronecker_single, mul_one]
  rw [hfac, recordEmbedding_stage_kronecker]
  exact mul_mem
    (ampliation_map_le_enlargedTarget ⟨_, pair01_mem_algebra01 _, rfl⟩)
    (ancillaSlot_range_le_enlargedTarget ⟨_, rfl⟩)

/-- The range of the record embedding is exactly the enlarged target. -/
theorem recordEmbedding_range_eq : recordEmbedding.range = enlargedTarget := by
  refine le_antisymm ?_ (sup_le ?_ ?_)
  · rintro Y ⟨X, rfl⟩
    exact recordEmbedding_mem_enlargedTarget X
  · rintro Y ⟨B, hB, rfl⟩
    exact ⟨B, recordEmbedding_agrees_on_algebra01 B hB⟩
  · rintro Y ⟨C, rfl⟩
    exact ⟨historyStageEquiv ((1 : Matrix (Spin × Spin) (Spin × Spin) ℂ) ⊗ₖ C),
      ancillaSlot_eq_recordEmbedding C⟩

/-- **Bimodule clause.**  The record embedding is `algebra01`-bimodular
through the canonical ampliation: the quantification is over the same
committed interval algebra as in the obstructed conjunction. -/
theorem recordEmbedding_bimodule :
    ∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
      recordEmbedding (B * X * B')
        = ampliation B * recordEmbedding X * ampliation B' := by
  intro B hB B' hB' X
  rw [map_mul, map_mul, recordEmbedding_agrees_on_algebra01 B hB,
    recordEmbedding_agrees_on_algebra01 B' hB']

/-! ## The entrywise formula and injectivity -/

/-- The history obtained from `h` by replacing its slot-two bit with `a`. -/
def readout (h : Fin 8) (a : Spin) : Fin 8 :=
  historyEquiv ((historyEquiv.symm h).1, a)

theorem historyEquiv_symm_apply (g : Fin 8) :
    historyEquiv.symm g = ((sourceState0 g, sourceState1 g), sourceState2 g) :=
  rfl

/-- Reinstalling the recorded slot-two bit recovers the history. -/
theorem readout_slot2 (h : Fin 8) : readout h (sourceState2 h) = h := by
  unfold readout
  have hpair : (((historyEquiv.symm h).1, sourceState2 h) : ThreeSlotIndex)
      = historyEquiv.symm h := rfl
  rw [hpair, Equiv.apply_symm_apply]

/-- The slot-two bit of a readout is the installed bit. -/
theorem sourceState2_readout (h : Fin 8) (a : Spin) :
    sourceState2 (readout h a) = a := by
  unfold readout
  calc sourceState2 (historyEquiv ((historyEquiv.symm h).1, a))
      = (historyEquiv.symm (historyEquiv ((historyEquiv.symm h).1, a))).2 := rfl
    _ = a := by rw [Equiv.symm_apply_apply]

/-- Readout only consults the slot-pair coordinates. -/
theorem readout_readout (g : Fin 8) (b a : Spin) :
    readout (readout g b) a = readout g a := by
  unfold readout
  rw [Equiv.symm_apply_apply]

/-- Histories `2` and `3` share their slot-pair coordinates, so they share
all readouts. -/
theorem readout_two_eq_three (a : Spin) :
    readout (2 : Fin 8) a = readout (3 : Fin 8) a := by
  unfold readout
  have h23 : (historyEquiv.symm (2 : Fin 8)).1
      = (historyEquiv.symm (3 : Fin 8)).1 := by decide
  rw [h23]

/-- **Entrywise formula.**  The record embedding pairs the slot-two record
bit with the ancilla coordinate and evaluates the source observable at the
readout histories. -/
theorem recordEmbedding_apply (X : HistoryMatrix) (h h' : Fin 8) (a a' : Spin) :
    recordEmbedding X (h, a) (h', a')
      = if sourceState2 h = sourceState2 h'
          then X (readout h a) (readout h' a') else 0 := by
  have hT : ∀ z z' : ThreeSlotIndex,
      historyStageEquiv.symm X z z' = X (historyEquiv z) (historyEquiv z') := by
    intro z z'
    conv_rhs => rw [← StarAlgEquiv.apply_symm_apply historyStageEquiv X]
    rw [historyStageEquiv_apply, Matrix.reindex_apply, Matrix.submatrix_apply,
      Equiv.symm_apply_apply, Equiv.symm_apply_apply]
  show enlargedStageEquiv (swapStageEquiv (slotLeft Spin
      (historyStageEquiv.symm X))) (h, a) (h', a') = _
  rw [enlargedStageEquiv_apply, Matrix.reindex_apply, Matrix.submatrix_apply,
    swapStageEquiv_apply, Matrix.reindex_apply, Matrix.submatrix_apply]
  have hidx : ∀ (g : Fin 8) (b : Spin),
      slotSwap.symm (enlargedIndexEquiv.symm (g, b))
        = (((historyEquiv.symm g).1, b), (historyEquiv.symm g).2) := by
    intro g b
    rfl
  rw [hidx, hidx]
  show historyStageEquiv.symm X ((historyEquiv.symm h).1, a)
        ((historyEquiv.symm h').1, a')
      * (1 : SpinMatrix) (historyEquiv.symm h).2 (historyEquiv.symm h').2 = _
  rw [hT, Matrix.one_apply]
  have hs : (historyEquiv.symm h).2 = sourceState2 h := rfl
  have hs' : (historyEquiv.symm h').2 = sourceState2 h' := rfl
  rw [hs, hs']
  unfold readout
  rw [mul_ite, mul_one, mul_zero]

/-- The record embedding is injective: the construction is an embedding of
the full source carrier. -/
theorem recordEmbedding_injective : Function.Injective recordEmbedding := by
  intro X Y hXY
  ext g g'
  have h1 := congrFun (congrFun hXY (readout g 0, sourceState2 g))
    (readout g' 0, sourceState2 g')
  rw [recordEmbedding_apply, recordEmbedding_apply,
    sourceState2_readout, sourceState2_readout, if_pos rfl, if_pos rfl,
    readout_readout, readout_readout, readout_slot2, readout_slot2] at h1
  exact h1

/-! ## The correlated state extension -/

/-- The enlarged diagonal weight: a history carries its committed empirical
weight exactly on the ancilla value equal to its own slot-two bit. -/
def enlargedWeight (z : EnlargedIndex) : ℂ :=
  if z.2 = sourceState2 z.1 then ((sourceTauEmpR z.1 : ℝ) : ℂ) else 0

/-- The exhibited state on the enlarged carrier: the diagonal density
correlating each history with a copy of its slot-two record bit. -/
def enlargedDensity : EnlargedHistoryMatrix :=
  Matrix.diagonal enlargedWeight

/-- The trace pairing with the exhibited enlarged density. -/
def enlargedExpectation (M : EnlargedHistoryMatrix) : ℂ :=
  (enlargedDensity * M).trace

/-- The committed expectation is the trace pairing with the committed
density; the enlarged functional mirrors this shape. -/
theorem source_expectation_eq_trace (X : HistoryMatrix) :
    EventAlgebra.expectation sourceHistoryDensity X
      = (sourceHistoryDensity * X).trace := rfl

/-- The trace pairing of a diagonal density with any observable. -/
theorem diagonal_mul_trace {ι : Type} [Fintype ι] [DecidableEq ι]
    (d : ι → ℂ) (M : Matrix ι ι ℂ) :
    (Matrix.diagonal d * M).trace = ∑ i, d i * M i i := by
  unfold Matrix.trace
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [Matrix.diag_apply, Matrix.diagonal_mul]

theorem enlargedExpectation_eq_sum (M : EnlargedHistoryMatrix) :
    enlargedExpectation M
      = ∑ h : Fin 8, ∑ a : Spin, enlargedWeight (h, a) * M (h, a) (h, a) := by
  unfold enlargedExpectation enlargedDensity
  rw [diagonal_mul_trace, Fintype.sum_prod_type]

theorem source_expectation_eq_sum (X : HistoryMatrix) :
    EventAlgebra.expectation sourceHistoryDensity X
      = ∑ g : Fin 8, ((sourceTauEmpR g : ℝ) : ℂ) * X g g := by
  rw [source_expectation_eq_trace, sourceHistoryDensity, diagonal_mul_trace]

/-- Collapsing the ancilla sum against the correlated weight. -/
theorem enlargedWeight_collapse (h : Fin 8) (f : Spin → ℂ) :
    ∑ a : Spin, enlargedWeight (h, a) * f a
      = ((sourceTauEmpR h : ℝ) : ℂ) * f (sourceState2 h) := by
  unfold enlargedWeight
  simp only [ite_mul, zero_mul]
  exact Fintype.sum_ite_eq' (sourceState2 h)
    (fun a => ((sourceTauEmpR h : ℝ) : ℂ) * f a)

/-- **State extension.**  The exhibited enlarged state restricts along the
ampliation to the committed source state. -/
theorem enlargedExpectation_ampliation (X : HistoryMatrix) :
    enlargedExpectation (ampliation X)
      = EventAlgebra.expectation sourceHistoryDensity X := by
  rw [enlargedExpectation_eq_sum, source_expectation_eq_sum]
  refine Finset.sum_congr rfl fun h _ => ?_
  have happ : ∀ a : Spin, ampliation X (h, a) (h, a) = X h h := by
    intro a
    rw [ampliation_apply]
    simp [Matrix.kroneckerMap_apply]
  calc ∑ a : Spin, enlargedWeight (h, a) * ampliation X (h, a) (h, a)
      = ∑ a : Spin, enlargedWeight (h, a) * X h h :=
        Finset.sum_congr rfl fun a _ => by rw [happ]
    _ = ((sourceTauEmpR h : ℝ) : ℂ) * X h h :=
        enlargedWeight_collapse h (fun _ => X h h)

/-- **State preservation.**  The record embedding preserves the exhibited
enlarged state: its trace pairing returns the committed expectation of the
source observable. -/
theorem enlargedExpectation_recordEmbedding (X : HistoryMatrix) :
    enlargedExpectation (recordEmbedding X)
      = EventAlgebra.expectation sourceHistoryDensity X := by
  rw [enlargedExpectation_eq_sum, source_expectation_eq_sum]
  refine Finset.sum_congr rfl fun h _ => ?_
  have happ : ∀ a : Spin,
      recordEmbedding X (h, a) (h, a) = X (readout h a) (readout h a) := by
    intro a
    rw [recordEmbedding_apply, if_pos rfl]
  calc ∑ a : Spin, enlargedWeight (h, a) * recordEmbedding X (h, a) (h, a)
      = ∑ a : Spin, enlargedWeight (h, a) * X (readout h a) (readout h a) :=
        Finset.sum_congr rfl fun a _ => by rw [happ]
    _ = ((sourceTauEmpR h : ℝ) : ℂ)
          * X (readout h (sourceState2 h)) (readout h (sourceState2 h)) :=
        enlargedWeight_collapse h (fun a => X (readout h a) (readout h a))
    _ = ((sourceTauEmpR h : ℝ) : ℂ) * X h h := by rw [readout_slot2]

/-- The exhibited enlarged density has unit trace. -/
theorem enlargedDensity_trace : enlargedDensity.trace = 1 := by
  unfold enlargedDensity
  rw [Matrix.trace_diagonal, Fintype.sum_prod_type]
  have hcol : ∀ h : Fin 8,
      ∑ a : Spin, enlargedWeight (h, a) = ((sourceTauEmpR h : ℝ) : ℂ) := by
    intro h
    have := enlargedWeight_collapse h (fun _ => (1 : ℂ))
    simpa using this
  rw [Finset.sum_congr rfl fun h _ => hcol h, ← Complex.ofReal_sum,
    sourceTauEmpR_sum, Complex.ofReal_one]

/-- The exhibited enlarged density is positive semidefinite. -/
theorem enlargedDensity_posSemidef : enlargedDensity.PosSemidef := by
  refine Matrix.PosSemidef.diagonal ?_
  intro z
  simp only [Pi.zero_apply]
  unfold enlargedWeight
  by_cases hz : z.2 = sourceState2 z.1
  · rw [if_pos hz]
    exact Complex.zero_le_real.mpr (le_of_lt (sourceTauEmpR_pos z.1))
  · rw [if_neg hz]

/-- The exhibited enlarged density is a state: positive semidefinite with
unit trace. -/
theorem enlargedDensity_isState :
    enlargedDensity.PosSemidef ∧ enlargedDensity.trace = 1 :=
  ⟨enlargedDensity_posSemidef, enlargedDensity_trace⟩

/-- **Non-product form.**  The exhibited extension differs from every
product of the committed density with an ancilla matrix: the escape route
uses a record-correlated extension. -/
theorem enlargedDensity_ne_product (σ : SpinMatrix) :
    enlargedDensity ≠ sourceHistoryDensity ⊗ₖ σ := by
  intro heq
  have h0 : enlargedDensity ((0 : Fin 8), (1 : Spin)) ((0 : Fin 8), (1 : Spin))
      = (sourceHistoryDensity ⊗ₖ σ) ((0 : Fin 8), (1 : Spin))
          ((0 : Fin 8), (1 : Spin)) := by rw [heq]
  have h1 : enlargedDensity ((1 : Fin 8), (1 : Spin)) ((1 : Fin 8), (1 : Spin))
      = (sourceHistoryDensity ⊗ₖ σ) ((1 : Fin 8), (1 : Spin))
          ((1 : Fin 8), (1 : Spin)) := by rw [heq]
  rw [enlargedDensity, Matrix.diagonal_apply_eq] at h0 h1
  have hw0 : enlargedWeight ((0 : Fin 8), (1 : Spin)) = 0 := if_neg (by decide)
  have hw1 : enlargedWeight ((1 : Fin 8), (1 : Spin))
      = ((sourceTauEmpR 1 : ℝ) : ℂ) := if_pos (by decide)
  rw [hw0] at h0
  rw [hw1] at h1
  have hde : ∀ g : Fin 8,
      sourceHistoryDensity g g = ((sourceTauEmpR g : ℝ) : ℂ) := by
    intro g
    rw [sourceHistoryDensity, Matrix.diagonal_apply_eq]
  have hk0 : (sourceHistoryDensity ⊗ₖ σ) ((0 : Fin 8), (1 : Spin))
      ((0 : Fin 8), (1 : Spin))
      = ((sourceTauEmpR 0 : ℝ) : ℂ) * σ 1 1 := by
    rw [Matrix.kroneckerMap_apply, hde]
  have hk1 : (sourceHistoryDensity ⊗ₖ σ) ((1 : Fin 8), (1 : Spin))
      ((1 : Fin 8), (1 : Spin))
      = ((sourceTauEmpR 1 : ℝ) : ℂ) * σ 1 1 := by
    rw [Matrix.kroneckerMap_apply, hde]
  rw [hk0] at h0
  rw [hk1] at h1
  have hτ0 : ((sourceTauEmpR 0 : ℝ) : ℂ) ≠ 0 :=
    Complex.ofReal_ne_zero.mpr (ne_of_gt (sourceTauEmpR_pos 0))
  have hτ1 : ((sourceTauEmpR 1 : ℝ) : ℂ) ≠ 0 :=
    Complex.ofReal_ne_zero.mpr (ne_of_gt (sourceTauEmpR_pos 1))
  have hσ : σ 1 1 = 0 := by
    rcases mul_eq_zero.mp h0.symm with hc | hc
    · exact absurd hc hτ0
    · exact hc
  rw [hσ, mul_zero] at h1
  exact hτ1 h1

/-! ## The wall pair on the enlarged target -/

/-- Histories `2` and `3` differ only in the slot-two record bit, so every
member of the enlarged target has equal diagonal ancilla blocks there. -/
theorem enlargedTarget_wall_pair {M : EnlargedHistoryMatrix}
    (hM : M ∈ enlargedTarget) (a a' : Spin) :
    M ((2 : Fin 8), a) ((2 : Fin 8), a') = M ((3 : Fin 8), a) ((3 : Fin 8), a') := by
  have hMr : M ∈ recordEmbedding.range := by
    rw [recordEmbedding_range_eq]
    exact hM
  obtain ⟨X, rfl⟩ := hMr
  show recordEmbedding X ((2 : Fin 8), a) ((2 : Fin 8), a')
      = recordEmbedding X ((3 : Fin 8), a) ((3 : Fin 8), a')
  rw [recordEmbedding_apply, recordEmbedding_apply, if_pos rfl, if_pos rfl,
    readout_two_eq_three, readout_two_eq_three]

/-! ## Delimitation one: product-form extensions stay obstructed -/

/-- Right-distribution of the kronecker product over finite sums. -/
theorem kronecker_sum_right {α β ι : Type} (s : Finset ι)
    (A : Matrix α α ℂ) (B : ι → Matrix β β ℂ) :
    A ⊗ₖ (∑ i ∈ s, B i) = ∑ i ∈ s, A ⊗ₖ B i := by
  ext z z'
  simp [Matrix.kroneckerMap_apply, Matrix.sum_apply, Finset.mul_sum]

/-- The trace pairing of a matrix-unit/ancilla kronecker factor against an
enlarged observable reads one diagonal ancilla block. -/
theorem kronecker_single_mul_trace (g g' : Fin 8) (c : ℂ) (σ : SpinMatrix)
    (Y : EnlargedHistoryMatrix) :
    ((Matrix.single g g' c ⊗ₖ σ) * Y).trace
      = c * ∑ a : Spin, ∑ a' : Spin, σ a a' * Y (g', a') (g, a) := by
  have hσ : Matrix.single g g' c ⊗ₖ σ
      = ∑ a : Spin, ∑ a' : Spin,
          Matrix.single ((g, a) : EnlargedIndex) (g', a') (c * σ a a') := by
    conv_lhs => rw [Matrix.matrix_eq_sum_single σ]
    rw [kronecker_sum_right]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [kronecker_sum_right]
    refine Finset.sum_congr rfl fun a' _ => ?_
    rw [Matrix.single_kronecker_single]
  rw [hσ, Finset.sum_mul, Matrix.trace_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [Finset.sum_mul, Matrix.trace_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun a' _ => ?_
  rw [Matrix.trace_single_mul, smul_eq_mul]
  ring

/-- Compression through ampliated interval elements against a product
functional reduces to a source-side sandwich. -/
theorem product_conj_trace (P : HistoryMatrix) (σ : SpinMatrix)
    (N N' : HistoryMatrix) (Y : EnlargedHistoryMatrix) :
    ((P ⊗ₖ σ) * (ampliation N * Y * ampliation N')).trace
      = (((N' * P * N) ⊗ₖ σ) * Y).trace := by
  have h1 : (P ⊗ₖ σ) * (ampliation N * Y * ampliation N')
      = (P ⊗ₖ σ) * ampliation N * Y * ampliation N' := by
    simp only [← mul_assoc]
  rw [h1, Matrix.trace_mul_comm]
  have h2 : ampliation N' * ((P ⊗ₖ σ) * ampliation N * Y)
      = ((N' * P * N) ⊗ₖ σ) * Y := by
    simp only [← mul_assoc]
    congr 1
    rw [ampliation_apply, ampliation_apply, ← Matrix.mul_kronecker_mul,
      ← Matrix.mul_kronecker_mul, one_mul, mul_one]
  rw [h2]

/-- The first sandwich value: the committed density compressed through the
interval shift pair. -/
theorem cellShift_density_sandwich :
    cellShiftStar * sourceHistoryDensity * cellShift
      = Matrix.single (2 : Fin 8) 2 ((1149 : ℂ) / 1754)
        + Matrix.single (3 : Fin 8) 3 ((96 : ℂ) / 1754) := by
  have hd00 : sourceHistoryDensity 0 0 = (1149 : ℂ) / 1754 := by
    rw [sourceHistoryDensity_eq_windowCount, sourceWindowCount_apply_0]
    norm_num
  have hd11 : sourceHistoryDensity 1 1 = (96 : ℂ) / 1754 := by
    rw [sourceHistoryDensity_eq_windowCount, sourceWindowCount_apply_1]
    norm_num
  have hd01 : sourceHistoryDensity 0 1 = 0 := by
    rw [sourceHistoryDensity]
    exact Matrix.diagonal_apply_ne _ (by decide)
  have hd10 : sourceHistoryDensity 1 0 = 0 := by
    rw [sourceHistoryDensity]
    exact Matrix.diagonal_apply_ne _ (by decide)
  rw [cellShiftStar_explicit, cellShift_explicit]
  simp only [add_mul, mul_add, Matrix.single_mul_mul_single, one_mul, mul_one,
    hd00, hd11, hd01, hd10, Matrix.single_zero, add_zero, zero_add]

/-- The second sandwich value: the committed density compressed into the
`(0,1)` interval cell. -/
theorem lateCellProj_density_sandwich :
    lateCellProj * sourceHistoryDensity * lateCellProj
      = Matrix.single (2 : Fin 8) 2 ((2 : ℂ) / 1754)
        + Matrix.single (3 : Fin 8) 3 ((87 : ℂ) / 1754) := by
  have hd22 : sourceHistoryDensity 2 2 = (2 : ℂ) / 1754 := by
    rw [sourceHistoryDensity_eq_windowCount, sourceWindowCount_apply_2]
    norm_num
  have hd33 : sourceHistoryDensity 3 3 = (87 : ℂ) / 1754 := by
    rw [sourceHistoryDensity_eq_windowCount, sourceWindowCount_apply_3]
    norm_num
  have hd23 : sourceHistoryDensity 2 3 = 0 := by
    rw [sourceHistoryDensity]
    exact Matrix.diagonal_apply_ne _ (by decide)
  have hd32 : sourceHistoryDensity 3 2 = 0 := by
    rw [sourceHistoryDensity]
    exact Matrix.diagonal_apply_ne _ (by decide)
  rw [lateCellProj_explicit]
  simp only [add_mul, mul_add, Matrix.single_mul_mul_single, one_mul, mul_one,
    hd22, hd33, hd23, hd32, Matrix.single_zero, add_zero, zero_add]

/-- **Product extensions stay obstructed.**  For every ancilla matrix `σ`,
no complex-linear map into the enlarged target satisfies the transported
bimodule clause together with preservation of the product functional
`Tr((ρ ⊗ σ) · )`.  Enlarging the target while keeping a product-form
extension keeps the committed obstruction; the trace-one positive `σ` of an
actual product state extension is the special case. -/
theorem no_product_state_bimodule_map_into_enlargedTarget (σ : SpinMatrix) :
    ¬ ∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ enlargedTarget) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = ampliation B * E X * ampliation B') ∧
        (∀ X : HistoryMatrix,
          ((sourceHistoryDensity ⊗ₖ σ) * E X).trace
            = EventAlgebra.expectation sourceHistoryDensity X) := by
  rintro ⟨E, hrange, hbimod, hstate⟩
  have h1 : ((sourceHistoryDensity ⊗ₖ σ)
        * (ampliation cellShift * E latePoint * ampliation cellShiftStar)).trace
      = (1149 / 1754 : ℂ) := by
    rw [← hbimod cellShift cellShift_mem_algebra01 cellShiftStar
      cellShiftStar_mem_algebra01 latePoint, hstate,
      cellShift_latePoint_conj, expectation_single]
    norm_num [sourceWindowCount_apply_0]
  have h2 : ((sourceHistoryDensity ⊗ₖ σ)
        * (ampliation lateCellProj * E latePoint * ampliation lateCellProj)).trace
      = (2 / 1754 : ℂ) := by
    rw [← hbimod lateCellProj lateCellProj_mem_algebra01 lateCellProj
      lateCellProj_mem_algebra01 latePoint, hstate,
      lateCellProj_latePoint_conj, expectation_single]
    norm_num [sourceWindowCount_apply_2]
  have e1 := (product_conj_trace sourceHistoryDensity σ cellShift cellShiftStar
    (E latePoint)).symm.trans h1
  have e2 := (product_conj_trace sourceHistoryDensity σ lateCellProj lateCellProj
    (E latePoint)).symm.trans h2
  rw [cellShift_density_sandwich, Matrix.add_kronecker, add_mul,
    Matrix.trace_add, kronecker_single_mul_trace, kronecker_single_mul_trace]
    at e1
  rw [lateCellProj_density_sandwich, Matrix.add_kronecker, add_mul,
    Matrix.trace_add, kronecker_single_mul_trace, kronecker_single_mul_trace]
    at e2
  have hS : (∑ a : Spin, ∑ a' : Spin,
        σ a a' * E latePoint ((3 : Fin 8), a') ((3 : Fin 8), a))
      = ∑ a : Spin, ∑ a' : Spin,
        σ a a' * E latePoint ((2 : Fin 8), a') ((2 : Fin 8), a) :=
    Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun a' _ => by
      rw [(enlargedTarget_wall_pair (hrange latePoint) a' a).symm]
  rw [hS] at e1 e2
  have hcontra : (99771 : ℂ) = 0 := by
    linear_combination (1245 * 1754 : ℂ) * e2 - (89 * 1754 : ℂ) * e1
  norm_num at hcontra

/-! ## Delimitation two: the ampliated range stays obstructed -/

/-- **The ancilla factor must be used.**  A map whose range lies in the
ampliated copy `algebra01 ⊗ 1` is obstructed even against the exhibited
correlated extension: within the enlargement, the ancilla-free range
reproduces the committed contradiction. -/
theorem no_ampliated_range_bimodule_map :
    ¬ ∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ algebra01.map ampliation) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = ampliation B * E X * ampliation B') ∧
        (∀ X : HistoryMatrix,
          enlargedExpectation (E X)
            = EventAlgebra.expectation sourceHistoryDensity X) := by
  rintro ⟨E, hrange, hbimod, hstate⟩
  obtain ⟨Z, hZ, hYZ0⟩ := hrange latePoint
  have hYZ : ampliation Z = E latePoint := hYZ0
  have hdiag : Z 2 2 = Z 3 3 := algebra01_wall_diagonal_pair hZ
  have h1 : enlargedExpectation
        (ampliation cellShift * E latePoint * ampliation cellShiftStar)
      = (1149 / 1754 : ℂ) := by
    rw [← hbimod cellShift cellShift_mem_algebra01 cellShiftStar
      cellShiftStar_mem_algebra01 latePoint, hstate,
      cellShift_latePoint_conj, expectation_single]
    norm_num [sourceWindowCount_apply_0]
  have h2 : enlargedExpectation
        (ampliation lateCellProj * E latePoint * ampliation lateCellProj)
      = (2 / 1754 : ℂ) := by
    rw [← hbimod lateCellProj lateCellProj_mem_algebra01 lateCellProj
      lateCellProj_mem_algebra01 latePoint, hstate,
      lateCellProj_latePoint_conj, expectation_single]
    norm_num [sourceWindowCount_apply_2]
  have hmm1 : ampliation cellShift * ampliation Z * ampliation cellShiftStar
      = ampliation (cellShift * Z * cellShiftStar) := by
    rw [map_mul, map_mul]
  have hmm2 : ampliation lateCellProj * ampliation Z * ampliation lateCellProj
      = ampliation (lateCellProj * Z * lateCellProj) := by
    rw [map_mul, map_mul]
  have h1' : enlargedExpectation
        (ampliation cellShift * E latePoint * ampliation cellShiftStar)
      = EventAlgebra.expectation sourceHistoryDensity
          (cellShift * Z * cellShiftStar) := by
    rw [← hYZ, hmm1, enlargedExpectation_ampliation]
  have h2' : enlargedExpectation
        (ampliation lateCellProj * E latePoint * ampliation lateCellProj)
      = EventAlgebra.expectation sourceHistoryDensity
          (lateCellProj * Z * lateCellProj) := by
    rw [← hYZ, hmm2, enlargedExpectation_ampliation]
  have e1 := (h1'.symm.trans h1)
  have e2 := (h2'.symm.trans h2)
  rw [expectation_cellShift_conj] at e1
  rw [expectation_lateCellProj_conj] at e2
  rw [hdiag] at e1 e2
  have hcontra : (99771 : ℂ) = 0 := by
    linear_combination (1245 * 1754 : ℂ) * e2 - (89 * 1754 : ℂ) * e1
  norm_num at hcontra

/-- The plain ampliation does land outside the enlarged target: the record
embedding routes the slot-two projection through the ancilla, and the
ampliated slot-two projection violates the wall pair. -/
theorem ampliation_latePoint_notMem_enlargedTarget :
    ampliation latePoint ∉ enlargedTarget := by
  intro hmem
  have h := enlargedTarget_wall_pair hmem 0 0
  have hL : ampliation latePoint ((2 : Fin 8), (0 : Spin))
      ((2 : Fin 8), (0 : Spin)) = 1 := by
    rw [ampliation_apply, Matrix.kroneckerMap_apply, latePoint_explicit]
    norm_num [Matrix.single_apply, Matrix.one_apply, Fin.ext_iff]
  have hR : ampliation latePoint ((3 : Fin 8), (0 : Spin))
      ((3 : Fin 8), (0 : Spin)) = 0 := by
    rw [ampliation_apply, Matrix.kroneckerMap_apply, latePoint_explicit]
    norm_num [Matrix.single_apply, Matrix.one_apply, Fin.ext_iff]
  rw [hL, hR] at h
  exact one_ne_zero h

/-! ## Headline: obstructed on the fixed target, inhabited on the enlarged
target -/

/-- **Existence on the enlarged target.**  A complex-linear map from the
source carrier satisfies the three transported clauses jointly: range in
the enlarged target, the `algebra01`-bimodule law through the ampliation,
and preservation of the exhibited state extension. -/
theorem enlargedTarget_statePreserving_bimodule_map_exists :
    ∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
      (∀ X : HistoryMatrix, E X ∈ enlargedTarget) ∧
      (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
        E (B * X * B') = ampliation B * E X * ampliation B') ∧
      (∀ X : HistoryMatrix,
        enlargedExpectation (E X)
          = EventAlgebra.expectation sourceHistoryDensity X) :=
  ⟨recordEmbedding.toAlgHom.toLinearMap,
    recordEmbedding_mem_enlargedTarget,
    recordEmbedding_bimodule,
    enlargedExpectation_recordEmbedding⟩

/-- **The boundary pair.**  The clause list is obstructed on the fixed
target `algebra01` with the committed state, and inhabited on the enlarged
target `algebra01 ⊗ M₂(ℂ)` with the exhibited correlated state extension.
The single enlarged clause is the range clause; the bimodule clause
quantifies over the same committed interval algebra, and the state clause
evaluates an extension of the committed state. -/
theorem fixed_target_obstructed_enlarged_target_inhabited :
    (¬ ∃ E : HistoryMatrix →ₗ[ℂ] HistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ algebra01) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = B * E X * B') ∧
        (∀ X : HistoryMatrix,
          EventAlgebra.expectation sourceHistoryDensity (E X)
            = EventAlgebra.expectation sourceHistoryDensity X)) ∧
      (∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ enlargedTarget) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = ampliation B * E X * ampliation B') ∧
        (∀ X : HistoryMatrix,
          enlargedExpectation (E X)
            = EventAlgebra.expectation sourceHistoryDensity X)) :=
  ⟨no_statePreserving_bimodule_projection_onto_interval01,
    enlargedTarget_statePreserving_bimodule_map_exists⟩

/-- **Embedding receipt.**  The constructed map is a unital star-algebra
homomorphism, injective, with range exactly the enlarged target. -/
theorem recordEmbedding_embedding_receipt :
    recordEmbedding 1 = 1 ∧
      (∀ X Y : HistoryMatrix,
        recordEmbedding (X * Y) = recordEmbedding X * recordEmbedding Y) ∧
      (∀ X : HistoryMatrix,
        recordEmbedding (star X) = star (recordEmbedding X)) ∧
      Function.Injective recordEmbedding ∧
      recordEmbedding.range = enlargedTarget :=
  ⟨map_one recordEmbedding,
    fun X Y => map_mul recordEmbedding X Y,
    fun X => map_star recordEmbedding X,
    recordEmbedding_injective,
    recordEmbedding_range_eq⟩

/-- **Changed-clause receipt.**  On the committed interval algebra the
embedding is the canonical ampliation, and the exhibited enlarged state
restricts along the ampliation to the committed source state: the bimodule
clause quantifies over the committed interval algebra transported by the
ampliation, and the range clause is the single clause whose target algebra
changes.  The state clause evaluates a strictly different functional, the
exhibited non-product extension of the committed state
(`enlargedDensity_ne_product`).  The delimitation
`no_product_state_bimodule_map_into_enlargedTarget` proves necessity only of
leaving the product-form family; it does not single out this extension. -/
theorem single_changed_clause_receipt :
    (∀ B ∈ algebra01, recordEmbedding B = ampliation B) ∧
      (∀ X : HistoryMatrix,
        enlargedExpectation (ampliation X)
          = EventAlgebra.expectation sourceHistoryDensity X) :=
  ⟨recordEmbedding_agrees_on_algebra01, enlargedExpectation_ampliation⟩

/-! ## Committed record means through the embedding -/

/-- The embedded repair Hamiltonian keeps the committed action mean. -/
theorem enlargedExpectation_embedded_hamiltonian :
    enlargedExpectation (recordEmbedding sourceHistoryHamiltonian)
      = (197 / 1754 : ℂ) := by
  rw [enlargedExpectation_recordEmbedding, sourceHistoryDensity_meanEnergy]

/-- The embedded early wall keeps the committed mean `94/1754`. -/
theorem enlargedExpectation_embedded_bond01 :
    enlargedExpectation (recordEmbedding bond01) = (94 / 1754 : ℂ) := by
  rw [enlargedExpectation_recordEmbedding,
    sourceHistoryDensity_bond01_expectation]

/-- The embedded late wall keeps the committed mean `103/1754`. -/
theorem enlargedExpectation_embedded_bond12 :
    enlargedExpectation (recordEmbedding bond12) = (103 / 1754 : ℂ) := by
  rw [enlargedExpectation_recordEmbedding,
    sourceHistoryDensity_bond12_expectation]

/-! ## Bundled receipt -/

/-- One bundled receipt for the enlarged-target record embedding: the
committed fixed-target obstruction, the clause-for-clause existence on the
enlarged target, the embedding structure, the state extension and its
non-product form, and the two delimitations showing that the ancilla
factor and the correlated extension are both required. -/
theorem enlargedTargetRecordEmbeddingAttachment :
    (¬ ∃ E : HistoryMatrix →ₗ[ℂ] HistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ algebra01) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = B * E X * B') ∧
        (∀ X : HistoryMatrix,
          EventAlgebra.expectation sourceHistoryDensity (E X)
            = EventAlgebra.expectation sourceHistoryDensity X)) ∧
      (∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ enlargedTarget) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = ampliation B * E X * ampliation B') ∧
        (∀ X : HistoryMatrix,
          enlargedExpectation (E X)
            = EventAlgebra.expectation sourceHistoryDensity X)) ∧
      Function.Injective recordEmbedding ∧
      recordEmbedding.range = enlargedTarget ∧
      (∀ B ∈ algebra01, recordEmbedding B = ampliation B) ∧
      (∀ X : HistoryMatrix,
        enlargedExpectation (ampliation X)
          = EventAlgebra.expectation sourceHistoryDensity X) ∧
      (enlargedDensity.PosSemidef ∧ enlargedDensity.trace = 1) ∧
      (∀ σ : SpinMatrix, enlargedDensity ≠ sourceHistoryDensity ⊗ₖ σ) ∧
      (∀ σ : SpinMatrix,
        ¬ ∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
          (∀ X : HistoryMatrix, E X ∈ enlargedTarget) ∧
          (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
            E (B * X * B') = ampliation B * E X * ampliation B') ∧
          (∀ X : HistoryMatrix,
            ((sourceHistoryDensity ⊗ₖ σ) * E X).trace
              = EventAlgebra.expectation sourceHistoryDensity X)) ∧
      (¬ ∃ E : HistoryMatrix →ₗ[ℂ] EnlargedHistoryMatrix,
        (∀ X : HistoryMatrix, E X ∈ algebra01.map ampliation) ∧
        (∀ B ∈ algebra01, ∀ B' ∈ algebra01, ∀ X : HistoryMatrix,
          E (B * X * B') = ampliation B * E X * ampliation B') ∧
        (∀ X : HistoryMatrix,
          enlargedExpectation (E X)
            = EventAlgebra.expectation sourceHistoryDensity X)) :=
  ⟨no_statePreserving_bimodule_projection_onto_interval01,
    enlargedTarget_statePreserving_bimodule_map_exists,
    recordEmbedding_injective,
    recordEmbedding_range_eq,
    recordEmbedding_agrees_on_algebra01,
    enlargedExpectation_ampliation,
    enlargedDensity_isState,
    enlargedDensity_ne_product,
    no_product_state_bimodule_map_into_enlargedTarget,
    no_ampliated_range_bimodule_map⟩

end

end OPH.QFT.EnlargedTargetRecordEmbedding

-- Axiom audit: all declarations must stay on the standard Mathlib basis.
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_stage_kronecker
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.pair01_mem_algebra01
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.algebra01_eq_pair01_range
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_agrees_on_algebra01
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_mem_enlargedTarget
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_range_eq
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_bimodule
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_apply
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_injective
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedExpectation_ampliation
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedExpectation_recordEmbedding
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedDensity_isState
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedDensity_ne_product
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedTarget_wall_pair
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.no_product_state_bimodule_map_into_enlargedTarget
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.no_ampliated_range_bimodule_map
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.ampliation_latePoint_notMem_enlargedTarget
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedTarget_statePreserving_bimodule_map_exists
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.fixed_target_obstructed_enlarged_target_inhabited
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.recordEmbedding_embedding_receipt
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.single_changed_clause_receipt
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedExpectation_embedded_hamiltonian
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedExpectation_embedded_bond01
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedExpectation_embedded_bond12
#print axioms OPH.QFT.EnlargedTargetRecordEmbedding.enlargedTargetRecordEmbeddingAttachment
