import EventAlgebra.ProductSplitSeparability
import EventAlgebra.SchroedingerFrameFlow
import Mathlib.Analysis.CStarAlgebra.Matrix
import Mathlib.Analysis.InnerProductSpace.Positive

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# An exact finite two-site Ising Hamiltonian benchmark

This module realizes the positive Ising bond
`H = (1 - Z ⊗ Z) / 2` on the declared Hilbert space
`ℂ² ⊗ ℂ² ≃ EuclideanSpace ℂ (Fin 2 × Fin 2)`.  It proves the finite
Hamiltonian, ground-state, unitary-flow, locality, interaction, and deletion
receipts by exact matrix calculation and represents the full matrix algebra
faithfully by bounded operators.

This is a coupled two-spin lattice benchmark, not a continuum quantum field
theory and not an attachment of this Hamiltonian to the completed-colimit GNS
representation.  The tensor factors are declared sites rather than physical
spacetime regions; the Hamiltonian, normalization, state, and time parameter
are supplied rather than source-selected or calibrated.  The ground space is
degenerate.  No Lorentz covariance, spectrum condition, continuum or
infinite-volume limit, renormalization flow, field or particle content,
scattering theory, detector readback, or physical time-slice theorem is
claimed.
-/

namespace OPH.QFT.FiniteTwoSiteIsingField

open Matrix
open OPH.Dynamics
open OPH.QFT
open EventAlgebra.SourceReachability
open EventAlgebra.ProductSplitSeparability
open EventAlgebra.Robertson
open EventAlgebra.QuantumSurface
open scoped ComplexOrder Matrix.Norms.L2Operator

noncomputable section

abbrev Spin := Fin 2
abbrev IsingIndex := Spin × Spin
abbrev IsingMatrix := Matrix IsingIndex IsingIndex ℂ
abbrev IsingHilbert := EuclideanSpace ℂ IsingIndex

/-- The two-site nearest-neighbour spin correlation. -/
def isingZZ : IsingMatrix :=
  slotLeft Spin pauliZ * slotRight Spin pauliZ

/-- The positive ferromagnetic Ising bond Hamiltonian `(1 - Z⊗Z)/2`. -/
def isingHamiltonian : IsingMatrix :=
  (2⁻¹ : ℂ) • (1 - isingZZ)

/-- The committed product state `|00⟩⟨00|`, used as a chosen ground density. -/
def isingGroundDensity : IsingMatrix := ket00

/-- The corresponding explicit unit vector in the finite Hilbert carrier. -/
def isingGroundVector : IsingHilbert :=
  PiLp.single 2 ((0 : Spin), (0 : Spin)) (1 : ℂ)

/-- A second explicit ground vector, supported on the aligned state `|11⟩`. -/
def isingSecondGroundVector : IsingHilbert :=
  PiLp.single 2 ((1 : Spin), (1 : Spin)) (1 : ℂ)

/-- The faithful bounded-operator realization of the full two-site matrix algebra. -/
def isingRepresentation :
    IsingMatrix ≃⋆ₐ[ℂ] (IsingHilbert →L[ℂ] IsingHilbert) :=
  Matrix.toEuclideanCLM

/-- The represented bounded Hamiltonian. -/
def isingHamiltonianOperator : IsingHilbert →L[ℂ] IsingHilbert :=
  isingRepresentation isingHamiltonian

/-- The unitary propagator generated by the Ising Hamiltonian. -/
def isingPropagator (t : ℝ) : IsingMatrix :=
  stonePropagator isingHamiltonian t

/-- The Heisenberg evolution of a two-site observable. -/
def isingHeisenberg (t : ℝ) (X : IsingMatrix) : IsingMatrix :=
  isingPropagator t * X * isingPropagator (-t)

/-- A left-local spin observable moved by the interaction. -/
def leftPauliX : IsingMatrix := slotLeft Spin pauliX

/-- A right-local spin observable moved by the interaction. -/
def rightPauliX : IsingMatrix := slotRight Spin pauliX

/-- The interaction-deletion control: removing only the `Z ⊗ Z` coupling
leaves the scalar offset `(1 / 2) I`. -/
def uncoupledHamiltonian : IsingMatrix := (2⁻¹ : ℂ) • 1

/-- Heisenberg evolution in the interaction-deleted control. -/
def uncoupledHeisenberg (t : ℝ) (X : IsingMatrix) : IsingMatrix :=
  stonePropagator uncoupledHamiltonian t * X *
    stonePropagator uncoupledHamiltonian (-t)

theorem pauliZ_mul_self : pauliZ * pauliZ = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [pauliZ, Matrix.mul_apply, Fin.sum_univ_two]

theorem isingZZ_mul_self : isingZZ * isingZZ = 1 := by
  let L : IsingMatrix := slotLeft Spin pauliZ
  let R : IsingMatrix := slotRight Spin pauliZ
  have hcomm : Commute L R :=
    slot_commute ⟨pauliZ, rfl⟩ ⟨pauliZ, rfl⟩
  have hL : L * L = 1 := by
    dsimp [L]
    rw [← map_mul, pauliZ_mul_self, map_one]
  have hR : R * R = 1 := by
    dsimp [R]
    rw [← map_mul, pauliZ_mul_self, map_one]
  change (L * R) * (L * R) = 1
  calc
    (L * R) * (L * R) = L * (R * L) * R := by
      simp only [mul_assoc]
    _ = L * (L * R) * R := by rw [hcomm.eq.symm]
    _ = (L * L) * (R * R) := by simp only [mul_assoc]
    _ = 1 := by rw [hL, hR, one_mul]

theorem isingZZ_isSelfAdjoint : IsSelfAdjoint isingZZ := by
  have hL : IsSelfAdjoint (slotLeft Spin pauliZ) :=
    pauliZ_isHermitian.isSelfAdjoint.map (slotLeft Spin)
  have hR : IsSelfAdjoint (slotRight Spin pauliZ) :=
    pauliZ_isHermitian.isSelfAdjoint.map (slotRight Spin)
  exact (hL.commute_iff hR).mp (slot_commute ⟨pauliZ, rfl⟩ ⟨pauliZ, rfl⟩)

theorem isingHamiltonian_isSelfAdjoint : IsSelfAdjoint isingHamiltonian := by
  have hhalf : IsSelfAdjoint (2⁻¹ : ℂ) := by
    norm_num [isSelfAdjoint_iff]
  have hone : IsSelfAdjoint (1 : IsingMatrix) := by simp
  exact hhalf.smul (hone.sub isingZZ_isSelfAdjoint)

theorem isingHamiltonian_mul_self :
    isingHamiltonian * isingHamiltonian = isingHamiltonian := by
  ext ⟨a, b⟩ ⟨c, d⟩
  fin_cases a <;> fin_cases b <;> fin_cases c <;> fin_cases d <;>
    norm_num [isingHamiltonian, isingZZ, slotLeft, slotRight, pauliZ,
      Matrix.mul_apply, Matrix.kroneckerMap_apply,
      Fintype.sum_prod_type, Fin.sum_univ_two]

theorem isingHamiltonian_posSemidef : isingHamiltonian.PosSemidef := by
  have h := Matrix.posSemidef_conjTranspose_mul_self isingHamiltonian
  rw [isingHamiltonian_isSelfAdjoint.isHermitian.eq,
    isingHamiltonian_mul_self] at h
  exact h

theorem isingGroundDensity_posSemidef : isingGroundDensity.PosSemidef :=
  ket00_isRecordLaw.posSemidef

theorem isingGroundDensity_trace : isingGroundDensity.trace = 1 :=
  ket00_isRecordLaw.trace_one

theorem isingHamiltonian_mul_groundDensity :
    isingHamiltonian * isingGroundDensity = 0 := by
  ext ⟨a, b⟩ ⟨c, d⟩
  fin_cases a <;> fin_cases b <;> fin_cases c <;> fin_cases d <;>
    norm_num [isingHamiltonian, isingZZ, isingGroundDensity, ket00,
      slotLeft, slotRight, pauliZ, Matrix.mul_apply,
      Matrix.kroneckerMap_apply, Fintype.sum_prod_type, Fin.sum_univ_two,
      Matrix.single_apply]

theorem isingGroundDensity_mul_hamiltonian :
    isingGroundDensity * isingHamiltonian = 0 := by
  ext ⟨a, b⟩ ⟨c, d⟩
  fin_cases a <;> fin_cases b <;> fin_cases c <;> fin_cases d <;>
    norm_num [isingHamiltonian, isingZZ, isingGroundDensity, ket00,
      slotLeft, slotRight, pauliZ, Matrix.mul_apply,
      Matrix.kroneckerMap_apply, Fintype.sum_prod_type, Fin.sum_univ_two,
      Matrix.single_apply]

theorem isingGroundDensity_zero_energy :
    (isingGroundDensity * isingHamiltonian).trace = 0 := by
  rw [isingGroundDensity_mul_hamiltonian, Matrix.trace_zero]

theorem norm_isingGroundVector : ‖isingGroundVector‖ = 1 := by
  simp [isingGroundVector]

theorem norm_isingSecondGroundVector : ‖isingSecondGroundVector‖ = 1 := by
  simp [isingSecondGroundVector]

theorem inner_isingGroundVector_secondGroundVector :
    inner ℂ isingGroundVector isingSecondGroundVector = 0 := by
  norm_num [isingGroundVector, isingSecondGroundVector, PiLp.inner_apply,
    Fintype.sum_prod_type, Fin.sum_univ_two, PiLp.single_apply]

theorem isingHamiltonianOperator_groundVector :
    isingHamiltonianOperator isingGroundVector = 0 := by
  change isingRepresentation isingHamiltonian
      (PiLp.single 2 ((0 : Spin), (0 : Spin)) (1 : ℂ)) = 0
  unfold isingRepresentation
  ext ⟨a, b⟩
  fin_cases a <;> fin_cases b <;>
    norm_num [isingHamiltonian, isingZZ, slotLeft, slotRight, pauliZ,
      Matrix.toEuclideanCLM_toLp, Matrix.mulVec, dotProduct,
      Matrix.mul_apply, Matrix.kroneckerMap_apply,
      Fintype.sum_prod_type, Fin.sum_univ_two, PiLp.single_apply]

theorem isingHamiltonianOperator_secondGroundVector :
    isingHamiltonianOperator isingSecondGroundVector = 0 := by
  change isingRepresentation isingHamiltonian
      (PiLp.single 2 ((1 : Spin), (1 : Spin)) (1 : ℂ)) = 0
  unfold isingRepresentation
  ext ⟨a, b⟩
  fin_cases a <;> fin_cases b <;>
    norm_num [isingHamiltonian, isingZZ, slotLeft, slotRight, pauliZ,
      Matrix.toEuclideanCLM_toLp, Matrix.mulVec, dotProduct,
      Matrix.mul_apply, Matrix.kroneckerMap_apply,
      Fintype.sum_prod_type, Fin.sum_univ_two, PiLp.single_apply]

/-- The zero-energy space contains two orthogonal unit vectors, so the ground
eigenspace is not one-dimensional. -/
theorem isingGroundSpace_degenerate :
    ‖isingGroundVector‖ = 1 ∧
      ‖isingSecondGroundVector‖ = 1 ∧
      inner ℂ isingGroundVector isingSecondGroundVector = 0 ∧
      isingHamiltonianOperator isingGroundVector = 0 ∧
      isingHamiltonianOperator isingSecondGroundVector = 0 :=
  ⟨norm_isingGroundVector, norm_isingSecondGroundVector,
    inner_isingGroundVector_secondGroundVector,
    isingHamiltonianOperator_groundVector,
    isingHamiltonianOperator_secondGroundVector⟩

theorem isingRepresentation_injective : Function.Injective isingRepresentation :=
  isingRepresentation.injective

theorem isingHamiltonianOperator_isSelfAdjoint :
    IsSelfAdjoint isingHamiltonianOperator :=
  isingHamiltonian_isSelfAdjoint.map isingRepresentation

theorem isingHamiltonianOperator_isPositive :
    isingHamiltonianOperator.IsPositive := by
  rw [← ContinuousLinearMap.isPositive_toLinearMap_iff]
  change (isingRepresentation isingHamiltonian :
    IsingHilbert →ₗ[ℂ] IsingHilbert).IsPositive
  unfold isingRepresentation
  rw [Matrix.coe_toEuclideanCLM_eq_toEuclideanLin]
  exact Matrix.isPositive_toEuclideanLin_iff.mpr isingHamiltonian_posSemidef

theorem isingPropagator_zero : isingPropagator 0 = 1 :=
  stonePropagator_zero isingHamiltonian

theorem isingPropagator_add (s t : ℝ) :
    isingPropagator (s + t) = isingPropagator s * isingPropagator t :=
  stonePropagator_add isingHamiltonian s t

theorem isingPropagator_unitary (t : ℝ) :
    isingPropagator t ∈ unitary IsingMatrix :=
  stonePropagator_mem_unitary isingHamiltonian
    isingHamiltonian_isSelfAdjoint t

theorem isingHeisenberg_zero (X : IsingMatrix) : isingHeisenberg 0 X = X := by
  simp [isingHeisenberg, isingPropagator_zero]

theorem isingHeisenberg_add (s t : ℝ) (X : IsingMatrix) :
    isingHeisenberg (s + t) X =
      isingHeisenberg s (isingHeisenberg t X) := by
  unfold isingHeisenberg isingPropagator
  rw [stonePropagator_add]
  have hneg : -(s + t) = -t + -s := by ring
  rw [hneg, stonePropagator_add]
  simp only [mul_assoc]

theorem isingGroundDensity_stationary (t : ℝ) :
    isingHeisenberg t isingGroundDensity = isingGroundDensity := by
  have hcomm : Commute isingHamiltonian isingGroundDensity := by
    show isingHamiltonian * isingGroundDensity =
      isingGroundDensity * isingHamiltonian
    rw [isingHamiltonian_mul_groundDensity,
      isingGroundDensity_mul_hamiltonian]
  have hgen : Commute
      (t • ((-Complex.I) • isingHamiltonian)) isingGroundDensity :=
    (hcomm.smul_left (-Complex.I)).smul_left t
  have hU : Commute (isingPropagator t) isingGroundDensity := by
    unfold isingPropagator stonePropagator
    exact hgen.exp_left
  unfold isingHeisenberg
  calc
    isingPropagator t * isingGroundDensity * isingPropagator (-t) =
        isingGroundDensity *
          (isingPropagator t * isingPropagator (-t)) := by
      rw [hU.eq]
      simp only [mul_assoc]
    _ = isingGroundDensity := by
      rw [show isingPropagator t * isingPropagator (-t) = 1 from
        stonePropagator_mul_neg isingHamiltonian t, mul_one]

theorem isingHeisenberg_mul (t : ℝ) (X Y : IsingMatrix) :
    isingHeisenberg t (X * Y) =
      isingHeisenberg t X * isingHeisenberg t Y := by
  let U := stonePropagator isingHamiltonian t
  let V := stonePropagator isingHamiltonian (-t)
  change U * (X * Y) * V = (U * X * V) * (U * Y * V)
  have hunit : V * U = 1 := by
    dsimp [U, V]
    simpa only [neg_neg] using
      stonePropagator_mul_neg isingHamiltonian (-t)
  calc
    U * (X * Y) * V = U * X * (1 * Y) * V := by
      simp only [one_mul, mul_assoc]
    _ = U * X * ((V * U) * Y) * V := by rw [hunit]
    _ = (U * X * V) * (U * Y * V) := by simp only [mul_assoc]

theorem left_right_equal_time_locality (t : ℝ)
    (A B : Matrix Spin Spin ℂ) :
    Commute
      (isingHeisenberg t (slotLeft Spin A))
      (isingHeisenberg t (slotRight Spin B)) := by
  have hlocal : Commute (slotLeft Spin A) (slotRight Spin B) :=
    slot_commute ⟨A, rfl⟩ ⟨B, rfl⟩
  show isingHeisenberg t (slotLeft Spin A) *
    isingHeisenberg t (slotRight Spin B) =
      isingHeisenberg t (slotRight Spin B) *
        isingHeisenberg t (slotLeft Spin A)
  rw [← isingHeisenberg_mul, hlocal.eq, isingHeisenberg_mul]

theorem isingCommutator_leftPauliX_entry :
    (isingHamiltonian * leftPauliX - leftPauliX * isingHamiltonian)
      ((0 : Spin), (0 : Spin)) ((1 : Spin), (0 : Spin)) = -1 := by
  norm_num [isingHamiltonian, isingZZ, leftPauliX,
    slotLeft, slotRight, pauliZ, pauliX, Matrix.mul_apply,
    Matrix.kroneckerMap_apply, Fintype.sum_prod_type, Fin.sum_univ_two]

theorem isingCommutator_rightPauliX_entry :
    (isingHamiltonian * rightPauliX - rightPauliX * isingHamiltonian)
      ((0 : Spin), (0 : Spin)) ((0 : Spin), (1 : Spin)) = -1 := by
  norm_num [isingHamiltonian, isingZZ, rightPauliX,
    slotLeft, slotRight, pauliZ, pauliX, Matrix.mul_apply,
    Matrix.kroneckerMap_apply, Fintype.sum_prod_type, Fin.sum_univ_two]

/-- The bond Hamiltonian is not an observable of the left site alone. -/
theorem isingHamiltonian_not_mem_leftSlot :
    isingHamiltonian ∉ (slotLeft Spin (α := Spin)).range := by
  intro hleft
  have hcomm : Commute isingHamiltonian rightPauliX :=
    slot_commute hleft ⟨pauliX, rfl⟩
  have hzero :
      (isingHamiltonian * rightPauliX - rightPauliX * isingHamiltonian)
        ((0 : Spin), (0 : Spin)) ((0 : Spin), (1 : Spin)) = 0 := by
    rw [hcomm.eq]
    simp
  rw [isingCommutator_rightPauliX_entry] at hzero
  norm_num at hzero

/-- The bond Hamiltonian is not an observable of the right site alone. -/
theorem isingHamiltonian_not_mem_rightSlot :
    isingHamiltonian ∉ (slotRight Spin (β := Spin)).range := by
  intro hright
  have hcomm : Commute leftPauliX isingHamiltonian :=
    slot_commute ⟨pauliX, rfl⟩ hright
  have hzero :
      (isingHamiltonian * leftPauliX - leftPauliX * isingHamiltonian)
        ((0 : Spin), (0 : Spin)) ((1 : Spin), (0 : Spin)) = 0 := by
    rw [hcomm.eq.symm]
    simp
  rw [isingCommutator_leftPauliX_entry] at hzero
  norm_num at hzero

/-- Exact witness that the declared bond is not reducible to either one-site algebra. -/
theorem isingHamiltonian_genuinely_two_site :
    isingHamiltonian ∉ (slotLeft Spin (α := Spin)).range ∧
      isingHamiltonian ∉ (slotRight Spin (β := Spin)).range :=
  ⟨isingHamiltonian_not_mem_leftSlot, isingHamiltonian_not_mem_rightSlot⟩

/-- The bond cannot be reduced even to a sum of independent one-site
Hamiltonians.  This is the exact interaction witness for the finite model. -/
theorem isingHamiltonian_not_sum_one_site
    (A B : Matrix Spin Spin ℂ) :
    slotLeft Spin A + slotRight Spin B ≠ isingHamiltonian := by
  intro h
  have h00 := congrFun (congrFun h
    ((0 : Spin), (0 : Spin))) ((0 : Spin), (0 : Spin))
  have h01 := congrFun (congrFun h
    ((0 : Spin), (1 : Spin))) ((0 : Spin), (1 : Spin))
  have h10 := congrFun (congrFun h
    ((1 : Spin), (0 : Spin))) ((1 : Spin), (0 : Spin))
  have h11 := congrFun (congrFun h
    ((1 : Spin), (1 : Spin))) ((1 : Spin), (1 : Spin))
  norm_num [isingHamiltonian, isingZZ, slotLeft, slotRight, pauliZ,
    Matrix.mul_apply, Matrix.kroneckerMap_apply,
    Fintype.sum_prod_type, Fin.sum_univ_two] at h00 h01 h10 h11
  have hfalse : (0 : ℂ) = -2 := by
    linear_combination h00 + h11 - h01 - h10
  norm_num at hfalse

/-- Deleting the interaction term while retaining the scalar offset makes
every observable static. -/
theorem uncoupledHeisenberg_eq (t : ℝ) (X : IsingMatrix) :
    uncoupledHeisenberg t X = X := by
  have hH : Commute uncoupledHamiltonian X := by
    exact (Commute.one_left X).smul_left (2⁻¹ : ℂ)
  have hgen : Commute
      (t • ((-Complex.I) • uncoupledHamiltonian)) X :=
    (hH.smul_left (-Complex.I)).smul_left t
  have hU : Commute (stonePropagator uncoupledHamiltonian t) X := by
    unfold stonePropagator
    exact hgen.exp_left
  unfold uncoupledHeisenberg
  calc
    stonePropagator uncoupledHamiltonian t * X *
          stonePropagator uncoupledHamiltonian (-t) =
        X * (stonePropagator uncoupledHamiltonian t *
          stonePropagator uncoupledHamiltonian (-t)) := by
      rw [hU.eq]
      simp only [mul_assoc]
    _ = X := by
      rw [stonePropagator_mul_neg, mul_one]

/-- In particular, the interaction-deleted control has zero `X_L` generator. -/
theorem uncoupledLeftPauliXGenerator_eq_zero :
    (-Complex.I) •
      (uncoupledHamiltonian * leftPauliX -
        leftPauliX * uncoupledHamiltonian) = 0 := by
  have hcomm : Commute uncoupledHamiltonian leftPauliX := by
    exact (Commute.one_left leftPauliX).smul_left (2⁻¹ : ℂ)
  rw [hcomm.eq, sub_self, smul_zero]

def isingLeftPauliXGenerator : IsingMatrix :=
  (-Complex.I) •
    (isingHamiltonian * leftPauliX - leftPauliX * isingHamiltonian)

theorem isingLeftPauliXGenerator_entry :
    isingLeftPauliXGenerator
      ((0 : Spin), (0 : Spin)) ((1 : Spin), (0 : Spin)) = Complex.I := by
  rw [isingLeftPauliXGenerator, Matrix.smul_apply,
    isingCommutator_leftPauliX_entry]
  norm_num

theorem isingLeftPauliXGenerator_ne_zero : isingLeftPauliXGenerator ≠ 0 := by
  intro h
  have hentry := congrFun (congrFun h
    ((0 : Spin), (0 : Spin))) ((1 : Spin), (0 : Spin))
  rw [isingLeftPauliXGenerator_entry, Matrix.zero_apply] at hentry
  exact Complex.I_ne_zero hentry

theorem isingLeftPauliX_dynamics_nontrivial :
    HasDerivAt (fun t : ℝ => isingHeisenberg t leftPauliX)
        isingLeftPauliXGenerator 0 ∧
      isingLeftPauliXGenerator ≠ 0 := by
  exact ⟨hasDerivAt_stoneFlow_zero isingHamiltonian leftPauliX,
    isingLeftPauliXGenerator_ne_zero⟩

/-- The interaction term is load-bearing for the committed local response:
the coupled generator is nonzero, whereas the scalar interaction-deletion
control leaves the same observable fixed for every parameter value. -/
theorem isingInteraction_load_bearing :
    isingLeftPauliXGenerator ≠ 0 ∧
      ∀ t : ℝ, uncoupledHeisenberg t leftPauliX = leftPauliX :=
  ⟨isingLeftPauliXGenerator_ne_zero,
    fun t => uncoupledHeisenberg_eq t leftPauliX⟩

end

end OPH.QFT.FiniteTwoSiteIsingField

-- Axiom audit: all declarations must remain on the standard Mathlib basis.
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingHamiltonian_posSemidef
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingHamiltonianOperator_isPositive
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingHamiltonianOperator_groundVector
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingGroundSpace_degenerate
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingGroundDensity_stationary
#print axioms OPH.QFT.FiniteTwoSiteIsingField.left_right_equal_time_locality
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingHamiltonian_genuinely_two_site
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingHamiltonian_not_sum_one_site
#print axioms OPH.QFT.FiniteTwoSiteIsingField.uncoupledHeisenberg_eq
#print axioms OPH.QFT.FiniteTwoSiteIsingField.uncoupledLeftPauliXGenerator_eq_zero
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingLeftPauliX_dynamics_nontrivial
#print axioms OPH.QFT.FiniteTwoSiteIsingField.isingInteraction_load_bearing
