import QFT.SourceOperatorGeneration
import ObserverPatchHolography.Locality.NoSignalling

/-!
# Joint two-slot factorisation of the designated observer pair

The committed source-operator payload records step-aligned label paths
for the four rich observers.  The alignment is the payload's conditional
chain: one shared engine snapshot list, the pinned history window of 32
checked in the run config, and the exactly-32-step count of every rich
observer forcing zero per-observer drops, so equal step indices refer to
one global snapshot.  This module assembles the designated pair
(observer 86, observer 88) on the joint slot space
`Fin 13 × Fin 14` and proves the factor-localisation receipts the E1
reopening names:

* the star algebra generated by observer 86's **lifted** source
  operators is exactly the left tensor-factor subalgebra (the range of
  `A ↦ A ⊗ₖ 1`), and symmetrically for observer 88 on the right; the
  factors of the split are thereby identified with the two regional
  generated algebras, which the generic B4 helper leaves open;
* every element of the left slot commutes with every element of the
  right slot: locality holds by tensor-slot disjointness;
* the B4 no-signalling helper is consumed with the checkpoint-projector
  Kraus family built from the committed field table: observer 86's four
  checkpoint projectors form a complete family inside the identified
  left slot, and pinching by them leaves the right marginal exactly
  invariant;
* the conditional expectation onto the right slot carries an explicit
  matrix-unit Kraus identity (the Kraus-criterion complete-positivity
  certificate), preserves positive semidefiniteness and the trace,
  fixes the right slot pointwise, scalarises the left slot, and is
  idempotent.  This is the trace- and positivity-preserving restriction
  map that replaces the impossible scalar-character restriction
  interface; its packaging through the committed `CMat`-typed CPTP
  predicate is left to the net-integration step.

Step-census receipts mirror the payload literals for the designated
pair: of the 31 counted joint steps, 4 change only the left label, 4
change only the right label, 14 change both, and 9 change neither.

**Boundary.**  The slot assembly (distinct observers as distinct tensor
factors) and the label conventions are declared postprocessors; the
paths, alphabets, and counts are post-hoc transcriptions of committed
run outputs, not preregistered, and ineligible as validation.  No region
lattice over a consensus tower, physical channel, instrument, causality,
or prediction is constructed here.  Issue #692 remains open for source
selection of the joint carrier, slot split, and regional attachment.
Closed issue #712 consumes the older finite-net interface and does not
supply that bridge.
-/

namespace OPH.QFT

open Matrix
open Kronecker
open scoped ComplexOrder

noncomputable section

variable {α β : Type*} [Fintype α] [Fintype β] [DecidableEq α] [DecidableEq β]

/-! ## The two slot embeddings -/

/-- The left slot embedding `A ↦ A ⊗ₖ 1` as a star algebra
homomorphism. -/
def slotLeft (β : Type*) [Fintype β] [DecidableEq β] :
    Matrix α α ℂ →⋆ₐ[ℂ] Matrix (α × β) (α × β) ℂ where
  toFun A := A ⊗ₖ (1 : Matrix β β ℂ)
  map_one' := Matrix.one_kronecker_one
  map_mul' A B := by
    rw [← Matrix.mul_kronecker_mul, one_mul]
  map_zero' := Matrix.zero_kronecker _
  map_add' A B := Matrix.add_kronecker A B _
  commutes' c := by
    rw [Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one,
      Matrix.smul_kronecker, Matrix.one_kronecker_one]
  map_star' A := by
    simp only [Matrix.star_eq_conjTranspose, Matrix.conjTranspose_kronecker,
      Matrix.conjTranspose_one]

/-- The right slot embedding `B ↦ 1 ⊗ₖ B` as a star algebra
homomorphism. -/
def slotRight (α : Type*) [Fintype α] [DecidableEq α] :
    Matrix β β ℂ →⋆ₐ[ℂ] Matrix (α × β) (α × β) ℂ where
  toFun B := (1 : Matrix α α ℂ) ⊗ₖ B
  map_one' := Matrix.one_kronecker_one
  map_mul' A B := by
    rw [← Matrix.mul_kronecker_mul, one_mul]
  map_zero' := Matrix.kronecker_zero _
  map_add' A B := Matrix.kronecker_add _ A B
  commutes' c := by
    rw [Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one,
      Matrix.kronecker_smul, Matrix.one_kronecker_one]
  map_star' A := by
    simp only [Matrix.star_eq_conjTranspose, Matrix.conjTranspose_kronecker,
      Matrix.conjTranspose_one]

/-- **Slot locality.**  Every left-slot element commutes with every
right-slot element: the two identified regional algebras commute
elementwise. -/
theorem slot_commute {X Y : Matrix (α × β) (α × β) ℂ}
    (hX : X ∈ (slotLeft β (α := α)).range)
    (hY : Y ∈ (slotRight α (β := β)).range) :
    Commute X Y := by
  obtain ⟨A, rfl⟩ := hX
  obtain ⟨B, rfl⟩ := hY
  show A ⊗ₖ (1 : Matrix β β ℂ) * (1 : Matrix α α ℂ) ⊗ₖ B =
    (1 : Matrix α α ℂ) ⊗ₖ B * (A ⊗ₖ (1 : Matrix β β ℂ))
  rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul,
    one_mul, mul_one, one_mul, mul_one]

/-- The bridge to the committed B4 helper: the slot embedding is the
declared `liftLeft`. -/
theorem slotLeft_eq_liftLeft (A : Matrix α α ℂ) :
    slotLeft β A = OPH.Locality.liftLeft A := by
  ext z z'
  simp [slotLeft, OPH.Locality.liftLeft, Matrix.kroneckerMap_apply,
    Matrix.one_apply]

/-! ## Factor localisation of the designated pair -/

/-- The joint slot space of the designated pair `(86, 88)`. -/
abbrev JointIndex := Fin 13 × Fin 14

/-- Observer 86's generated algebra, lifted into the left slot, is
exactly the left factor: the factors of the split are identified with
the regional generated algebras. -/
theorem obs86_lifted_eq_leftSlot :
    StarSubalgebra.map (slotLeft (Fin 14)) obs86.sourceAlgebra =
      (slotLeft (Fin 14) (α := Fin 13)).range := by
  rw [obs86_sourceAlgebra_eq_top]
  exact (StarAlgHom.range_eq_map_top _).symm

/-- Observer 88's generated algebra, lifted into the right slot, is
exactly the right factor. -/
theorem obs88_lifted_eq_rightSlot :
    StarSubalgebra.map (slotRight (Fin 13)) obs88.sourceAlgebra =
      (slotRight (Fin 13) (β := Fin 14)).range := by
  rw [obs88_sourceAlgebra_eq_top]
  exact (StarAlgHom.range_eq_map_top _).symm

/-! ## The B4 helper consumed with a source Kraus family -/

/-- Observer 86's checkpoint projectors: the diagonal projectors of the
four realized `checkpoint_class` values. -/
def chk86 (v : Fin 4) : Matrix (Fin 13) (Fin 13) ℂ :=
  Matrix.diagonal fun s => if obs86.tbl s 1 = (v : ℕ) then 1 else 0

/-- Every realized checkpoint value lies below four. -/
theorem chk86_value_lt : ∀ s : Fin 13, obs86.tbl s 1 < 4 := by decide

/-- One-hot summation for a bounded value. -/
theorem sum_indicator_val {n : ℕ} (c : ℕ) (hc : c < n) :
    ∑ v : Fin n, (if c = (v : ℕ) then (1 : ℂ) else 0) = 1 := by
  have hcond : ∀ v : Fin n, (c = (v : ℕ)) ↔ (v = ⟨c, hc⟩) := by
    intro v
    constructor
    · intro h
      exact Fin.ext h.symm
    · intro h
      subst h
      rfl
  simp_rw [hcond]
  simp

/-- The checkpoint projectors are self-adjoint. -/
theorem chk86_conjTranspose (v : Fin 4) : (chk86 v)ᴴ = chk86 v := by
  unfold chk86
  rw [Matrix.diagonal_conjTranspose]
  congr 1
  funext s
  by_cases h : obs86.tbl s 1 = (v : ℕ) <;> simp [h, Pi.star_apply]

/-- The checkpoint projectors are idempotent. -/
theorem chk86_idem (v : Fin 4) : chk86 v * chk86 v = chk86 v := by
  unfold chk86
  rw [Matrix.diagonal_mul_diagonal]
  congr 1
  funext s
  by_cases h : obs86.tbl s 1 = (v : ℕ) <;> simp [h]

/-- The checkpoint projectors form a complete Kraus family. -/
theorem chk86_complete :
    ∑ v : Fin 4, (chk86 v)ᴴ * chk86 v = 1 := by
  calc ∑ v : Fin 4, (chk86 v)ᴴ * chk86 v
      = ∑ v : Fin 4, chk86 v := by
        refine Finset.sum_congr rfl fun v _ => ?_
        rw [chk86_conjTranspose v, chk86_idem v]
    _ = 1 := by
        unfold chk86
        have hds : (∑ v : Fin 4, Matrix.diagonal fun s =>
            if obs86.tbl s 1 = (v : ℕ) then (1 : ℂ) else 0) =
            Matrix.diagonal fun s => ∑ v : Fin 4,
              if obs86.tbl s 1 = (v : ℕ) then (1 : ℂ) else 0 := by
          ext a b
          rw [Matrix.sum_apply]
          by_cases h : a = b
          · subst h
            simp [Matrix.diagonal]
          · simp [Matrix.diagonal, h]
        rw [hds]
        have hone : (fun s => ∑ v : Fin 4,
            if obs86.tbl s 1 = (v : ℕ) then (1 : ℂ) else 0) =
            fun _ => (1 : ℂ) := by
          funext s
          exact sum_indicator_val _ (chk86_value_lt s)
        rw [hone, Matrix.diagonal_one]

/-- The checkpoint projectors sum to the identity. -/
theorem chk86_sum : ∑ v : Fin 4, chk86 v = 1 := by
  have h := chk86_complete
  calc ∑ v : Fin 4, chk86 v
      = ∑ v : Fin 4, (chk86 v)ᴴ * chk86 v := by
        refine Finset.sum_congr rfl fun v _ => ?_
        rw [chk86_conjTranspose v, chk86_idem v]
    _ = 1 := h

/-- The checkpoint Kraus operators live inside the identified left
slot. -/
theorem chk86_lift_mem_leftSlot (v : Fin 4) :
    OPH.Locality.liftLeft (β := Fin 14) (chk86 v) ∈
      (slotLeft (Fin 14) (α := Fin 13)).range := by
  exact ⟨chk86 v, (slotLeft_eq_liftLeft (chk86 v))⟩

/-- **Regional no-signalling, consumed.**  Pinching the joint state by
observer 86's checkpoint projectors, lifted into the identified left
slot, leaves observer 88's marginal exactly invariant. -/
theorem obs86_checkpoint_pinch_no_signalling
    (M : Matrix JointIndex JointIndex ℂ) :
    OPH.Locality.ptraceFst
        (∑ v : Fin 4,
          OPH.Locality.liftLeft (chk86 v) * M *
            (OPH.Locality.liftLeft (chk86 v))ᴴ) =
      OPH.Locality.ptraceFst M :=
  OPH.Locality.ptraceFst_local_kraus Finset.univ chk86 chk86_complete M

/-! ## The CP conditional expectation onto the right slot -/

omit [DecidableEq α] [DecidableEq β] in
/-- The partial trace over the left slot reproduces the trace. -/
theorem ptraceFst_trace (M : Matrix (α × β) (α × β) ℂ) :
    (OPH.Locality.ptraceFst M).trace = M.trace := by
  unfold OPH.Locality.ptraceFst Matrix.trace
  rw [Fintype.sum_prod_type]
  exact Finset.sum_comm

omit [Fintype β] [DecidableEq β] in
/-- The partial trace of a right-slot element. -/
theorem ptraceFst_slotRight (B : Matrix β β ℂ) :
    OPH.Locality.ptraceFst ((1 : Matrix α α ℂ) ⊗ₖ B) =
      (Fintype.card α : ℂ) • B := by
  ext b b'
  unfold OPH.Locality.ptraceFst
  simp only [Matrix.kroneckerMap_apply, Matrix.smul_apply, smul_eq_mul]
  have hred : (∑ x : α, (1 : Matrix α α ℂ) x x * B b b') =
      (Fintype.card α : ℂ) * B b b' := by
    simp [Matrix.one_apply_eq, Finset.sum_const, Finset.card_univ,
      nsmul_eq_mul]
  exact hred

omit [Fintype β] [DecidableEq α] in
/-- The partial trace of a left-slot element. -/
theorem ptraceFst_slotLeft (A : Matrix α α ℂ) :
    OPH.Locality.ptraceFst (A ⊗ₖ (1 : Matrix β β ℂ)) =
      A.trace • (1 : Matrix β β ℂ) := by
  ext b b'
  unfold OPH.Locality.ptraceFst
  simp only [Matrix.kroneckerMap_apply, Matrix.smul_apply, smul_eq_mul]
  have htr : A.trace = ∑ x : α, A x x := rfl
  have hred : (∑ x : α, A x x * (1 : Matrix β β ℂ) b b') =
      A.trace * (1 : Matrix β β ℂ) b b' := by
    rw [← Finset.sum_mul, htr]
  exact hred

/-- The conditional expectation onto the right slot. -/
def rightSlotExpectation :
    Matrix (α × β) (α × β) ℂ →ₗ[ℂ] Matrix (α × β) (α × β) ℂ where
  toFun M := (Fintype.card α : ℂ)⁻¹ •
    ((1 : Matrix α α ℂ) ⊗ₖ OPH.Locality.ptraceFst M)
  map_add' M N := by
    unfold OPH.Locality.ptraceFst
    rw [← smul_add, ← Matrix.kronecker_add]
    congr 2
    ext b b'
    simp [Finset.sum_add_distrib]
  map_smul' c M := by
    unfold OPH.Locality.ptraceFst
    rw [RingHom.id_apply, smul_comm]
    congr 1
    rw [← Matrix.kronecker_smul]
    congr 1
    ext b b'
    simp [Finset.mul_sum]

/-- The matrix-unit Kraus identity of the conditional expectation:
conjugating by every left-slot matrix unit sums to the right-slot
replacement of the partial trace. -/
theorem sum_single_conj_eq_slotRight_ptraceFst
    (M : Matrix (α × β) (α × β) ℂ) :
    ∑ p : α × α,
        OPH.Locality.liftLeft (β := β) (Matrix.single p.1 p.2 (1 : ℂ)) * M *
          (OPH.Locality.liftLeft (β := β) (Matrix.single p.1 p.2 (1 : ℂ)))ᴴ =
      (1 : Matrix α α ℂ) ⊗ₖ OPH.Locality.ptraceFst M := by
  ext z z'
  rw [Matrix.sum_apply]
  have hterm : ∀ p : α × α,
      (OPH.Locality.liftLeft (β := β) (Matrix.single p.1 p.2 (1 : ℂ)) * M *
        (OPH.Locality.liftLeft (β := β)
          (Matrix.single p.1 p.2 (1 : ℂ)))ᴴ) z z' =
      if p.1 = z.1 ∧ p.1 = z'.1 then M (p.2, z.2) (p.2, z'.2) else 0 := by
    intro p
    rw [OPH.Locality.liftLeft_conj_apply]
    rw [Finset.sum_eq_single p.2
      (fun c _ hc => by
        have hzero : Matrix.single p.1 p.2 (1 : ℂ) z.1 c = 0 := by
          simp [Matrix.single, Ne.symm hc]
        simp [hzero])
      (fun h => absurd (Finset.mem_univ _) h)]
    rw [Finset.sum_eq_single p.2
      (fun c' _ hc' => by
        have hzero : Matrix.single p.1 p.2 (1 : ℂ) z'.1 c' = 0 := by
          simp [Matrix.single, Ne.symm hc']
        simp [hzero])
      (fun h => absurd (Finset.mem_univ _) h)]
    by_cases h1 : p.1 = z.1 <;> by_cases h2 : p.1 = z'.1 <;>
      simp [Matrix.single, h1, h2]
  rw [Finset.sum_congr rfl fun p _ => hterm p]
  by_cases hz : z.1 = z'.1
  · simp [Fintype.sum_prod_type, hz, Finset.sum_ite_eq',
      OPH.Locality.ptraceFst, Matrix.kroneckerMap_apply, Matrix.one_apply]
  · have hfalse : ∀ p1 : α, ¬ (p1 = z.1 ∧ p1 = z'.1) := by
      intro p1 hp
      exact hz (hp.1 ▸ hp.2 ▸ rfl)
    simp [hfalse, OPH.Locality.ptraceFst, Matrix.kroneckerMap_apply, hz]

omit [Fintype β] [DecidableEq β] in
/-- The conditional expectation fixes the right slot pointwise. -/
theorem rightSlotExpectation_fixes_right [Nonempty α] (B : Matrix β β ℂ) :
    rightSlotExpectation ((1 : Matrix α α ℂ) ⊗ₖ B) =
      (1 : Matrix α α ℂ) ⊗ₖ B := by
  have hcard : (Fintype.card α : ℂ) ≠ 0 :=
    Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have h : rightSlotExpectation ((1 : Matrix α α ℂ) ⊗ₖ B) =
      (Fintype.card α : ℂ)⁻¹ • ((1 : Matrix α α ℂ) ⊗ₖ
        OPH.Locality.ptraceFst ((1 : Matrix α α ℂ) ⊗ₖ B)) := rfl
  rw [h, ptraceFst_slotRight, Matrix.kronecker_smul, smul_smul,
    inv_mul_cancel₀ hcard, one_smul]

omit [Fintype β] in
/-- The conditional expectation scalarises the left slot: a left-slot
observable is replaced by its normalized trace. -/
theorem rightSlotExpectation_scalarises_left [Nonempty α]
    (A : Matrix α α ℂ) :
    rightSlotExpectation (A ⊗ₖ (1 : Matrix β β ℂ)) =
      ((Fintype.card α : ℂ)⁻¹ * A.trace) • 1 := by
  have h : rightSlotExpectation (A ⊗ₖ (1 : Matrix β β ℂ)) =
      (Fintype.card α : ℂ)⁻¹ • ((1 : Matrix α α ℂ) ⊗ₖ
        OPH.Locality.ptraceFst (A ⊗ₖ (1 : Matrix β β ℂ))) := rfl
  rw [h, ptraceFst_slotLeft, Matrix.kronecker_smul, smul_smul,
    Matrix.one_kronecker_one]

omit [Fintype β] [DecidableEq β] in
/-- The conditional expectation is idempotent. -/
theorem rightSlotExpectation_idem [Nonempty α]
    (M : Matrix (α × β) (α × β) ℂ) :
    rightSlotExpectation (α := α) (β := β)
        (rightSlotExpectation M) = rightSlotExpectation M := by
  have h : rightSlotExpectation (α := α) (β := β) M =
      (Fintype.card α : ℂ)⁻¹ •
        ((1 : Matrix α α ℂ) ⊗ₖ OPH.Locality.ptraceFst M) := rfl
  rw [h, map_smul, rightSlotExpectation_fixes_right, ← h]

omit [DecidableEq β] in
/-- The conditional expectation preserves the trace. -/
theorem rightSlotExpectation_trace [Nonempty α]
    (M : Matrix (α × β) (α × β) ℂ) :
    (rightSlotExpectation M).trace = M.trace := by
  have hcard : (Fintype.card α : ℂ) ≠ 0 :=
    Nat.cast_ne_zero.mpr Fintype.card_ne_zero
  have h : rightSlotExpectation (α := α) (β := β) M =
      (Fintype.card α : ℂ)⁻¹ • ((1 : Matrix α α ℂ) ⊗ₖ
        OPH.Locality.ptraceFst M) := rfl
  rw [h, Matrix.trace_smul, Matrix.trace_kronecker, Matrix.trace_one,
    ptraceFst_trace, smul_eq_mul, ← mul_assoc, inv_mul_cancel₀ hcard,
    one_mul]

/-- The conditional expectation preserves positive semidefiniteness:
together with its matrix-unit Kraus identity this is the standard
Kraus-criterion complete-positivity certificate. -/
theorem rightSlotExpectation_posSemidef [Nonempty α]
    {M : Matrix (α × β) (α × β) ℂ} (hM : M.PosSemidef) :
    (rightSlotExpectation (α := α) (β := β) M).PosSemidef := by
  have h : rightSlotExpectation (α := α) (β := β) M =
      (Fintype.card α : ℂ)⁻¹ • ∑ p : α × α,
        OPH.Locality.liftLeft (β := β) (Matrix.single p.1 p.2 (1 : ℂ)) * M *
          (OPH.Locality.liftLeft (β := β)
            (Matrix.single p.1 p.2 (1 : ℂ)))ᴴ := by
    rw [sum_single_conj_eq_slotRight_ptraceFst]
    rfl
  rw [h]
  have hnn : (0 : ℂ) ≤ (Fintype.card α : ℂ)⁻¹ := by
    rw [← Complex.ofReal_natCast, ← Complex.ofReal_inv]
    exact_mod_cast inv_nonneg.mpr (Nat.cast_nonneg _)
  exact (Matrix.posSemidef_sum _ fun p _ =>
    hM.mul_mul_conjTranspose_same _).smul hnn

/-! ## Step-census receipts of the designated pair -/

/-- The step-aligned joint path of the designated pair. -/
def jointPath : Fin 32 → Fin 13 × Fin 14 :=
  fun t => (obs86.path t, obs88.path t)

/-- Census of the 31 joint steps: 4 left-only changes, 4 right-only
changes, 14 double changes, 9 no-changes. -/
theorem jointPath_census :
    ((Finset.univ : Finset (Fin 31)).filter fun t =>
        jointPath t.castSucc ≠ jointPath t.succ ∧
          (jointPath t.castSucc).2 = (jointPath t.succ).2).card = 4 ∧
    ((Finset.univ : Finset (Fin 31)).filter fun t =>
        jointPath t.castSucc ≠ jointPath t.succ ∧
          (jointPath t.castSucc).1 = (jointPath t.succ).1).card = 4 ∧
    ((Finset.univ : Finset (Fin 31)).filter fun t =>
        (jointPath t.castSucc).1 ≠ (jointPath t.succ).1 ∧
          (jointPath t.castSucc).2 ≠ (jointPath t.succ).2).card = 14 ∧
    ((Finset.univ : Finset (Fin 31)).filter fun t =>
        jointPath t.castSucc = jointPath t.succ).card = 9 := by
  decide

end

end OPH.QFT

-- Axiom audit: no project-specific axiom or admission is permitted here.
#print axioms OPH.QFT.slot_commute
#print axioms OPH.QFT.obs86_lifted_eq_leftSlot
#print axioms OPH.QFT.obs88_lifted_eq_rightSlot
#print axioms OPH.QFT.chk86_complete
#print axioms OPH.QFT.obs86_checkpoint_pinch_no_signalling
#print axioms OPH.QFT.sum_single_conj_eq_slotRight_ptraceFst
#print axioms OPH.QFT.rightSlotExpectation_fixes_right
#print axioms OPH.QFT.rightSlotExpectation_scalarises_left
#print axioms OPH.QFT.rightSlotExpectation_idem
#print axioms OPH.QFT.rightSlotExpectation_trace
#print axioms OPH.QFT.rightSlotExpectation_posSemidef
#print axioms OPH.QFT.jointPath_census
