import QFT.TowerAnchoredDiamond
import QFT.SourceCorrelationCapstone

/-!
# A finite one-step net-evolution interface and committed candidates

This module gives a finite **one-step** algebraic interface related to the
open PR-58 direction.  It is not a full time-slice or Cauchy-evolution
interface: no geometry, clock, source selection, group action, or multi-step
cocycle is supplied.

The crucial generation clause is transport-aware.  Admitted data live in the
current regional algebra; the algebra generated by their image under the
one-step automorphism must equal the next regional algebra.  The earlier raw
comparison of unevolved admitted data with the next algebra artificially
forced next-algebra containment in the current algebra and therefore produced
an invalid step-invariance/no-new-net conclusion.  No such conclusion is made
here.

`stepEvolve` is a checked family of reindexing automorphisms on cyclic time
`Fin 32`.  For indices zero through thirty it follows the 31 actual adjacent
source rows.  At index thirty-one it closes the index cycle by swapping the
last and first labels even though the corresponding source-transition counts
are zero.  That terminal automorphism is a declared bookkeeping closure, not
a committed source transition.  `sourceGeneratorEvolution` inhabits the corrected
interface on a constant left region.  The single-projector walk candidate
still fails generation even after transport, because its evolved generator is
again one diagonal projector.  These are finite structural facts only; PR-58
and PR-52 remain open.
-/

set_option autoImplicit false

namespace OPH.QFT

open Matrix
open Kronecker
open scoped ComplexOrder

noncomputable section

/-! ## The finite one-step interface -/

/-- **A finite one-step net-evolution interface.**  Over one
conditional-expectation net it types: a
finite time index with an evolution direction `step`; a region family
`slice` per time; per-time ambient star-automorphisms `evolve` that are
net-compatible (each carries the slice region's algebra onto the
evolved slice region's algebra); admitted slice data lying in the slice
region's algebra; and a transport-aware generation property: the algebra
generated by the **evolved image** of the admitted data equals the next
regional algebra.  This is one-step typing only; it has no multi-step
coherence, Cauchy geometry, physical time, or source-selection field. -/
structure TimeIndexedNetEvolution (γ : Type*) [Fintype γ] [DecidableEq γ]
    (N : CPRegionalNet γ) where
  /-- The time index (finite boundary). -/
  Time : Type
  /-- The time index is finite. -/
  [timeFintype : Fintype Time]
  /-- The evolution direction on the time index. -/
  step : Time → Time
  /-- The region family: one admitted-slice region per time. -/
  slice : Time → N.Region
  /-- The admitted slice data at each time. -/
  admitted : Time → Set (Matrix γ γ ℂ)
  /-- The evolution: one ambient star-automorphism per time step. -/
  evolve : Time → (Matrix γ γ ℂ ≃⋆ₐ[ℂ] Matrix γ γ ℂ)
  /-- Net compatibility: each step's automorphism carries the slice
  region's algebra onto the evolved slice region's algebra. -/
  evolve_net_compatible : ∀ t : Time,
    StarSubalgebra.map (evolve t : Matrix γ γ ℂ →⋆ₐ[ℂ] Matrix γ γ ℂ)
        (N.localAlgebra (slice t)) =
      N.localAlgebra (slice (step t))
  /-- Admission: the admitted slice data lie in the slice region's
  algebra. -/
  admitted_mem : ∀ t : Time,
    admitted t ⊆ (N.localAlgebra (slice t) : Set (Matrix γ γ ℂ))
  /-- Transport-aware generation: evolve the admitted data first, then
  generate the next regional algebra. -/
  slice_generates : ∀ t : Time,
    StarAlgebra.adjoin ℂ
        ((evolve t : Matrix γ γ ℂ → Matrix γ γ ℂ) '' admitted t) =
      N.localAlgebra (slice (step t))

attribute [instance] TimeIndexedNetEvolution.timeFintype

/-! ## Evolved-data compatibility -/

/-- Admitted data are carried into the next regional algebra.  This is the
one-step compatibility that was absent when generation used the raw,
unevolved admitted set. -/
theorem TimeIndexedNetEvolution.evolved_admitted_mem
    {γ : Type*} [Fintype γ] [DecidableEq γ] {N : CPRegionalNet γ}
    (E : TimeIndexedNetEvolution γ N) (t : E.Time) :
    (E.evolve t : Matrix γ γ ℂ → Matrix γ γ ℂ) '' E.admitted t ⊆
      (N.localAlgebra (E.slice (E.step t)) : Set (Matrix γ γ ℂ)) := by
  rintro Y ⟨X, hX, rfl⟩
  rw [← E.evolve_net_compatible t]
  exact ⟨X, E.admitted_mem t hX, rfl⟩

/-- The scalars are a proper star subalgebra of a matrix algebra with
two distinct index points. -/
theorem matrix_bot_ne_top {γ : Type*} [Fintype γ] [DecidableEq γ]
    {g₀ g₁ : γ} (hg : g₀ ≠ g₁) :
    (⊥ : StarSubalgebra ℂ (Matrix γ γ ℂ)) ≠ ⊤ := by
  intro hbt
  have hmem : Matrix.single g₀ g₁ (1 : ℂ) ∈
      (⊥ : StarSubalgebra ℂ (Matrix γ γ ℂ)) := by
    rw [hbt]; trivial
  obtain ⟨c, hc⟩ := StarSubalgebra.mem_bot.mp hmem
  have hc' : c • (1 : Matrix γ γ ℂ) = Matrix.single g₀ g₁ (1 : ℂ) := by
    rw [← Algebra.algebraMap_eq_smul_one]; exact hc
  have hentry := congrFun (congrFun hc' g₀) g₁
  rw [Matrix.smul_apply, Matrix.one_apply_ne hg, smul_zero,
    Matrix.single_apply_same] at hentry
  exact zero_ne_one hentry

/-- The scalars are not the left slot: the left slot carries a
non-scalar diagonal. -/
theorem bot_ne_slotLeftRange {α β : Type*} [Fintype α] [DecidableEq α]
    [Fintype β] [DecidableEq β] {a₀ a₁ : α} (ha : a₀ ≠ a₁) (b₀ : β) :
    (⊥ : StarSubalgebra ℂ (Matrix (α × β) (α × β) ℂ)) ≠
      (slotLeft β (α := α)).range := by
  intro hbl
  have hmem : slotLeft β (Matrix.single a₀ a₀ (1 : ℂ)) ∈
      (⊥ : StarSubalgebra ℂ (Matrix (α × β) (α × β) ℂ)) := by
    rw [hbl]; exact ⟨_, rfl⟩
  obtain ⟨c, hc⟩ := StarSubalgebra.mem_bot.mp hmem
  have hc' : c • (1 : Matrix (α × β) (α × β) ℂ) =
      Matrix.single a₀ a₀ (1 : ℂ) ⊗ₖ (1 : Matrix β β ℂ) := by
    rw [← Algebra.algebraMap_eq_smul_one]; exact hc
  have h₀ := congrFun (congrFun hc' ((a₀, b₀) : α × β)) ((a₀, b₀) : α × β)
  have h₁ := congrFun (congrFun hc' ((a₁, b₀) : α × β)) ((a₁, b₀) : α × β)
  simp only [Matrix.smul_apply, Matrix.one_apply_eq, smul_eq_mul, mul_one,
    Matrix.kroneckerMap_apply, Matrix.single_apply_same] at h₀
  have hs : Matrix.single a₀ a₀ (1 : ℂ) a₁ a₁ = 0 :=
    Matrix.single_apply_of_ne _ _ _ _ _ (fun h => ha h.1)
  simp only [Matrix.smul_apply, Matrix.one_apply_eq, smul_eq_mul, mul_one,
    Matrix.kroneckerMap_apply, hs] at h₁
  rw [h₀] at h₁
  exact one_ne_zero h₁

/-- The scalars are not the right slot. -/
theorem bot_ne_slotRightRange {α β : Type*} [Fintype α] [DecidableEq α]
    [Fintype β] [DecidableEq β] (a₀ : α) {b₀ b₁ : β} (hb : b₀ ≠ b₁) :
    (⊥ : StarSubalgebra ℂ (Matrix (α × β) (α × β) ℂ)) ≠
      (slotRight α (β := β)).range := by
  intro hbr
  have hmem : slotRight α (Matrix.single b₀ b₀ (1 : ℂ)) ∈
      (⊥ : StarSubalgebra ℂ (Matrix (α × β) (α × β) ℂ)) := by
    rw [hbr]; exact ⟨_, rfl⟩
  obtain ⟨c, hc⟩ := StarSubalgebra.mem_bot.mp hmem
  have hc' : c • (1 : Matrix (α × β) (α × β) ℂ) =
      (1 : Matrix α α ℂ) ⊗ₖ Matrix.single b₀ b₀ (1 : ℂ) := by
    rw [← Algebra.algebraMap_eq_smul_one]; exact hc
  have h₀ := congrFun (congrFun hc' ((a₀, b₀) : α × β)) ((a₀, b₀) : α × β)
  have h₁ := congrFun (congrFun hc' ((a₀, b₁) : α × β)) ((a₀, b₁) : α × β)
  simp only [Matrix.smul_apply, Matrix.one_apply_eq, smul_eq_mul, mul_one,
    Matrix.kroneckerMap_apply, Matrix.single_apply_same] at h₀
  have hs : Matrix.single b₀ b₀ (1 : ℂ) b₁ b₁ = 0 :=
    Matrix.single_apply_of_ne _ _ _ _ _ (fun h => hb h.1)
  simp only [Matrix.smul_apply, Matrix.one_apply_eq, smul_eq_mul, mul_one,
    Matrix.kroneckerMap_apply, hs, mul_zero] at h₁
  rw [h₀] at h₁
  exact one_ne_zero h₁

/-- The left slot is not the right slot: a non-scalar left diagonal is
in no right-slot form. -/
theorem slotLeftRange_ne_slotRightRange {α β : Type*} [Fintype α]
    [DecidableEq α] [Fintype β] [DecidableEq β] {a₀ a₁ : α} (ha : a₀ ≠ a₁)
    (b₀ : β) :
    (slotLeft β (α := α)).range ≠ (slotRight α (β := β)).range := by
  intro hlr
  have hmem : slotLeft β (Matrix.single a₀ a₀ (1 : ℂ)) ∈
      (slotRight α (β := β)).range := by
    rw [← hlr]; exact ⟨_, rfl⟩
  obtain ⟨B, hB⟩ := hmem
  have hB' : (1 : Matrix α α ℂ) ⊗ₖ B =
      Matrix.single a₀ a₀ (1 : ℂ) ⊗ₖ (1 : Matrix β β ℂ) := hB
  have h₀ := congrFun (congrFun hB' ((a₀, b₀) : α × β)) ((a₀, b₀) : α × β)
  have h₁ := congrFun (congrFun hB' ((a₁, b₀) : α × β)) ((a₁, b₀) : α × β)
  simp only [Matrix.kroneckerMap_apply, Matrix.one_apply_eq, one_mul,
    mul_one, Matrix.single_apply_same] at h₀
  have hs : Matrix.single a₀ a₀ (1 : ℂ) a₁ a₁ = 0 :=
    Matrix.single_apply_of_ne _ _ _ _ _ (fun h => ha h.1)
  simp only [Matrix.kroneckerMap_apply, Matrix.one_apply_eq, one_mul, hs,
    zero_mul] at h₁
  rw [h₀] at h₁
  exact one_ne_zero h₁

/-- The left slot is proper: an off-diagonal right matrix unit lies
outside it. -/
theorem slotLeftRange_ne_top {α β : Type*} [Fintype α] [DecidableEq α]
    [Fintype β] [DecidableEq β] (a₀ : α) {b₀ b₁ : β} (hb : b₀ ≠ b₁) :
    (slotLeft β (α := α)).range ≠
      (⊤ : StarSubalgebra ℂ (Matrix (α × β) (α × β) ℂ)) := by
  intro hlt
  have hmem : (1 : Matrix α α ℂ) ⊗ₖ Matrix.single b₀ b₁ (1 : ℂ) ∈
      (slotLeft β (α := α)).range := by
    rw [hlt]; trivial
  obtain ⟨A, hA⟩ := hmem
  have hA' : A ⊗ₖ (1 : Matrix β β ℂ) =
      (1 : Matrix α α ℂ) ⊗ₖ Matrix.single b₀ b₁ (1 : ℂ) := hA
  have hentry := congrFun (congrFun hA' ((a₀, b₀) : α × β)) ((a₀, b₁) : α × β)
  simp only [Matrix.kroneckerMap_apply] at hentry
  rw [Matrix.one_apply_ne hb, mul_zero, Matrix.one_apply_eq, one_mul,
    Matrix.single_apply_same] at hentry
  exact zero_ne_one hentry

/-- The right slot is proper: an off-diagonal left matrix unit lies
outside it. -/
theorem slotRightRange_ne_top {α β : Type*} [Fintype α] [DecidableEq α]
    [Fintype β] [DecidableEq β] {a₀ a₁ : α} (ha : a₀ ≠ a₁) (b₀ : β) :
    (slotRight α (β := β)).range ≠
      (⊤ : StarSubalgebra ℂ (Matrix (α × β) (α × β) ℂ)) := by
  intro hrt
  have hmem : Matrix.single a₀ a₁ (1 : ℂ) ⊗ₖ (1 : Matrix β β ℂ) ∈
      (slotRight α (β := β)).range := by
    rw [hrt]; trivial
  obtain ⟨B, hB⟩ := hmem
  have hB' : (1 : Matrix α α ℂ) ⊗ₖ B =
      Matrix.single a₀ a₁ (1 : ℂ) ⊗ₖ (1 : Matrix β β ℂ) := hB
  have hentry := congrFun (congrFun hB' ((a₀, b₀) : α × β)) ((a₁, b₀) : α × β)
  simp only [Matrix.kroneckerMap_apply] at hentry
  rw [Matrix.one_apply_ne ha, zero_mul, Matrix.single_apply_same,
    Matrix.one_apply_eq, mul_one] at hentry
  exact zero_ne_one hentry

/-- The committed 86/247 region-to-algebra map is injective: the four
regional algebras of the committed diamond are pairwise distinct. -/
theorem twoSlotAlgebra247_injective :
    Function.Injective twoSlotAlgebra247 := by
  intro U V h
  cases U <;> cases V <;>
    first
    | rfl
    | exact absurd h (bot_ne_slotLeftRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 13))
    | exact absurd h.symm (bot_ne_slotLeftRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 13))
    | exact absurd h (bot_ne_slotRightRange (0 : Fin 13)
        (show (0 : Fin 13) ≠ 1 by decide))
    | exact absurd h.symm (bot_ne_slotRightRange (0 : Fin 13)
        (show (0 : Fin 13) ≠ 1 by decide))
    | exact absurd h (matrix_bot_ne_top
        (show ((0, 0) : PairIndex247) ≠ ((1, 1) : PairIndex247) by decide))
    | exact absurd h.symm (matrix_bot_ne_top
        (show ((0, 0) : PairIndex247) ≠ ((1, 1) : PairIndex247) by decide))
    | exact absurd h (slotLeftRange_ne_slotRightRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 13))
    | exact absurd h.symm (slotLeftRange_ne_slotRightRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 13))
    | exact absurd h (slotLeftRange_ne_top (0 : Fin 13)
        (show (0 : Fin 13) ≠ 1 by decide))
    | exact absurd h.symm (slotLeftRange_ne_top (0 : Fin 13)
        (show (0 : Fin 13) ≠ 1 by decide))
    | exact absurd h (slotRightRange_ne_top
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 13))
    | exact absurd h.symm (slotRightRange_ne_top
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 13))

/-- The committed 86/88 region-to-algebra map is injective: the four
regional algebras of that committed diamond are pairwise distinct. -/
theorem twoSlotAlgebra_injective :
    Function.Injective twoSlotAlgebra := by
  intro U V h
  cases U <;> cases V <;>
    first
    | rfl
    | exact absurd h (bot_ne_slotLeftRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 14))
    | exact absurd h.symm (bot_ne_slotLeftRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 14))
    | exact absurd h (bot_ne_slotRightRange (0 : Fin 13)
        (show (0 : Fin 14) ≠ 1 by decide))
    | exact absurd h.symm (bot_ne_slotRightRange (0 : Fin 13)
        (show (0 : Fin 14) ≠ 1 by decide))
    | exact absurd h (matrix_bot_ne_top
        (show ((0, 0) : PairIndex) ≠ ((1, 1) : PairIndex) by decide))
    | exact absurd h.symm (matrix_bot_ne_top
        (show ((0, 0) : PairIndex) ≠ ((1, 1) : PairIndex) by decide))
    | exact absurd h (slotLeftRange_ne_slotRightRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 14))
    | exact absurd h.symm (slotLeftRange_ne_slotRightRange
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 14))
    | exact absurd h (slotLeftRange_ne_top (0 : Fin 13)
        (show (0 : Fin 14) ≠ 1 by decide))
    | exact absurd h.symm (slotLeftRange_ne_top (0 : Fin 13)
        (show (0 : Fin 14) ≠ 1 by decide))
    | exact absurd h (slotRightRange_ne_top
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 14))
    | exact absurd h.symm (slotRightRange_ne_top
        (show (0 : Fin 13) ≠ 1 by decide) (0 : Fin 14))

/-! ## Generic reindexing helpers -/

/-- Reindexing along an equivalence preserves the identity matrix. -/
theorem reindex_one {α α' : Type*} [DecidableEq α] [DecidableEq α']
    (e : α ≃ α') :
    Matrix.reindex e e (1 : Matrix α α ℂ) = 1 := by
  rw [Matrix.reindex_apply]
  exact Matrix.submatrix_one_equiv e.symm

/-- Reindexing along a product equivalence factorises over the
Kronecker product. -/
theorem reindex_prodCongr_kronecker {α β α' β' : Type*}
    [DecidableEq α] [DecidableEq β] [DecidableEq α'] [DecidableEq β']
    (σ : α ≃ α') (τ : β ≃ β')
    (A : Matrix α α ℂ) (B : Matrix β β ℂ) :
    Matrix.reindex (σ.prodCongr τ) (σ.prodCongr τ) (A ⊗ₖ B) =
      (Matrix.reindex σ σ A) ⊗ₖ (Matrix.reindex τ τ B) := by
  ext ⟨a, b⟩ ⟨a', b'⟩
  simp [Matrix.reindex_apply, Matrix.submatrix_apply,
    Matrix.kroneckerMap_apply, Equiv.prodCongr_symm, Equiv.prodCongr_apply]

/-- Reindexing forward after reindexing backward is the identity. -/
theorem reindex_reindex_symm {α α' : Type*} (e : α ≃ α')
    (M : Matrix α' α' ℂ) :
    Matrix.reindex e e (Matrix.reindex e.symm e.symm M) = M := by
  rw [← Matrix.reindex_symm]
  exact (Matrix.reindex e e).apply_symm_apply M

/-- Reindexing carries a diagonal matrix unit to the diagonal matrix
unit of the image point. -/
theorem reindex_single {α α' : Type*} [DecidableEq α] [DecidableEq α']
    (e : α ≃ α') (x y : α) :
    Matrix.reindex e e (Matrix.single x y (1 : ℂ)) =
      Matrix.single (e x) (e y) 1 := by
  ext i j
  rw [Matrix.reindex_apply, Matrix.submatrix_apply,
    Matrix.single_apply, Matrix.single_apply]
  have h1 : (x = e.symm i) ↔ (e x = i) := by
    constructor
    · intro h
      rw [h, Equiv.apply_symm_apply]
    · intro h
      rw [← h, Equiv.symm_apply_apply]
  have h2 : (y = e.symm j) ↔ (e y = j) := by
    constructor
    · intro h
      rw [h, Equiv.apply_symm_apply]
    · intro h
      rw [← h, Equiv.symm_apply_apply]
  rw [if_congr (and_congr h1 h2) rfl rfl]

/-! ## The walk-step evolution of the support-disjoint pair -/

/-- The left-factor walk transposition at one cyclic index: it exchanges
observer 86's labels at `t` and `t + 1`.  At `t=31`, `Fin 32` wraps to zero;
that last swap is a declared cyclic closure rather than a source transition. -/
def walkSwapLeft (t : Fin 32) : Fin 13 ≃ Fin 13 :=
  Equiv.swap (obs86.path t) (obs86.path (t + 1))

/-- The right-factor walk transposition with the same declared cyclic endpoint
convention as `walkSwapLeft`. -/
def walkSwapRight (t : Fin 32) : Fin 13 ≃ Fin 13 :=
  Equiv.swap (obs247.path t) (obs247.path (t + 1))

/-- The joint walk-step equivalence: the product of the two marginal
transpositions. -/
def walkStepEquiv (t : Fin 32) : PairIndex247 ≃ PairIndex247 :=
  (walkSwapLeft t).prodCongr (walkSwapRight t)

/-- The walk-step evolution: matrix reindexing along the joint
walk-step equivalence, as an ambient star-automorphism. -/
def stepEvolve (t : Fin 32) :
    Matrix PairIndex247 PairIndex247 ℂ ≃⋆ₐ[ℂ]
      Matrix PairIndex247 PairIndex247 ℂ :=
  StarAlgEquiv.ofAlgEquiv (Matrix.reindexAlgEquiv ℂ ℂ (walkStepEquiv t))
    (fun M => by
      simp only [Matrix.reindexAlgEquiv_apply, Matrix.star_eq_conjTranspose]
      exact reindex_conjTranspose (walkStepEquiv t) M)

theorem stepEvolve_apply (t : Fin 32)
    (M : Matrix PairIndex247 PairIndex247 ℂ) :
    stepEvolve t M = Matrix.reindex (walkStepEquiv t) (walkStepEquiv t) M :=
  rfl

/-- The walk-step evolution acts factorwise on the left slot. -/
theorem stepEvolve_slotLeft (t : Fin 32) (A : Matrix (Fin 13) (Fin 13) ℂ) :
    stepEvolve t (A ⊗ₖ (1 : Matrix (Fin 13) (Fin 13) ℂ)) =
      (Matrix.reindex (walkSwapLeft t) (walkSwapLeft t) A) ⊗ₖ
        (1 : Matrix (Fin 13) (Fin 13) ℂ) := by
  rw [stepEvolve_apply]
  show Matrix.reindex ((walkSwapLeft t).prodCongr (walkSwapRight t))
      ((walkSwapLeft t).prodCongr (walkSwapRight t))
      (A ⊗ₖ (1 : Matrix (Fin 13) (Fin 13) ℂ)) = _
  rw [reindex_prodCongr_kronecker, reindex_one]

/-- The walk-step evolution acts factorwise on the right slot. -/
theorem stepEvolve_slotRight (t : Fin 32) (B : Matrix (Fin 13) (Fin 13) ℂ) :
    stepEvolve t ((1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ B) =
      (1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ
        (Matrix.reindex (walkSwapRight t) (walkSwapRight t) B) := by
  rw [stepEvolve_apply]
  show Matrix.reindex ((walkSwapLeft t).prodCongr (walkSwapRight t))
      ((walkSwapLeft t).prodCongr (walkSwapRight t))
      ((1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ B) = _
  rw [reindex_prodCongr_kronecker, reindex_one]

/-- **Net compatibility of the walk-step evolution.**  At every time,
the walk-step automorphism carries each regional algebra of the
committed 86/247 diamond onto itself. -/
theorem stepEvolve_maps_regions (t : Fin 32) (U : TwoSlotRegion) :
    StarSubalgebra.map
        (stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →⋆ₐ[ℂ]
          Matrix PairIndex247 PairIndex247 ℂ)
        (twoSlotAlgebra247 U) = twoSlotAlgebra247 U := by
  cases U
  · -- bottom: the scalars map onto the scalars.
    apply le_antisymm
    · rintro x ⟨y, hy, rfl⟩
      obtain ⟨c, rfl⟩ := StarSubalgebra.mem_bot.mp hy
      exact ⟨c, (AlgHomClass.commutes
        (stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →⋆ₐ[ℂ]
          Matrix PairIndex247 PairIndex247 ℂ) c).symm⟩
    · intro x hx
      obtain ⟨c, rfl⟩ := StarSubalgebra.mem_bot.mp hx
      exact ⟨algebraMap ℂ _ c, ⟨c, rfl⟩,
        AlgHomClass.commutes
          (stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →⋆ₐ[ℂ]
            Matrix PairIndex247 PairIndex247 ℂ) c⟩
  · -- left: the left factor maps onto the left factor.
    apply le_antisymm
    · rintro x ⟨y, ⟨A, rfl⟩, rfl⟩
      refine ⟨Matrix.reindex (walkSwapLeft t) (walkSwapLeft t) A, ?_⟩
      show (Matrix.reindex (walkSwapLeft t) (walkSwapLeft t) A) ⊗ₖ
          (1 : Matrix (Fin 13) (Fin 13) ℂ) =
        stepEvolve t (A ⊗ₖ (1 : Matrix (Fin 13) (Fin 13) ℂ))
      exact (stepEvolve_slotLeft t A).symm
    · rintro x ⟨B, rfl⟩
      refine ⟨slotLeft (Fin 13) (Matrix.reindex (walkSwapLeft t).symm
        (walkSwapLeft t).symm B), ⟨_, rfl⟩, ?_⟩
      show stepEvolve t ((Matrix.reindex (walkSwapLeft t).symm
          (walkSwapLeft t).symm B) ⊗ₖ (1 : Matrix (Fin 13) (Fin 13) ℂ)) =
        B ⊗ₖ (1 : Matrix (Fin 13) (Fin 13) ℂ)
      rw [stepEvolve_slotLeft, reindex_reindex_symm]
  · -- right: the right factor maps onto the right factor.
    apply le_antisymm
    · rintro x ⟨y, ⟨B, rfl⟩, rfl⟩
      refine ⟨Matrix.reindex (walkSwapRight t) (walkSwapRight t) B, ?_⟩
      show (1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ
          (Matrix.reindex (walkSwapRight t) (walkSwapRight t) B) =
        stepEvolve t ((1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ B)
      exact (stepEvolve_slotRight t B).symm
    · rintro x ⟨A, rfl⟩
      refine ⟨slotRight (Fin 13) (Matrix.reindex (walkSwapRight t).symm
        (walkSwapRight t).symm A), ⟨_, rfl⟩, ?_⟩
      show stepEvolve t ((1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ
          (Matrix.reindex (walkSwapRight t).symm
            (walkSwapRight t).symm A)) =
        (1 : Matrix (Fin 13) (Fin 13) ℂ) ⊗ₖ A
      rw [stepEvolve_slotRight, reindex_reindex_symm]
  · -- top: a star-algebra equivalence is surjective.
    show StarSubalgebra.map
        (stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →⋆ₐ[ℂ]
          Matrix PairIndex247 PairIndex247 ℂ) ⊤ = ⊤
    rw [← StarAlgHom.range_eq_map_top, StarSubalgebra.eq_top_iff]
    intro x
    exact ⟨(stepEvolve t).symm x, (stepEvolve t).apply_symm_apply x⟩

/-! ## The committed walk slices and their transport -/

/-- The committed walk-slice projector at one time: the diagonal matrix
unit of the committed joint label at that step. -/
def walkSliceProjector (t : Fin 32) : Matrix PairIndex247 PairIndex247 ℂ :=
  Matrix.single (jointPath247 t) (jointPath247 t) 1

/-- The joint walk-step equivalence carries the committed joint label
at time `t` to the committed joint label at time `t + 1`. -/
theorem walkStepEquiv_carries_path (t : Fin 32) :
    walkStepEquiv t (jointPath247 t) = jointPath247 (t + 1) := by
  have hp : jointPath247 t = (obs86.path t, obs247.path t) :=
    Prod.ext (jointPath247_marginals t).1 (jointPath247_marginals t).2
  have hp' : jointPath247 (t + 1) =
      (obs86.path (t + 1), obs247.path (t + 1)) :=
    Prod.ext (jointPath247_marginals (t + 1)).1
      (jointPath247_marginals (t + 1)).2
  rw [hp, hp']
  show (Equiv.swap (obs86.path t) (obs86.path (t + 1)) (obs86.path t),
      Equiv.swap (obs247.path t) (obs247.path (t + 1)) (obs247.path t)) =
    (obs86.path (t + 1), obs247.path (t + 1))
  rw [Equiv.swap_apply_left, Equiv.swap_apply_left]

/-- **Slice transport.**  The walk-step evolution carries the committed
slice projector at time `t` exactly to the slice projector at time
`t + 1`: the evolution is read from the committed path, not declared
beside it. -/
theorem stepEvolve_transports_slice (t : Fin 32) :
    stepEvolve t (walkSliceProjector t) = walkSliceProjector (t + 1) := by
  unfold walkSliceProjector
  rw [stepEvolve_apply, reindex_single, walkStepEquiv_carries_path]

/-- The walk-step evolution is not the identity at time zero: it moves
the committed slice projector. -/
theorem stepEvolve_moves_first_slice :
    stepEvolve 0 (walkSliceProjector 0) ≠ walkSliceProjector 0 := by
  rw [stepEvolve_transports_slice 0]
  intro h
  have hp1 : jointPath247 (0 + 1) = ((2, 4) : Fin 13 × Fin 13) := by decide
  have hp0 : jointPath247 0 = ((1, 5) : Fin 13 × Fin 13) := by decide
  have hentry := congrFun (congrFun h ((2, 4) : PairIndex247))
    ((2, 4) : PairIndex247)
  unfold walkSliceProjector at hentry
  rw [hp0, hp1, Matrix.single_apply_same] at hentry
  have hRHS : Matrix.single ((1, 5) : PairIndex247) ((1, 5) : PairIndex247)
      (1 : ℂ) ((2, 4) : PairIndex247) ((2, 4) : PairIndex247) = 0 :=
    Matrix.single_apply_of_ne _ _ _ _ _ (by decide)
  rw [hRHS] at hentry
  exact one_ne_zero hentry

/-! ## The generation failure of the walk-slice candidate -/

/-- The diagonal matrices over an arbitrary finite index form a star
subalgebra (the index-generic form of the committed
`diagonalStar`). -/
def diagonalStarOf (γ : Type*) [Fintype γ] [DecidableEq γ] :
    StarSubalgebra ℂ (Matrix γ γ ℂ) where
  carrier := {M | ∀ i j : γ, i ≠ j → M i j = 0}
  mul_mem' := by
    intro M N hM hN i j hij
    have : ∀ l : γ, M i l * N l j = 0 := by
      intro l
      by_cases hil : i = l
      · subst hil
        rw [hN i j hij, mul_zero]
      · rw [hM i l hil, zero_mul]
    simp [Matrix.mul_apply, this]
  add_mem' := by
    intro M N hM hN i j hij
    simp [Matrix.add_apply, hM i j hij, hN i j hij]
  algebraMap_mem' := by
    intro c i j hij
    simp [Matrix.algebraMap_matrix_apply, hij]
  star_mem' := by
    intro M hM i j hij
    have := hM j i (Ne.symm hij)
    simp [this]

/-- Each walk-slice projector is diagonal. -/
theorem walkSliceProjector_offdiag_zero (t : Fin 32) {i j : PairIndex247}
    (hij : i ≠ j) : walkSliceProjector t i j = 0 := by
  unfold walkSliceProjector
  apply Matrix.single_apply_of_ne
  rintro ⟨hi, hj⟩
  exact hij (hi.symm.trans hj)

/-- The top regional algebra of the committed 86/247 diamond. -/
theorem twoSlotNet247_top_localAlgebra :
    twoSlotNet247.localAlgebra
        (show twoSlotNet247.Region from TwoSlotRegion.top) = ⊤ := rfl

/-- A single walk projector does not generate the top regional algebra: its
generated algebra is diagonal, whereas the top algebra contains an
off-diagonal matrix unit. -/
theorem walkSlice_generation_fails (t : Fin 32) :
    StarAlgebra.adjoin ℂ ({walkSliceProjector t} :
        Set (Matrix PairIndex247 PairIndex247 ℂ)) ≠
      twoSlotNet247.localAlgebra
        (show twoSlotNet247.Region from TwoSlotRegion.top) := by
  rw [twoSlotNet247_top_localAlgebra]
  intro htop
  have hle : StarAlgebra.adjoin ℂ ({walkSliceProjector t} :
      Set (Matrix PairIndex247 PairIndex247 ℂ)) ≤
        diagonalStarOf PairIndex247 := by
    rw [StarAlgebra.adjoin_le_iff]
    intro M hM
    rw [Set.mem_singleton_iff] at hM
    subst hM
    intro i j hij
    exact walkSliceProjector_offdiag_zero t hij
  have hmem : Matrix.single ((0, 0) : PairIndex247) ((1, 1) : PairIndex247)
      (1 : ℂ) ∈ StarAlgebra.adjoin ℂ ({walkSliceProjector t} :
        Set (Matrix PairIndex247 PairIndex247 ℂ)) := by
    rw [htop]
    trivial
  have hzero := hle hmem ((0, 0) : PairIndex247) ((1, 1) : PairIndex247)
    (by decide)
  rw [Matrix.single_apply_same] at hzero
  exact one_ne_zero hzero

/-- **Transport-aware generation failure.**  Evolving the admitted singleton
first does not repair the candidate: it becomes the singleton containing the
next walk projector, which still generates only a diagonal algebra. -/
theorem walkSlice_evolved_generation_fails (t : Fin 32) :
    StarAlgebra.adjoin ℂ
        ((stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →
            Matrix PairIndex247 PairIndex247 ℂ) ''
          ({walkSliceProjector t} : Set (Matrix PairIndex247 PairIndex247 ℂ))) ≠
      twoSlotNet247.localAlgebra
        (show twoSlotNet247.Region from TwoSlotRegion.top) := by
  rw [Set.image_singleton, stepEvolve_transports_slice]
  exact walkSlice_generation_fails (t + 1)

/-- **The partial witness of the walk-slice candidate.**  Every field of the
finite one-step interface is supplied except transport-aware generation,
which stays an explicit (and refuted) hypothesis. -/
def walkSlicePartialWitness
    (hgen : ∀ t : Fin 32,
      StarAlgebra.adjoin ℂ
          ((stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →
              Matrix PairIndex247 PairIndex247 ℂ) ''
            ({walkSliceProjector t} : Set (Matrix PairIndex247 PairIndex247 ℂ))) =
        twoSlotNet247.localAlgebra
          (show twoSlotNet247.Region from TwoSlotRegion.top)) :
    TimeIndexedNetEvolution PairIndex247 twoSlotNet247 where
  Time := Fin 32
  timeFintype := inferInstance
  step := fun t => t + 1
  slice := fun _ => (show twoSlotNet247.Region from TwoSlotRegion.top)
  admitted := fun t => {walkSliceProjector t}
  evolve := stepEvolve
  evolve_net_compatible := fun t =>
    stepEvolve_maps_regions t TwoSlotRegion.top
  admitted_mem := fun t => by
    intro X _
    trivial
  slice_generates := hgen

/-! ## The full inhabitant -/

/-- The admitted source-generator slice: observer 86's committed source
generators (the counted transition operator and the field projectors),
lifted into the left slot. -/
def liftedSourceGenerators : Set (Matrix PairIndex247 PairIndex247 ℂ) :=
  (slotLeft (Fin 13) (α := Fin 13) : Matrix (Fin 13) (Fin 13) ℂ →⋆ₐ[ℂ]
    Matrix PairIndex247 PairIndex247 ℂ) '' obs86.generators

/-- The lifted source generators generate exactly the left regional
algebra, by the committed source-generation theorem. -/
theorem liftedSourceGenerators_generate_left :
    StarAlgebra.adjoin ℂ liftedSourceGenerators =
      (slotLeft (Fin 13) (α := Fin 13)).range := by
  unfold liftedSourceGenerators
  rw [← StarAlgHom.map_adjoin]
  exact obs86_lifted_eq_leftSlot247

/-- After one declared reindexing step, the evolved source generators still
generate the next (here also left) regional algebra. -/
theorem evolvedLiftedSourceGenerators_generate_left (t : Fin 32) :
    StarAlgebra.adjoin ℂ
        ((stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →
            Matrix PairIndex247 PairIndex247 ℂ) '' liftedSourceGenerators) =
      (slotLeft (Fin 13) (α := Fin 13)).range := by
  change StarAlgebra.adjoin ℂ
      ((stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →⋆ₐ[ℂ]
          Matrix PairIndex247 PairIndex247 ℂ) '' liftedSourceGenerators) =
    (slotLeft (Fin 13) (α := Fin 13)).range
  rw [← StarAlgHom.map_adjoin, liftedSourceGenerators_generate_left]
  exact stepEvolve_maps_regions t TwoSlotRegion.left

/-- **A full finite one-step inhabitant.**  The corrected interface is
inhabited over the
committed 86/247 diamond: cyclic time `Fin 32`, the walk-step evolution
(the 31 adjacent source pairs plus one declared terminal-to-initial bookkeeping
closure, not the identity and not the slot swap), the left region at
every time, and the admitted slice data given by the lifted committed
source generators.  Generation is proved only after applying each one-step
automorphism.  The region family is constant by construction; no theorem
claims that constancy is forced for other inhabitants, and this finite object
does not discharge the source/Cauchy content of PR-58. -/
def sourceGeneratorEvolution :
    TimeIndexedNetEvolution PairIndex247 twoSlotNet247 where
  Time := Fin 32
  timeFintype := inferInstance
  step := fun t => t + 1
  slice := fun _ => (show twoSlotNet247.Region from TwoSlotRegion.left)
  admitted := fun _ => liftedSourceGenerators
  evolve := stepEvolve
  evolve_net_compatible := fun t =>
    stepEvolve_maps_regions t TwoSlotRegion.left
  admitted_mem := fun t => by
    rintro X ⟨A, _, rfl⟩
    exact ⟨A, rfl⟩
  slice_generates := evolvedLiftedSourceGenerators_generate_left

/-- The region family of this particular inhabitant is constant by
construction. -/
theorem sourceGeneratorEvolution_slice_constant (t : Fin 32) :
    sourceGeneratorEvolution.slice t =
      (show twoSlotNet247.Region from TwoSlotRegion.left) := rfl

/-! ## The composed delimitation record -/

/-- **The walk-slice candidate, delimited in one statement.**  The committed
one-step maps are net-compatible, transport the walk projector, and the
transport-aware generation clause fails for that single-projector candidate
at every step. -/
theorem walkSlice_candidate_receipts :
    (∀ (t : Fin 32) (U : TwoSlotRegion),
      StarSubalgebra.map
          (stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →⋆ₐ[ℂ]
            Matrix PairIndex247 PairIndex247 ℂ)
          (twoSlotAlgebra247 U) = twoSlotAlgebra247 U) ∧
    (∀ t : Fin 32, stepEvolve t (walkSliceProjector t) =
      walkSliceProjector (t + 1)) ∧
    (∀ t : Fin 32,
      StarAlgebra.adjoin ℂ
          ((stepEvolve t : Matrix PairIndex247 PairIndex247 ℂ →
              Matrix PairIndex247 PairIndex247 ℂ) ''
            ({walkSliceProjector t} : Set (Matrix PairIndex247 PairIndex247 ℂ))) ≠
        twoSlotNet247.localAlgebra
          (show twoSlotNet247.Region from TwoSlotRegion.top)) :=
  ⟨stepEvolve_maps_regions, stepEvolve_transports_slice,
    walkSlice_evolved_generation_fails⟩

end

end OPH.QFT

-- Axiom audit: no project-specific axiom or admission is permitted here.
-- Expected axioms per declaration: propext, Classical.choice, Quot.sound.
#print axioms OPH.QFT.TimeIndexedNetEvolution.evolved_admitted_mem
#print axioms OPH.QFT.matrix_bot_ne_top
#print axioms OPH.QFT.bot_ne_slotLeftRange
#print axioms OPH.QFT.bot_ne_slotRightRange
#print axioms OPH.QFT.slotLeftRange_ne_slotRightRange
#print axioms OPH.QFT.slotLeftRange_ne_top
#print axioms OPH.QFT.slotRightRange_ne_top
#print axioms OPH.QFT.twoSlotAlgebra247_injective
#print axioms OPH.QFT.twoSlotAlgebra_injective
#print axioms OPH.QFT.reindex_one
#print axioms OPH.QFT.reindex_prodCongr_kronecker
#print axioms OPH.QFT.reindex_reindex_symm
#print axioms OPH.QFT.reindex_single
#print axioms OPH.QFT.walkSwapLeft
#print axioms OPH.QFT.walkSwapRight
#print axioms OPH.QFT.walkStepEquiv
#print axioms OPH.QFT.stepEvolve
#print axioms OPH.QFT.stepEvolve_apply
#print axioms OPH.QFT.stepEvolve_slotLeft
#print axioms OPH.QFT.stepEvolve_slotRight
#print axioms OPH.QFT.stepEvolve_maps_regions
#print axioms OPH.QFT.walkSliceProjector
#print axioms OPH.QFT.walkStepEquiv_carries_path
#print axioms OPH.QFT.stepEvolve_transports_slice
#print axioms OPH.QFT.stepEvolve_moves_first_slice
#print axioms OPH.QFT.diagonalStarOf
#print axioms OPH.QFT.walkSliceProjector_offdiag_zero
#print axioms OPH.QFT.twoSlotNet247_top_localAlgebra
#print axioms OPH.QFT.walkSlice_generation_fails
#print axioms OPH.QFT.walkSlice_evolved_generation_fails
#print axioms OPH.QFT.walkSlicePartialWitness
#print axioms OPH.QFT.liftedSourceGenerators
#print axioms OPH.QFT.liftedSourceGenerators_generate_left
#print axioms OPH.QFT.evolvedLiftedSourceGenerators_generate_left
#print axioms OPH.QFT.sourceGeneratorEvolution
#print axioms OPH.QFT.sourceGeneratorEvolution_slice_constant
#print axioms OPH.QFT.walkSlice_candidate_receipts
