import Mathlib

/-!
# Regional algebras generated by source-local transition operators

Literal mirror of `docs/E1_SOURCE_OPERATOR_PAYLOAD.json` of
`oph-physics-sim` (schema `oph.sim.e1_source_operator_payload.v1`, payload
sha256 `98d17ab4683eb967acd3b420ea96c14f6130b7802a61e7ef56561ef8f413ca6c`,
extracted post hoc from the retained gates-passing rich-fibre bundle
`runs/e1_prereg2_64k_20260810`): for each of the four committed rich
observers, the 32-step support-modal label path over the five packet
fields, the realized state alphabet, the counted transition operator, and
the field projectors.

The mathematical content is the adapter-preflight generation theorem the
completion plan names for E1: the star-algebra generated by one
observer's counted transition operator together with its diagonal field
projectors is the **full matrix algebra** on its realized alphabet.  The
proof route is reachability: the field projectors separate the realized
states (kernel-decided), so every diagonal matrix unit is a product of
projectors; compressing the transition operator between two diagonal
units extracts each counted step as a matrix unit; and the committed walk
visits every realized state, so products and adjoints of step units reach
every matrix unit.  A diagonal-only negative control proves that the
projectors alone stay inside the diagonal algebra, so the transition
operator is load-bearing.

**Boundary.**  The state alphabet, walk, and counts are post-hoc
transcriptions of committed run outputs; the extraction was not
preregistered and is ineligible as validation.  The generated algebras
replace the declared pair-groupoid enrichment of the earlier packet at
the level of one observer's realized label space; no region lattice,
restriction system, tensor factorisation, physical channel, instrument,
or prediction is constructed here.  Issue #692 stays open.
-/

namespace OPH.QFT

open Matrix
open scoped ComplexOrder

noncomputable section

/-! ## Generic reachability lemmas -/

/-- Indicator arithmetic for diagonal projector products. -/
theorem indicator_mul (a b : Prop) [Decidable a] [Decidable b] :
    (if a then (1 : ℂ) else 0) * (if b then 1 else 0) =
      if a ∧ b then 1 else 0 := by
  by_cases ha : a <;> by_cases hb : b <;> simp [ha, hb]

/-- The adjoint of a unit matrix entry. -/
theorem single_one_conjTranspose {k : ℕ} (i j : Fin k) :
    (Matrix.single i j (1 : ℂ))ᴴ = Matrix.single j i 1 := by
  ext a b
  simp only [Matrix.conjTranspose_apply]
  by_cases hja : j = a <;> by_cases hib : i = b <;>
    simp [Matrix.single, hja, hib, and_comm]

/-- **Reachability generation.**  If a star subalgebra of a matrix
algebra contains every diagonal matrix unit and the unit step of every
edge of a walk that visits every index, it is the whole algebra. -/
theorem adjoin_eq_top_of_walk {k n : ℕ}
    (A : StarSubalgebra ℂ (Matrix (Fin k) (Fin k) ℂ))
    (w : Fin (n + 1) → Fin k)
    (hsurj : ∀ j : Fin k, ∃ t, w t = j)
    (hdiag : ∀ i : Fin k, Matrix.single i i (1 : ℂ) ∈ A)
    (hstep : ∀ t : Fin n,
      Matrix.single (w t.castSucc) (w t.succ) (1 : ℂ) ∈ A) :
    A = ⊤ := by
  have hwalk : ∀ t : Fin (n + 1),
      Matrix.single (w 0) (w t) (1 : ℂ) ∈ A := by
    intro t
    induction t using Fin.induction with
    | zero => exact hdiag (w 0)
    | succ t ih =>
        have hmul := mul_mem ih (hstep t)
        rwa [Matrix.single_mul_single_same, one_mul] at hmul
  have hfrom : ∀ j : Fin k, Matrix.single (w 0) j (1 : ℂ) ∈ A := by
    intro j
    obtain ⟨t, rfl⟩ := hsurj j
    exact hwalk t
  have hunit : ∀ i j : Fin k, Matrix.single i j (1 : ℂ) ∈ A := by
    intro i j
    have hstar : Matrix.single i (w 0) (1 : ℂ) ∈ A := by
      have := star_mem (hfrom i)
      rwa [Matrix.star_eq_conjTranspose, single_one_conjTranspose] at this
    have hmul := mul_mem hstar (hfrom j)
    rwa [Matrix.single_mul_single_same, one_mul] at hmul
  rw [StarSubalgebra.eq_top_iff]
  intro X
  rw [Matrix.matrix_eq_sum_single X]
  refine sum_mem fun i _ => sum_mem fun j _ => ?_
  have : Matrix.single i j (X i j) = X i j • Matrix.single i j (1 : ℂ) := by
    rw [Matrix.smul_single, smul_eq_mul, mul_one]
  rw [this]
  exact SMulMemClass.smul_mem _ (hunit i j)

/-- The diagonal matrices form a star subalgebra. -/
def diagonalStar (k : ℕ) : StarSubalgebra ℂ (Matrix (Fin k) (Fin k) ℂ) where
  carrier := {M | ∀ i j : Fin k, i ≠ j → M i j = 0}
  mul_mem' := by
    intro M N hM hN i j hij
    have : ∀ l : Fin k, M i l * N l j = 0 := by
      intro l
      by_cases hil : i = l
      · subst hil
        rw [hN i j hij, mul_zero]
      · rw [hM i l hil, zero_mul]
    simp [Matrix.mul_apply, this]
  add_mem' := by
    intro M N hM hN i j hij
    simp [Matrix.add_apply, hM i j hij, hN i j hij]
  algebraMap_mem' := by
    intro c i j hij
    simp [Matrix.algebraMap_matrix_apply, hij]
  star_mem' := by
    intro M hM i j hij
    have := hM j i (Ne.symm hij)
    simp [this]

theorem single_not_mem_diagonalStar {k : ℕ} (i j : Fin k) (hij : i ≠ j) :
    Matrix.single i j (1 : ℂ) ∉ diagonalStar k := by
  intro h
  have := h i j hij
  simp [Matrix.single] at this

/-! ## The source walk data of one observer -/

/-- The payload literals of one observer: the field-value table of its
realized alphabet, the committed walk, and the counted transitions. -/
structure SourceWalkData (k n : ℕ) where
  tbl : Fin k → Fin 5 → ℕ
  path : Fin (n + 1) → Fin k
  cnt : Fin k → Fin k → ℕ

namespace SourceWalkData

variable {k n : ℕ} (d : SourceWalkData k n)

/-- The counted transition operator, as a complex matrix. -/
def transitionOp : Matrix (Fin k) (Fin k) ℂ :=
  fun i j => (d.cnt i j : ℂ)

/-- The diagonal field projector matching one field value of one realized
state. -/
def fieldProjector (f : Fin 5) (i : Fin k) : Matrix (Fin k) (Fin k) ℂ :=
  Matrix.diagonal fun s => if d.tbl s f = d.tbl i f then 1 else 0

/-- The source generators: the transition operator and the field
projectors. -/
def generators : Set (Matrix (Fin k) (Fin k) ℂ) :=
  {d.transitionOp} ∪ Set.range fun p : Fin 5 × Fin k =>
    d.fieldProjector p.1 p.2

/-- The regional algebra generated by the source operators. -/
def sourceAlgebra : StarSubalgebra ℂ (Matrix (Fin k) (Fin k) ℂ) :=
  StarAlgebra.adjoin ℂ d.generators

/-- Field separation: the five projectors of one state multiply to the
diagonal matrix unit of that state. -/
theorem projector_prod_eq_single
    (hsep : ∀ i s : Fin k,
      (d.tbl s 0 = d.tbl i 0 ∧ d.tbl s 1 = d.tbl i 1 ∧
        d.tbl s 2 = d.tbl i 2 ∧ d.tbl s 3 = d.tbl i 3 ∧
        d.tbl s 4 = d.tbl i 4) ↔ s = i)
    (i : Fin k) :
    d.fieldProjector 0 i * d.fieldProjector 1 i * d.fieldProjector 2 i *
        d.fieldProjector 3 i * d.fieldProjector 4 i =
      Matrix.single i i 1 := by
  unfold fieldProjector
  rw [Matrix.diagonal_mul_diagonal, Matrix.diagonal_mul_diagonal,
    Matrix.diagonal_mul_diagonal, Matrix.diagonal_mul_diagonal]
  have hdiag : (Matrix.single i i (1 : ℂ)) =
      Matrix.diagonal fun s => if s = i then 1 else 0 := by
    ext a b
    by_cases hia : i = a <;> by_cases hab : a = b <;>
      simp only [Matrix.single, Matrix.diagonal, Matrix.of_apply, hia, hab] <;>
      first
        | rfl
        | (simp_all; tauto)
  rw [hdiag]
  congr 1
  funext s
  rw [indicator_mul, indicator_mul, indicator_mul, indicator_mul]
  by_cases h : s = i
  · subst h
    simp
  · have hne := (not_iff_not.mpr (hsep i s)).mpr h
    simp only [h, if_false]
    rw [if_neg]
    intro hc
    exact hne ⟨hc.1.1.1.1, hc.1.1.1.2, hc.1.1.2, hc.1.2, hc.2⟩

/-- Every diagonal matrix unit lies in the source algebra. -/
theorem single_diag_mem
    (hsep : ∀ i s : Fin k,
      (d.tbl s 0 = d.tbl i 0 ∧ d.tbl s 1 = d.tbl i 1 ∧
        d.tbl s 2 = d.tbl i 2 ∧ d.tbl s 3 = d.tbl i 3 ∧
        d.tbl s 4 = d.tbl i 4) ↔ s = i)
    (i : Fin k) :
    Matrix.single i i (1 : ℂ) ∈ d.sourceAlgebra := by
  rw [← d.projector_prod_eq_single hsep i]
  have hp : ∀ f : Fin 5, d.fieldProjector f i ∈ d.sourceAlgebra :=
    fun f => StarAlgebra.subset_adjoin ℂ _
      (Or.inr ⟨(f, i), rfl⟩)
  exact mul_mem (mul_mem (mul_mem (mul_mem (hp 0) (hp 1)) (hp 2))
    (hp 3)) (hp 4)

/-- Every counted step unit lies in the source algebra. -/
theorem single_step_mem
    (hsep : ∀ i s : Fin k,
      (d.tbl s 0 = d.tbl i 0 ∧ d.tbl s 1 = d.tbl i 1 ∧
        d.tbl s 2 = d.tbl i 2 ∧ d.tbl s 3 = d.tbl i 3 ∧
        d.tbl s 4 = d.tbl i 4) ↔ s = i)
    {i j : Fin k} (hij : d.cnt i j ≠ 0) :
    Matrix.single i j (1 : ℂ) ∈ d.sourceAlgebra := by
  have hT : d.transitionOp ∈ d.sourceAlgebra :=
    StarAlgebra.subset_adjoin ℂ _ (Or.inl rfl)
  have hcompress :
      Matrix.single i i (1 : ℂ) * d.transitionOp *
          Matrix.single j j (1 : ℂ) =
        Matrix.single i j (d.transitionOp i j) := by
    rw [Matrix.single_mul_mul_single, one_mul, mul_one]
  have hmem : Matrix.single i j (d.transitionOp i j) ∈ d.sourceAlgebra := by
    rw [← hcompress]
    exact mul_mem (mul_mem (d.single_diag_mem hsep i) hT)
      (d.single_diag_mem hsep j)
  have hz : (d.transitionOp i j) ≠ 0 := by
    simpa [transitionOp] using Nat.cast_ne_zero.mpr hij
  have hscale :
      Matrix.single i j (1 : ℂ) =
        (d.transitionOp i j)⁻¹ • Matrix.single i j (d.transitionOp i j) := by
    rw [Matrix.smul_single, smul_eq_mul, inv_mul_cancel₀ hz]
  rw [hscale]
  exact SMulMemClass.smul_mem _ hmem

/-- **The generation theorem.**  The counted transition operator and the
field projectors of one committed observer generate the full matrix
algebra on its realized alphabet. -/
theorem sourceAlgebra_eq_top
    (hsep : ∀ i s : Fin k,
      (d.tbl s 0 = d.tbl i 0 ∧ d.tbl s 1 = d.tbl i 1 ∧
        d.tbl s 2 = d.tbl i 2 ∧ d.tbl s 3 = d.tbl i 3 ∧
        d.tbl s 4 = d.tbl i 4) ↔ s = i)
    (hsurj : ∀ j : Fin k, ∃ t, d.path t = j)
    (hcnt : ∀ t : Fin n,
      d.cnt (d.path t.castSucc) (d.path t.succ) ≠ 0) :
    d.sourceAlgebra = ⊤ :=
  adjoin_eq_top_of_walk d.sourceAlgebra d.path hsurj
    (d.single_diag_mem hsep)
    (fun t => d.single_step_mem hsep (hcnt t))

/-- **Negative control.**  The field projectors alone generate only
diagonal matrices; the transition operator is load-bearing. -/
theorem projectors_only_ne_top (hk : 1 < k) :
    StarAlgebra.adjoin ℂ
        (Set.range fun p : Fin 5 × Fin k => d.fieldProjector p.1 p.2) ≠
      ⊤ := by
  intro htop
  have hle : StarAlgebra.adjoin ℂ
      (Set.range fun p : Fin 5 × Fin k => d.fieldProjector p.1 p.2) ≤
        diagonalStar k := by
    rw [StarAlgebra.adjoin_le_iff]
    rintro M ⟨p, rfl⟩
    intro i j hij
    simp [fieldProjector, Matrix.diagonal, hij]
  have hmem : Matrix.single (⟨0, by omega⟩ : Fin k) (⟨1, hk⟩ : Fin k)
      (1 : ℂ) ∈ StarAlgebra.adjoin ℂ
        (Set.range fun p : Fin 5 × Fin k => d.fieldProjector p.1 p.2) := by
    rw [htop]
    exact StarSubalgebra.mem_top
  have h0 : (⟨0, by omega⟩ : Fin k) ≠ (⟨1, hk⟩ : Fin k) := by
    intro h
    have hv := congrArg Fin.val h
    simp at hv
  exact single_not_mem_diagonalStar _ _ h0 (hle hmem)

end SourceWalkData

/-! ## The four committed observers -/

/-- Observer 86: 13 realized states. -/
def obs86 : SourceWalkData 13 31 where
  tbl := fun i => ![![0,0,0,0,0],![0,0,0,0,3],![0,0,0,0,4],![0,0,0,0,7],
    ![0,0,1,0,6],![0,0,1,0,7],![0,1,1,0,3],![0,1,1,0,4],![0,1,1,0,5],
    ![0,1,1,0,6],![0,1,1,0,7],![0,2,0,0,0],![0,3,0,0,0]] i
  path := ![1,2,2,7,8,10,8,9,7,2,2,8,8,6,6,7,5,8,4,4,3,0,0,0,0,0,0,0,
    12,12,12,11]
  cnt := fun i => ![![6,0,0,0,0,0,0,0,0,0,0,0,1],![0,0,1,0,0,0,0,0,0,0,0,0,0],
    ![0,0,2,0,0,0,0,1,1,0,0,0,0],![1,0,0,0,0,0,0,0,0,0,0,0,0],
    ![0,0,0,1,1,0,0,0,0,0,0,0,0],![0,0,0,0,0,0,0,0,1,0,0,0,0],
    ![0,0,0,0,0,0,1,1,0,0,0,0,0],![0,0,1,0,0,1,0,0,1,0,0,0,0],
    ![0,0,0,0,1,0,1,0,1,1,1,0,0],![0,0,0,0,0,0,0,1,0,0,0,0,0],
    ![0,0,0,0,0,0,0,0,1,0,0,0,0],![0,0,0,0,0,0,0,0,0,0,0,0,0],
    ![0,0,0,0,0,0,0,0,0,0,0,1,2]] i

/-- Observer 88: 14 realized states. -/
def obs88 : SourceWalkData 14 31 where
  tbl := fun i => ![![0,0,0,0,3],![0,0,0,0,4],![0,0,0,0,5],![0,0,0,0,6],
    ![0,0,0,0,7],![0,0,1,0,0],![0,0,1,0,3],![0,0,1,0,4],![0,0,1,0,5],
    ![0,0,1,0,7],![0,1,1,0,4],![0,1,1,0,5],![0,1,1,0,6],![0,3,1,0,0]] i
  path := ![4,1,1,3,2,0,0,0,1,10,1,2,11,6,0,10,7,8,12,12,9,5,5,5,5,5,
    13,13,13,13,13,13]
  cnt := fun i => ![![2,1,0,0,0,0,0,0,0,0,1,0,0,0],
    ![0,1,1,1,0,0,0,0,0,0,1,0,0,0],![1,0,0,0,0,0,0,0,0,0,0,1,0,0],
    ![0,0,1,0,0,0,0,0,0,0,0,0,0,0],![0,1,0,0,0,0,0,0,0,0,0,0,0,0],
    ![0,0,0,0,0,4,0,0,0,0,0,0,0,1],![1,0,0,0,0,0,0,0,0,0,0,0,0,0],
    ![0,0,0,0,0,0,0,0,1,0,0,0,0,0],![0,0,0,0,0,0,0,0,0,0,0,0,1,0],
    ![0,0,0,0,0,1,0,0,0,0,0,0,0,0],![0,1,0,0,0,0,0,1,0,0,0,0,0,0],
    ![0,0,0,0,0,0,1,0,0,0,0,0,0,0],![0,0,0,0,0,0,0,0,0,1,0,0,1,0],
    ![0,0,0,0,0,0,0,0,0,0,0,0,0,5]] i

/-- Observer 247: 13 realized states. -/
def obs247 : SourceWalkData 13 31 where
  tbl := fun i => ![![0,0,0,0,0],![0,0,0,0,3],![0,0,0,0,4],![0,0,0,0,5],
    ![0,0,0,0,6],![0,0,0,0,7],![0,1,1,0,2],![0,1,1,0,4],![0,1,1,0,5],
    ![0,1,1,0,6],![0,1,1,0,7],![0,2,0,0,0],![0,3,0,0,0]] i
  path := ![5,4,6,6,8,10,10,9,7,7,7,3,5,1,4,4,2,3,4,4,5,0,0,0,0,0,0,0,
    12,12,11,11]
  cnt := fun i => ![![6,0,0,0,0,0,0,0,0,0,0,0,1],![0,0,0,0,1,0,0,0,0,0,0,0,0],
    ![0,0,0,1,0,0,0,0,0,0,0,0,0],![0,0,0,0,1,1,0,0,0,0,0,0,0],
    ![0,0,1,0,2,1,1,0,0,0,0,0,0],![1,1,0,0,1,0,0,0,0,0,0,0,0],
    ![0,0,0,0,0,0,1,0,1,0,0,0,0],![0,0,0,1,0,0,0,2,0,0,0,0,0],
    ![0,0,0,0,0,0,0,0,0,0,1,0,0],![0,0,0,0,0,0,0,1,0,0,0,0,0],
    ![0,0,0,0,0,0,0,0,0,1,1,0,0],![0,0,0,0,0,0,0,0,0,0,0,1,0],
    ![0,0,0,0,0,0,0,0,0,0,0,1,1]] i

/-- Observer 384: 12 realized states. -/
def obs384 : SourceWalkData 12 31 where
  tbl := fun i => ![![0,0,0,0,0],![0,0,0,0,2],![0,0,0,0,4],![0,0,0,0,5],
    ![0,0,0,0,6],![0,0,0,0,7],![0,0,1,0,5],![0,1,1,0,3],![0,1,1,0,4],
    ![0,1,1,0,5],![0,2,0,0,0],![0,3,0,0,0]] i
  path := ![5,2,2,1,3,3,9,7,8,8,8,9,9,9,4,8,8,6,4,4,5,0,0,0,0,0,0,0,
    11,11,11,10]
  cnt := fun i => ![![6,0,0,0,0,0,0,0,0,0,0,1],![0,0,0,1,0,0,0,0,0,0,0,0],
    ![0,1,1,0,0,0,0,0,0,0,0,0],![0,0,0,1,0,0,0,0,0,1,0,0],
    ![0,0,0,0,1,1,0,0,1,0,0,0],![1,0,1,0,0,0,0,0,0,0,0,0],
    ![0,0,0,0,1,0,0,0,0,0,0,0],![0,0,0,0,0,0,0,0,1,0,0,0],
    ![0,0,0,0,0,0,1,0,3,1,0,0],![0,0,0,0,1,0,0,1,0,2,0,0],
    ![0,0,0,0,0,0,0,0,0,0,0,0],![0,0,0,0,0,0,0,0,0,0,1,2]] i

/-- Observer 86's source operators generate its full matrix algebra. -/
theorem obs86_sourceAlgebra_eq_top : obs86.sourceAlgebra = ⊤ :=
  obs86.sourceAlgebra_eq_top (by decide) (by decide) (by decide)

/-- Observer 88's source operators generate its full matrix algebra. -/
theorem obs88_sourceAlgebra_eq_top : obs88.sourceAlgebra = ⊤ :=
  obs88.sourceAlgebra_eq_top (by decide) (by decide) (by decide)

/-- Observer 247's source operators generate its full matrix algebra. -/
theorem obs247_sourceAlgebra_eq_top : obs247.sourceAlgebra = ⊤ :=
  obs247.sourceAlgebra_eq_top (by decide) (by decide) (by decide)

/-- Observer 384's source operators generate its full matrix algebra. -/
theorem obs384_sourceAlgebra_eq_top : obs384.sourceAlgebra = ⊤ :=
  obs384.sourceAlgebra_eq_top (by decide) (by decide) (by decide)

/-- The diagonal-only negative control at observer 86's size. -/
theorem obs86_projectors_only_ne_top :
    StarAlgebra.adjoin ℂ
        (Set.range fun p : Fin 5 × Fin 13 =>
          obs86.fieldProjector p.1 p.2) ≠ ⊤ :=
  obs86.projectors_only_ne_top (by norm_num)

end

end OPH.QFT

-- Axiom audit: no project-specific axiom or admission is permitted here.
#print axioms OPH.QFT.adjoin_eq_top_of_walk
#print axioms OPH.QFT.SourceWalkData.sourceAlgebra_eq_top
#print axioms OPH.QFT.obs86_sourceAlgebra_eq_top
#print axioms OPH.QFT.obs88_sourceAlgebra_eq_top
#print axioms OPH.QFT.obs247_sourceAlgebra_eq_top
#print axioms OPH.QFT.obs384_sourceAlgebra_eq_top
#print axioms OPH.QFT.obs86_projectors_only_ne_top
