import QFT.SourceHistoryGNSDynamics
import QFT.FiniteTwoSiteIsingField

set_option autoImplicit false
set_option relaxedAutoImplicit false

/-!
# Three-slot locality for the source-history GNS attachment

The eight retained length-three histories are identified exactly with three
binary tensor slots.  On that carrier this module constructs the three
one-slot matrix algebras and the two adjacent interval algebras, decomposes
the source repair Hamiltonian into the two positive Ising domain-wall bonds,
and proves one-step propagation of the commutator generator.  The source
density restricts compatibly to every local algebra, and all algebra,
Hamiltonian, locality, and propagation statements are transported through
the selected source-history GNS representation.

These are history-slot algebras for a finite source packet.  The slot order is
not a Lorentzian spacetime localization, and the result supplies no continuum
limit, spectrum condition, physical clock, vacuum, fields, particles,
scattering, or detector model.
-/

namespace OPH.QFT.SourceHistoryThreeSlotLocalGNS

open Matrix
open Kronecker
open OPH.QFT
open OPH.InformationProjection
open OPH.QFT.FiniteTwoSiteIsingField
open OPH.QFT.SourceHistoryGNSDynamics
open EventAlgebra.Robertson

open scoped ComplexOrder InnerProductSpace

noncomputable section

abbrev ThreeSlotIndex := (Spin × Spin) × Spin
abbrev ThreeSlotMatrix := Matrix ThreeSlotIndex ThreeSlotIndex ℂ
abbrev SpinMatrix := Matrix Spin Spin ℂ

/-! ## Exact source-history/tensor-slot identification -/

/-- The exact bit encoding `((s₀,s₁),s₂) ↦ 4s₀+2s₁+s₂`. -/
def historyEquiv : ThreeSlotIndex ≃ Fin 8 where
  toFun s :=
    ⟨4 * s.1.1.val + 2 * s.1.2.val + s.2.val, by omega⟩
  invFun g := ((sourceState0 g, sourceState1 g), sourceState2 g)
  left_inv s := by
    rcases s with ⟨⟨s₀, s₁⟩, s₂⟩
    fin_cases s₀ <;> fin_cases s₁ <;> fin_cases s₂ <;> rfl
  right_inv g := by
    apply Fin.ext
    exact sourceState_encoding g

/-- Reindex the three tensor slots onto the exact `Fin 8` source carrier. -/
def historyStageEquiv : ThreeSlotMatrix ≃⋆ₐ[ℂ] HistoryMatrix :=
  StarAlgEquiv.ofAlgEquiv (Matrix.reindexAlgEquiv ℂ ℂ historyEquiv)
    (fun M => by
      simp only [Matrix.reindexAlgEquiv_apply, Matrix.star_eq_conjTranspose]
      exact reindex_conjTranspose historyEquiv M)

@[simp]
theorem historyStageEquiv_apply (M : ThreeSlotMatrix) :
    historyStageEquiv M = Matrix.reindex historyEquiv historyEquiv M :=
  rfl

/-! ## Tensor-factor site and interval algebras -/

/-- Slot zero, first embedded in the `(0,1)` pair and then in the triple. -/
def rawSlot0 : SpinMatrix →⋆ₐ[ℂ] ThreeSlotMatrix :=
  (slotLeft Spin (α := Spin × Spin)).comp
    (slotLeft Spin (α := Spin))

/-- Slot one, first embedded in the `(0,1)` pair and then in the triple. -/
def rawSlot1 : SpinMatrix →⋆ₐ[ℂ] ThreeSlotMatrix :=
  (slotLeft Spin (α := Spin × Spin)).comp
    (slotRight Spin (β := Spin))

/-- Slot two, embedded as the right factor of `(0,1) × 2`. -/
def rawSlot2 : SpinMatrix →⋆ₐ[ℂ] ThreeSlotMatrix :=
  slotRight (Spin × Spin) (β := Spin)

/-- The three site embeddings on the exact source carrier. -/
def slot0 : SpinMatrix →⋆ₐ[ℂ] HistoryMatrix :=
  (historyStageEquiv : ThreeSlotMatrix →⋆ₐ[ℂ] HistoryMatrix).comp rawSlot0

def slot1 : SpinMatrix →⋆ₐ[ℂ] HistoryMatrix :=
  (historyStageEquiv : ThreeSlotMatrix →⋆ₐ[ℂ] HistoryMatrix).comp rawSlot1

def slot2 : SpinMatrix →⋆ₐ[ℂ] HistoryMatrix :=
  (historyStageEquiv : ThreeSlotMatrix →⋆ₐ[ℂ] HistoryMatrix).comp rawSlot2

/-- Exact one-site and connected-interval algebras.  An interval algebra is
the star algebra generated by its tensor-factor site algebras. -/
def algebra0 : StarSubalgebra ℂ HistoryMatrix := slot0.range
def algebra1 : StarSubalgebra ℂ HistoryMatrix := slot1.range
def algebra2 : StarSubalgebra ℂ HistoryMatrix := slot2.range
def algebra01 : StarSubalgebra ℂ HistoryMatrix := algebra0 ⊔ algebra1
def algebra12 : StarSubalgebra ℂ HistoryMatrix := algebra1 ⊔ algebra2
def algebra012 : StarSubalgebra ℂ HistoryMatrix := ⊤

theorem algebra0_le_algebra01 : algebra0 ≤ algebra01 := le_sup_left
theorem algebra1_le_algebra01 : algebra1 ≤ algebra01 := le_sup_right
theorem algebra1_le_algebra12 : algebra1 ≤ algebra12 := le_sup_left
theorem algebra2_le_algebra12 : algebra2 ≤ algebra12 := le_sup_right
theorem algebra01_le_algebra012 : algebra01 ≤ algebra012 := le_top
theorem algebra12_le_algebra012 : algebra12 ≤ algebra012 := le_top

/-- Endpoint locality: every slot-zero observable commutes with every
slot-two observable. -/
theorem algebra0_algebra2_locality {X Y : HistoryMatrix}
    (hX : X ∈ algebra0) (hY : Y ∈ algebra2) : Commute X Y := by
  obtain ⟨A, rfl⟩ := hX
  obtain ⟨C, rfl⟩ := hY
  have hraw : Commute (rawSlot0 A) (rawSlot2 C) :=
    slot_commute
      (X := rawSlot0 A) (Y := rawSlot2 C)
      ⟨slotLeft Spin A, rfl⟩ ⟨C, rfl⟩
  exact hraw.map historyStageEquiv

theorem algebra0_algebra1_locality {X Y : HistoryMatrix}
    (hX : X ∈ algebra0) (hY : Y ∈ algebra1) : Commute X Y := by
  obtain ⟨A, rfl⟩ := hX
  obtain ⟨B, rfl⟩ := hY
  have hpair : Commute (slotLeft Spin A) (slotRight Spin B) :=
    slot_commute ⟨A, rfl⟩ ⟨B, rfl⟩
  exact (hpair.map (slotLeft Spin (α := Spin × Spin))).map historyStageEquiv

theorem algebra1_algebra2_locality {X Y : HistoryMatrix}
    (hX : X ∈ algebra1) (hY : Y ∈ algebra2) : Commute X Y := by
  obtain ⟨B, rfl⟩ := hX
  obtain ⟨C, rfl⟩ := hY
  have hraw : Commute (rawSlot1 B) (rawSlot2 C) :=
    slot_commute
      (X := rawSlot1 B) (Y := rawSlot2 C)
      ⟨slotRight Spin B, rfl⟩ ⟨C, rfl⟩
  exact hraw.map historyStageEquiv

/-! ## Adjacent Ising bonds and exact source decomposition -/

def z0 : HistoryMatrix := slot0 pauliZ
def z1 : HistoryMatrix := slot1 pauliZ
def z2 : HistoryMatrix := slot2 pauliZ

def spinSign (b : Spin) : ℂ := if b = 0 then 1 else -1

theorem z0_eq_diagonal :
    z0 = Matrix.diagonal fun g => spinSign (sourceState0 g) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [z0, spinSign, slot0, rawSlot0, historyStageEquiv,
      historyEquiv, sourceState0, sourceState1, sourceState2,
      slotLeft, pauliZ,
      Matrix.reindex_apply, Matrix.kroneckerMap_apply,
      Matrix.one_apply]

theorem z1_eq_diagonal :
    z1 = Matrix.diagonal fun g => spinSign (sourceState1 g) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [z1, spinSign, slot1, rawSlot1, historyStageEquiv,
      historyEquiv, sourceState0, sourceState1, sourceState2,
      slotLeft, slotRight, pauliZ,
      Matrix.reindex_apply, Matrix.kroneckerMap_apply,
      Matrix.one_apply]

theorem z2_eq_diagonal :
    z2 = Matrix.diagonal fun g => spinSign (sourceState2 g) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [z2, spinSign, slot2, rawSlot2, historyStageEquiv,
      historyEquiv, sourceState0, sourceState1, sourceState2,
      slotRight, pauliZ, Matrix.reindex_apply,
      Matrix.kroneckerMap_apply, Matrix.one_apply]

/-- The `(0,1)` and `(1,2)` ferromagnetic Ising domain-wall bonds. -/
def bond01 : HistoryMatrix := (2⁻¹ : ℂ) • (1 - z0 * z1)
def bond12 : HistoryMatrix := (2⁻¹ : ℂ) • (1 - z1 * z2)

def bond01Energy (g : Fin 8) : ℕ :=
  if sourceState0 g = sourceState1 g then 0 else 1

def bond12Energy (g : Fin 8) : ℕ :=
  if sourceState1 g = sourceState2 g then 0 else 1

@[simp] theorem bond01Energy_apply_0 : bond01Energy 0 = 0 := by decide
@[simp] theorem bond01Energy_apply_1 : bond01Energy 1 = 0 := by decide
@[simp] theorem bond01Energy_apply_2 : bond01Energy 2 = 1 := by decide
@[simp] theorem bond01Energy_apply_3 : bond01Energy 3 = 1 := by decide
@[simp] theorem bond01Energy_apply_4 : bond01Energy 4 = 1 := by decide
@[simp] theorem bond01Energy_apply_5 : bond01Energy 5 = 1 := by decide
@[simp] theorem bond01Energy_apply_6 : bond01Energy 6 = 0 := by decide
@[simp] theorem bond01Energy_apply_7 : bond01Energy 7 = 0 := by decide

@[simp] theorem bond12Energy_apply_0 : bond12Energy 0 = 0 := by decide
@[simp] theorem bond12Energy_apply_1 : bond12Energy 1 = 1 := by decide
@[simp] theorem bond12Energy_apply_2 : bond12Energy 2 = 1 := by decide
@[simp] theorem bond12Energy_apply_3 : bond12Energy 3 = 0 := by decide
@[simp] theorem bond12Energy_apply_4 : bond12Energy 4 = 0 := by decide
@[simp] theorem bond12Energy_apply_5 : bond12Energy 5 = 1 := by decide
@[simp] theorem bond12Energy_apply_6 : bond12Energy 6 = 1 := by decide
@[simp] theorem bond12Energy_apply_7 : bond12Energy 7 = 0 := by decide

theorem sourceTauEmpQ_bond01_mean :
    ∑ g, sourceTauEmpQ g * (bond01Energy g : ℚ) = 94 / 1754 := by
  rw [Fin.sum_univ_eight, sourceTauEmpQ_apply_0, sourceTauEmpQ_apply_1,
    sourceTauEmpQ_apply_2, sourceTauEmpQ_apply_3,
    sourceTauEmpQ_apply_4, sourceTauEmpQ_apply_5,
    sourceTauEmpQ_apply_6, sourceTauEmpQ_apply_7,
    bond01Energy_apply_0, bond01Energy_apply_1, bond01Energy_apply_2,
    bond01Energy_apply_3, bond01Energy_apply_4, bond01Energy_apply_5,
    bond01Energy_apply_6, bond01Energy_apply_7]
  norm_num

theorem sourceTauEmpQ_bond12_mean :
    ∑ g, sourceTauEmpQ g * (bond12Energy g : ℚ) = 103 / 1754 := by
  rw [Fin.sum_univ_eight, sourceTauEmpQ_apply_0, sourceTauEmpQ_apply_1,
    sourceTauEmpQ_apply_2, sourceTauEmpQ_apply_3,
    sourceTauEmpQ_apply_4, sourceTauEmpQ_apply_5,
    sourceTauEmpQ_apply_6, sourceTauEmpQ_apply_7,
    bond12Energy_apply_0, bond12Energy_apply_1, bond12Energy_apply_2,
    bond12Energy_apply_3, bond12Energy_apply_4, bond12Energy_apply_5,
    bond12Energy_apply_6, bond12Energy_apply_7]
  norm_num

theorem sourceTauEmpR_bond01_mean :
    ∑ g, sourceTauEmpR g * (bond01Energy g : ℝ) = 94 / 1754 := by
  rw [Finset.sum_congr rfl fun g _ =>
    show sourceTauEmpR g * (bond01Energy g : ℝ) =
        ((sourceTauEmpQ g * (bond01Energy g : ℚ) : ℚ) : ℝ) by
      simp only [sourceTauEmpR]
      push_cast
      ring]
  rw [← Rat.cast_sum, sourceTauEmpQ_bond01_mean]
  norm_num

theorem sourceTauEmpR_bond12_mean :
    ∑ g, sourceTauEmpR g * (bond12Energy g : ℝ) = 103 / 1754 := by
  rw [Finset.sum_congr rfl fun g _ =>
    show sourceTauEmpR g * (bond12Energy g : ℝ) =
        ((sourceTauEmpQ g * (bond12Energy g : ℚ) : ℚ) : ℝ) by
      simp only [sourceTauEmpR]
      push_cast
      ring]
  rw [← Rat.cast_sum, sourceTauEmpQ_bond12_mean]
  norm_num

theorem z0_mem_algebra0 : z0 ∈ algebra0 := ⟨pauliZ, rfl⟩
theorem z1_mem_algebra1 : z1 ∈ algebra1 := ⟨pauliZ, rfl⟩
theorem z2_mem_algebra2 : z2 ∈ algebra2 := ⟨pauliZ, rfl⟩

theorem bond01_mem_algebra01 : bond01 ∈ algebra01 := by
  exact (algebra01.smul_mem
    (algebra01.sub_mem (one_mem algebra01)
      (algebra01.mul_mem
        (algebra0_le_algebra01 z0_mem_algebra0)
        (algebra1_le_algebra01 z1_mem_algebra1))) (2⁻¹ : ℂ))

theorem bond12_mem_algebra12 : bond12 ∈ algebra12 := by
  exact (algebra12.smul_mem
    (algebra12.sub_mem (one_mem algebra12)
      (algebra12.mul_mem
        (algebra1_le_algebra12 z1_mem_algebra1)
        (algebra2_le_algebra12 z2_mem_algebra2))) (2⁻¹ : ℂ))

theorem bond01_eq_diagonal :
    bond01 = Matrix.diagonal fun g => ((bond01Energy g : ℝ) : ℂ) := by
  rw [bond01, z0_eq_diagonal, z1_eq_diagonal,
    Matrix.diagonal_mul_diagonal]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [bond01Energy, spinSign, sourceState0, sourceState1,
      Matrix.one_apply]

theorem bond12_eq_diagonal :
    bond12 = Matrix.diagonal fun g => ((bond12Energy g : ℝ) : ℂ) := by
  rw [bond12, z1_eq_diagonal, z2_eq_diagonal,
    Matrix.diagonal_mul_diagonal]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [bond12Energy, spinSign, sourceState1, sourceState2,
      Matrix.one_apply]

theorem bond01_posSemidef : bond01.PosSemidef := by
  rw [bond01_eq_diagonal]
  refine Matrix.PosSemidef.diagonal ?_
  intro g
  fin_cases g <;>
    exact Complex.zero_le_real.mpr (by
      norm_num [bond01Energy, sourceState0, sourceState1])

theorem bond12_posSemidef : bond12.PosSemidef := by
  rw [bond12_eq_diagonal]
  refine Matrix.PosSemidef.diagonal ?_
  intro g
  fin_cases g <;>
    exact Complex.zero_le_real.mpr (by
      norm_num [bond12Energy, sourceState1, sourceState2])

/-- The source repair Hamiltonian is exactly the sum of the two adjacent
Ising bonds, with no residual three-body term. -/
theorem sourceHistoryHamiltonian_eq_bond01_add_bond12 :
    sourceHistoryHamiltonian = bond01 + bond12 := by
  rw [bond01_eq_diagonal, bond12_eq_diagonal,
    sourceHistoryHamiltonian]
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [sourceActionR, sourceAction, bond01Energy, bond12Energy,
      sourceState0, sourceState1, sourceState2]

theorem sourceHistoryDensity_bond01_expectation :
    EventAlgebra.expectation sourceHistoryDensity bond01 = (94 / 1754 : ℂ) := by
  change (sourceHistoryDensity * bond01).trace = _
  rw [sourceHistoryDensity, bond01_eq_diagonal,
    Matrix.diagonal_mul_diagonal, Matrix.trace_diagonal]
  simp only [← Complex.ofReal_mul]
  rw [← Complex.ofReal_sum, sourceTauEmpR_bond01_mean]
  norm_num

theorem sourceHistoryDensity_bond12_expectation :
    EventAlgebra.expectation sourceHistoryDensity bond12 = (103 / 1754 : ℂ) := by
  change (sourceHistoryDensity * bond12).trace = _
  rw [sourceHistoryDensity, bond12_eq_diagonal,
    Matrix.diagonal_mul_diagonal, Matrix.trace_diagonal]
  simp only [← Complex.ofReal_mul]
  rw [← Complex.ofReal_sum, sourceTauEmpR_bond12_mean]
  norm_num

/-! ## Restricted source state and finite propagation -/

/-- The selected source state restricted to an arbitrary local
star-subalgebra. -/
def restrictedSourceState (A : StarSubalgebra ℂ HistoryMatrix) : A →ₗ[ℂ] ℂ :=
  (EventAlgebra.stateExpectationLinearMap sourceHistoryDensity).comp
    A.subtype.toLinearMap

theorem restrictedSourceState_normalized (A : StarSubalgebra ℂ HistoryMatrix) :
    restrictedSourceState A 1 = 1 := by
  change EventAlgebra.expectation sourceHistoryDensity 1 = 1
  exact EventAlgebra.expectation_one sourceHistoryDensity_isState

theorem restrictedSourceState_nonneg
    (A : StarSubalgebra ℂ HistoryMatrix) (X : A)
    (hX : (X : HistoryMatrix).PosSemidef) :
    0 ≤ restrictedSourceState A X := by
  change 0 ≤ EventAlgebra.expectation sourceHistoryDensity (X : HistoryMatrix)
  exact EventAlgebra.expectation_nonneg sourceHistoryDensity_isState.1 hX

/-- Restriction is compatible along every interval inclusion. -/
theorem restrictedSourceState_compatible
    {A B : StarSubalgebra ℂ HistoryMatrix} (hAB : A ≤ B) (X : A) :
    restrictedSourceState B ⟨X, hAB X.2⟩ = restrictedSourceState A X := by
  rfl

theorem restrictedSourceState_receipt :
    (∀ A : StarSubalgebra ℂ HistoryMatrix,
      restrictedSourceState A 1 = 1) ∧
    (∀ (A : StarSubalgebra ℂ HistoryMatrix) (X : A),
      (X : HistoryMatrix).PosSemidef → 0 ≤ restrictedSourceState A X) ∧
    (∀ (A B : StarSubalgebra ℂ HistoryMatrix) (hAB : A ≤ B) (X : A),
      restrictedSourceState B ⟨X, hAB X.2⟩ = restrictedSourceState A X) := by
  exact ⟨restrictedSourceState_normalized,
    fun A X hX => restrictedSourceState_nonneg A X hX,
    fun _ _ hAB X => restrictedSourceState_compatible hAB X⟩

theorem bond12_commutes_algebra0 {X : HistoryMatrix} (hX : X ∈ algebra0) :
    Commute bond12 X := by
  have h1 : Commute X z1 :=
    algebra0_algebra1_locality hX z1_mem_algebra1
  have h2 : Commute X z2 :=
    algebra0_algebra2_locality hX z2_mem_algebra2
  exact (((Commute.one_right X).sub_right (h1.mul_right h2)).smul_right
    (2⁻¹ : ℂ)).symm

theorem bond01_commutes_algebra2 {X : HistoryMatrix} (hX : X ∈ algebra2) :
    Commute bond01 X := by
  have h0 : Commute z0 X :=
    algebra0_algebra2_locality z0_mem_algebra0 hX
  have h1 : Commute z1 X :=
    algebra1_algebra2_locality z1_mem_algebra1 hX
  exact (((Commute.one_right X).sub_right
    (h0.symm.mul_right h1.symm)).smul_right (2⁻¹ : ℂ)).symm

/-- A slot-zero observable can spread at first commutator order only into
the adjacent interval `(0,1)`. -/
theorem sourceHistoryGenerator_maps_algebra0_to_algebra01
    {X : HistoryMatrix} (hX : X ∈ algebra0) :
    sourceHistoryGenerator X ∈ algebra01 := by
  have hc := bond12_commutes_algebra0 hX
  have hcomm :
      sourceHistoryHamiltonian * X - X * sourceHistoryHamiltonian =
        bond01 * X - X * bond01 := by
    rw [sourceHistoryHamiltonian_eq_bond01_add_bond12,
      add_mul, mul_add, hc.eq]
    abel
  change (-Complex.I) •
      (sourceHistoryHamiltonian * X - X * sourceHistoryHamiltonian) ∈ algebra01
  rw [hcomm]
  exact algebra01.smul_mem
    (algebra01.sub_mem
      (algebra01.mul_mem bond01_mem_algebra01
        (algebra0_le_algebra01 hX))
      (algebra01.mul_mem (algebra0_le_algebra01 hX)
        bond01_mem_algebra01)) (-Complex.I)

/-- Symmetrically, a slot-two observable spreads at first order only into
the adjacent interval `(1,2)`. -/
theorem sourceHistoryGenerator_maps_algebra2_to_algebra12
    {X : HistoryMatrix} (hX : X ∈ algebra2) :
    sourceHistoryGenerator X ∈ algebra12 := by
  have hc := bond01_commutes_algebra2 hX
  have hcomm :
      sourceHistoryHamiltonian * X - X * sourceHistoryHamiltonian =
        bond12 * X - X * bond12 := by
    rw [sourceHistoryHamiltonian_eq_bond01_add_bond12,
      add_mul, mul_add, hc.eq]
    abel
  change (-Complex.I) •
      (sourceHistoryHamiltonian * X - X * sourceHistoryHamiltonian) ∈ algebra12
  rw [hcomm]
  exact algebra12.smul_mem
    (algebra12.sub_mem
      (algebra12.mul_mem bond12_mem_algebra12
        (algebra2_le_algebra12 hX))
      (algebra12.mul_mem (algebra2_le_algebra12 hX)
        bond12_mem_algebra12)) (-Complex.I)

/-! ## Selected-GNS transport -/

def representedAlgebra0 : StarSubalgebra ℂ SourceHistoryColimitGNSOperators :=
  algebra0.map stageRepresentation
def representedAlgebra2 : StarSubalgebra ℂ SourceHistoryColimitGNSOperators :=
  algebra2.map stageRepresentation
def representedAlgebra01 : StarSubalgebra ℂ SourceHistoryColimitGNSOperators :=
  algebra01.map stageRepresentation
def representedAlgebra12 : StarSubalgebra ℂ SourceHistoryColimitGNSOperators :=
  algebra12.map stageRepresentation

def representedBond01 : SourceHistoryColimitGNSOperators :=
  stageRepresentation bond01
def representedBond12 : SourceHistoryColimitGNSOperators :=
  stageRepresentation bond12

theorem representedBond01_mem_algebra01 :
    representedBond01 ∈ representedAlgebra01 :=
  ⟨bond01, bond01_mem_algebra01, rfl⟩

theorem representedBond12_mem_algebra12 :
    representedBond12 ∈ representedAlgebra12 :=
  ⟨bond12, bond12_mem_algebra12, rfl⟩

theorem representedHamiltonian_eq_bond01_add_bond12 :
    representedHamiltonian = representedBond01 + representedBond12 := by
  rw [representedHamiltonian, sourceHistoryHamiltonian_eq_bond01_add_bond12,
    map_add]
  rfl

theorem represented_endpoint_locality
    {X Y : SourceHistoryColimitGNSOperators}
    (hX : X ∈ representedAlgebra0) (hY : Y ∈ representedAlgebra2) :
    Commute X Y := by
  obtain ⟨X₀, hX₀, rfl⟩ := hX
  obtain ⟨Y₂, hY₂, rfl⟩ := hY
  exact (algebra0_algebra2_locality hX₀ hY₂).map stageRepresentation

theorem represented_generator_of_algebra0_mem_algebra01
    {X : HistoryMatrix} (hX : X ∈ algebra0) :
    stageRepresentation (sourceHistoryGenerator X) ∈ representedAlgebra01 :=
  ⟨sourceHistoryGenerator X,
    sourceHistoryGenerator_maps_algebra0_to_algebra01 hX, rfl⟩

theorem represented_generator_of_algebra2_mem_algebra12
    {X : HistoryMatrix} (hX : X ∈ algebra2) :
    stageRepresentation (sourceHistoryGenerator X) ∈ representedAlgebra12 :=
  ⟨sourceHistoryGenerator X,
    sourceHistoryGenerator_maps_algebra2_to_algebra12 hX, rfl⟩

/-- One bundled receipt for the exact three-history-slot local GNS rung. -/
theorem sourceHistoryThreeSlotLocalGNSAttachment :
    sourceHistoryHamiltonian = bond01 + bond12 ∧
      bond01.PosSemidef ∧ bond12.PosSemidef ∧
      EventAlgebra.expectation sourceHistoryDensity bond01 = (94 / 1754 : ℂ) ∧
      EventAlgebra.expectation sourceHistoryDensity bond12 = (103 / 1754 : ℂ) ∧
      bond01 ∈ algebra01 ∧ bond12 ∈ algebra12 ∧
      (∀ X ∈ algebra0, ∀ Y ∈ algebra2, Commute X Y) ∧
      (∀ X ∈ algebra0, sourceHistoryGenerator X ∈ algebra01) ∧
      (∀ X ∈ algebra2, sourceHistoryGenerator X ∈ algebra12) ∧
      ((∀ A : StarSubalgebra ℂ HistoryMatrix,
          restrictedSourceState A 1 = 1) ∧
        (∀ (A : StarSubalgebra ℂ HistoryMatrix) (X : A),
          (X : HistoryMatrix).PosSemidef →
            0 ≤ restrictedSourceState A X) ∧
        (∀ (A B : StarSubalgebra ℂ HistoryMatrix) (hAB : A ≤ B) (X : A),
          restrictedSourceState B ⟨X, hAB X.2⟩ =
            restrictedSourceState A X)) ∧
      representedHamiltonian = representedBond01 + representedBond12 ∧
      representedBond01 ∈ representedAlgebra01 ∧
      representedBond12 ∈ representedAlgebra12 := by
  exact ⟨sourceHistoryHamiltonian_eq_bond01_add_bond12,
    bond01_posSemidef, bond12_posSemidef,
    sourceHistoryDensity_bond01_expectation,
    sourceHistoryDensity_bond12_expectation,
    bond01_mem_algebra01, bond12_mem_algebra12,
    fun _ hX _ hY => algebra0_algebra2_locality hX hY,
    fun _ hX => sourceHistoryGenerator_maps_algebra0_to_algebra01 hX,
    fun _ hX => sourceHistoryGenerator_maps_algebra2_to_algebra12 hX,
    restrictedSourceState_receipt,
    representedHamiltonian_eq_bond01_add_bond12,
    representedBond01_mem_algebra01,
    representedBond12_mem_algebra12⟩

end

end OPH.QFT.SourceHistoryThreeSlotLocalGNS

#print axioms OPH.QFT.SourceHistoryThreeSlotLocalGNS.sourceHistoryHamiltonian_eq_bond01_add_bond12
#print axioms OPH.QFT.SourceHistoryThreeSlotLocalGNS.sourceHistoryGenerator_maps_algebra0_to_algebra01
#print axioms OPH.QFT.SourceHistoryThreeSlotLocalGNS.represented_endpoint_locality
#print axioms OPH.QFT.SourceHistoryThreeSlotLocalGNS.sourceHistoryThreeSlotLocalGNSAttachment
