import QFT.ObserverEventTower
import ObserverPatchHolography.Provenance.CausalInterval
import ObserverPatchHolography.Provenance.HistoryCausalInvariance

/-!
# Source-derived event precedence for observer event worlds

The event precedence adapter of `QFT/ObserverEventTower.lean` decorates an
observer event world with declared strict order data on event slots.  This
module replaces the declaration with a derivation.  A semantic event log on
the event carrier generates its causal order from certified read-from
provenance, and the generated order inhabits the adapter interface
directly: `generatedPrecedenceAdapter` builds an `EventPrecedenceAdapter`
whose event order is the transitive closure of the log's direct parent
edges, with the record-order consistency law discharged against generated
precedence rather than declared precedence.

The exactness theorem closes the other direction.  Any adapter whose event
order contains every direct parent edge and asserts no comparability
beyond the generated order has exactly the generated order.  An admissible
adapter therefore verifies the source-derived precedence; it cannot choose
a different one.

The chain witness stack realizes both statements on committed data.  A
two-commit log over one register generates exactly one edge, the derived
adapter reproduces the declared chain adapter's order on every pair, and
the declared adapter satisfies the exactness clauses, so its declaration
was redundant on that world.  No physical causal order, spacetime, clock,
or continuum object is attached; those identifications remain premises of
the geometric branch.
-/

namespace OPH.QFT

open OPH.Tower
open OPH.TimeOrderLedger
open OPH.Provenance

universe u v w x

variable {ι : Type u} [Preorder ι]
variable {T : ConsensusTower ι} {N : FiniteCausalObserverNet T}
variable {r : ι} {A : ObserverAccessCut T N r} {sig : EventWorldSignature}
variable {S : OPH.C2Soldering.EventFrameSoldering sig.Event sig.Chart}
variable {Register : Type w} {Value : Type x} [DecidableEq Register]

/-- The event precedence adapter generated by a semantic event log: the
event order is the transitive closure of the log's direct parent edges,
and the consistency law is supplied against that generated order.  No
strict order data is declared. -/
noncomputable def generatedPrecedenceAdapter
    (W : FiniteEventGeometryWorld A sig S)
    (L : SemanticEventLog Register Value sig.Event)
    (labeled : sig.Event → Prop)
    (recordLabel : ∀ e : sig.Event, labeled e → T.Record r)
    (hconsistent : ∀ {i : sig.Chart} {e f : sig.Event},
      W.activeChart i → W.activeEvent e → W.activeEvent f →
      S.visible i e → S.visible i f →
      ∀ (hle : labeled e) (hlf : labeled f),
        L.GeneratedBefore e f →
          (T.recordOrder r (W.chartOwner i)).precedes
            (recordLabel e hle) (recordLabel f hlf)) :
    EventPrecedenceAdapter W where
  eventOrder := L.generatedRecordOrder
  labeled := labeled
  recordLabel := recordLabel
  precedes_consistent := by
    intro i e f hchart he hf hve hvf hle hlf hp
    exact hconsistent hchart he hf hve hvf hle hlf hp

/-- The generated adapter's event order is the generated causal
precedence, definitionally. -/
theorem generatedPrecedenceAdapter_precedes
    (W : FiniteEventGeometryWorld A sig S)
    (L : SemanticEventLog Register Value sig.Event)
    (labeled : sig.Event → Prop)
    (recordLabel : ∀ e : sig.Event, labeled e → T.Record r)
    (hconsistent : ∀ {i : sig.Chart} {e f : sig.Event},
      W.activeChart i → W.activeEvent e → W.activeEvent f →
      S.visible i e → S.visible i f →
      ∀ (hle : labeled e) (hlf : labeled f),
        L.GeneratedBefore e f →
          (T.recordOrder r (W.chartOwner i)).precedes
            (recordLabel e hle) (recordLabel f hlf))
    (e f : sig.Event) :
    (generatedPrecedenceAdapter W L labeled recordLabel
        hconsistent).eventOrder.precedes e f ↔
      L.GeneratedBefore e f :=
  Iff.rfl

/-! ## Threaded-execution adapter

The general constructor above accepts an abstract certified event log.  The
constructor below is the producer-facing path: it first derives that log and
its rank from one fresh, duplicate-free, carrier-complete threaded execution,
then installs its authenticated closure as the QFT event order.  The only
remaining consistency input is the explicitly typed attachment from that
informational order to the tower's observer-record labels. -/

/-- A QFT precedence adapter built directly from a threaded semantic
execution.  Neither direct edges nor a rank are supplied to this
constructor. -/
noncomputable def generatedPrecedenceAdapterOfExecution
    (W : FiniteEventGeometryWorld A sig S)
    (q : VersionedState Register Value sig.Event)
    (specs : List (CommitSpec Register Value sig.Event))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs)
    (labeled : sig.Event → Prop)
    (recordLabel : ∀ e : sig.Event, labeled e → T.Record r)
    (hconsistent : ∀ {i : sig.Chart} {e f : sig.Event},
      W.activeChart i → W.activeEvent e → W.activeEvent f →
      S.visible i e → S.visible i f →
      ∀ (hle : labeled e) (hlf : labeled f),
        Relation.TransGen (execAuthenticatedParents q specs) e f →
          (T.recordOrder r (W.chartOwner i)).precedes
            (recordLabel e hle) (recordLabel f hlf)) :
    EventPrecedenceAdapter W := by
  letI : DecidableEq sig.Event := Classical.decEq sig.Event
  let L := semanticEventLogOfExecution q specs hfresh hnodup hcomplete
  exact generatedPrecedenceAdapter W L labeled recordLabel (by
    intro i e f hchart he hf hve hvf hle hlf hbefore
    apply hconsistent hchart he hf hve hvf hle hlf
    exact (semanticEventLogOfExecution_generatedBefore_iff q specs hfresh
      hnodup hcomplete e f).mp hbefore)

/-- The execution-built adapter's order is exactly the transitive closure
of authenticated executed read-after-write edges. -/
theorem generatedPrecedenceAdapterOfExecution_precedes
    (W : FiniteEventGeometryWorld A sig S)
    (q : VersionedState Register Value sig.Event)
    (specs : List (CommitSpec Register Value sig.Event))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs)
    (labeled : sig.Event → Prop)
    (recordLabel : ∀ e : sig.Event, labeled e → T.Record r)
    (hconsistent : ∀ {i : sig.Chart} {e f : sig.Event},
      W.activeChart i → W.activeEvent e → W.activeEvent f →
      S.visible i e → S.visible i f →
      ∀ (hle : labeled e) (hlf : labeled f),
        Relation.TransGen (execAuthenticatedParents q specs) e f →
          (T.recordOrder r (W.chartOwner i)).precedes
            (recordLabel e hle) (recordLabel f hlf))
    (e f : sig.Event) :
    (generatedPrecedenceAdapterOfExecution W q specs hfresh hnodup
      hcomplete labeled recordLabel hconsistent).eventOrder.precedes e f ↔
      Relation.TransGen (execAuthenticatedParents q specs) e f := by
  letI : DecidableEq sig.Event := Classical.decEq sig.Event
  change
    (semanticEventLogOfExecution q specs hfresh hnodup hcomplete).GeneratedBefore
        e f ↔ _
  exact semanticEventLogOfExecution_generatedBefore_iff q specs hfresh
    hnodup hcomplete e f

/-- Exactness: an adapter whose event order contains every direct parent
edge and asserts no comparability beyond the generated order carries
exactly the generated order.  An admissible adapter verifies the
source-derived precedence and cannot choose a different one. -/
theorem eventOrder_eq_generated_of_exact
    {W : FiniteEventGeometryWorld A sig S}
    (P : EventPrecedenceAdapter W)
    (L : SemanticEventLog Register Value sig.Event)
    (hedges : ∀ c d : sig.Event,
      L.ParentEdge c d → P.eventOrder.precedes c d)
    (hsupported : ∀ c d : sig.Event,
      P.eventOrder.precedes c d → L.GeneratedBefore c d)
    (c d : sig.Event) :
    P.eventOrder.precedes c d ↔ L.GeneratedBefore c d :=
  L.eq_generatedBefore_of_exact P.eventOrder.precedes hedges
    (fun h h' => P.eventOrder.trans h h') hsupported c d

/-! ## The chain witness log

Two commits over one register: the first writes the register and stamps
its identifier, the second cites that version.  The generated order is the
single edge from the first event to the second. -/

section ChainWitness

open OPH.D1Time

/-- The pre-write snapshot: the register holds `false` with no writer. -/
def chainState0 : VersionedState Unit Bool (Fin 2) :=
  ⟨fun _ => false, fun _ => none⟩

/-- After the first commit: the register holds `true`, written by event
`0`. -/
def chainState1 : VersionedState Unit Bool (Fin 2) :=
  ⟨fun _ => true, fun _ => some 0⟩

/-- The writing commit: event `0` writes the register from the initial
snapshot and cites nothing. -/
def chainWriter : SemanticCommit Unit Bool (Fin 2) where
  eventId := 0
  before := chainState0
  after := chainState1
  readSet := ∅
  writeSet := {()}
  causalSupp := ∅
  supp_subset_read := by decide
  frame_value := by decide
  frame_writer := by decide
  stamp := by intro a _; rfl

/-- The citing commit: event `1` reads and cites the written version and
writes nothing. -/
def chainReader : SemanticCommit Unit Bool (Fin 2) where
  eventId := 1
  before := chainState1
  after := chainState1
  readSet := {()}
  writeSet := ∅
  causalSupp := {()}
  supp_subset_read := by decide
  frame_value := fun _ _ => rfl
  frame_writer := fun _ _ => rfl
  stamp := by decide

/-- The two-commit chain log with ancestry rank the event index. -/
def chainLog : SemanticEventLog Unit Bool (Fin 2) where
  commitOf := ![chainWriter, chainReader]
  commitOf_eventId := by decide
  rank e := e.val
  rank_lt_of_parent := by
    have h : ∀ c d : Fin 2,
        AuthenticatedDirectSemanticParent (![chainWriter, chainReader] c)
            (![chainWriter, chainReader] d) →
          c.val < d.val := by decide
    intro c d
    exact h c d

/-- The generated order of the chain log holds at the ordered pair. -/
theorem chainLog_generatedBefore_zero_one :
    chainLog.GeneratedBefore 0 1 :=
  Relation.TransGen.single (by decide)

/-- The generated order of the chain log agrees with the strict chain on
every pair of events. -/
theorem chainLog_generatedBefore_iff (e f : Fin 2) :
    chainLog.GeneratedBefore e f ↔ e < f := by
  constructor
  · intro h
    exact Fin.lt_def.mpr (chainLog.rank_lt_of_generatedBefore h)
  · intro h
    have h01 : e = 0 ∧ f = 1 := by
      revert h
      revert e f
      decide
    rw [h01.1, h01.2]
    exact chainLog_generatedBefore_zero_one

/-- The source-generated adapter on the chain witness event world: the
event order is derived from the chain log, the labels are the events
themselves, and the consistency law is discharged through the generated
order. -/
noncomputable def chainWitnessGeneratedAdapter :
    EventPrecedenceAdapter chainWitnessEventWorld :=
  generatedPrecedenceAdapter chainWitnessEventWorld chainLog
    (fun _ => True) (fun e _ => e)
    (by
      intro i e f _ _ _ _ _ _ _ hp
      exact (chainLog_generatedBefore_iff e f).mp hp)

/-- The derived adapter reproduces the declared chain adapter's order on
every pair: the declaration is redundant on this world. -/
theorem chainWitnessGeneratedAdapter_eq_declared (e f : Fin 2) :
    chainWitnessGeneratedAdapter.eventOrder.precedes e f ↔
      chainWitnessPrecedenceAdapter.eventOrder.precedes e f :=
  chainLog_generatedBefore_iff e f

/-- The declared chain adapter satisfies the exactness clauses against the
chain log, so its event order is exactly the generated order. -/
theorem chainWitnessPrecedenceAdapter_exact (e f : Fin 2) :
    chainWitnessPrecedenceAdapter.eventOrder.precedes e f ↔
      chainLog.GeneratedBefore e f := by
  refine eventOrder_eq_generated_of_exact
    chainWitnessPrecedenceAdapter chainLog ?_ ?_ e f
  · intro c d hedge
    have h : c = 0 ∧ d = 1 := by
      revert hedge
      revert c d
      decide
    rw [h.1, h.2]
    show (0 : Fin 2) < 1
    decide
  · intro c d h
    exact (chainLog_generatedBefore_iff c d).mpr h

end ChainWitness

#print axioms generatedPrecedenceAdapter
#print axioms generatedPrecedenceAdapterOfExecution
#print axioms generatedPrecedenceAdapterOfExecution_precedes
#print axioms eventOrder_eq_generated_of_exact
#print axioms chainLog
#print axioms chainLog_generatedBefore_iff
#print axioms chainWitnessGeneratedAdapter_eq_declared
#print axioms chainWitnessPrecedenceAdapter_exact

end OPH.QFT
