import QFT.SourceContextTomographyNoGo

/-!
# The exact phase-lift boundary of the current source context web

The committed B13 source payload realizes gauge labels and counts.  Applying
the declared two-dimensional S3 representation and projector adapter gives
two source-attached noncommuting real projector candidates on its designated
fibre: `recordProjector` and `conjProjector 3`.  The algebraic web is not complex-tomographically complete,
as witnessed by `rhoYPlus` and `rhoYMinus` in
`SourceContextTomographyNoGo`.

This module locates the missing operation exactly.  Subtracting the normalized
complex commutator from `I / 2`, with the normalization fixed by the payload's
exact `sqrt 3 / 4` commutator entry, produces the missing `+Y` projector.  The
three effects consisting of the record projector, the algebraically rotated
projector, and this phase lift are tomographically complete for trace-one
Hermitian two-by-two matrices.

The positive statement is an operator-algebra closure theorem, not a source
instrument receipt.  The current payload contains no phase-lift producer and
no outcome counts for either the rotated or phase-lifted context.  A second
theorem below gives the complementary no-go: even a generous closure under
real coarse graining, real scaling, complements, and real Kraus pullbacks
remains symmetric-real and cannot distinguish the two Pauli-Y states.  Thus
more phase-free real contexts cannot close B13; the minimal new capability is
a source-attached phase-sensitive operation (or an equivalent genuinely
complex effect) with common-preparation outcome receipts.
-/

namespace OPH.QFT

open Matrix
open scoped ComplexOrder

noncomputable section

/-! ## The phase lift generated by the source-attached algebraic pair -/

/-- The complex phase lift of the exact algebraic commutator.  Its coefficient
is not fitted: `commutator_three` has off-diagonal magnitude `sqrt 3 / 4`, so
`(2 sqrt 3 / 3) i` normalizes the half-commutator appearing in a rank-one
Pauli-Y projector. -/
def sourcePhaseLift : Matrix (Fin 2) (Fin 2) ℂ :=
  (2⁻¹ : ℂ) • 1 -
    ((((2 * sqrt3 / 3 : ℝ) : ℂ) * Complex.I) •
      complexifyRealMatrix
        (conjProjector 3 * recordProjector - recordProjector * conjProjector 3))

/-- The phase lift is exactly the missing pure `+Y` projector. -/
theorem sourcePhaseLift_eq_rhoYPlus : sourcePhaseLift = rhoYPlus := by
  rw [sourcePhaseLift, commutator_three]
  have hs : ((sqrt3 : ℂ) * (sqrt3 : ℂ)) = 3 := by
    have hsR : sqrt3 * sqrt3 = 3 := by
      simpa [pow_two] using sqrt3_sq
    exact_mod_cast hsR
  have hsPow : (sqrt3 : ℂ) ^ 2 = 3 := by
    simpa [pow_two] using hs
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [complexifyRealMatrix, rhoYPlus, Matrix.smul_apply] <;>
    ring_nf
  all_goals rw [hsPow]
  all_goals ring

/-- Hence the algebraically generated phase lift is a certified projection
event. -/
theorem sourcePhaseLift_isEvent : EventAlgebra.IsEvent sourcePhaseLift := by
  rw [sourcePhaseLift_eq_rhoYPlus]
  exact rhoYPlus_isEvent

/-- The complementary phase-lifted outcome is also a projection event. -/
theorem sourcePhaseLift_complement_isEvent :
    EventAlgebra.IsEvent (1 - sourcePhaseLift) :=
  sourcePhaseLift_isEvent.compl

/-- The phase-lifted binary context is exactly complete. -/
theorem sourcePhaseLift_context_complete :
    sourcePhaseLift + (1 - sourcePhaseLift) = 1 := by
  abel

/-- The exact positive control: the phase lift separates the pair which the
entire native real S3 web cannot distinguish. -/
theorem sourcePhaseLift_distinguishes_Y_states :
    EventAlgebra.bornWeight rhoYPlus sourcePhaseLift = 1 ∧
      EventAlgebra.bornWeight rhoYMinus sourcePhaseLift = 0 := by
  rw [sourcePhaseLift_eq_rhoYPlus]
  exact pauliY_context_distinguishes_states

/-! ## Exact membership in the complex operator-algebra closure -/

/-- The unital complex operator-algebra grammar generated by the declared
record projector and all S3-conjugated projector candidates.  This is
algebraic closure, not a declaration that the simulator implements these
operations as instruments. -/
inductive ComplexSourceAlgebraClosure : Matrix (Fin 2) (Fin 2) ℂ → Prop
  | one : ComplexSourceAlgebraClosure 1
  | record :
      ComplexSourceAlgebraClosure (complexifyRealMatrix recordProjector)
  | conjugatedRecord (g : Fin 6) :
      ComplexSourceAlgebraClosure
        (complexifyRealMatrix (conjProjector g))
  | add {A B} (hA : ComplexSourceAlgebraClosure A)
      (hB : ComplexSourceAlgebraClosure B) :
      ComplexSourceAlgebraClosure (A + B)
  | sub {A B} (hA : ComplexSourceAlgebraClosure A)
      (hB : ComplexSourceAlgebraClosure B) :
      ComplexSourceAlgebraClosure (A - B)
  | mul {A B} (hA : ComplexSourceAlgebraClosure A)
      (hB : ComplexSourceAlgebraClosure B) :
      ComplexSourceAlgebraClosure (A * B)
  | complexScale (c : ℂ) {A} (hA : ComplexSourceAlgebraClosure A) :
      ComplexSourceAlgebraClosure (c • A)

theorem complexifyRealMatrix_mul
    (A B : Matrix (Fin 2) (Fin 2) ℝ) :
    complexifyRealMatrix (A * B) =
      complexifyRealMatrix A * complexifyRealMatrix B := by
  ext i j
  simp [complexifyRealMatrix, Matrix.mul_apply]

/-- The exact phase lift belongs to the complex algebra generated by the
source-attached algebraic noncommuting pair.  The decisive composite absent from the
phase-free effect grammar below is the phase-sensitive commutator
`A, B ↦ i * (A * B - B * A)`; arbitrary nonsymmetric products in this proof
are algebraic intermediates, not measurement effects. -/
theorem sourcePhaseLift_mem_complexSourceAlgebra :
    ComplexSourceAlgebraClosure sourcePhaseLift := by
  rw [sourcePhaseLift, complexifyRealMatrix_sub,
    complexifyRealMatrix_mul, complexifyRealMatrix_mul]
  exact ComplexSourceAlgebraClosure.sub
    (ComplexSourceAlgebraClosure.complexScale (2⁻¹ : ℂ)
      ComplexSourceAlgebraClosure.one)
    (ComplexSourceAlgebraClosure.complexScale
      (((2 * sqrt3 / 3 : ℝ) : ℂ) * Complex.I)
      (ComplexSourceAlgebraClosure.sub
        (ComplexSourceAlgebraClosure.mul
          (ComplexSourceAlgebraClosure.conjugatedRecord 3)
          ComplexSourceAlgebraClosure.record)
        (ComplexSourceAlgebraClosure.mul
          ComplexSourceAlgebraClosure.record
          (ComplexSourceAlgebraClosure.conjugatedRecord 3))))

/-! ## The phase-free real operational closure -/

/-- A generous phase-free closure of the source effects, kept over real
matrices.  Besides every S3-conjugated binary outcome it permits complements,
real linear coarse graining, and pullback by an arbitrary real Kraus matrix.
This is an upper-bound grammar: the committed simulator does not claim to
implement every constructor. -/
inductive RealSourceEffectClosure : Matrix (Fin 2) (Fin 2) ℝ → Prop
  | record : RealSourceEffectClosure recordProjector
  | companion : RealSourceEffectClosure companionProjector
  | conjugatedRecord (g : Fin 6) :
      RealSourceEffectClosure (conjProjector g)
  | conjugatedCompanion (g : Fin 6) :
      RealSourceEffectClosure (conjCompanionProjector g)
  | zero : RealSourceEffectClosure 0
  | one : RealSourceEffectClosure 1
  | complement {E} (hE : RealSourceEffectClosure E) :
      RealSourceEffectClosure (1 - E)
  | add {E F} (hE : RealSourceEffectClosure E)
      (hF : RealSourceEffectClosure F) : RealSourceEffectClosure (E + F)
  | realScale (r : ℝ) {E} (hE : RealSourceEffectClosure E) :
      RealSourceEffectClosure (r • E)
  | realKrausPullback (K : Matrix (Fin 2) (Fin 2) ℝ) {E}
      (hE : RealSourceEffectClosure E) :
      RealSourceEffectClosure (Kᵀ * E * K)

/-- Every matrix in the phase-free closure is symmetric. -/
theorem realSourceEffectClosure_symmetric {E : Matrix (Fin 2) (Fin 2) ℝ}
    (hE : RealSourceEffectClosure E) : Eᵀ = E := by
  induction hE with
  | record =>
      ext i j
      fin_cases i <;> fin_cases j <;> simp [recordProjector]
  | companion =>
      ext i j
      fin_cases i <;> fin_cases j <;> simp [companionProjector]
  | conjugatedRecord g =>
      have h := conjProjector_offdiag_symmetric g
      ext i j
      fin_cases i <;> fin_cases j <;> simp [Matrix.transpose_apply, h]
  | conjugatedCompanion g =>
      rw [conjCompanionProjector_eq_complement]
      have h := conjProjector_offdiag_symmetric g
      ext i j
      fin_cases i <;> fin_cases j <;>
        simp [Matrix.transpose_apply, h]
  | zero => simp
  | one => simp
  | complement h ih => rw [Matrix.transpose_sub, Matrix.transpose_one, ih]
  | add hE hF ihE ihF => rw [Matrix.transpose_add, ihE, ihF]
  | realScale r h ih => rw [Matrix.transpose_smul, ih]
  | realKrausPullback K h ih =>
      rw [Matrix.transpose_mul, Matrix.transpose_mul, Matrix.transpose_transpose,
        ih]
      simp only [Matrix.mul_assoc]

/-- Opposite Pauli-Y coherences give equal trace weights against every real
symmetric matrix; trace-one and positivity of the matrix are unnecessary. -/
theorem rhoY_bornWeight_equal_on_real_symmetric
    (E : Matrix (Fin 2) (Fin 2) ℝ) (hE : Eᵀ = E) :
    EventAlgebra.bornWeight rhoYPlus (complexifyRealMatrix E) =
      EventAlgebra.bornWeight rhoYMinus (complexifyRealMatrix E) := by
  have h01 : E 0 1 = E 1 0 := by
    have h := congrFun (congrFun hE (1 : Fin 2)) (0 : Fin 2)
    simpa [Matrix.transpose_apply] using h
  simp [EventAlgebra.bornWeight, rhoYPlus, rhoYMinus,
    complexifyRealMatrix, Matrix.trace, Matrix.diag, Matrix.mul_apply,
    Fin.sum_univ_two]
  rw [h01]
  ring

/-- Even the generous phase-free closure cannot distinguish the exact
Pauli-Y witness states. -/
theorem realSourceEffectClosure_Y_blind {E : Matrix (Fin 2) (Fin 2) ℝ}
    (hE : RealSourceEffectClosure E) :
    EventAlgebra.bornWeight rhoYPlus (complexifyRealMatrix E) =
      EventAlgebra.bornWeight rhoYMinus (complexifyRealMatrix E) :=
  rhoY_bornWeight_equal_on_real_symmetric E
    (realSourceEffectClosure_symmetric hE)

/-- The entire phase-free closure is not complex-tomographically complete,
witnessed by two distinct certified states. -/
theorem realSourceEffectClosure_not_tomographically_complete :
    ∃ rho sigma : Matrix (Fin 2) (Fin 2) ℂ,
      EventAlgebra.IsState rho ∧ EventAlgebra.IsState sigma ∧ rho ≠ sigma ∧
        ∀ E : Matrix (Fin 2) (Fin 2) ℝ,
          RealSourceEffectClosure E →
            EventAlgebra.bornWeight rho (complexifyRealMatrix E) =
              EventAlgebra.bornWeight sigma (complexifyRealMatrix E) := by
  exact ⟨rhoYPlus, rhoYMinus, rhoYPlus_isState, rhoYMinus_isState,
    rhoYPlus_ne_rhoYMinus, fun E hE => realSourceEffectClosure_Y_blind hE⟩

/-- The phase lift is genuinely complex: its upper off-diagonal entry has
imaginary part `-1/2`. -/
theorem sourcePhaseLift_not_complexification :
    ¬ ∃ E : Matrix (Fin 2) (Fin 2) ℝ,
      complexifyRealMatrix E = sourcePhaseLift := by
  rintro ⟨E, hE⟩
  have h01 := congrFun (congrFun hE (0 : Fin 2)) (1 : Fin 2)
  rw [sourcePhaseLift_eq_rhoYPlus] at h01
  have him := congrArg Complex.im h01
  norm_num [complexifyRealMatrix, rhoYPlus] at him

/-- Consequently no amount of the declared phase-free real processing can
produce the phase-lifted effect. -/
theorem sourcePhaseLift_not_in_realSourceEffectClosure :
    ¬ ∃ E : Matrix (Fin 2) (Fin 2) ℝ,
      RealSourceEffectClosure E ∧
        complexifyRealMatrix E = sourcePhaseLift := by
  rintro ⟨E, _, hE⟩
  exact sourcePhaseLift_not_complexification ⟨E, hE⟩

/-! ## Exact tomography after the phase lift -/

/-- The three operator coordinates in the algebraic phase-lift extension. -/
def sourcePhaseTomography (rho : Matrix (Fin 2) (Fin 2) ℂ) : Fin 3 → ℂ :=
  ![EventAlgebra.bornWeight rho (complexifyRealMatrix recordProjector),
    EventAlgebra.bornWeight rho (complexifyRealMatrix (conjProjector 3)),
    EventAlgebra.bornWeight rho sourcePhaseLift]

/-- Record, one algebraically rotated projector, and the exact phase lift separate
all two-by-two matrices on any fixed-trace slice.  Hermiticity and positivity
are not required for this linear-algebra statement. -/
theorem sourcePhaseTomography_injective_on_equalTrace
    {rho sigma : Matrix (Fin 2) (Fin 2) ℂ}
    (htrace : Matrix.trace rho = Matrix.trace sigma)
    (hweights : sourcePhaseTomography rho = sourcePhaseTomography sigma) :
    rho = sigma := by
  have h0 := congrFun hweights (0 : Fin 3)
  have h1 := congrFun hweights (1 : Fin 3)
  have h2 := congrFun hweights (2 : Fin 3)
  change EventAlgebra.bornWeight rho
      (complexifyRealMatrix recordProjector) =
    EventAlgebra.bornWeight sigma
      (complexifyRealMatrix recordProjector) at h0
  change EventAlgebra.bornWeight rho
      (complexifyRealMatrix (conjProjector 3)) =
    EventAlgebra.bornWeight sigma
      (complexifyRealMatrix (conjProjector 3)) at h1
  change EventAlgebra.bornWeight rho sourcePhaseLift =
    EventAlgebra.bornWeight sigma sourcePhaseLift at h2
  rw [sourcePhaseLift_eq_rhoYPlus] at h2
  simp [EventAlgebra.bornWeight,
    complexifyRealMatrix, recordProjector, conjProjector_three, rhoYPlus,
    Matrix.trace, Matrix.diag, Matrix.mul_apply, Fin.sum_univ_two] at h0 h1 h2
  have ht : rho 0 0 + rho 1 1 = sigma 0 0 + sigma 1 1 := by
    simpa [Matrix.trace, Matrix.diag, Fin.sum_univ_two] using htrace
  have h00 : rho 0 0 = sigma 0 0 := by
    linear_combination h0
  have h11 : rho 1 1 = sigma 1 1 := by
    linear_combination ht - h00
  have hsum : rho 0 1 + rho 1 0 = sigma 0 1 + sigma 1 0 := by
    have hsC : (sqrt3 : ℂ) ≠ 0 := by
      exact_mod_cast sqrt3_ne_zero
    apply mul_left_cancel₀ hsC
    linear_combination (-4 : ℂ) * h1 + h00 + 3 * h11
  have hdiff : rho 0 1 - rho 1 0 = sigma 0 1 - sigma 1 0 := by
    have hI : Complex.I ≠ 0 := Complex.I_ne_zero
    have hIdiff : Complex.I * (rho 0 1 - rho 1 0) =
        Complex.I * (sigma 0 1 - sigma 1 0) := by
      linear_combination (2 : ℂ) * h2 - h00 - h11
    exact mul_left_cancel₀ hI hIdiff
  ext i j
  fin_cases i <;> fin_cases j
  · simpa using h00
  · change rho 0 1 = sigma 0 1
    linear_combination (hsum + hdiff) / 2
  · change rho 1 0 = sigma 1 0
    linear_combination (hsum - hdiff) / 2
  · simpa using h11

/-- In particular, the algebraically phase-lifted frame is tomographically
complete on certified states. -/
theorem sourcePhaseTomography_injective_on_states
    {rho sigma : Matrix (Fin 2) (Fin 2) ℂ}
    (hrho : EventAlgebra.IsState rho) (hsigma : EventAlgebra.IsState sigma)
    (hweights : sourcePhaseTomography rho = sourcePhaseTomography sigma) :
    rho = sigma :=
  sourcePhaseTomography_injective_on_equalTrace
    (hrho.2.trans hsigma.2.symm) hweights

/-! ## Campaign summary -/

/-- Exact B13 boundary in one theorem: the phase lift is a projection in the
complex algebra generated by the source-attached algebraic pair, it makes the fixed-trace frame
injective, no phase-free real closure can produce it, and the committed run's
outcome statistics still inhabit only the diagonal native context. -/
theorem sourcePhaseLift_boundary_summary :
    ComplexSourceAlgebraClosure sourcePhaseLift ∧
      EventAlgebra.IsEvent sourcePhaseLift ∧
      (∀ rho sigma : Matrix (Fin 2) (Fin 2) ℂ,
        Matrix.trace rho = Matrix.trace sigma →
        sourcePhaseTomography rho = sourcePhaseTomography sigma →
        rho = sigma) ∧
      (¬ ∃ E : Matrix (Fin 2) (Fin 2) ℝ,
        RealSourceEffectClosure E ∧
          complexifyRealMatrix E = sourcePhaseLift) ∧
      (∀ c : WebContext,
        (realizedOutcomeCounts c).isSome ↔ c = WebContext.diagonal) := by
  exact ⟨sourcePhaseLift_mem_complexSourceAlgebra, sourcePhaseLift_isEvent,
    fun _ _ => sourcePhaseTomography_injective_on_equalTrace,
    sourcePhaseLift_not_in_realSourceEffectClosure,
    realized_statistics_only_diagonal⟩

end

-- Axiom audit: each must report only standard Mathlib axioms.
#print axioms sourcePhaseLift_eq_rhoYPlus
#print axioms sourcePhaseLift_isEvent
#print axioms sourcePhaseLift_distinguishes_Y_states
#print axioms sourcePhaseLift_mem_complexSourceAlgebra
#print axioms realSourceEffectClosure_symmetric
#print axioms rhoY_bornWeight_equal_on_real_symmetric
#print axioms realSourceEffectClosure_Y_blind
#print axioms realSourceEffectClosure_not_tomographically_complete
#print axioms sourcePhaseLift_not_complexification
#print axioms sourcePhaseLift_not_in_realSourceEffectClosure
#print axioms sourcePhaseTomography_injective_on_equalTrace
#print axioms sourcePhaseTomography_injective_on_states
#print axioms sourcePhaseLift_boundary_summary

end OPH.QFT
