#!/usr/bin/env python3
"""Generate the single-page claims scoreboard (Phase 0 of the completion plan).

The scoreboard is one generated artifact: claims x class x status x live gates,
emitted from the same fail-closed sources the claim-registry validator checks
(the registry and the committed GitHub issue snapshot). It is never edited by
hand; ``--check`` fails when the committed page drifts from its sources, and
the mandatory suite runs that check on every push.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCOREBOARD = ROOT / "tracking" / "claims_scoreboard.md"

CLASS_ORDER = [
    "physical_establishment",
    "empirical_implementation",
    "emitted_artifact",
    "branch_entry",
    "conditional_implication",
    "declared_structure",
]


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def render() -> str:
    registry = load(ROOT / "claims" / "claim_registry.yaml")
    snapshot = load(ROOT / "tracking" / "open_issues" / "open_problem_ledger.json")
    claims = registry["claims"]
    repo = snapshot.get("repo", "")
    open_titles = {row["number"]: row.get("title", "") for row in snapshot.get("rows", [])}

    by_class: dict[str, int] = {}
    for claim in claims:
        by_class[claim["claim_class"]] = by_class.get(claim["claim_class"], 0) + 1
    gated = [claim for claim in claims if claim["gates"]]
    gate_numbers = sorted({gate for claim in gated for gate in claim["gates"]})

    lines = [
        "# OPH claims scoreboard",
        "",
        "Generated by `tools/build_scoreboard.py` from `claims/claim_registry.yaml`",
        "and `tracking/open_issues/open_problem_ledger.json`. Do not edit by hand;",
        "`tools/run_mandatory_suite.py` fails when this page drifts from its sources.",
        "",
        f"Release: `{registry['release_id']}` — {len(claims)} claims, "
        f"{len(gate_numbers)} distinct live gates across {len(gated)} gated claims.",
        "",
        "| Class | Claims |",
        "|---|---|",
    ]
    for cls in CLASS_ORDER:
        lines.append(f"| `{cls}` | {by_class.get(cls, 0)} |")
    lines += [
        "",
        "| Claim | Class | Status | Live gates |",
        "|---|---|---|---|",
    ]
    for claim in claims:
        gates = ", ".join(
            f"[#{gate}](https://github.com/{repo}/issues/{gate})" for gate in claim["gates"]
        ) or "—"
        lines.append(
            f"| `{claim['claim_id']}` | `{claim['claim_class']}` "
            f"| `{claim['status']}` | {gates} |"
        )
    lines += [
        "",
        "## Live gates",
        "",
        "| Issue | Title | Gated claims |",
        "|---|---|---|",
    ]
    for gate in gate_numbers:
        holders = ", ".join(
            f"`{claim['claim_id']}`" for claim in claims if gate in claim["gates"]
        )
        title = open_titles.get(gate, "").replace("|", "\\|")
        lines.append(
            f"| [#{gate}](https://github.com/{repo}/issues/{gate}) | {title} | {holders} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    page = render()
    if "--check" in sys.argv[1:]:
        on_disk = SCOREBOARD.read_text(encoding="utf-8") if SCOREBOARD.exists() else ""
        if on_disk != page:
            raise SystemExit(
                f"{SCOREBOARD.relative_to(ROOT)} has drifted from its sources; "
                "regenerate with: python tools/build_scoreboard.py"
            )
        print("claims scoreboard OK: in sync with registry and issue snapshot")
        return
    SCOREBOARD.write_text(page, encoding="utf-8")
    print(f"wrote {SCOREBOARD.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
