"""Build and validate the frozen-prediction ladder surface (issue #607).

The machine-readable register is ``claims/frozen_prediction_register.json``.
This tool validates it fail-closed and renders
``docs/FROZEN_PREDICTION_LADDER.md``; ``--check`` fails when the committed
page differs from the render, and the mandatory suite runs that check.

Fail-closed rules: frozen rows carry a freeze time, custody, attestation,
content hash, kill band, and comparison protocol; pending rows carry an
owning issue that is open in the committed snapshot and a milestone; the
FZ-02 content hash must equal the live receipt hash recomputed from the
committed angular-multiplet receipt, so the registry cannot drift from the
executable content it froze.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTER_PATH = ROOT / "claims" / "frozen_prediction_register.json"
SURFACE_PATH = ROOT / "docs" / "FROZEN_PREDICTION_LADDER.md"
SNAPSHOT_PATH = ROOT / "tracking" / "open_issues" / "open_problem_ledger.json"
FZ02_RECEIPT_PATH = (
    ROOT / "code" / "a5_closure" / "receipts" / "a5_angular_multiplet_reference.receipt.json"
)

SCHEMA = "oph.frozen_prediction_register.v1"
STATUSES = {
    "frozen_attested",
    "frozen_stamped_upgrade_pending",
    "standing_frozen",
    "registered_pending_freeze",
}
FROZEN_STATUSES = {"frozen_attested", "frozen_stamped_upgrade_pending", "standing_frozen"}

ROW_KEYS = {
    "id",
    "content",
    "status",
    "frozen_utc",
    "custody",
    "attestation",
    "content_sha256",
    "kill_band",
    "comparison_protocol",
    "owning_issue",
    "milestone",
}


def fail(message: str) -> None:
    raise SystemExit(f"frozen-prediction register: {message}")


def load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        fail(f"missing input {path.relative_to(ROOT)}")
    except json.JSONDecodeError as error:
        fail(f"invalid JSON in {path.relative_to(ROOT)}: {error}")
    raise AssertionError("unreachable")


def validate(register: dict) -> list[dict]:
    if register.get("schema") != SCHEMA:
        fail(f"schema must equal {SCHEMA}")
    if register.get("issue") != 607:
        fail("issue must equal 607")
    rows = register.get("rows")
    if not isinstance(rows, list) or not rows:
        fail("rows must be a nonempty list")

    snapshot = load_json(SNAPSHOT_PATH)
    open_issues = {row["number"] for row in snapshot["rows"]}

    expected_ids = [f"FZ-{index:02d}" for index in range(1, len(rows) + 1)]
    seen_ids = [row.get("id") for row in rows]
    if seen_ids != expected_ids:
        fail(f"rows must be the contiguous ladder {expected_ids}, got {seen_ids}")

    for index, row in enumerate(rows):
        where = f"rows[{index}] ({row.get('id')})"
        if set(row) != ROW_KEYS:
            fail(f"{where}: keys mismatch")
        if row["status"] not in STATUSES:
            fail(f"{where}: unknown status {row['status']}")
        for key in ("content", "kill_band", "comparison_protocol"):
            if not isinstance(row[key], str) or not row[key].strip():
                fail(f"{where}: {key} must be nonempty")
        if row["status"] in FROZEN_STATUSES:
            for key in ("frozen_utc", "custody", "attestation", "content_sha256"):
                if not isinstance(row[key], str) or not row[key].strip():
                    fail(f"{where}: a frozen row requires {key}")
        else:
            owning = row["owning_issue"]
            if not isinstance(owning, int):
                fail(f"{where}: a pending row requires an owning issue")
            if owning not in open_issues:
                fail(f"{where}: owning issue #{owning} is not open in the snapshot")
            if not isinstance(row["milestone"], str) or not row["milestone"].strip():
                fail(f"{where}: a pending row requires a milestone")

    fz02 = rows[1]
    receipt = load_json(FZ02_RECEIPT_PATH)
    live_hash = receipt.get("receipt_sha256")
    if fz02["content_sha256"] != live_hash:
        fail(
            "the FZ-02 content hash does not equal the live angular-multiplet "
            f"receipt hash {live_hash}"
        )
    return rows


def render(register: dict, rows: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# The frozen-prediction ladder")
    lines.append("")
    lines.append(
        "Generated by `tools/build_fz_registry.py` from"
        " `claims/frozen_prediction_register.json`; edit the JSON, then"
        " regenerate. Issue #607 tracks this register."
    )
    lines.append("")
    lines.append(register["policy"])
    lines.append("")
    lines.append("| Freeze | Content | Status | Frozen (UTC) | Owner | Kill band |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    for row in rows:
        owner = (
            f"[#{row['owning_issue']}](https://github.com/FloatingPragma/observer-patch-holography/issues/{row['owning_issue']})"
            f" ({row['milestone']})"
            if row["owning_issue"] is not None
            else row["milestone"]
        )
        frozen = row["frozen_utc"] if row["frozen_utc"] else "to freeze"
        lines.append(
            f"| {row['id']} | {row['content']} | {row['status']} | {frozen} |"
            f" {owner} | {row['kill_band']} |"
        )
    lines.append("")
    lines.append("## Custody and attestation")
    lines.append("")
    for row in rows:
        if row["status"] in FROZEN_STATUSES:
            lines.append(f"- **{row['id']}**: {row['custody']} {row['attestation']}.")
            lines.append(
                f"  Content hash: `{row['content_sha256']}`."
                f" Comparison protocol: {row['comparison_protocol']}"
            )
    lines.append("")
    lines.append(
        "Pending rows freeze at their milestones, before their comparison data"
    )
    lines.append(
        "is examined; the register validation requires each pending row to name"
    )
    lines.append("a live owning issue and fails closed otherwise.")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    register = load_json(REGISTER_PATH)
    rows = validate(register)
    surface = render(register, rows)
    if args.check:
        committed = (
            SURFACE_PATH.read_text(encoding="utf-8") if SURFACE_PATH.is_file() else ""
        )
        if committed != surface:
            print(
                "frozen-prediction register: docs/FROZEN_PREDICTION_LADDER.md is "
                "stale; run python tools/build_fz_registry.py",
                file=sys.stderr,
            )
            return 1
        print("frozen-prediction register: surface is current")
        return 0
    SURFACE_PATH.write_text(surface, encoding="utf-8", newline="\n")
    print(f"frozen-prediction register: wrote {SURFACE_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
