#!/usr/bin/env python3
"""Generate the single-page claims scoreboard (Phase 0 of the completion plan).

The scoreboard is one generated artifact: claims x class x status x live gates,
emitted from the same fail-closed sources the claim-registry validator checks
(the registry and the committed GitHub issue snapshot). It is never edited by
hand; ``--check`` fails when the committed page drifts from its sources, and
the mandatory suite runs that check on every push.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCOREBOARD = ROOT / "tracking" / "claims_scoreboard.md"
PROOF_SPINE = ROOT / "docs" / "PROOF_SPINE.md"
COMPRESSION_SCORECARD = ROOT / "docs" / "COMPRESSION_SCORECARD.md"

PROJECTION_START = "<!-- CLAIM-STATUS-PROJECTION:BEGIN -->"
PROJECTION_END = "<!-- CLAIM-STATUS-PROJECTION:END -->"

COMPRESSION_TEMPLATE = """# OPH Compression Scorecard

This scorecard deliberately does not collapse heterogeneous mathematical,
artifact, empirical, and physical-establishment rows into one scalar evidence
score. The canonical claim classes, descriptive statuses, and live gates are
the only fail-closed accounting on this surface. Any future quantitative
compression claim must name its input menu and target exposure separately.

<!-- CLAIM-STATUS-PROJECTION:BEGIN -->
<!-- Regenerate with: python tools/build_scoreboard.py -->
<!-- CLAIM-STATUS-PROJECTION:END -->

## Reading rule

Zero adjustable continuous parameters in a declared map is not, by itself,
physical establishment or statistical compression. The claim class and live
gates in the generated projection remain binding.
"""

CLASS_ORDER = [
    "physical_establishment",
    "empirical_implementation",
    "emitted_artifact",
    "branch_entry",
    "conditional_implication",
    "declared_structure",
]


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def source_documents() -> tuple[dict, dict]:
    return (
        load(ROOT / "claims" / "claim_registry.yaml"),
        load(ROOT / "tracking" / "open_issues" / "open_problem_ledger.json"),
    )


def canonical_projection_payload(registry: dict, snapshot: dict) -> dict:
    """Return the normalized status payload shared by all claim surfaces.

    The full open-issue-number set is included. It is broader than the issue
    subset referenced by current claims. Thus opening or closing a GitHub gate
    makes the proof spine and compression scorecard stale until the ledger and
    projection are regenerated together.
    """
    return {
        "schema": 1,
        "release_id": registry["release_id"],
        "claims": registry["claims"],
        "open_issue_numbers": sorted(row["number"] for row in snapshot["rows"]),
    }


def projection_digest(payload: dict) -> str:
    encoded = json.dumps(
        payload,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def render_projection(registry: dict, snapshot: dict) -> str:
    payload = canonical_projection_payload(registry, snapshot)
    claims = registry["claims"]
    by_class = {
        cls: sum(claim["claim_class"] == cls for claim in claims)
        for cls in CLASS_ORDER
    }
    distinct_gates = sorted(
        {gate for claim in claims for gate in claim["gates"]}
    )
    class_census = ", ".join(
        f"`{cls}` {by_class[cls]}" for cls in CLASS_ORDER
    )
    return "\n".join(
        [
            PROJECTION_START,
            "## Canonical claims and live-gates projection",
            "",
            "Generated by `tools/build_scoreboard.py`; do not edit this block. "
            "Its SHA-256 commits to every complete ordered canonical claim row "
            "(including class, status, and gates)",
            "and to the complete open-issue-number set in the committed "
            "GitHub ledger. The generated "
            "[claims scoreboard](../tracking/claims_scoreboard.md) is the "
            "row-by-row view.",
            "",
            f"- Release: `{registry['release_id']}`",
            f"- Projection SHA-256: `{projection_digest(payload)}`",
            f"- Registry: {len(claims)} canonical claims ({class_census})",
            f"- Claim gates: {len(distinct_gates)} distinct open issues across "
            f"{sum(bool(claim['gates']) for claim in claims)} gated claims",
            f"- Open-problem ledger: {len(snapshot['rows'])} open issues",
            PROJECTION_END,
        ]
    )


def replace_projection(text: str, projection: str, relative_path: Path) -> str:
    if text.count(PROJECTION_START) != 1 or text.count(PROJECTION_END) != 1:
        raise SystemExit(
            f"{relative_path}: expected exactly one generated claim-status block; "
            "restore its BEGIN/END markers"
        )
    before, remainder = text.split(PROJECTION_START, 1)
    _, after = remainder.split(PROJECTION_END, 1)
    return before + projection + after


def render(registry: dict | None = None, snapshot: dict | None = None) -> str:
    if registry is None or snapshot is None:
        registry, snapshot = source_documents()
    claims = registry["claims"]
    repo = snapshot.get("repo", "")
    open_titles = {row["number"]: row.get("title", "") for row in snapshot.get("rows", [])}

    by_class: dict[str, int] = {}
    for claim in claims:
        by_class[claim["claim_class"]] = by_class.get(claim["claim_class"], 0) + 1
    gated = [claim for claim in claims if claim["gates"]]
    gate_numbers = sorted({gate for claim in gated for gate in claim["gates"]})

    lines = [
        "# OPH claims scoreboard",
        "",
        "Generated by `tools/build_scoreboard.py` from `claims/claim_registry.yaml`",
        "and `tracking/open_issues/open_problem_ledger.json`. Do not edit by hand;",
        "`tools/run_mandatory_suite.py` fails when this page drifts from its sources.",
        "",
        f"Release: `{registry['release_id']}`. {len(claims)} claims, "
        f"{len(gate_numbers)} distinct live gates across {len(gated)} gated claims.",
        "",
        "| Class | Claims |",
        "|---|---|",
    ]
    for cls in CLASS_ORDER:
        lines.append(f"| `{cls}` | {by_class.get(cls, 0)} |")
    lines += [
        "",
        "| Claim | Class | Status | Live gates |",
        "|---|---|---|---|",
    ]
    for claim in claims:
        gates = ", ".join(
            f"[#{gate}](https://github.com/{repo}/issues/{gate})" for gate in claim["gates"]
        ) or "none"
        lines.append(
            f"| `{claim['claim_id']}` | `{claim['claim_class']}` "
            f"| `{claim['status']}` | {gates} |"
        )
    lines += [
        "",
        "## Live gates",
        "",
        "| Issue | Title | Gated claims |",
        "|---|---|---|",
    ]
    for gate in gate_numbers:
        holders = ", ".join(
            f"`{claim['claim_id']}`" for claim in claims if gate in claim["gates"]
        )
        title = open_titles.get(gate, "").replace("|", "\\|")
        lines.append(
            f"| [#{gate}](https://github.com/{repo}/issues/{gate}) | {title} | {holders} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    registry, snapshot = source_documents()
    page = render(registry, snapshot)
    projection = render_projection(registry, snapshot)
    projection_surfaces = [
        (PROOF_SPINE, None),
        (COMPRESSION_SCORECARD, COMPRESSION_TEMPLATE),
    ]
    if "--check" in sys.argv[1:]:
        on_disk = SCOREBOARD.read_text(encoding="utf-8") if SCOREBOARD.exists() else ""
        if on_disk != page:
            raise SystemExit(
                f"{SCOREBOARD.relative_to(ROOT)} has drifted from its sources; "
                "regenerate with: python tools/build_scoreboard.py"
            )
        for path, _ in projection_surfaces:
            if not path.exists():
                raise SystemExit(
                    f"{path.relative_to(ROOT)} is missing; regenerate with: "
                    "python tools/build_scoreboard.py"
                )
            current = path.read_text(encoding="utf-8")
            expected = replace_projection(current, projection, path.relative_to(ROOT))
            if current != expected:
                raise SystemExit(
                    f"{path.relative_to(ROOT)} claim-status projection has drifted; "
                    "regenerate with: python tools/build_scoreboard.py"
                )
        print(
            "claims scoreboard, proof spine, and compression scorecard OK: "
            "in sync with registry and issue snapshot"
        )
        return
    SCOREBOARD.write_text(page, encoding="utf-8")
    written = [SCOREBOARD.relative_to(ROOT)]
    for path, template in projection_surfaces:
        current = (
            path.read_text(encoding="utf-8")
            if path.exists()
            else template
        )
        if current is None:
            raise SystemExit(f"{path.relative_to(ROOT)} is missing")
        path.write_text(
            replace_projection(current, projection, path.relative_to(ROOT)),
            encoding="utf-8",
        )
        written.append(path.relative_to(ROOT))
    print("wrote " + ", ".join(map(str, written)))


if __name__ == "__main__":
    main()
