import ObserverPatchHolography.Provenance.MismatchProvenance

/-!
# History invariance of the generated causal order

An implementation history executes commit specifications against a threaded
versioned state; a specification declares its identity, read, write, and
certified support sets, and its written payload.  Executor stutters are
steps that commit nothing: the executed event list and the final state read
only the committed specifications, so stutters generate no event and no
edge.

The schedule-invariance theorems bound one specific executor equivalence.
Two adjacent commits whose write sets are disjoint from each other and from
each other's certified supports commute: swapping them preserves the final
state and the raw writer-citation relation on event identifiers.  Histories
related by a chain generated by those adjacent swaps therefore carry equal
citations.  This is not a theorem about all admissible schedules or all
implementations.  A dependent pair is the boundary: swapping a writer past
a reader that certifies the written register changes the citation set, so
the independence clauses are load-bearing.

On complete finite executed histories the authenticated read-after-write
relation and a termination rank are both derived rather than declared.
`semanticEventLogOfExecution` selects the unique executed commit for every
carrier identifier, derives that witness from list position, and proves that
its parent edges and generated closure are exactly the executed authenticated
relation and its transitive closure.  The finite wrapper
`semanticEventLogOfExecutionWithSourceHeight` then replaces list position by
the canonical longest authenticated-parent-path height without changing an
edge or generated comparison.

A separate persistence theorem supplies the record-side reading of a
long-lived cut: a freshly injected overlap mismatch survives every
continuation whose commits avoid the overlap support, at full strength, at
every intermediate stage.  Nothing here selects a schedule, derives
fairness, assigns physical time, or identifies the informational order with
physical signal propagation.
-/

namespace OPH.Provenance

universe u v w

variable {Register : Type u} {Value : Type v} {EventId : Type w}
variable [DecidableEq Register]

/-- A commit specification: identity, declared register sets, and the
written payload.  The payload is declared per specification, so execution
threads only provenance. -/
structure CommitSpec (Register : Type u) (Value : Type v)
    (EventId : Type w) [DecidableEq Register] where
  /-- The specification's event identifier. -/
  eventId : EventId
  /-- The declared read set. -/
  readSet : Finset Register
  /-- The declared write set. -/
  writeSet : Finset Register
  /-- The certified causal read support. -/
  causalSupp : Finset Register
  /-- The causal support only cites read registers. -/
  supp_subset_read : causalSupp ⊆ readSet
  /-- The written payload on the write set. -/
  writeValue : Register → Value

namespace CommitSpec

/-- Applying a specification writes its payload and stamps its identifier
on the write set, and fixes every other register. -/
def apply (s : CommitSpec Register Value EventId)
    (q : VersionedState Register Value EventId) :
    VersionedState Register Value EventId where
  value a := if a ∈ s.writeSet then s.writeValue a else q.value a
  writer a := if a ∈ s.writeSet then some s.eventId else q.writer a

@[simp] theorem apply_value_mem {s : CommitSpec Register Value EventId}
    {q : VersionedState Register Value EventId} {a : Register}
    (ha : a ∈ s.writeSet) : (s.apply q).value a = s.writeValue a :=
  if_pos ha

@[simp] theorem apply_value_notMem {s : CommitSpec Register Value EventId}
    {q : VersionedState Register Value EventId} {a : Register}
    (ha : a ∉ s.writeSet) : (s.apply q).value a = q.value a :=
  if_neg ha

@[simp] theorem apply_writer_mem {s : CommitSpec Register Value EventId}
    {q : VersionedState Register Value EventId} {a : Register}
    (ha : a ∈ s.writeSet) : (s.apply q).writer a = some s.eventId :=
  if_pos ha

@[simp] theorem apply_writer_notMem {s : CommitSpec Register Value EventId}
    {q : VersionedState Register Value EventId} {a : Register}
    (ha : a ∉ s.writeSet) : (s.apply q).writer a = q.writer a :=
  if_neg ha

/-- The semantic commit executed by a specification at a state. -/
def commitAt (s : CommitSpec Register Value EventId)
    (q : VersionedState Register Value EventId) :
    SemanticCommit Register Value EventId where
  eventId := s.eventId
  before := q
  after := s.apply q
  readSet := s.readSet
  writeSet := s.writeSet
  causalSupp := s.causalSupp
  supp_subset_read := s.supp_subset_read
  frame_value := fun _ ha => if_neg ha
  frame_writer := fun _ ha => if_neg ha
  stamp := fun _ ha => if_pos ha

/-- Direct parenthood of an executed commit reads only the pre-commit
writers on the certified support. -/
theorem parent_commitAt_iff (c : SemanticCommit Register Value EventId)
    (s : CommitSpec Register Value EventId)
    (q : VersionedState Register Value EventId) :
    DirectSemanticParent c (s.commitAt q) ↔
      ∃ a ∈ s.causalSupp, q.writer a = some c.eventId :=
  Iff.rfl

/-- Two states agreeing on the writers of the certified support execute
the same parent verdicts. -/
theorem parent_commitAt_congr {s : CommitSpec Register Value EventId}
    {q q' : VersionedState Register Value EventId}
    (h : ∀ a ∈ s.causalSupp, q.writer a = q'.writer a)
    (c : SemanticCommit Register Value EventId) :
    DirectSemanticParent c (s.commitAt q) ↔
      DirectSemanticParent c (s.commitAt q') := by
  constructor
  · rintro ⟨a, ha, hw⟩
    exact ⟨a, ha, (h a ha).symm.trans hw⟩
  · rintro ⟨a, ha, hw⟩
    exact ⟨a, ha, (h a ha).trans hw⟩

/-- Two write-disjoint specifications apply in either order to the same
state. -/
theorem apply_comm {s t : CommitSpec Register Value EventId}
    (h : ∀ a : Register, a ∈ s.writeSet → a ∉ t.writeSet)
    (q : VersionedState Register Value EventId) :
    t.apply (s.apply q) = s.apply (t.apply q) := by
  have value_eq : ∀ a : Register,
      (t.apply (s.apply q)).value a = (s.apply (t.apply q)).value a := by
    intro a
    by_cases hs : a ∈ s.writeSet
    · have ht : a ∉ t.writeSet := h a hs
      simp [apply_value_mem, apply_value_notMem, hs, ht]
    · by_cases ht : a ∈ t.writeSet
      · simp [apply_value_mem, apply_value_notMem, hs, ht]
      · simp [apply_value_notMem, hs, ht]
  have writer_eq : ∀ a : Register,
      (t.apply (s.apply q)).writer a = (s.apply (t.apply q)).writer a := by
    intro a
    by_cases hs : a ∈ s.writeSet
    · have ht : a ∉ t.writeSet := h a hs
      simp [apply_writer_mem, apply_writer_notMem, hs, ht]
    · by_cases ht : a ∈ t.writeSet
      · simp [apply_writer_mem, apply_writer_notMem, hs, ht]
      · simp [apply_writer_notMem, hs, ht]
  cases hq : t.apply (s.apply q) with
  | mk v w =>
      cases hq' : s.apply (t.apply q) with
      | mk v' w' =>
          have hv : v = v' := by
            funext a
            have := value_eq a
            rw [hq, hq'] at this
            exact this
          have hw : w = w' := by
            funext a
            have := writer_eq a
            rw [hq, hq'] at this
            exact this
          rw [hv, hw]

end CommitSpec

/-! ## Execution of histories with stutters -/

/-- An implementation step: one commit specification or one executor
stutter. -/
inductive RunStep (Register : Type u) (Value : Type v) (EventId : Type w)
    [DecidableEq Register] where
  /-- A semantic commit step. -/
  | commit (s : CommitSpec Register Value EventId)
  /-- An executor stutter: no record changes and no event. -/
  | stutter

/-- The committed specifications of a history: stutters contribute
nothing. -/
def committedSpecs :
    List (RunStep Register Value EventId) →
      List (CommitSpec Register Value EventId)
  | [] => []
  | RunStep.commit s :: rest => s :: committedSpecs rest
  | RunStep.stutter :: rest => committedSpecs rest

/-- The state after executing a specification list. -/
def execState (q : VersionedState Register Value EventId) :
    List (CommitSpec Register Value EventId) →
      VersionedState Register Value EventId
  | [] => q
  | s :: rest => execState (s.apply q) rest

/-- The executed event list of a specification list. -/
def execLog (q : VersionedState Register Value EventId) :
    List (CommitSpec Register Value EventId) →
      List (SemanticCommit Register Value EventId)
  | [] => []
  | s :: rest => s.commitAt q :: execLog (s.apply q) rest

/-- Inserting a stutter anywhere in a history changes neither the
committed specifications, hence neither the executed event list nor the
final state. -/
theorem committedSpecs_insert_stutter
    (pre post : List (RunStep Register Value EventId)) :
    committedSpecs (pre ++ RunStep.stutter :: post) =
      committedSpecs (pre ++ post) := by
  induction pre with
  | nil => rfl
  | cons head tail ih =>
      cases head with
      | commit s => simp [committedSpecs, ih]
      | stutter => simp [committedSpecs, ih]

@[simp] theorem execState_append (q : VersionedState Register Value EventId)
    (xs ys : List (CommitSpec Register Value EventId)) :
    execState q (xs ++ ys) = execState (execState q xs) ys := by
  induction xs generalizing q with
  | nil => rfl
  | cons s rest ih => simp [execState, ih]

@[simp] theorem execLog_append (q : VersionedState Register Value EventId)
    (xs ys : List (CommitSpec Register Value EventId)) :
    execLog q (xs ++ ys) = execLog q xs ++ execLog (execState q xs) ys := by
  induction xs generalizing q with
  | nil => rfl
  | cons s rest ih => simp [execLog, execState, ih]

/-! ## The executed direct-parent relation -/

/-- The direct-parent relation of an executed history, read on event
identifiers. -/
def execParents (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (e f : EventId) : Prop :=
  ∃ c ∈ execLog q specs, ∃ d ∈ execLog q specs,
    c.eventId = e ∧ d.eventId = f ∧ DirectSemanticParent c d

/-- Writers in a threaded state are initial or stamped by an executed
specification. -/
theorem execState_writer_cases
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId)) (a : Register) :
    (execState q specs).writer a = q.writer a ∨
      ∃ s ∈ specs, a ∈ s.writeSet ∧
        (execState q specs).writer a = some s.eventId := by
  induction specs generalizing q with
  | nil => exact Or.inl rfl
  | cons s rest ih =>
      rcases ih (s.apply q) with h | ⟨t, ht, hat, hw⟩
      · by_cases ha : a ∈ s.writeSet
        · exact Or.inr ⟨s, List.mem_cons_self, ha, by
            simpa [execState, CommitSpec.apply_writer_mem ha] using h⟩
        · exact Or.inl (by
            simpa [execState, CommitSpec.apply_writer_notMem ha] using h)
      · exact Or.inr ⟨t, List.mem_cons_of_mem s ht, hat, hw⟩

/-- Writers and values evolve together in a threaded execution: a final
register is either the untouched initial pair or the value-version stamped
by an executed specification which wrote that register. -/
theorem execState_version_cases
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId)) (a : Register) :
    ((execState q specs).writer a = q.writer a ∧
        (execState q specs).value a = q.value a) ∨
      ∃ s ∈ specs, a ∈ s.writeSet ∧
        (execState q specs).writer a = some s.eventId ∧
        (execState q specs).value a = s.writeValue a := by
  induction specs generalizing q with
  | nil => exact Or.inl ⟨rfl, rfl⟩
  | cons s rest ih =>
      rcases ih (s.apply q) with h | ⟨t, ht, hat, hw, hv⟩
      · by_cases ha : a ∈ s.writeSet
        · exact Or.inr ⟨s, List.mem_cons_self, ha, by
            simpa [execState, CommitSpec.apply_writer_mem ha] using h.1,
            by simpa [execState, CommitSpec.apply_value_mem ha] using h.2⟩
        · exact Or.inl ⟨by
            simpa [execState, CommitSpec.apply_writer_notMem ha] using h.1,
            by simpa [execState, CommitSpec.apply_value_notMem ha] using h.2⟩
      · exact Or.inr
          ⟨t, List.mem_cons_of_mem s ht, hat, hw, hv⟩

/-- Executed events carry exactly the specification identifiers, in
order. -/
theorem execLog_ids (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId)) :
    (execLog q specs).map SemanticCommit.eventId =
      specs.map CommitSpec.eventId := by
  induction specs generalizing q with
  | nil => rfl
  | cons s rest ih => simp [execLog, CommitSpec.commitAt, ih]

/-! ## The append-only rank and authenticated log are derived on executions -/

/-- A history is provenance-fresh at a start state when no specification
identifier occurs as a writer of the start state. -/
def FreshStart (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId)) : Prop :=
  ∀ s ∈ specs, ∀ a : Register, q.writer a ≠ some s.eventId

/-- The parent of an executed commit is always stamped by a strict-prefix
specification: executed provenance is append-only. -/
theorem exec_parent_mem_prefix
    {q : VersionedState Register Value EventId}
    {xs ys : List (CommitSpec Register Value EventId)}
    {s : CommitSpec Register Value EventId}
    (hfresh : FreshStart q (xs ++ s :: ys))
    {c : SemanticCommit Register Value EventId}
    (hclog : c.eventId ∈ (xs ++ s :: ys).map CommitSpec.eventId)
    (hparent : DirectSemanticParent c (s.commitAt (execState q xs))) :
    c.eventId ∈ xs.map CommitSpec.eventId := by
  obtain ⟨a, _, hw⟩ := hparent
  have hw' : (execState q xs).writer a = some c.eventId := hw
  rcases execState_writer_cases q xs a with hinit | ⟨t, ht, _, hwt⟩
  · rw [hinit] at hw'
    obtain ⟨e, he, hid⟩ := List.mem_map.mp hclog
    exact absurd (hw'.trans (congrArg some hid.symm)) (hfresh e he a)
  · rw [hwt] at hw'
    have hid : t.eventId = c.eventId := by
      simpa using hw'
    exact hid ▸ List.mem_map_of_mem ht

/-- Identifier rank in a list: the position of the first occurrence. -/
def idRank [DecidableEq EventId] :
    List EventId → EventId → ℕ
  | [], _ => 0
  | x :: rest, e => if x = e then 0 else idRank rest e + 1

theorem idRank_append_self [DecidableEq EventId]
    {l₁ l₂ : List EventId} {e : EventId} (h : e ∉ l₁) :
    idRank (l₁ ++ e :: l₂) e = l₁.length := by
  induction l₁ with
  | nil => simp [idRank]
  | cons x rest ih =>
      have hxe : x ≠ e := fun hx => h (hx ▸ List.mem_cons_self)
      have hrest : e ∉ rest := fun hr => h (List.mem_cons_of_mem x hr)
      simp [idRank, hxe, ih hrest]

theorem idRank_lt_of_mem_prefix [DecidableEq EventId]
    {l₁ l₂ : List EventId} {e : EventId} (h : e ∈ l₁) :
    idRank (l₁ ++ l₂) e < l₁.length := by
  induction l₁ with
  | nil => exact absurd h (List.not_mem_nil)
  | cons x rest ih =>
      by_cases hxe : x = e
      · simp [idRank, hxe]
      · have hrest : e ∈ rest := by
          rcases List.mem_cons.mp h with hx | hr
          · exact absurd hx.symm hxe
          · exact hr
        have := ih hrest
        simp only [List.cons_append, idRank, hxe, if_false,
          List.length_cons]
        omega

/-- Every executed event is the commit of one specification at the state
after a strict prefix. -/
theorem execLog_mem_split
    {q : VersionedState Register Value EventId}
    {specs : List (CommitSpec Register Value EventId)}
    {d : SemanticCommit Register Value EventId}
    (hd : d ∈ execLog q specs) :
    ∃ xs s ys, specs = xs ++ s :: ys ∧
      d = CommitSpec.commitAt s (execState q xs) := by
  induction specs generalizing q with
  | nil => simp [execLog] at hd
  | cons s rest ih =>
      rcases List.mem_cons.mp hd with hds | hdrest
      · exact ⟨[], s, rest, by simp, by simpa [execState] using hds⟩
      · obtain ⟨xs, t, ys, hsplit, hcommit⟩ := ih hdrest
        exact ⟨s :: xs, t, ys, by rw [hsplit]; rfl, by
          simpa [execState] using hcommit⟩

/-- On a fresh, duplicate-free executed history the specification position
supplies the abstract ancestry-rank acyclicity witness: every executed
direct-parent pair is position-ordered. The append-only rank premise is
derived on this branch. Geometry does not use these numerical values; it
recomputes canonical `sourceHeight` from authenticated parenthood. -/
theorem execParents_rank_lt [DecidableEq EventId]
    {q : VersionedState Register Value EventId}
    {specs : List (CommitSpec Register Value EventId)}
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    {e f : EventId} (h : execParents q specs e f) :
    idRank (specs.map CommitSpec.eventId) e <
      idRank (specs.map CommitSpec.eventId) f := by
  classical
  obtain ⟨c, hc, d, hd, hce, hdf, hparent⟩ := h
  obtain ⟨xs, s, ys, hsplit, hcommit⟩ := execLog_mem_split hd
  subst hsplit
  have hce' : c.eventId ∈
      (xs ++ s :: ys).map CommitSpec.eventId := by
    have := List.mem_map_of_mem (f := SemanticCommit.eventId) hc
    rwa [execLog_ids] at this
  have hprefix : c.eventId ∈ xs.map CommitSpec.eventId := by
    refine exec_parent_mem_prefix hfresh hce' ?_
    rw [← hcommit]
    exact hparent
  have hf : f = s.eventId := by
    rw [← hdf, hcommit]
    rfl
  have hids :
      (xs ++ s :: ys).map CommitSpec.eventId =
        xs.map CommitSpec.eventId ++
          s.eventId :: ys.map CommitSpec.eventId := by
    simp
  have hnot : s.eventId ∉ xs.map CommitSpec.eventId := by
    rw [hids] at hnodup
    have hdisj :=
      (List.nodup_append.mp hnodup).2.2
    intro hmem
    exact hdisj s.eventId hmem s.eventId List.mem_cons_self rfl
  have hlt :
      idRank ((xs ++ s :: ys).map CommitSpec.eventId) c.eventId <
        (xs.map CommitSpec.eventId).length := by
    rw [hids]
    exact idRank_lt_of_mem_prefix hprefix
  have heq :
      idRank ((xs ++ s :: ys).map CommitSpec.eventId) s.eventId =
        (xs.map CommitSpec.eventId).length := by
    rw [hids]
    exact idRank_append_self hnot
  rw [← hce, hf, heq]
  exact hlt

/-! ### Authenticated execution relation and exact log bridge -/

/-- Authenticated direct parents appearing in one threaded execution.  In
addition to event membership and writer attribution, an edge witnesses that
the parent wrote the cited support register and that the child's pre-state
contains the parent's committed value. -/
def execAuthenticatedParents
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (e f : EventId) : Prop :=
  ∃ c ∈ execLog q specs, ∃ d ∈ execLog q specs,
    c.eventId = e ∧ d.eventId = f ∧
      AuthenticatedDirectSemanticParent c d

/-- Authenticated execution parents inherit the position rank proved for
raw citations. -/
theorem execAuthenticatedParents_rank_lt [DecidableEq EventId]
    {q : VersionedState Register Value EventId}
    {specs : List (CommitSpec Register Value EventId)}
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    {e f : EventId} (h : execAuthenticatedParents q specs e f) :
    idRank (specs.map CommitSpec.eventId) e <
      idRank (specs.map CommitSpec.eventId) f := by
  apply execParents_rank_lt hfresh hnodup
  obtain ⟨c, hc, d, hd, hce, hdf, hparent⟩ := h
  exact ⟨c, hc, d, hd, hce, hdf,
    directSemanticParent_of_authenticated hparent⟩

/-- A list whose mapped labels are duplicate-free contains at most one
element with any given label.  This generic helper is the uniqueness step
used to recover the actual executed commit rather than merely trusting an
event identifier written into a snapshot. -/
theorem eq_of_mem_of_mem_of_map_nodup
    {α β : Type*} (f : α → β) {l : List α} {x y : α}
    (hnodup : (l.map f).Nodup) (hx : x ∈ l) (hy : y ∈ l)
    (hxy : f x = f y) : x = y := by
  induction l generalizing x y with
  | nil => exact absurd hx (List.not_mem_nil)
  | cons z rest ih =>
      rw [List.map_cons, List.nodup_cons] at hnodup
      rcases List.mem_cons.mp hx with rfl | hxrest
      · rcases List.mem_cons.mp hy with rfl | hyrest
        · rfl
        · have hz : f x ∈ rest.map f := by
            rw [hxy]
            exact List.mem_map_of_mem hyrest
          exact absurd hz hnodup.1
      · rcases List.mem_cons.mp hy with rfl | hyrest
        · have hz : f y ∈ rest.map f := by
            rw [← hxy]
            exact List.mem_map_of_mem hxrest
          exact absurd hz hnodup.1
        · exact ih hnodup.2 hxrest hyrest hxy

/-- On a fresh duplicate-free threaded execution, every raw writer citation
between executed commits is an authenticated read-after-write edge.  This
is the theorem which rules out forged writer identifiers at the producer
boundary: the named commit is uniquely recovered from the history, it wrote
the support register, and the value stayed paired with its writer stamp. -/
theorem execParents_authenticated [DecidableEq EventId]
    {q : VersionedState Register Value EventId}
    {specs : List (CommitSpec Register Value EventId)}
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    {e f : EventId} (h : execParents q specs e f) :
    execAuthenticatedParents q specs e f := by
  obtain ⟨c, hc, d, hd, hce, hdf, a, ha, hwriter⟩ := h
  obtain ⟨cpre, cs, cpost, hcsplit, hccommit⟩ := execLog_mem_split hc
  obtain ⟨dpre, ds, dpost, hdsplit, hdcommit⟩ := execLog_mem_split hd
  have hcsmem : cs ∈ specs := by
    rw [hcsplit]
    exact List.mem_append_right cpre List.mem_cons_self
  have hcid : c.eventId = cs.eventId := by rw [hccommit]; rfl
  have hwriter' : (execState q dpre).writer a = some c.eventId := by
    rwa [hdcommit] at hwriter
  rcases execState_version_cases q dpre a with hinit |
      ⟨t, ht, hat, htwriter, htvalue⟩
  · have hq : q.writer a = some cs.eventId := by
      rw [← hcid]
      exact hinit.1.symm.trans hwriter'
    exact absurd hq (hfresh cs hcsmem a)
  · have htspecs : t ∈ specs := by
      rw [hdsplit]
      exact List.mem_append_left (ds :: dpost) ht
    have htid : t.eventId = cs.eventId := by
      have : t.eventId = c.eventId := by
        rw [htwriter] at hwriter'
        simpa using hwriter'
      exact this.trans hcid
    have htcs : t = cs := by
      apply eq_of_mem_of_mem_of_map_nodup CommitSpec.eventId hnodup
        htspecs hcsmem htid
    have hacs : a ∈ cs.writeSet := by simpa [htcs] using hat
    have hac : a ∈ c.writeSet := by simpa [hccommit] using hacs
    have hvalue : d.before.value a = c.after.value a := by
      calc
        d.before.value a = (execState q dpre).value a := by
          simp [hdcommit, CommitSpec.commitAt]
        _ = t.writeValue a := htvalue
        _ = cs.writeValue a := by rw [htcs]
        _ = c.after.value a := by
          simp [hccommit, CommitSpec.commitAt,
            CommitSpec.apply_value_mem hacs]
    exact ⟨c, hc, d, hd, hce, hdf,
      ⟨a, ha, hac, hwriter, hvalue⟩⟩

/-- On a fresh duplicate-free execution the raw writer-citation relation
and authenticated parent relation coincide. -/
theorem execParents_iff_authenticated [DecidableEq EventId]
    {q : VersionedState Register Value EventId}
    {specs : List (CommitSpec Register Value EventId)}
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (e f : EventId) :
    execParents q specs e f ↔ execAuthenticatedParents q specs e f := by
  constructor
  · exact execParents_authenticated hfresh hnodup
  · rintro ⟨c, hc, d, hd, hce, hdf, hparent⟩
    exact ⟨c, hc, d, hd, hce, hdf,
      directSemanticParent_of_authenticated hparent⟩

/-- Completeness of a finite event carrier for an executed history: every
carrier identifier occurs in the committed specification list.  This is a
coverage requirement, not a causal or physical assumption. -/
def ExecutedCarrierComplete
    (specs : List (CommitSpec Register Value EventId)) : Prop :=
  ∀ e : EventId, e ∈ specs.map CommitSpec.eventId

private theorem executedCommit_exists
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hcomplete : ExecutedCarrierComplete specs) (e : EventId) :
    ∃ c ∈ execLog q specs, c.eventId = e := by
  have he : e ∈ (execLog q specs).map SemanticCommit.eventId := by
    rw [execLog_ids]
    exact hcomplete e
  exact List.mem_map.mp he

/-- The unique executed semantic commit carrying an event identifier.  The
definition is used only under carrier completeness and duplicate-free
identifiers; its membership and uniqueness are exposed by the following
theorems. -/
noncomputable def executedCommitOf
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hcomplete : ExecutedCarrierComplete specs) (e : EventId) :
    SemanticCommit Register Value EventId :=
  Classical.choose (executedCommit_exists q specs hcomplete e)

theorem executedCommitOf_mem
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hcomplete : ExecutedCarrierComplete specs) (e : EventId) :
    executedCommitOf q specs hcomplete e ∈ execLog q specs :=
  (Classical.choose_spec (executedCommit_exists q specs hcomplete e)).1

theorem executedCommitOf_eventId
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hcomplete : ExecutedCarrierComplete specs) (e : EventId) :
    (executedCommitOf q specs hcomplete e).eventId = e :=
  (Classical.choose_spec (executedCommit_exists q specs hcomplete e)).2

/-- The canonical semantic event log of a fresh, duplicate-free, complete
threaded execution.  Its rank is the first occurrence position in the
executed specification list and is proved increasing; no unrelated rank is
accepted at this construction boundary. -/
noncomputable def semanticEventLogOfExecution [DecidableEq EventId]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) :
    SemanticEventLog Register Value EventId where
  commitOf := executedCommitOf q specs hcomplete
  commitOf_eventId := executedCommitOf_eventId q specs hcomplete
  rank := idRank (specs.map CommitSpec.eventId)
  rank_lt_of_parent := by
    intro e f hparent
    apply execAuthenticatedParents_rank_lt hfresh hnodup
    exact ⟨executedCommitOf q specs hcomplete e,
      executedCommitOf_mem q specs hcomplete e,
      executedCommitOf q specs hcomplete f,
      executedCommitOf_mem q specs hcomplete f,
      executedCommitOf_eventId q specs hcomplete e,
      executedCommitOf_eventId q specs hcomplete f, hparent⟩

/-- The parent edges of the canonical executed log are exactly the
authenticated read-after-write edges found in the threaded execution. -/
theorem semanticEventLogOfExecution_parentEdge_iff [DecidableEq EventId]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) (e f : EventId) :
    (semanticEventLogOfExecution q specs hfresh hnodup hcomplete).ParentEdge
        e f ↔
      execAuthenticatedParents q specs e f := by
  let L := semanticEventLogOfExecution q specs hfresh hnodup hcomplete
  have hlognodup :
      ((execLog q specs).map SemanticCommit.eventId).Nodup := by
    rw [execLog_ids]
    exact hnodup
  constructor
  · intro h
    exact ⟨executedCommitOf q specs hcomplete e,
      executedCommitOf_mem q specs hcomplete e,
      executedCommitOf q specs hcomplete f,
      executedCommitOf_mem q specs hcomplete f,
      executedCommitOf_eventId q specs hcomplete e,
      executedCommitOf_eventId q specs hcomplete f, h⟩
  · rintro ⟨c, hc, d, hd, hce, hdf, hparent⟩
    have hcEq : c = executedCommitOf q specs hcomplete e :=
      eq_of_mem_of_mem_of_map_nodup SemanticCommit.eventId hlognodup hc
        (executedCommitOf_mem q specs hcomplete e)
        (hce.trans (executedCommitOf_eventId q specs hcomplete e).symm)
    have hdEq : d = executedCommitOf q specs hcomplete f :=
      eq_of_mem_of_mem_of_map_nodup SemanticCommit.eventId hlognodup hd
        (executedCommitOf_mem q specs hcomplete f)
        (hdf.trans (executedCommitOf_eventId q specs hcomplete f).symm)
    simpa [L, semanticEventLogOfExecution, hcEq, hdEq] using hparent

/-- The generated precedence of the canonical executed log is exactly the
transitive closure of authenticated execution edges. -/
theorem semanticEventLogOfExecution_generatedBefore_iff
    [DecidableEq EventId]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) (e f : EventId) :
    (semanticEventLogOfExecution q specs hfresh hnodup hcomplete).GeneratedBefore
        e f ↔
      Relation.TransGen (execAuthenticatedParents q specs) e f := by
  constructor
  · intro h
    induction h with
    | single hedge =>
        exact Relation.TransGen.single
          ((semanticEventLogOfExecution_parentEdge_iff q specs hfresh
            hnodup hcomplete _ _).mp hedge)
    | tail _ hedge ih =>
        exact Relation.TransGen.tail ih
          ((semanticEventLogOfExecution_parentEdge_iff q specs hfresh
            hnodup hcomplete _ _).mp hedge)
  · intro h
    induction h with
    | single hedge =>
        exact Relation.TransGen.single
          ((semanticEventLogOfExecution_parentEdge_iff q specs hfresh
            hnodup hcomplete _ _).mpr hedge)
    | tail _ hedge ih =>
        exact Relation.TransGen.tail ih
          ((semanticEventLogOfExecution_parentEdge_iff q specs hfresh
            hnodup hcomplete _ _).mpr hedge)

/-- The finite executed semantic log re-ranked by the canonical longest
authenticated-parent path.  The execution-position rank is retained only as
the termination certificate used to compute `sourceHeight`; the exposed rank
of this wrapper is determined by authenticated parenthood alone. -/
noncomputable def semanticEventLogOfExecutionWithSourceHeight
    [Fintype EventId] [DecidableEq EventId] [DecidableEq Value]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) :
    SemanticEventLog Register Value EventId :=
  (semanticEventLogOfExecution q specs hfresh hnodup hcomplete).withSourceHeight

@[simp] theorem semanticEventLogOfExecutionWithSourceHeight_rank
    [Fintype EventId] [DecidableEq EventId] [DecidableEq Value]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) (e : EventId) :
    (semanticEventLogOfExecutionWithSourceHeight q specs hfresh hnodup
      hcomplete).rank e =
      (semanticEventLogOfExecution q specs hfresh hnodup hcomplete).sourceHeight e :=
  rfl

/-- Canonical source-height re-ranking preserves the exact executed parent
relation. -/
theorem semanticEventLogOfExecutionWithSourceHeight_parentEdge_iff
    [Fintype EventId] [DecidableEq EventId] [DecidableEq Value]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) (e f : EventId) :
    (semanticEventLogOfExecutionWithSourceHeight q specs hfresh hnodup
      hcomplete).ParentEdge e f ↔ execAuthenticatedParents q specs e f := by
  simpa [semanticEventLogOfExecutionWithSourceHeight] using
    (semanticEventLogOfExecution_parentEdge_iff q specs hfresh hnodup
      hcomplete e f)

/-- Canonical source-height re-ranking preserves the exact executed generated
precedence. -/
theorem semanticEventLogOfExecutionWithSourceHeight_generatedBefore_iff
    [Fintype EventId] [DecidableEq EventId] [DecidableEq Value]
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hfresh : FreshStart q specs)
    (hnodup : (specs.map CommitSpec.eventId).Nodup)
    (hcomplete : ExecutedCarrierComplete specs) (e f : EventId) :
    (semanticEventLogOfExecutionWithSourceHeight q specs hfresh hnodup
      hcomplete).GeneratedBefore e f ↔
      Relation.TransGen (execAuthenticatedParents q specs) e f := by
  simpa [semanticEventLogOfExecutionWithSourceHeight] using
    (semanticEventLogOfExecution_generatedBefore_iff q specs hfresh hnodup
      hcomplete e f)

/-! ## Independent commutation -/

/-- A specification cites an event at a state: it carries the child
identifier and certifies a register whose writer is the cited event. -/
def SpecCites (s : CommitSpec Register Value EventId)
    (q : VersionedState Register Value EventId) (e f : EventId) : Prop :=
  s.eventId = f ∧ ∃ a ∈ s.causalSupp, q.writer a = some e

/-- The executed child-citation relation. -/
def execChildCites (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (e f : EventId) : Prop :=
  ∃ d ∈ execLog q specs, d.eventId = f ∧
    ∃ a ∈ d.causalSupp, d.before.writer a = some e

theorem execChildCites_nil (q : VersionedState Register Value EventId)
    (e f : EventId) : ¬ execChildCites q [] e f := by
  rintro ⟨d, hd, _⟩
  simp [execLog] at hd

theorem execChildCites_cons (q : VersionedState Register Value EventId)
    (s : CommitSpec Register Value EventId)
    (rest : List (CommitSpec Register Value EventId)) (e f : EventId) :
    execChildCites q (s :: rest) e f ↔
      SpecCites s q e f ∨ execChildCites (s.apply q) rest e f := by
  constructor
  · rintro ⟨d, hd, hdf, a, ha, hw⟩
    rcases List.mem_cons.mp hd with hds | hdrest
    · subst hds
      exact Or.inl ⟨hdf, a, ha, hw⟩
    · exact Or.inr ⟨d, hdrest, hdf, a, ha, hw⟩
  · rintro (⟨hdf, a, ha, hw⟩ | ⟨d, hd, hdf, a, ha, hw⟩)
    · exact ⟨s.commitAt q, List.mem_cons_self, hdf, a, ha, hw⟩
    · exact ⟨d, List.mem_cons_of_mem _ hd, hdf, a, ha, hw⟩

theorem execChildCites_append (q : VersionedState Register Value EventId)
    (xs ys : List (CommitSpec Register Value EventId)) (e f : EventId) :
    execChildCites q (xs ++ ys) e f ↔
      execChildCites q xs e f ∨
        execChildCites (execState q xs) ys e f := by
  constructor
  · rintro ⟨d, hd, hrest⟩
    rw [execLog_append] at hd
    rcases List.mem_append.mp hd with hx | hy
    · exact Or.inl ⟨d, hx, hrest⟩
    · exact Or.inr ⟨d, hy, hrest⟩
  · rintro (⟨d, hd, hrest⟩ | ⟨d, hd, hrest⟩)
    · exact ⟨d, by rw [execLog_append]; exact List.mem_append_left _ hd,
        hrest⟩
    · exact ⟨d, by rw [execLog_append]; exact List.mem_append_right _ hd,
        hrest⟩

/-- The executed parent relation splits into identifier presence and a
child citation. -/
theorem execParents_iff (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId)) (e f : EventId) :
    execParents q specs e f ↔
      e ∈ specs.map CommitSpec.eventId ∧ execChildCites q specs e f := by
  constructor
  · rintro ⟨c, hc, d, hd, hce, hdf, a, ha, hw⟩
    refine ⟨?_, d, hd, hdf, a, ha, by rw [hw, hce]⟩
    have := List.mem_map_of_mem (f := SemanticCommit.eventId) hc
    rw [execLog_ids] at this
    exact hce ▸ this
  · rintro ⟨hmem, d, hd, hdf, a, ha, hw⟩
    rw [← execLog_ids q specs] at hmem
    obtain ⟨c, hc, hce⟩ := List.mem_map.mp hmem
    exact ⟨c, hc, d, hd, hce, hdf, a, ha, by rw [hw, hce]⟩

/-- Independence of two specifications: disjoint writes, and neither
writes into the other's certified support. -/
def IndependentPair (c d : CommitSpec Register Value EventId) : Prop :=
  (∀ a ∈ c.writeSet, a ∉ d.writeSet) ∧
    (∀ a ∈ c.writeSet, a ∉ d.causalSupp) ∧
    (∀ a ∈ d.writeSet, a ∉ c.causalSupp)

theorem IndependentPair.symm {c d : CommitSpec Register Value EventId}
    (h : IndependentPair c d) : IndependentPair d c :=
  ⟨fun a ha hb => h.1 a hb ha, h.2.2, h.2.1⟩

/-- Swapping an independent adjacent pair preserves the final state. -/
theorem swap_execState {c d : CommitSpec Register Value EventId}
    (h : IndependentPair c d)
    (q : VersionedState Register Value EventId)
    (pre post : List (CommitSpec Register Value EventId)) :
    execState q (pre ++ c :: d :: post) =
      execState q (pre ++ d :: c :: post) := by
  rw [execState_append, execState_append]
  show execState (d.apply (c.apply (execState q pre))) post =
    execState (c.apply (d.apply (execState q pre))) post
  rw [CommitSpec.apply_comm h.1]

theorem specCites_congr {s : CommitSpec Register Value EventId}
    {q q' : VersionedState Register Value EventId}
    (h : ∀ a ∈ s.causalSupp, q.writer a = q'.writer a) (e f : EventId) :
    SpecCites s q e f ↔ SpecCites s q' e f := by
  constructor
  · rintro ⟨hf, a, ha, hw⟩
    exact ⟨hf, a, ha, (h a ha).symm.trans hw⟩
  · rintro ⟨hf, a, ha, hw⟩
    exact ⟨hf, a, ha, (h a ha).trans hw⟩

/-- Swapping an independent adjacent pair preserves the executed raw
writer-citation relation on event identifiers.  Authentication is lifted
below under freshness and duplicate-free identifiers. -/
theorem swap_execParents {c d : CommitSpec Register Value EventId}
    (h : IndependentPair c d)
    (q : VersionedState Register Value EventId)
    (pre post : List (CommitSpec Register Value EventId)) (e f : EventId) :
    execParents q (pre ++ c :: d :: post) e f ↔
      execParents q (pre ++ d :: c :: post) e f := by
  rw [execParents_iff, execParents_iff]
  have hmem : e ∈ (pre ++ c :: d :: post).map CommitSpec.eventId ↔
      e ∈ (pre ++ d :: c :: post).map CommitSpec.eventId := by
    simp only [List.map_append, List.map_cons, List.mem_append,
      List.mem_cons]
    tauto
  have hqp := execState q pre
  have hcqp : ∀ a ∈ c.causalSupp,
      (execState q pre).writer a =
        (d.apply (execState q pre)).writer a := by
    intro a ha
    have : a ∉ d.writeSet := fun hw => h.2.2 a hw ha
    rw [CommitSpec.apply_writer_notMem this]
  have hdqp : ∀ a ∈ d.causalSupp,
      (c.apply (execState q pre)).writer a =
        (execState q pre).writer a := by
    intro a ha
    have : a ∉ c.writeSet := fun hw => h.2.1 a hw ha
    rw [CommitSpec.apply_writer_notMem this]
  have hstate : d.apply (c.apply (execState q pre)) =
      c.apply (d.apply (execState q pre)) :=
    CommitSpec.apply_comm h.1 (execState q pre)
  have hcites :
      execChildCites q (pre ++ c :: d :: post) e f ↔
        execChildCites q (pre ++ d :: c :: post) e f := by
    rw [execChildCites_append, execChildCites_append,
      execChildCites_cons, execChildCites_cons,
      execChildCites_cons, execChildCites_cons]
    show _ ∨ SpecCites c (execState q pre) e f ∨
        SpecCites d (c.apply (execState q pre)) e f ∨
        execChildCites (execState (c.apply (execState q pre)) [d]) post e f
      ↔ _ ∨ SpecCites d (execState q pre) e f ∨
        SpecCites c (d.apply (execState q pre)) e f ∨
        execChildCites (execState (d.apply (execState q pre)) [c]) post e f
    have h1 : SpecCites c (execState q pre) e f ↔
        SpecCites c (d.apply (execState q pre)) e f :=
      specCites_congr hcqp e f
    have h2 : SpecCites d (c.apply (execState q pre)) e f ↔
        SpecCites d (execState q pre) e f :=
      specCites_congr (fun a ha => (hdqp a ha)) e f
    have h3 : execState (c.apply (execState q pre)) [d] =
        execState (d.apply (execState q pre)) [c] := by
      show d.apply (c.apply (execState q pre)) =
        c.apply (d.apply (execState q pre))
      exact hstate
    rw [h3]
    tauto
  rw [hmem, hcites]

/-- Swapping an independent adjacent pair preserves authenticated
read-after-write parenthood, provided both serializations satisfy the
freshness and duplicate-free producer contract. -/
theorem swap_execAuthenticatedParents [DecidableEq EventId]
    {c d : CommitSpec Register Value EventId}
    (h : IndependentPair c d)
    (q : VersionedState Register Value EventId)
    (pre post : List (CommitSpec Register Value EventId))
    (hfresh₁ : FreshStart q (pre ++ c :: d :: post))
    (hnodup₁ : ((pre ++ c :: d :: post).map CommitSpec.eventId).Nodup)
    (hfresh₂ : FreshStart q (pre ++ d :: c :: post))
    (hnodup₂ : ((pre ++ d :: c :: post).map CommitSpec.eventId).Nodup)
    (e f : EventId) :
    execAuthenticatedParents q (pre ++ c :: d :: post) e f ↔
      execAuthenticatedParents q (pre ++ d :: c :: post) e f := by
  rw [← execParents_iff_authenticated hfresh₁ hnodup₁,
    ← execParents_iff_authenticated hfresh₂ hnodup₂]
  exact swap_execParents h q pre post e f

/-- Pointwise equivalent edge relations have equivalent transitive
closures. -/
theorem transGen_congr {α : Type*} {R S : α → α → Prop}
    (h : ∀ a b, R a b ↔ S a b) (a b : α) :
    Relation.TransGen R a b ↔ Relation.TransGen S a b := by
  constructor
  · intro hab
    induction hab with
    | single hedge => exact Relation.TransGen.single ((h _ _).mp hedge)
    | tail _ hedge ih =>
        exact Relation.TransGen.tail ih ((h _ _).mp hedge)
  · intro hab
    induction hab with
    | single hedge => exact Relation.TransGen.single ((h _ _).mpr hedge)
    | tail _ hedge ih =>
        exact Relation.TransGen.tail ih ((h _ _).mpr hedge)

/-- The full generated authenticated closure is invariant under a certified
independent adjacent swap.  This remains a theorem about the equivalence
generated by the stated swap contract, not arbitrary schedule or
implementation invariance. -/
theorem swap_authenticatedGeneratedBefore [DecidableEq EventId]
    {c d : CommitSpec Register Value EventId}
    (h : IndependentPair c d)
    (q : VersionedState Register Value EventId)
    (pre post : List (CommitSpec Register Value EventId))
    (hfresh₁ : FreshStart q (pre ++ c :: d :: post))
    (hnodup₁ : ((pre ++ c :: d :: post).map CommitSpec.eventId).Nodup)
    (hfresh₂ : FreshStart q (pre ++ d :: c :: post))
    (hnodup₂ : ((pre ++ d :: c :: post).map CommitSpec.eventId).Nodup)
    (e f : EventId) :
    Relation.TransGen
        (execAuthenticatedParents q (pre ++ c :: d :: post)) e f ↔
      Relation.TransGen
        (execAuthenticatedParents q (pre ++ d :: c :: post)) e f :=
  transGen_congr
    (swap_execAuthenticatedParents h q pre post hfresh₁ hnodup₁
      hfresh₂ hnodup₂) e f

/-- One independent adjacent swap between two histories. -/
def IndependentSwap
    (l l' : List (CommitSpec Register Value EventId)) : Prop :=
  ∃ pre c d post, IndependentPair c d ∧
    l = pre ++ c :: d :: post ∧ l' = pre ++ d :: c :: post

/-- Histories related by any chain of independent adjacent swaps execute
to the same final state and the same raw writer-citation relation.  The
authenticated adjacent-swap and closure theorems above additionally require
freshness and duplicate-free identifiers for each compared execution. -/
theorem eqvGen_independentSwap_invariant
    {l l' : List (CommitSpec Register Value EventId)}
    (h : Relation.EqvGen IndependentSwap l l')
    (q : VersionedState Register Value EventId) :
    execState q l = execState q l' ∧
      ∀ e f : EventId, execParents q l e f ↔ execParents q l' e f := by
  induction h with
  | rel x y hxy =>
      obtain ⟨pre, c, d, post, hpair, hx, hy⟩ := hxy
      subst hx hy
      exact ⟨swap_execState hpair q pre post,
        fun e f => swap_execParents hpair q pre post e f⟩
  | refl x => exact ⟨rfl, fun _ _ => Iff.rfl⟩
  | symm x y _ ih =>
      exact ⟨ih.1.symm, fun e f => (ih.2 e f).symm⟩
  | trans x y z _ _ ih₁ ih₂ =>
      exact ⟨ih₁.1.trans ih₂.1,
        fun e f => (ih₁.2 e f).trans (ih₂.2 e f)⟩

/-- Stutters are history-transparent: inserting an executor stutter
anywhere changes neither the executed state nor the executed parent
relation. -/
theorem stutter_transparent
    (q : VersionedState Register Value EventId)
    (pre post : List (RunStep Register Value EventId)) :
    execState q (committedSpecs (pre ++ RunStep.stutter :: post)) =
        execState q (committedSpecs (pre ++ post)) ∧
      ∀ e f : EventId,
        execParents q (committedSpecs (pre ++ RunStep.stutter :: post)) e f ↔
          execParents q (committedSpecs (pre ++ post)) e f := by
  rw [committedSpecs_insert_stutter]
  exact ⟨rfl, fun _ _ => Iff.rfl⟩

/-- Authenticated parenthood and its generated closure are transparent to
executor stutters because stutters contribute no committed specification. -/
theorem stutter_authenticated_transparent
    (q : VersionedState Register Value EventId)
    (pre post : List (RunStep Register Value EventId)) (e f : EventId) :
    execAuthenticatedParents q
        (committedSpecs (pre ++ RunStep.stutter :: post)) e f ↔
      execAuthenticatedParents q (committedSpecs (pre ++ post)) e f := by
  rw [committedSpecs_insert_stutter]

theorem stutter_authenticatedGeneratedBefore_transparent
    (q : VersionedState Register Value EventId)
    (pre post : List (RunStep Register Value EventId)) (e f : EventId) :
    Relation.TransGen
        (execAuthenticatedParents q
          (committedSpecs (pre ++ RunStep.stutter :: post))) e f ↔
      Relation.TransGen
        (execAuthenticatedParents q (committedSpecs (pre ++ post))) e f := by
  rw [committedSpecs_insert_stutter]

/-! ## Persistence while the overlap support is unwritten -/

/-- A continuation that avoids an overlap support leaves that overlap's
score unchanged. -/
theorem execState_score_eq {Overlap : Type v}
    (M : MismatchSystem Register Value EventId Overlap) {e : Overlap}
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (h : ∀ s ∈ specs, ∀ a ∈ M.support e, a ∉ s.writeSet) :
    M.score e (execState q specs) = M.score e q := by
  induction specs generalizing q with
  | nil => rfl
  | cons s rest ih =>
      have hstep : M.score e (s.apply q) = M.score e q :=
        M.score_local e (s.apply q) q
          (fun a ha =>
            CommitSpec.apply_value_notMem (h s List.mem_cons_self a ha))
      calc M.score e (execState (s.apply q) rest)
          = M.score e (s.apply q) :=
            ih (s.apply q) (fun t ht => h t (List.mem_cons_of_mem s ht))
        _ = M.score e q := hstep

/-- A standing mismatch whose entire support remains unwritten persists at
full strength through every stage.  This is strictly stronger than saying
that no later commit reads or "consumes" the mismatch: a blind overwrite is
excluded by the hypothesis. -/
theorem unwritten_support_mismatch_persists {Overlap : Type v}
    (M : MismatchSystem Register Value EventId Overlap) {e : Overlap}
    (q : VersionedState Register Value EventId)
    (specs : List (CommitSpec Register Value EventId))
    (hpos : 0 < M.score e q)
    (h : ∀ s ∈ specs, ∀ a ∈ M.support e, a ∉ s.writeSet)
    {xs ys : List (CommitSpec Register Value EventId)}
    (hsplit : specs = xs ++ ys) :
    0 < M.score e (execState q xs) := by
  have hxs : ∀ s ∈ xs, ∀ a ∈ M.support e, a ∉ s.writeSet := by
    intro s hs
    exact h s (hsplit ▸ List.mem_append_left ys hs)
  rw [execState_score_eq M q xs hxs]
  exact hpos

/-! ## The dependent boundary

Swapping a writer past a reader that certifies the written register
changes the executed edge set: the independence clauses are
load-bearing. -/

namespace DependentSwapControl

/-- The writer specification: event `0` writes the single register. -/
def writerSpec : CommitSpec Unit Bool (Fin 2) where
  eventId := 0
  readSet := ∅
  writeSet := {()}
  causalSupp := ∅
  supp_subset_read := by decide
  writeValue _ := true

/-- The reader specification: event `1` certifies the single register and
writes nothing. -/
def readerSpec : CommitSpec Unit Bool (Fin 2) where
  eventId := 1
  readSet := {()}
  writeSet := ∅
  causalSupp := {()}
  supp_subset_read := by decide
  writeValue _ := false

/-- The blank start state. -/
def start : VersionedState Unit Bool (Fin 2) :=
  ⟨fun _ => false, fun _ => none⟩

/-- Writer before reader executes the provenance edge; reader before
writer does not.  The pair fails independence exactly because the writer
writes into the reader's certified support. -/
theorem dependent_swap_changes_edges :
    execParents start [writerSpec, readerSpec] 0 1 ∧
      ¬ execParents start [readerSpec, writerSpec] 0 1 ∧
      ¬ IndependentPair writerSpec readerSpec := by
  refine ⟨?_, ?_, ?_⟩
  · refine (execParents_iff start _ 0 1).mpr ⟨by simp [writerSpec], ?_⟩
    rw [execChildCites_cons]
    refine Or.inr ?_
    rw [execChildCites_cons]
    refine Or.inl ⟨rfl, (), by simp [readerSpec], ?_⟩
    exact CommitSpec.apply_writer_mem (by simp [writerSpec])
  · intro h
    obtain ⟨_, hcites⟩ := (execParents_iff start _ 0 1).mp h
    rw [execChildCites_cons] at hcites
    rcases hcites with ⟨_, a, _, hw⟩ | hcites
    · exact absurd hw (by simp [start])
    · rw [execChildCites_cons] at hcites
      rcases hcites with ⟨hid, _⟩ | hcites
      · exact absurd hid (by decide)
      · exact execChildCites_nil _ _ _ hcites
  · rintro ⟨_, hsupp, _⟩
    exact hsupp () (by simp [writerSpec]) (by simp [readerSpec])

end DependentSwapControl

/-! ## The diamond under two schedules

The two response specifications of the Boolean diamond are independent,
so the serialization order of the responses leaves the final state and
the full parent relation unchanged: the committed instance of history
invariance. -/

namespace DiamondScheduleWitness

/-- The injection: event `0` writes the seam register. -/
def injectionSpec : CommitSpec (Fin 4) Bool (Fin 4) where
  eventId := 0
  readSet := ∅
  writeSet := {0}
  causalSupp := ∅
  supp_subset_read := by decide
  writeValue _ := true

/-- The first response: certifies the seam, writes its own output. -/
def leftSpec : CommitSpec (Fin 4) Bool (Fin 4) where
  eventId := 1
  readSet := {0}
  writeSet := {1}
  causalSupp := {0}
  supp_subset_read := by decide
  writeValue _ := true

/-- The second response: certifies the seam, writes a disjoint output. -/
def rightSpec : CommitSpec (Fin 4) Bool (Fin 4) where
  eventId := 2
  readSet := {0}
  writeSet := {2}
  causalSupp := {0}
  supp_subset_read := by decide
  writeValue _ := true

/-- The answer: certifies both outputs. -/
def answerSpec : CommitSpec (Fin 4) Bool (Fin 4) where
  eventId := 3
  readSet := {1, 2}
  writeSet := {3}
  causalSupp := {1, 2}
  supp_subset_read := by decide
  writeValue _ := true

/-- The blank start state. -/
def start : VersionedState (Fin 4) Bool (Fin 4) :=
  ⟨fun _ => false, fun _ => none⟩

/-- The two responses are independent. -/
theorem responses_independent : IndependentPair leftSpec rightSpec := by
  refine ⟨?_, ?_, ?_⟩ <;> decide

/-- The two serializations of the diamond execute to the same final state
and the same direct-parent relation. -/
theorem diamond_schedule_invariant :
    execState start [injectionSpec, leftSpec, rightSpec, answerSpec] =
        execState start [injectionSpec, rightSpec, leftSpec, answerSpec] ∧
      ∀ e f : Fin 4,
        execParents start
            [injectionSpec, leftSpec, rightSpec, answerSpec] e f ↔
          execParents start
            [injectionSpec, rightSpec, leftSpec, answerSpec] e f :=
  ⟨swap_execState responses_independent start [injectionSpec] [answerSpec],
    fun e f =>
      swap_execParents responses_independent start
        [injectionSpec] [answerSpec] e f⟩

/-- The forward diamond execution is fresh. -/
theorem forward_fresh :
    FreshStart start [injectionSpec, leftSpec, rightSpec, answerSpec] := by
  intro s hs a
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
  rcases hs with rfl | rfl | rfl | rfl <;>
    simp [start, injectionSpec, leftSpec, rightSpec, answerSpec]

/-- The swapped diamond execution is fresh. -/
theorem swapped_fresh :
    FreshStart start [injectionSpec, rightSpec, leftSpec, answerSpec] := by
  intro s hs a
  simp only [List.mem_cons, List.not_mem_nil, or_false] at hs
  rcases hs with rfl | rfl | rfl | rfl <;>
    simp [start, injectionSpec, leftSpec, rightSpec, answerSpec]

theorem forward_ids_nodup :
    ([injectionSpec, leftSpec, rightSpec, answerSpec].map
      CommitSpec.eventId).Nodup := by decide

theorem swapped_ids_nodup :
    ([injectionSpec, rightSpec, leftSpec, answerSpec].map
      CommitSpec.eventId).Nodup := by decide

theorem forward_carrier_complete :
    ExecutedCarrierComplete
      [injectionSpec, leftSpec, rightSpec, answerSpec] := by
  intro e
  fin_cases e <;>
    simp [injectionSpec, leftSpec, rightSpec, answerSpec]

/-- The authenticated edge relation, not merely raw citations, is invariant
under the two independent response serializations. -/
theorem diamond_authenticated_schedule_invariant (e f : Fin 4) :
    execAuthenticatedParents start
        [injectionSpec, leftSpec, rightSpec, answerSpec] e f ↔
      execAuthenticatedParents start
        [injectionSpec, rightSpec, leftSpec, answerSpec] e f :=
  swap_execAuthenticatedParents responses_independent start
    [injectionSpec] [answerSpec] forward_fresh forward_ids_nodup
    swapped_fresh swapped_ids_nodup e f

/-- The generated authenticated closure is invariant under the same
certified swap. -/
theorem diamond_authenticatedGeneratedBefore_invariant (e f : Fin 4) :
    Relation.TransGen
        (execAuthenticatedParents start
          [injectionSpec, leftSpec, rightSpec, answerSpec]) e f ↔
      Relation.TransGen
        (execAuthenticatedParents start
          [injectionSpec, rightSpec, leftSpec, answerSpec]) e f :=
  swap_authenticatedGeneratedBefore responses_independent start
    [injectionSpec] [answerSpec] forward_fresh forward_ids_nodup
    swapped_fresh swapped_ids_nodup e f

/-- The concrete forward diamond log built through the executed-history
constructor; its rank and edges are derived from the threaded run. -/
noncomputable def forwardExecutedLog :
    SemanticEventLog (Fin 4) Bool (Fin 4) :=
  semanticEventLogOfExecution start
    [injectionSpec, leftSpec, rightSpec, answerSpec]
    forward_fresh forward_ids_nodup forward_carrier_complete

/-- The derived execution log contains the authenticated injection-to-left
edge. -/
theorem forwardExecutedLog_injection_left :
    forwardExecutedLog.ParentEdge 0 1 := by
  unfold forwardExecutedLog
  rw [semanticEventLogOfExecution_parentEdge_iff]
  refine ⟨injectionSpec.commitAt start, by simp [execLog],
    leftSpec.commitAt (injectionSpec.apply start), by simp [execLog],
    rfl, rfl, ?_⟩
  exact ⟨0, by simp [leftSpec, CommitSpec.commitAt],
    by simp [injectionSpec, CommitSpec.commitAt],
    CommitSpec.apply_writer_mem (by simp [injectionSpec]),
    by simp [CommitSpec.commitAt, CommitSpec.apply_value_mem,
      injectionSpec, leftSpec, start]⟩

/-- The invariant relation is nonempty: the injection parents the first
response in both serializations. -/
theorem injection_parents_left :
    execParents start [injectionSpec, leftSpec, rightSpec, answerSpec]
      0 1 := by
  refine (execParents_iff start _ 0 1).mpr ⟨by simp [injectionSpec], ?_⟩
  rw [execChildCites_cons]
  refine Or.inr ?_
  rw [execChildCites_cons]
  refine Or.inl ⟨rfl, 0, by simp [leftSpec], ?_⟩
  exact CommitSpec.apply_writer_mem (by simp [injectionSpec])

end DiamondScheduleWitness

#print axioms execParents_rank_lt
#print axioms semanticEventLogOfExecution
#print axioms semanticEventLogOfExecution_parentEdge_iff
#print axioms semanticEventLogOfExecution_generatedBefore_iff
#print axioms semanticEventLogOfExecutionWithSourceHeight
#print axioms semanticEventLogOfExecutionWithSourceHeight_parentEdge_iff
#print axioms semanticEventLogOfExecutionWithSourceHeight_generatedBefore_iff
#print axioms swap_execState
#print axioms swap_execParents
#print axioms swap_execAuthenticatedParents
#print axioms swap_authenticatedGeneratedBefore
#print axioms eqvGen_independentSwap_invariant
#print axioms stutter_transparent
#print axioms stutter_authenticatedGeneratedBefore_transparent
#print axioms execState_score_eq
#print axioms unwritten_support_mismatch_persists
#print axioms DependentSwapControl.dependent_swap_changes_edges
#print axioms DiamondScheduleWitness.diamond_schedule_invariant
#print axioms DiamondScheduleWitness.diamond_authenticated_schedule_invariant
#print axioms DiamondScheduleWitness.diamond_authenticatedGeneratedBefore_invariant
#print axioms DiamondScheduleWitness.forwardExecutedLog
#print axioms DiamondScheduleWitness.forwardExecutedLog_injection_left
#print axioms DiamondScheduleWitness.injection_parents_left

end OPH.Provenance
