import Mathlib.Logic.Relation
import Mathlib.Data.Finset.Basic

/-!
# Conflict-class aggregation condition for seam proposals

A seam-supported mismatch score can only move when some proposal writes
into the seam support.  Under semantic-dependency-complete read sets, any
proposal whose write meets the support reads the complete support.  Two
such proposals therefore overlap read-against-write in both directions, so
they conflict under any declared conflict relation containing mutual
read/write overlap, and every supplied conflict-respecting aggregation maps
them to equal aggregate labels.

A two-proposal countermodel shows the dependency-completeness clause is
load-bearing: with empty read sets, two proposals writing into the same
  support share no mutual overlap, and the generated conflict equivalence
identifies nothing.

This module neither constructs an aggregation function nor proves that one
aggregate commit exists or is its support's unique writer.  Those are
producer/transaction-layer obligations.  It proves only the conditional
conflict-class equality needed by such a producer.
-/

namespace OPH.Provenance

universe u p

variable {Register : Type u} {Proposal : Type p}
variable [DecidableEq Register]

/-- Declared read and write register sets of a proposal family. -/
structure ProposalFamily (Register : Type u) (Proposal : Type p)
    [DecidableEq Register] where
  /-- The declared read set of each proposal. -/
  readSet : Proposal → Finset Register
  /-- The declared write set of each proposal. -/
  writeSet : Proposal → Finset Register

namespace ProposalFamily

variable (F : ProposalFamily Register Proposal)

/-- A proposal touches a support when its write set meets it. -/
def Touches (support : Finset Register) (p : Proposal) : Prop :=
  (F.writeSet p ∩ support).Nonempty

/-- Semantic-dependency-complete read sets over one support: every
proposal able to write into the support reads the complete support. -/
def DependencyComplete (support : Finset Register) : Prop :=
  ∀ p : Proposal, F.Touches support p → support ⊆ F.readSet p

/-- Mutual read/write overlap between two proposals. -/
def MutualOverlap (p q : Proposal) : Prop :=
  (F.writeSet p ∩ F.readSet q).Nonempty ∧
    (F.writeSet q ∩ F.readSet p).Nonempty

/-- Two proposals touching one dependency-complete support overlap
read-against-write in both directions. -/
theorem mutualOverlap_of_touches {support : Finset Register}
    (hcomplete : F.DependencyComplete support) {p q : Proposal}
    (hp : F.Touches support p) (hq : F.Touches support q) :
    F.MutualOverlap p q := by
  obtain ⟨a, ha⟩ := hp
  obtain ⟨b, hb⟩ := hq
  have hamem := Finset.mem_inter.mp ha
  have hbmem := Finset.mem_inter.mp hb
  constructor
  · exact ⟨a, Finset.mem_inter.mpr
      ⟨hamem.1, hcomplete q ⟨b, hb⟩ hamem.2⟩⟩
  · exact ⟨b, Finset.mem_inter.mpr
      ⟨hbmem.1, hcomplete p ⟨a, ha⟩ hbmem.2⟩⟩

/-- Any two proposals touching one dependency-complete support are
identified by the conflict equivalence generated by any conflict relation
containing mutual overlap. -/
theorem conflictEquiv_of_touches
    (Conflict : Proposal → Proposal → Prop)
    (hmutual : ∀ p q : Proposal, F.MutualOverlap p q → Conflict p q)
    {support : Finset Register}
    (hcomplete : F.DependencyComplete support) {p q : Proposal}
    (hp : F.Touches support p) (hq : F.Touches support q) :
    Relation.EqvGen Conflict p q :=
  Relation.EqvGen.rel p q
    (hmutual p q (F.mutualOverlap_of_touches hcomplete hp hq))

/-- Every supplied aggregation constant on conflict edges assigns equal
aggregate labels to proposals touching one dependency-complete support.
Existence and uniqueness of an aggregate commit do not follow. -/
theorem aggregate_equal_of_touches {Aggregate : Type p}
    (Conflict : Proposal → Proposal → Prop)
    (hmutual : ∀ p q : Proposal, F.MutualOverlap p q → Conflict p q)
    (agg : Proposal → Aggregate)
    (hagg : ∀ p q : Proposal, Conflict p q → agg p = agg q)
    {support : Finset Register}
    (hcomplete : F.DependencyComplete support) {p q : Proposal}
    (hp : F.Touches support p) (hq : F.Touches support q) :
    agg p = agg q :=
  hagg p q (hmutual p q (F.mutualOverlap_of_touches hcomplete hp hq))

end ProposalFamily

/-! ## Dependency completeness is load-bearing

Two proposals with empty read sets each write into the same two-register
support. No mutual overlap holds anywhere, the generated conflict
equivalence is equality, and the two proposals remain inequivalent under it. -/

namespace SeparateWriterControl

/-- Two blind proposals: proposal `b` writes register `b` and reads
nothing. -/
def family : ProposalFamily Bool Bool where
  readSet _ := ∅
  writeSet b := {b}

/-- Both proposals touch the full two-register support. -/
theorem touches_both :
    family.Touches {false, true} false ∧
      family.Touches {false, true} true := by
  constructor
  · exact ⟨false, by simp [family]⟩
  · exact ⟨true, by simp [family]⟩

/-- No mutual overlap holds between any two proposals. -/
theorem no_mutualOverlap (p q : Bool) : ¬ family.MutualOverlap p q := by
  rintro ⟨⟨a, ha⟩, _⟩
  have := (Finset.mem_inter.mp ha).2
  simp [family] at this

/-- The conflict equivalence generated by mutual overlap identifies
nothing: it is equality. -/
theorem conflictEquiv_eq {p q : Bool}
    (h : Relation.EqvGen family.MutualOverlap p q) : p = q := by
  induction h with
  | rel x y hxy => exact absurd hxy (no_mutualOverlap x y)
  | refl x => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- The two support-touching proposals are not identified by the generated
conflict equivalence.  This does not itself construct two committed
writers. -/
theorem not_conflictEquivalent :
    ¬ Relation.EqvGen family.MutualOverlap false true := by
  intro h
  exact Bool.false_ne_true (conflictEquiv_eq h)

end SeparateWriterControl

#print axioms ProposalFamily.mutualOverlap_of_touches
#print axioms ProposalFamily.conflictEquiv_of_touches
#print axioms ProposalFamily.aggregate_equal_of_touches
#print axioms SeparateWriterControl.not_conflictEquivalent

end OPH.Provenance
