import Mathlib.Logic.Relation
import Mathlib.Data.Finset.Basic

/-!
# Single-aggregate provenance of seam deltas

A seam-supported mismatch score can only move when some proposal writes
into the seam support.  Under semantic-dependency-complete read sets, any
proposal whose write meets the support reads the complete support.  Two
such proposals therefore overlap read-against-write in both directions, so
they conflict under any declared conflict relation containing mutual
read/write overlap, and every conflict-respecting aggregation assigns them
one aggregate.  A committed seam delta at one source batch consequently has
exactly one canonical aggregate semantic event as its writer.

A two-proposal countermodel shows the dependency-completeness clause is
load-bearing: with empty read sets, two proposals writing into the same
support share no mutual overlap, and the generated conflict equivalence
identifies nothing, so they can commit as separate writers.

The aggregation discipline itself, replacing each connected conflict
component by one canonical aggregate transaction, is the committed
transactional layer of the consensus protocol; this module proves the
conflict step that routes every seam delta into one component.
-/

namespace OPH.Provenance

universe u p

variable {Register : Type u} {Proposal : Type p}
variable [DecidableEq Register]

/-- Declared read and write register sets of a proposal family. -/
structure ProposalFamily (Register : Type u) (Proposal : Type p)
    [DecidableEq Register] where
  /-- The declared read set of each proposal. -/
  readSet : Proposal → Finset Register
  /-- The declared write set of each proposal. -/
  writeSet : Proposal → Finset Register

namespace ProposalFamily

variable (F : ProposalFamily Register Proposal)

/-- A proposal touches a support when its write set meets it. -/
def Touches (support : Finset Register) (p : Proposal) : Prop :=
  (F.writeSet p ∩ support).Nonempty

/-- Semantic-dependency-complete read sets over one support: every
proposal able to write into the support reads the complete support. -/
def DependencyComplete (support : Finset Register) : Prop :=
  ∀ p : Proposal, F.Touches support p → support ⊆ F.readSet p

/-- Mutual read/write overlap between two proposals. -/
def MutualOverlap (p q : Proposal) : Prop :=
  (F.writeSet p ∩ F.readSet q).Nonempty ∧
    (F.writeSet q ∩ F.readSet p).Nonempty

/-- Two proposals touching one dependency-complete support overlap
read-against-write in both directions. -/
theorem mutualOverlap_of_touches {support : Finset Register}
    (hcomplete : F.DependencyComplete support) {p q : Proposal}
    (hp : F.Touches support p) (hq : F.Touches support q) :
    F.MutualOverlap p q := by
  obtain ⟨a, ha⟩ := hp
  obtain ⟨b, hb⟩ := hq
  have hamem := Finset.mem_inter.mp ha
  have hbmem := Finset.mem_inter.mp hb
  constructor
  · exact ⟨a, Finset.mem_inter.mpr
      ⟨hamem.1, hcomplete q ⟨b, hb⟩ hamem.2⟩⟩
  · exact ⟨b, Finset.mem_inter.mpr
      ⟨hbmem.1, hcomplete p ⟨a, ha⟩ hbmem.2⟩⟩

/-- Any two proposals touching one dependency-complete support are
identified by the conflict equivalence generated by any conflict relation
containing mutual overlap. -/
theorem conflictEquiv_of_touches
    (Conflict : Proposal → Proposal → Prop)
    (hmutual : ∀ p q : Proposal, F.MutualOverlap p q → Conflict p q)
    {support : Finset Register}
    (hcomplete : F.DependencyComplete support) {p q : Proposal}
    (hp : F.Touches support p) (hq : F.Touches support q) :
    Relation.EqvGen Conflict p q :=
  Relation.EqvGen.rel p q
    (hmutual p q (F.mutualOverlap_of_touches hcomplete hp hq))

/-- Single-aggregate writer: every aggregation constant on the generated
conflict classes assigns one aggregate to all proposals touching one
dependency-complete support. -/
theorem aggregate_unique_of_touches {Aggregate : Type p}
    (Conflict : Proposal → Proposal → Prop)
    (hmutual : ∀ p q : Proposal, F.MutualOverlap p q → Conflict p q)
    (agg : Proposal → Aggregate)
    (hagg : ∀ p q : Proposal, Conflict p q → agg p = agg q)
    {support : Finset Register}
    (hcomplete : F.DependencyComplete support) {p q : Proposal}
    (hp : F.Touches support p) (hq : F.Touches support q) :
    agg p = agg q :=
  hagg p q (hmutual p q (F.mutualOverlap_of_touches hcomplete hp hq))

end ProposalFamily

/-! ## Dependency completeness is load-bearing

Two proposals with empty read sets each write into the same two-register
support.  No mutual overlap holds anywhere, the generated conflict
equivalence is equality, and the two proposals stay separate writers. -/

namespace SeparateWriterControl

/-- Two blind proposals: proposal `b` writes register `b` and reads
nothing. -/
def family : ProposalFamily Bool Bool where
  readSet _ := ∅
  writeSet b := {b}

/-- Both proposals touch the full two-register support. -/
theorem touches_both :
    family.Touches {false, true} false ∧
      family.Touches {false, true} true := by
  constructor
  · exact ⟨false, by simp [family]⟩
  · exact ⟨true, by simp [family]⟩

/-- No mutual overlap holds between any two proposals. -/
theorem no_mutualOverlap (p q : Bool) : ¬ family.MutualOverlap p q := by
  rintro ⟨⟨a, ha⟩, _⟩
  have := (Finset.mem_inter.mp ha).2
  simp [family] at this

/-- The conflict equivalence generated by mutual overlap identifies
nothing: it is equality. -/
theorem conflictEquiv_eq {p q : Bool}
    (h : Relation.EqvGen family.MutualOverlap p q) : p = q := by
  induction h with
  | rel x y hxy => exact absurd hxy (no_mutualOverlap x y)
  | refl x => rfl
  | symm x y _ ih => exact ih.symm
  | trans x y z _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- The two support-touching proposals are not identified: without
dependency completeness the seam delta admits two separate writers. -/
theorem separate_writers :
    ¬ Relation.EqvGen family.MutualOverlap false true := by
  intro h
  exact Bool.false_ne_true (conflictEquiv_eq h)

end SeparateWriterControl

#print axioms ProposalFamily.mutualOverlap_of_touches
#print axioms ProposalFamily.conflictEquiv_of_touches
#print axioms ProposalFamily.aggregate_unique_of_touches
#print axioms SeparateWriterControl.separate_writers

end OPH.Provenance
