import EventAlgebra.Lueders

/-!
# Bundled arbitrary-partition pinching onto the block-diagonal commutant

A finite family of pairwise-orthogonal events summing to the identity (a
`ProjectivePartition`) generates the commutative algebra `D = span{Pᵢ}`.
This module constructs the trace-preserving pinching map

  `partitionPinching part X = ∑ i, Pᵢ X Pᵢ`,

whose range is the commutant `N = {X : X Pᵢ = Pᵢ X for every i}`. That
commutant is the block-diagonal algebra `⊕ᵢ M_{rank Pᵢ}(ℂ)`, generally
noncommutative; it is not the commutative algebra generated by the
partition. The module bundles both the commutant as a star-subalgebra and the pinching
as a complex-linear map. It verifies the finite-matrix
projection properties directly:

* **existence and range**: the pinching lands in the bundled commutant,
  fixes it pointwise, and has exactly that linear range;
* **map structure**: it is linear, unital, positive, trace preserving,
  idempotent, and satisfies the commutant bimodule law;
* **selfadjointness and contractivity**: it is selfadjoint for the trace
  inner product `⟨X, Y⟩ = Tr(Xᴴ Y)`, satisfies the Pythagorean identity,
  and is a squared-`L²` contraction;
* **uniqueness**: it is the unique commutant-valued linear map satisfying
  the stated trace-duality property;
* **compatibility with conditioning**: compression and both the raw and
  typed Lüders updates commute with pinching for commutant events.

No rank-one classical-representation theorem or completely-positive channel
bundle is claimed in this module.

## Tagging convention

As in `EventAlgebra.Basic`: each lemma is tagged **algebra-only** or
**trace-dependent** according to whether its content passes through the
trace pairing.
-/

namespace EventAlgebra

open Matrix
open scoped ComplexOrder

variable {n k : ℕ}

/-- A **projective partition**: a finite family of pairwise-orthogonal
events summing to the identity. The family generates the commutative
algebra `D = span{Pᵢ}` (see `ProjectivePartition.proj_commute`). -/
structure ProjectivePartition (n k : ℕ) where
  /-- The orthogonal projections constituting the partition. -/
  proj : Fin k → Matrix (Fin n) (Fin n) ℂ
  /-- Every member of the partition is an event. -/
  isEvent : ∀ i, IsEvent (proj i)
  /-- Distinct members are orthogonal. -/
  orthogonal : ∀ i j, i ≠ j → proj i * proj j = 0
  /-- The partition is complete: the members sum to the sure event. -/
  complete : ∑ i, proj i = 1

namespace ProjectivePartition

variable (part : ProjectivePartition n k)

/-- **Algebra-only.** Product formula for partition members:
`Pᵢ Pⱼ = δᵢⱼ Pᵢ`. -/
theorem proj_mul_proj (i j : Fin k) :
    part.proj i * part.proj j = if i = j then part.proj i else 0 := by
  by_cases h : i = j
  · subst h
    simp [(part.isEvent i).2]
  · simp [h, part.orthogonal i j h]

/-- **Algebra-only.** Partition members commute pairwise: the partition
generates the commutative subalgebra `D = span{Pᵢ}`. -/
theorem proj_commute (i j : Fin k) :
    part.proj i * part.proj j = part.proj j * part.proj i := by
  by_cases h : i = j
  · rw [h]
  · rw [part.orthogonal i j h, part.orthogonal j i (Ne.symm h)]

/-- The bundled star-subalgebra of matrices commuting with every projector
of the partition. -/
noncomputable def commutant :
    StarSubalgebra ℂ (Matrix (Fin n) (Fin n) ℂ) :=
  StarSubalgebra.centralizer ℂ (Set.range part.proj)

/-- Membership in the bundled commutant is exactly the pointwise commutation
predicate used by the elementary matrix lemmas. -/
@[simp]
theorem mem_commutant_iff {X : Matrix (Fin n) (Fin n) ℂ} :
    X ∈ part.commutant ↔ ∀ i, X * part.proj i = part.proj i * X := by
  rw [commutant, StarSubalgebra.mem_centralizer_iff]
  constructor
  · intro h i
    exact (h (part.proj i) ⟨i, rfl⟩).1.symm
  · intro h g hg
    obtain ⟨i, rfl⟩ := hg
    constructor
    · exact (h i).symm
    · change (part.proj i)ᴴ * X = X * (part.proj i)ᴴ
      rw [(part.isEvent i).1.eq]
      exact (h i).symm

end ProjectivePartition

/-- The **pinching onto the commutant** determined by a partition: the map
`X ↦ ∑ i, Pᵢ X Pᵢ`. -/
noncomputable def partitionPinching (part : ProjectivePartition n k)
    (X : Matrix (Fin n) (Fin n) ℂ) : Matrix (Fin n) (Fin n) ℂ :=
  ∑ i, part.proj i * X * part.proj i

/-- The arbitrary-partition pinching bundled as a complex-linear map. -/
noncomputable def partitionPinchingLinearMap (part : ProjectivePartition n k) :
    Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin n) (Fin n) ℂ where
  toFun := partitionPinching part
  map_add' X Y := by
    simp only [partitionPinching, mul_add, add_mul, Finset.sum_add_distrib]
  map_smul' c X := by
    simp only [partitionPinching, mul_smul_comm, smul_mul_assoc, Finset.smul_sum,
      RingHom.id_apply]

@[simp]
theorem partitionPinchingLinearMap_apply (part : ProjectivePartition n k)
    (X : Matrix (Fin n) (Fin n) ℂ) :
    partitionPinchingLinearMap part X = partitionPinching part X :=
  rfl

variable (part : ProjectivePartition n k)

/-- **Algebra-only.** Absorption on the right: multiplying the pinching by
a partition member selects the corresponding block. -/
theorem partitionPinching_mul_proj (X : Matrix (Fin n) (Fin n) ℂ)
    (i : Fin k) :
    partitionPinching part X * part.proj i = part.proj i * X * part.proj i := by
  rw [partitionPinching, Finset.sum_mul]
  rw [Finset.sum_eq_single i
    (fun j _ hji => by
      rw [mul_assoc, part.orthogonal j i hji, mul_zero])
    (fun h => absurd (Finset.mem_univ i) h)]
  rw [mul_assoc, (part.isEvent i).2]

/-- **Algebra-only.** Absorption on the left. -/
theorem proj_mul_partitionPinching (X : Matrix (Fin n) (Fin n) ℂ)
    (i : Fin k) :
    part.proj i * partitionPinching part X = part.proj i * X * part.proj i := by
  rw [partitionPinching, Finset.mul_sum]
  rw [Finset.sum_eq_single i
    (fun j _ hji => by
      rw [← mul_assoc, ← mul_assoc, part.orthogonal i j (Ne.symm hji),
        zero_mul, zero_mul])
    (fun h => absurd (Finset.mem_univ i) h)]
  rw [← mul_assoc, ← mul_assoc, (part.isEvent i).2]

/-- **Algebra-only.** The pinching lands in the commutant of the partition:
its output commutes with every partition member. -/
theorem proj_commute_partitionPinching (X : Matrix (Fin n) (Fin n) ℂ)
    (i : Fin k) :
    part.proj i * partitionPinching part X = partitionPinching part X * part.proj i := by
  rw [proj_mul_partitionPinching, partitionPinching_mul_proj]

/-- **Algebra-only.** The bundled pinching lands in the bundled partition
commutant. -/
theorem partitionPinching_mem_commutant (X : Matrix (Fin n) (Fin n) ℂ) :
    partitionPinching part X ∈ part.commutant := by
  rw [ProjectivePartition.mem_commutant_iff]
  intro i
  exact (proj_commute_partitionPinching part X i).symm

/-- **Algebra-only.** The pinching fixes the commutant pointwise: any `X`
commuting with every partition member is left unchanged. -/
theorem partitionPinching_fixes {X : Matrix (Fin n) (Fin n) ℂ}
    (h : ∀ i, X * part.proj i = part.proj i * X) :
    partitionPinching part X = X := by
  calc partitionPinching part X = ∑ i, X * part.proj i :=
        Finset.sum_congr rfl fun i _ => by
          rw [← h i, mul_assoc, (part.isEvent i).2]
    _ = X * ∑ i, part.proj i := (Finset.mul_sum _ _ _).symm
    _ = X := by rw [part.complete, mul_one]

/-- **Algebra-only.** Exact fixed-point characterization of partition
pinching in terms of the bundled commutant. -/
theorem partitionPinching_eq_self_iff_mem_commutant
    (X : Matrix (Fin n) (Fin n) ℂ) :
    partitionPinching part X = X ↔ X ∈ part.commutant := by
  constructor
  · intro h
    rw [← h]
    exact partitionPinching_mem_commutant part X
  · intro h
    exact partitionPinching_fixes part
      ((ProjectivePartition.mem_commutant_iff part).mp h)

/-- **Algebra-only.** The pinching is idempotent: it is a projector onto
the commutant. -/
theorem partitionPinching_idem (X : Matrix (Fin n) (Fin n) ℂ) :
    partitionPinching part (partitionPinching part X) = partitionPinching part X :=
  partitionPinching_fixes part fun i =>
    (proj_commute_partitionPinching part X i).symm

/-- **Algebra-only.** The bundled pinching is unital. -/
theorem partitionPinching_unital : partitionPinching part 1 = 1 :=
  partitionPinching_fixes part fun _ => by simp

/-- **Trace-dependent.** Partition pinching preserves the trace of every
matrix, independently of positivity or normalization. -/
theorem trace_partitionPinching (X : Matrix (Fin n) (Fin n) ℂ) :
    (partitionPinching part X).trace = X.trace := by
  rw [partitionPinching, trace_sum]
  calc
    ∑ i, (part.proj i * X * part.proj i).trace =
        ∑ i, bornWeight X (part.proj i) :=
      Finset.sum_congr rfl fun i _ => trace_sandwich (part.isEvent i).2 X
    _ = bornWeight X (∑ i, part.proj i) := (bornWeight_sum X _ _).symm
    _ = X.trace := by rw [part.complete, bornWeight, mul_one]

/-- **Trace-dependent.** Partition pinching preserves positive
semidefiniteness. -/
theorem partitionPinching_posSemidef {X : Matrix (Fin n) (Fin n) ℂ}
    (hX : X.PosSemidef) : (partitionPinching part X).PosSemidef :=
  posSemidef_sum _ fun i _ => by
    have h := hX.mul_mul_conjTranspose_same (part.proj i)
    rwa [(part.isEvent i).1.eq] at h

/-- **Algebra-only.** The pinching commutes with conjugate transposition. -/
theorem conjTranspose_partitionPinching (X : Matrix (Fin n) (Fin n) ℂ) :
    (partitionPinching part X)ᴴ = partitionPinching part Xᴴ := by
  rw [partitionPinching, partitionPinching, conjTranspose_sum]
  exact Finset.sum_congr rfl fun i _ => by
    simp only [conjTranspose_mul, (part.isEvent i).1.eq, mul_assoc]

/-- **Trace-dependent.** The pinching maps states to states: the pinching
of a density matrix is again a density matrix. -/
theorem partitionPinching_isState {ρ : Matrix (Fin n) (Fin n) ℂ}
    (hρ : IsState ρ) : IsState (partitionPinching part ρ) := by
  exact ⟨partitionPinching_posSemidef part hρ.1,
    (trace_partitionPinching part ρ).trans hρ.2⟩

/-- **Algebra-only.** Bimodule law over the bundled commutant. This is the
multiplication law required of the finite-matrix conditional expectation. -/
theorem partitionPinching_bimodule
    {A B : Matrix (Fin n) (Fin n) ℂ}
    (hA : A ∈ part.commutant) (hB : B ∈ part.commutant)
    (X : Matrix (Fin n) (Fin n) ℂ) :
    partitionPinching part (A * X * B) =
      A * partitionPinching part X * B := by
  have hA' := (ProjectivePartition.mem_commutant_iff part).mp hA
  have hB' := (ProjectivePartition.mem_commutant_iff part).mp hB
  rw [partitionPinching, partitionPinching, Finset.mul_sum, Finset.sum_mul]
  exact Finset.sum_congr rfl fun i _ => by
    calc
      part.proj i * (A * X * B) * part.proj i =
          (part.proj i * A) * X * (B * part.proj i) := by
            simp only [mul_assoc]
      _ = (A * part.proj i) * X * (part.proj i * B) := by
            rw [(hA' i).symm, hB' i]
      _ = A * (part.proj i * X * part.proj i) * B := by
            simp only [mul_assoc]

/-- **Algebra-only.** The linear range of the bundled pinching is exactly
the underlying submodule of the partition commutant. -/
theorem range_partitionPinchingLinearMap :
    LinearMap.range (partitionPinchingLinearMap part) =
      part.commutant.toSubalgebra.toSubmodule := by
  ext X
  constructor
  · rintro ⟨Y, rfl⟩
    exact partitionPinching_mem_commutant part Y
  · intro hX
    refine ⟨X, ?_⟩
    exact partitionPinching_fixes part
      ((ProjectivePartition.mem_commutant_iff part).mp hX)

/-- **Trace-dependent.** Selfadjointness of the pinching for the
trace inner product `⟨X, Y⟩ = Tr(Xᴴ Y)`. -/
theorem trace_conjTranspose_partitionPinching_mul
    (X Y : Matrix (Fin n) (Fin n) ℂ) :
    ((partitionPinching part X)ᴴ * Y).trace =
      (Xᴴ * partitionPinching part Y).trace := by
  have hterm : ∀ i : Fin k,
      (part.proj i * Xᴴ * part.proj i * Y).trace =
        (Xᴴ * (part.proj i * Y * part.proj i)).trace := by
    intro i
    rw [trace_mul_comm (part.proj i * Xᴴ * part.proj i) Y,
      trace_mul_comm Xᴴ (part.proj i * Y * part.proj i),
      show Y * (part.proj i * Xᴴ * part.proj i) =
        (Y * part.proj i * Xᴴ) * part.proj i by simp only [mul_assoc],
      trace_mul_comm (Y * part.proj i * Xᴴ) (part.proj i)]
    simp only [mul_assoc]
  rw [conjTranspose_partitionPinching, partitionPinching, partitionPinching,
    Finset.sum_mul, Finset.mul_sum, trace_sum, trace_sum]
  exact Finset.sum_congr rfl fun i _ => hterm i

/-- **Trace-dependent.** The Pythagorean identity for the
pinching: the squared trace norm splits into the squared norm of the
conditional expectation plus the squared norm of the residual. This is the
quantum counterpart of the classical `L²` energy identity for conditional
expectations. -/
theorem trace_partitionPinching_pythagoras (X : Matrix (Fin n) (Fin n) ℂ) :
    (Xᴴ * X).trace =
      ((partitionPinching part X)ᴴ * partitionPinching part X).trace +
      ((X - partitionPinching part X)ᴴ * (X - partitionPinching part X)).trace := by
  have hTX : ((partitionPinching part X)ᴴ * X).trace =
      (Xᴴ * partitionPinching part X).trace :=
    trace_conjTranspose_partitionPinching_mul part X X
  have hTT : ((partitionPinching part X)ᴴ * partitionPinching part X).trace =
      (Xᴴ * partitionPinching part X).trace := by
    have := trace_conjTranspose_partitionPinching_mul part X
      (partitionPinching part X)
    rwa [partitionPinching_idem part X] at this
  simp only [conjTranspose_sub, sub_mul, mul_sub, trace_sub]
  rw [hTX, hTT]
  ring

/-- **Trace-dependent.** Squared-`L²` contractivity of the
pinching for the trace norm: `Tr((𝔼X)ᴴ (𝔼X)) ≤ Tr(Xᴴ X)` in the partial
order of `ℂ`. -/
theorem trace_partitionPinching_contraction (X : Matrix (Fin n) (Fin n) ℂ) :
    ((partitionPinching part X)ᴴ * partitionPinching part X).trace ≤
      (Xᴴ * X).trace := by
  rw [trace_partitionPinching_pythagoras part X]
  exact le_add_of_nonneg_right
    (posSemidef_conjTranspose_mul_self _).trace_nonneg

/-- **Trace-dependent.** Trace compatibility: against any element
`C` of the commutant of the partition, the pinching is invisible to the
trace pairing. This is the defining property of a conditional
expectation. -/
theorem trace_partitionPinching_mul_commutant (X C : Matrix (Fin n) (Fin n) ℂ)
    (hC : ∀ i, C * part.proj i = part.proj i * C) :
    (partitionPinching part X * C).trace = (X * C).trace := by
  have hterm : ∀ i : Fin k,
      ((part.proj i * X * part.proj i) * C).trace =
        (X * (C * part.proj i)).trace := by
    intro i
    rw [trace_mul_comm (part.proj i * X * part.proj i) C,
      show C * (part.proj i * X * part.proj i) =
        (C * part.proj i) * X * part.proj i by simp only [mul_assoc],
      trace_mul_comm ((C * part.proj i) * X) (part.proj i),
      show part.proj i * ((C * part.proj i) * X) =
        ((part.proj i * C) * part.proj i) * X by simp only [mul_assoc],
      ← hC i,
      show ((C * part.proj i) * part.proj i) * X =
        (C * (part.proj i * part.proj i)) * X by simp only [mul_assoc],
      (part.isEvent i).2, trace_mul_comm (C * part.proj i) X]
  have hsum : ∑ i, ((part.proj i * X * part.proj i) * C).trace =
      ∑ i, (X * (C * part.proj i)).trace :=
    Finset.sum_congr rfl fun i _ => hterm i
  rw [partitionPinching, Finset.sum_mul, trace_sum, hsum, ← trace_sum,
    ← Finset.mul_sum, ← Finset.mul_sum, part.complete, mul_one]

/-- **Trace-dependent.** Pointwise trace-duality characterization: any
commutant-valued matrix `Y` that is trace-compatible with
`X` against the whole commutant equals the pinching of `X`. The proof
tests against `C = (Y - 𝔼X)ᴴ` and uses faithfulness of the trace. -/
theorem partitionPinching_unique {X Y : Matrix (Fin n) (Fin n) ℂ}
    (hYcomm : ∀ i, Y * part.proj i = part.proj i * Y)
    (hYtr : ∀ C : Matrix (Fin n) (Fin n) ℂ,
      (∀ i, C * part.proj i = part.proj i * C) → (Y * C).trace = (X * C).trace) :
    Y = partitionPinching part X := by
  set D := Y - partitionPinching part X with hD
  have hDcomm : ∀ i, D * part.proj i = part.proj i * D := by
    intro i
    rw [hD, sub_mul, mul_sub, hYcomm i,
      ← proj_commute_partitionPinching part X i]
  have hDHcomm : ∀ i, Dᴴ * part.proj i = part.proj i * Dᴴ := by
    intro i
    have := congrArg conjTranspose (hDcomm i)
    rw [conjTranspose_mul, conjTranspose_mul, (part.isEvent i).1.eq] at this
    exact this.symm
  have htr0 : (D * Dᴴ).trace = 0 := by
    have h1 : (Y * Dᴴ).trace = (X * Dᴴ).trace := hYtr Dᴴ hDHcomm
    have h2 : (partitionPinching part X * Dᴴ).trace = (X * Dᴴ).trace :=
      trace_partitionPinching_mul_commutant part X Dᴴ hDHcomm
    rw [hD, sub_mul, trace_sub, h1, h2, sub_self]
  have hD0 : D = 0 := trace_mul_conjTranspose_self_eq_zero_iff.mp htr0
  rw [← sub_eq_zero]
  exact hD0

/-- **Trace-dependent.** Map-level uniqueness: a complex-linear map whose
values lie in the partition commutant and which has the same trace pairing
against every commutant element is the bundled partition pinching. -/
theorem partitionPinchingLinearMap_unique
    (F : Matrix (Fin n) (Fin n) ℂ →ₗ[ℂ] Matrix (Fin n) (Fin n) ℂ)
    (hRange : ∀ X, F X ∈ part.commutant)
    (hTrace : ∀ X C, C ∈ part.commutant →
      (F X * C).trace = (X * C).trace) :
    F = partitionPinchingLinearMap part := by
  apply LinearMap.ext
  intro X
  exact partitionPinching_unique part
    ((ProjectivePartition.mem_commutant_iff part).mp (hRange X))
    (fun C hC => hTrace X C
      ((ProjectivePartition.mem_commutant_iff part).mpr hC))

/-- **Trace-dependent.** For an event `P` in the commutant of the
partition, the Born weight is invariant under the pinching. -/
theorem bornWeight_partitionPinching (ρ P : Matrix (Fin n) (Fin n) ℂ)
    (hPc : ∀ i, P * part.proj i = part.proj i * P) :
    bornWeight (partitionPinching part ρ) P = bornWeight ρ P :=
  trace_partitionPinching_mul_commutant part ρ P hPc

/-- **Trace-dependent.** **Lüders-formula compatibility**: for a matrix `P`
in the commutant of the partition, the zero-totalized sandwich formula
commutes with pinching. Event and nonzero-weight hypotheses are not required
for this algebraic identity. -/
theorem partitionPinching_luedersUpdate (ρ P : Matrix (Fin n) (Fin n) ℂ)
    (hPc : ∀ i, P * part.proj i = part.proj i * P) :
    partitionPinching part (luedersUpdate ρ P) =
      luedersUpdate (partitionPinching part ρ) P := by
  have hsand : ∀ i : Fin k,
      part.proj i * (P * ρ * P) * part.proj i =
        P * (part.proj i * ρ * part.proj i) * P := by
    intro i
    have h1 : part.proj i * (P * ρ * P) * part.proj i =
        (part.proj i * P) * ρ * (P * part.proj i) := by simp only [mul_assoc]
    have h2 : P * (part.proj i * ρ * part.proj i) * P =
        (P * part.proj i) * ρ * (part.proj i * P) := by simp only [mul_assoc]
    rw [h1, h2, hPc i]
  rw [luedersUpdate, luedersUpdate, bornWeight_partitionPinching part ρ P hPc,
    partitionPinching, partitionPinching]
  simp only [mul_smul_comm, smul_mul_assoc]
  rw [← Finset.smul_sum]
  congr 1
  rw [Finset.mul_sum, Finset.sum_mul]
  exact Finset.sum_congr rfl fun i _ => hsand i

/-- **Trace-dependent.** State-facing Lüders naturality. For a commutant
event of nonzero weight, the typed state update commutes with partition
pinching. The codomain makes state preservation explicit. -/
theorem partitionPinching_luedersStateUpdate [NeZero n]
    (ρ : StateMatrix n) (P : ProjectionEvent n)
    (hPc : ∀ i, P.1 * part.proj i = part.proj i * P.1)
    (hw : bornWeight ρ.1 P.1 ≠ 0) :
    partitionPinching part (luedersStateUpdate ρ P hw).1 =
      (luedersStateUpdate
        (⟨partitionPinching part ρ.1,
          partitionPinching_isState part ρ.2⟩ : StateMatrix n)
        P (by
          rw [bornWeight_partitionPinching part ρ.1 P.1 hPc]
          exact hw)).1 := by
  rw [coe_luedersStateUpdate, coe_luedersStateUpdate]
  exact partitionPinching_luedersUpdate part ρ.1 P.1 hPc

-- Axiom audit: each must report only `[propext, Classical.choice, Quot.sound]`.
#print axioms ProjectivePartition.proj_mul_proj
#print axioms ProjectivePartition.proj_commute
#print axioms ProjectivePartition.mem_commutant_iff
#print axioms partitionPinchingLinearMap_apply
#print axioms partitionPinching_mul_proj
#print axioms proj_mul_partitionPinching
#print axioms proj_commute_partitionPinching
#print axioms partitionPinching_mem_commutant
#print axioms partitionPinching_fixes
#print axioms partitionPinching_eq_self_iff_mem_commutant
#print axioms partitionPinching_idem
#print axioms partitionPinching_unital
#print axioms trace_partitionPinching
#print axioms partitionPinching_posSemidef
#print axioms conjTranspose_partitionPinching
#print axioms partitionPinching_isState
#print axioms partitionPinching_bimodule
#print axioms range_partitionPinchingLinearMap
#print axioms trace_conjTranspose_partitionPinching_mul
#print axioms trace_partitionPinching_pythagoras
#print axioms trace_partitionPinching_contraction
#print axioms trace_partitionPinching_mul_commutant
#print axioms partitionPinching_unique
#print axioms partitionPinchingLinearMap_unique
#print axioms bornWeight_partitionPinching
#print axioms partitionPinching_luedersUpdate
#print axioms partitionPinching_luedersStateUpdate

end EventAlgebra
