import Geometry.EventPopulationChartInterface
import PrimitivePortFrameQuotient
import ObserverPatchHolography.Provenance.CausalInterval

/-!
# Source-derived finite 1+3 carrier and canonical-height causal placement

The exact rank-three source Gram quotient combines with an independent real
axis to define an ambient carrier without postulating a Hermitian event
carrier. Canonical source height enters only when events are placed in that
carrier. This file makes the separation explicit:

* `SourceSpacetimeCarrier := ℝ × FrameQuotient` has real dimension four;
* the bilinear form `tt' - quotientGram x x'` has one displayed positive
  direction and three displayed negative directions;
* it is linearly and metrically equivalent to the existing Pauli-coordinate
  Lorentz module;
* every source-unit spatial direction gives a canonical future-null vector;
* a finite semantic log derives canonical source height from authenticated
  parenthood, while a spatial readback and one positive `timeScale` remain
  supplied; positive `timeScale` times source height is only the temporal
  coordinate of the resulting event placement, not a physical clock reading;
* one explicit squared-speed bound on authenticated parent edges implies
  that every generated precedence is future-causal; and
* an explicit converse-support condition promotes this to a faithful finite
  order/cone embedding and constructs a one-chart source-native causal-chart
  interface.

The abstract semantic-log interface carries a well-foundedness certificate;
on a finite carrier, `SemanticEventLog.sourceHeight` replaces it by the
canonical longest-parent-chain height computed from authenticated parenthood
alone.
The converse-support clause is load-bearing: neither provenance nor the
rank-three quotient selects the spatial readback, the positive `timeScale`,
or proves that every cone comparison is generated by authenticated ancestry.
The module supplies a finite ambient Lorentz carrier and a conditional
faithful placement.  It proves no local finiteness under refinement,
count--volume law, manifoldlikeness, topology, smooth atlas, curvature,
physical signal interpretation, or continuum limit.
-/

namespace OPH.SourceDerivedSpacetime

noncomputable section

open OPH.C1Lorentz OPH.C2Soldering OPH.CausalComposition
  OPH.EventPopulation OPH.PrimitivePortFrameQuotient OPH.Provenance

universe u v w

/-! ## The exact source 1+3 carrier -/

/-- An independent real axis adjoined to the proved rank-three source Gram
quotient. Canonical source height enters only through `eventPoint` below. -/
abbrev SourceSpacetimeCarrier := ℝ × FrameQuotient

/-- Exact source-carrier equivalence to Pauli coordinates.  The spatial map
is the already proved quotient equivalence, not a new dimension premise. -/
noncomputable def sourceSpacetimeEquivHerm2 :
    SourceSpacetimeCarrier ≃ₗ[ℝ] Herm2 :=
  (LinearEquiv.refl ℝ ℝ).prodCongr quotientEquivVec3

/-- The source carrier has dimension `1 + 3 = 4`. -/
theorem sourceSpacetimeCarrier_finrank :
    Module.finrank ℝ SourceSpacetimeCarrier = 4 := by
  simp [SourceSpacetimeCarrier, frameQuotient_finrank]

/-- The Lorentz bilinear form constructed from source data: the time-axis
coordinate is positive and the source Gram quotient is negative. -/
noncomputable def sourceLorentzB
    (a b : SourceSpacetimeCarrier) : ℝ :=
  a.1 * b.1 - quotientGram a.2 b.2

/-- Quadratic form of the constructed source carrier. -/
noncomputable def sourceLorentzQ (a : SourceSpacetimeCarrier) : ℝ :=
  sourceLorentzB a a

/-- The constructed form is exactly the existing `(+---)` Pauli-coordinate
form under the source quotient equivalence. -/
theorem sourceLorentzB_equiv (a b : SourceSpacetimeCarrier) :
    sourceLorentzB a b =
      lorentzB (sourceSpacetimeEquivHerm2 a)
        (sourceSpacetimeEquivHerm2 b) := by
  rfl

/-- Quadratic-form version of the exact Lorentz equivalence. -/
theorem sourceLorentzQ_equiv (a : SourceSpacetimeCarrier) :
    sourceLorentzQ a = lorentzQ (sourceSpacetimeEquivHerm2 a) := by
  rw [sourceLorentzQ, sourceLorentzB_equiv, lorentzB_self]

/-- The positive unit time-axis direction. -/
def sourceTimeAxis : SourceSpacetimeCarrier := (1, 0)

/-- The source quotient embedded as the spatial hyperplane. -/
def sourceSpatial (q : FrameQuotient) : SourceSpacetimeCarrier := (0, q)

@[simp] theorem sourceLorentzQ_timeAxis :
    sourceLorentzQ sourceTimeAxis = 1 := by
  simp [sourceLorentzQ, sourceLorentzB, sourceTimeAxis, quotientGram,
    OPH.PrimitivePortTranslationBridge.dot]

@[simp] theorem sourceLorentzQ_spatial (q : FrameQuotient) :
    sourceLorentzQ (sourceSpatial q) = -quotientGram q q := by
  simp [sourceLorentzQ, sourceLorentzB, sourceSpatial]

theorem quotientGram_self_nonneg (q : FrameQuotient) :
    0 ≤ quotientGram q q := by
  change 0 ≤ ∑ d : Fin 3,
    quotientEquivVec3 q d * quotientEquivVec3 q d
  exact Finset.sum_nonneg fun d _ ↦ mul_self_nonneg _

/-- Every nonzero source-spatial direction is strictly negative for the
constructed form. -/
theorem sourceLorentzQ_spatial_neg {q : FrameQuotient} (hq : q ≠ 0) :
    sourceLorentzQ (sourceSpatial q) < 0 := by
  rw [sourceLorentzQ_spatial]
  apply neg_lt_zero.mpr
  exact lt_of_le_of_ne (quotientGram_self_nonneg q)
    (fun h ↦ hq ((quotientGram_self_eq_zero_iff q).mp h.symm))

/-- Three explicit source-spatial axes obtained by pulling back the Cartesian
axes through the proved quotient equivalence. -/
noncomputable def sourceSpatialAxis (i : Fin 3) : SourceSpacetimeCarrier :=
  sourceSpatial (quotientEquivVec3.symm (Pi.single i 1))

@[simp] theorem sourceLorentzQ_spatialAxis (i : Fin 3) :
    sourceLorentzQ (sourceSpatialAxis i) = -1 := by
  fin_cases i <;>
    simp [sourceSpatialAxis, sourceLorentzQ, sourceLorentzB, sourceSpatial,
      quotientGram, OPH.PrimitivePortTranslationBridge.dot,
      Fin.sum_univ_succ]

@[simp] theorem sourceLorentzB_time_spatialAxis (i : Fin 3) :
    sourceLorentzB sourceTimeAxis (sourceSpatialAxis i) = 0 := by
  simp [sourceLorentzB, sourceTimeAxis, sourceSpatialAxis, sourceSpatial,
    quotientGram, OPH.PrimitivePortTranslationBridge.dot]

/-- The three displayed source-spatial axes are mutually orthogonal and
have norm square `-1`. -/
theorem sourceLorentzB_spatialAxis (i j : Fin 3) :
    sourceLorentzB (sourceSpatialAxis i) (sourceSpatialAxis j) =
      if i = j then -1 else 0 := by
  fin_cases i <;> fin_cases j <;>
    simp [sourceLorentzB, sourceSpatialAxis, sourceSpatial, quotientGram,
      OPH.PrimitivePortTranslationBridge.dot, Fin.sum_univ_succ]

/-- Exposed finite signature receipt: dimension four, one positive unit axis,
three negative unit axes, and time--space orthogonality. -/
theorem sourceCarrier_one_three_signature :
    Module.finrank ℝ SourceSpacetimeCarrier = 4 ∧
    sourceLorentzQ sourceTimeAxis = 1 ∧
    (∀ i : Fin 3, sourceLorentzQ (sourceSpatialAxis i) = -1) ∧
    (∀ i : Fin 3,
      sourceLorentzB sourceTimeAxis (sourceSpatialAxis i) = 0) ∧
    (∀ i j : Fin 3,
      sourceLorentzB (sourceSpatialAxis i) (sourceSpatialAxis j) =
        if i = j then -1 else 0) :=
  ⟨sourceSpacetimeCarrier_finrank, sourceLorentzQ_timeAxis,
    sourceLorentzQ_spatialAxis, sourceLorentzB_time_spatialAxis,
    sourceLorentzB_spatialAxis⟩

/-! ## Source-unit directions are canonically future null -/

/-- Unit directions of the source Gram quotient, stated locally so this
carrier construction does not depend on a frame packet. -/
abbrev SourceSpatialUnitDirection :=
  {q : FrameQuotient // quotientGram q q = 1}

/-- Canonical future-null vector `(1,q)` of one source-unit direction. -/
def sourceUnitNullVector
    (q : SourceSpatialUnitDirection) : SourceSpacetimeCarrier :=
  (1, q.1)

@[simp] theorem sourceUnitNullVector_time
    (q : SourceSpatialUnitDirection) : (sourceUnitNullVector q).1 = 1 :=
  rfl

theorem sourceUnitNullVector_null (q : SourceSpatialUnitDirection) :
    sourceLorentzQ (sourceUnitNullVector q) = 0 := by
  simp [sourceUnitNullVector, sourceLorentzQ, sourceLorentzB, q.2]

/-! ## The future cone on the source carrier -/

/-- Future-causal vectors of the constructed source carrier. -/
def IsSourceFutureCausal (a : SourceSpacetimeCarrier) : Prop :=
  0 ≤ sourceLorentzQ a ∧ 0 ≤ a.1

/-- The source future cone is exactly the existing Pauli-coordinate future
cone under the constructed equivalence. -/
theorem isSourceFutureCausal_iff (a : SourceSpacetimeCarrier) :
    IsSourceFutureCausal a ↔
      IsFutureCausal (sourceSpacetimeEquivHerm2 a) := by
  rw [IsSourceFutureCausal, IsFutureCausal, ← sourceLorentzQ_equiv]
  rfl

/-- Every unit source direction has a canonical future-null representative. -/
theorem sourceUnitNullVector_futureCausal
    (q : SourceSpatialUnitDirection) :
    IsSourceFutureCausal (sourceUnitNullVector q) := by
  exact ⟨le_of_eq (sourceUnitNullVector_null q).symm, by simp⟩

/-- Causal order induced by the constructed source carrier. -/
def sourceCausalLE (a b : SourceSpacetimeCarrier) : Prop :=
  IsSourceFutureCausal (b - a)

theorem sourceCausalLE_iff (a b : SourceSpacetimeCarrier) :
    sourceCausalLE a b ↔
      causalLE (sourceSpacetimeEquivHerm2 a)
        (sourceSpacetimeEquivHerm2 b) := by
  unfold sourceCausalLE causalLE
  rw [isSourceFutureCausal_iff]
  simp

theorem sourceCausalLE_refl (a : SourceSpacetimeCarrier) :
    sourceCausalLE a a :=
  (sourceCausalLE_iff a a).mpr (causalLE_refl _)

theorem sourceCausalLE_trans {a b c : SourceSpacetimeCarrier}
    (hab : sourceCausalLE a b) (hbc : sourceCausalLE b c) :
    sourceCausalLE a c :=
  (sourceCausalLE_iff a c).mpr
    (causalLE_trans ((sourceCausalLE_iff a b).mp hab)
      ((sourceCausalLE_iff b c).mp hbc))

/-- Antisymmetry of the future-cone order on the constructed source carrier. -/
theorem sourceCausalLE_antisymm {a b : SourceSpacetimeCarrier}
    (hab : sourceCausalLE a b) (hba : sourceCausalLE b a) : a = b := by
  apply sourceSpacetimeEquivHerm2.injective
  exact causalLE_antisymm ((sourceCausalLE_iff a b).mp hab)
    ((sourceCausalLE_iff b a).mp hba)

/-- The constructed ambient Lorentz-cone relation is itself a partial order. -/
theorem sourceCausalLE_isPartialOrder :
    (∀ a, sourceCausalLE a a) ∧
    (∀ a b c, sourceCausalLE a b → sourceCausalLE b c →
      sourceCausalLE a c) ∧
    (∀ a b, sourceCausalLE a b → sourceCausalLE b a → a = b) :=
  ⟨sourceCausalLE_refl,
    fun _ _ _ hab hbc ↦ sourceCausalLE_trans hab hbc,
    fun _ _ hab hba ↦ sourceCausalLE_antisymm hab hba⟩

/-! ## Canonical source height plus supplied scale and spatial readback -/

/-- A placement of authenticated events in the constructed source carrier.
The ordinal coordinate is the canonical longest authenticated-parent-path
height. One positive `timeScale` and the spatial readback are
supplied, together with the explicit condition that every direct
authenticated edge lies in the resulting source cone. -/
structure RankSpatialCausalPlacement
    {Register : Type u} {Value : Type v} {Event : Type w}
    [DecidableEq Register] [Fintype Event] [DecidableEq Event]
    [DecidableEq Value]
    (L : SemanticEventLog Register Value Event) where
  timeScale : ℝ
  timeScale_pos : 0 < timeScale
  spatial : Event → FrameQuotient
  edge_speed_sq : ∀ {e f : Event}, L.ParentEdge e f →
    quotientGram (spatial f - spatial e) (spatial f - spatial e) ≤
      (timeScale * ((L.sourceHeight f : ℝ) -
        (L.sourceHeight e : ℝ))) ^ 2

namespace RankSpatialCausalPlacement

variable {Register : Type u} {Value : Type v} {Event : Type w}
variable [DecidableEq Register] [Fintype Event] [DecidableEq Event]
  [DecidableEq Value]
variable {L : SemanticEventLog Register Value Event}
variable (P : RankSpatialCausalPlacement L)

/-- Event point with the canonical source-height ordinal coordinate, one
supplied positive `timeScale`, and supplied rank-three spatial readback. -/
def eventPoint (e : Event) : SourceSpacetimeCarrier :=
  (P.timeScale * (L.sourceHeight e : ℝ), P.spatial e)

/-- The squared-speed certificate makes every authenticated direct parent
future-causal in the constructed source carrier. -/
theorem parentEdge_sourceCausalLE {e f : Event} (h : L.ParentEdge e f) :
    sourceCausalLE (P.eventPoint e) (P.eventPoint f) := by
  have hrNat : L.sourceHeight e < L.sourceHeight f :=
    L.sourceHeight_lt_of_parent h
  have hr : (L.sourceHeight e : ℝ) < (L.sourceHeight f : ℝ) := by
    exact_mod_cast hrNat
  constructor
  · simp only [sourceLorentzQ, sourceLorentzB, eventPoint, Prod.fst_sub,
      Prod.snd_sub]
    nlinarith [P.edge_speed_sq h, P.timeScale_pos]
  · simp only [eventPoint, Prod.fst_sub]
    nlinarith [P.timeScale_pos]

/-- Closure plus cone transitivity promotes the edge certificate to every
source-generated precedence relation. -/
theorem generatedBefore_sourceCausalLE {e f : Event}
    (h : L.GeneratedBefore e f) :
    sourceCausalLE (P.eventPoint e) (P.eventPoint f) :=
  L.generatedBefore_le_of_transitive
    (fun a b ↦ sourceCausalLE (P.eventPoint a) (P.eventPoint b))
    (fun _ _ hedge ↦ P.parentEdge_sourceCausalLE hedge)
    (fun hab hbc ↦ sourceCausalLE_trans hab hbc) h

/-- Reflexive generated precedence also maps into the constructed cone. -/
theorem generatedBeforeEq_sourceCausalLE {e f : Event}
    (h : L.GeneratedBeforeEq e f) :
    sourceCausalLE (P.eventPoint e) (P.eventPoint f) := by
  rcases h with rfl | h
  · exact sourceCausalLE_refl _
  · exact P.generatedBefore_sourceCausalLE h

/-- Every future-cone comparison of source-height event points is monotone in
canonical source height, independently of the spatial readback. -/
theorem sourceHeight_le_of_sourceCausalLE {e f : Event}
    (h : sourceCausalLE (P.eventPoint e) (P.eventPoint f)) :
    L.sourceHeight e ≤ L.sourceHeight f := by
  have ht := h.2
  simp only [eventPoint, Prod.fst_sub] at ht
  have hr : (L.sourceHeight e : ℝ) ≤ (L.sourceHeight f : ℝ) := by
    nlinarith [P.timeScale_pos]
  exact_mod_cast hr

end RankSpatialCausalPlacement

/-! ## Conditional faithful finite embedding -/

/-- A faithful placement adds the explicit converse condition: every cone
comparison among placed events must be supported by reflexive authenticated
ancestry.  This clause is not derivable from the speed bound alone. -/
structure FaithfulRankSpatialCausalPlacement
    {Register : Type u} {Value : Type v} {Event : Type w}
    [DecidableEq Register] [Fintype Event] [DecidableEq Event]
    [DecidableEq Value]
    (L : SemanticEventLog Register Value Event)
    extends RankSpatialCausalPlacement L where
  cone_supported : ∀ e f : Event,
    sourceCausalLE (toRankSpatialCausalPlacement.eventPoint e)
        (toRankSpatialCausalPlacement.eventPoint f) →
      L.GeneratedBeforeEq e f

namespace FaithfulRankSpatialCausalPlacement

variable {Register : Type u} {Value : Type v} {Event : Type w}
variable [DecidableEq Register] [Fintype Event] [DecidableEq Event]
  [DecidableEq Value]
variable {L : SemanticEventLog Register Value Event}
variable (P : FaithfulRankSpatialCausalPlacement L)

/-- Exact two-way order/cone equivalence on the finite placed carrier. -/
theorem generatedBeforeEq_iff_sourceCausalLE (e f : Event) :
    L.GeneratedBeforeEq e f ↔
      sourceCausalLE (P.toRankSpatialCausalPlacement.eventPoint e)
        (P.toRankSpatialCausalPlacement.eventPoint f) :=
  ⟨P.toRankSpatialCausalPlacement.generatedBeforeEq_sourceCausalLE,
    P.cone_supported e f⟩

/-- A faithful placement preserves every finite causal interval exactly.
Consequently, interval-order statistics may be computed either in the
source-generated poset or among the placed event points in the Lorentz cone.
This transports the finite order data; it supplies no count--volume law or
manifoldlikeness conclusion. -/
theorem mem_interval_iff_sourceCausalInterval (a b x : Event) :
    x ∈ L.interval a b ↔
      sourceCausalLE (P.toRankSpatialCausalPlacement.eventPoint a)
          (P.toRankSpatialCausalPlacement.eventPoint x) ∧
        sourceCausalLE (P.toRankSpatialCausalPlacement.eventPoint x)
          (P.toRankSpatialCausalPlacement.eventPoint b) := by
  change (L.GeneratedBeforeEq a x ∧ L.GeneratedBeforeEq x b) ↔ _
  exact and_congr
    (P.generatedBeforeEq_iff_sourceCausalLE a x)
    (P.generatedBeforeEq_iff_sourceCausalLE x b)

omit [Fintype Event] [DecidableEq Event] [DecidableEq Value] in
/-- Antisymmetry of reflexive authenticated ancestry. -/
theorem generatedBeforeEq_antisymm {e f : Event}
    (hef : L.GeneratedBeforeEq e f) (hfe : L.GeneratedBeforeEq f e) :
    e = f := by
  rcases hef with rfl | hef
  · rfl
  · rcases hfe with rfl | hfe
    · exact False.elim (L.generatedBefore_irrefl _ hef)
    · exact False.elim (L.generatedBefore_asymm hef hfe)

/-- A faithful causal placement separates events; no additional chart
separation premise is required. -/
theorem eventPoint_injective :
    Function.Injective P.toRankSpatialCausalPlacement.eventPoint := by
  intro e f hpoint
  apply generatedBeforeEq_antisymm (L := L)
  · apply (P.generatedBeforeEq_iff_sourceCausalLE e f).mpr
    rw [hpoint]
    exact sourceCausalLE_refl _
  · apply (P.generatedBeforeEq_iff_sourceCausalLE f e).mpr
    rw [hpoint]
    exact sourceCausalLE_refl _

/-- The faithful placement constructs a one-chart source-native causal-chart
interface.  The chart is finite/global; this is not an open manifold atlas. -/
def toSourceDerivedCausalChartInterface :
    SourceDerivedCausalChartInterface Register Value Event Unit where
  semanticLog := L
  atlas := {
    visible := fun _ _ ↦ True
    coordinate := fun _ e ↦
      sourceSpacetimeEquivHerm2
        (P.toRankSpatialCausalPlacement.eventPoint e)
    overlap := trivialOverlap Unit
    coordinate_overlap := by
      intro i j e _ _
      simp [trivialOverlap, LorentzOverlapCocycle.act,
        OrientedLorentzEquiv.refl] }
  total := fun _ _ ↦ trivial
  base := ()
  separation := sourceSpacetimeEquivHerm2.injective.comp P.eventPoint_injective
  generated_cone_base := by
    intro e f
    exact (P.generatedBeforeEq_iff_sourceCausalLE e f).trans
      (sourceCausalLE_iff _ _)

end FaithfulRankSpatialCausalPlacement

/-! ## Non-chain authenticated control -/

namespace BooleanDiamondPlacement

open BooleanDiamond

/-- The canonical source-derived longest-parent-chain heights of the
authenticated Boolean diamond. -/
@[simp] theorem sourceHeight_zero : log.sourceHeight 0 = 0 := by
  rw [log.sourceHeight_eq]
  simp [parentEdge_iff]

@[simp] theorem sourceHeight_left : log.sourceHeight 1 = 1 := by
  rw [log.sourceHeight_eq]
  apply le_antisymm
  · apply Finset.sup_le
    intro p _
    fin_cases p <;> simp [parentEdge_iff, sourceHeight_zero]
  · simpa [parentEdge_iff, sourceHeight_zero] using
      (Finset.le_sup
        (s := (Finset.univ : Finset (Fin 4)))
        (f := fun p : Fin 4 ↦
          if log.ParentEdge p 1 then log.sourceHeight p + 1 else 0)
        (Finset.mem_univ (0 : Fin 4)))

@[simp] theorem sourceHeight_right : log.sourceHeight 2 = 1 := by
  rw [log.sourceHeight_eq]
  apply le_antisymm
  · apply Finset.sup_le
    intro p _
    fin_cases p <;> simp [parentEdge_iff, sourceHeight_zero]
  · simpa [parentEdge_iff, sourceHeight_zero] using
      (Finset.le_sup
        (s := (Finset.univ : Finset (Fin 4)))
        (f := fun p : Fin 4 ↦
          if log.ParentEdge p 2 then log.sourceHeight p + 1 else 0)
        (Finset.mem_univ (0 : Fin 4)))

@[simp] theorem sourceHeight_answer : log.sourceHeight 3 = 2 := by
  rw [log.sourceHeight_eq]
  apply le_antisymm
  · apply Finset.sup_le
    intro p _
    fin_cases p <;>
      simp [parentEdge_iff, sourceHeight_left,
        sourceHeight_right]
  · simpa [parentEdge_iff, sourceHeight_left] using
      (Finset.le_sup
        (s := (Finset.univ : Finset (Fin 4)))
        (f := fun p : Fin 4 ↦
          if log.ParentEdge p 3 then log.sourceHeight p + 1 else 0)
        (Finset.mem_univ (1 : Fin 4)))

/-- One exact unit source-spatial axis. -/
noncomputable def unitAxis : FrameQuotient :=
  quotientEquivVec3.symm ![1, 0, 0]

@[simp] theorem unitAxis_gram : quotientGram unitAxis unitAxis = 1 := by
  simp [unitAxis, quotientGram, OPH.PrimitivePortTranslationBridge.dot,
    Fin.sum_univ_succ]

/-- Spatial placement of the Boolean fork/join: the two source-height-one
responses occupy opposite unit directions, while injection and answer lie at
the spatial origin. -/
noncomputable def spatial : Fin 4 → FrameQuotient :=
  ![0, unitAxis, -unitAxis, 0]

/-- Every authenticated diamond edge is null (hence satisfies the squared
speed bound) in the constructed source carrier. -/
noncomputable def causalPlacement : RankSpatialCausalPlacement log where
  timeScale := 1
  timeScale_pos := by norm_num
  spatial := spatial
  edge_speed_sq := by
    intro e f h
    have hcase := (parentEdge_iff e f).mp h
    rcases hcase with ⟨he, hf⟩ | ⟨he, hf⟩ | ⟨he, hf⟩ | ⟨he, hf⟩ <;>
      subst he <;> subst hf <;>
      simp [spatial, unitAxis, sourceHeight_zero, sourceHeight_left,
        sourceHeight_right, sourceHeight_answer, quotientGram,
        OPH.PrimitivePortTranslationBridge.dot, Fin.sum_univ_succ] <;>
      norm_num

@[simp] theorem point_zero :
    causalPlacement.eventPoint 0 = (0, 0) := by
  simp [RankSpatialCausalPlacement.eventPoint, causalPlacement, spatial,
    sourceHeight_zero]

@[simp] theorem point_left :
    causalPlacement.eventPoint 1 = (1, unitAxis) := by
  simp [RankSpatialCausalPlacement.eventPoint, causalPlacement, spatial,
    sourceHeight_left]

@[simp] theorem point_right :
    causalPlacement.eventPoint 2 = (1, -unitAxis) := by
  simp [RankSpatialCausalPlacement.eventPoint, causalPlacement, spatial,
    sourceHeight_right]

@[simp] theorem point_answer :
    causalPlacement.eventPoint 3 = (2, 0) := by
  simp [RankSpatialCausalPlacement.eventPoint, causalPlacement, spatial,
    sourceHeight_answer]

private theorem not_sourceCausalLE_of_computation
    (a b : SourceSpacetimeCarrier)
    (hq : sourceLorentzQ (b - a) < 0 ∨ (b - a).1 < 0) :
    ¬ sourceCausalLE a b := by
  intro h
  rcases hq with hq | ht
  · exact (not_le_of_gt hq) h.1
  · exact (not_le_of_gt ht) h.2

/-- The converse cone-support clause holds exactly on the Boolean diamond:
the responses are spacelike and all reversed comparisons point to negative
source-height time. -/
noncomputable def faithfulPlacement :
    FaithfulRankSpatialCausalPlacement log where
  toRankSpatialCausalPlacement := causalPlacement
  cone_supported := by
    intro e f h
    fin_cases e <;> fin_cases f
    · exact Or.inl rfl
    · exact Or.inr before_left
    · exact Or.inr before_right
    · exact Or.inr injection_before_answer
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inr (by simp [point_zero, point_left]))) h)
    · exact Or.inl rfl
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inl (by
          simp [point_left, point_right, sourceLorentzQ, sourceLorentzB,
            unitAxis, quotientGram, OPH.PrimitivePortTranslationBridge.dot,
            Fin.sum_univ_succ]
          norm_num))) h)
    · exact Or.inr left_before_answer
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inr (by simp [point_zero, point_right]))) h)
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inl (by
          simp [point_left, point_right, sourceLorentzQ, sourceLorentzB,
            unitAxis, quotientGram, OPH.PrimitivePortTranslationBridge.dot,
            Fin.sum_univ_succ]))) h)
    · exact Or.inl rfl
    · exact Or.inr right_before_answer
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inr (by simp [point_zero, point_answer]))) h)
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inr (by simp [point_left, point_answer]))) h)
    · exact False.elim ((not_sourceCausalLE_of_computation _ _
        (Or.inr (by simp [point_right, point_answer]))) h)
    · exact Or.inl rfl

/-- Exact non-chain finite faithful embedding receipt. -/
theorem exactDiamondConeOrder (e f : Fin 4) :
    log.GeneratedBeforeEq e f ↔
      sourceCausalLE (causalPlacement.eventPoint e)
        (causalPlacement.eventPoint f) :=
  faithfulPlacement.generatedBeforeEq_iff_sourceCausalLE e f

/-- The two independent responses are spacelike in the constructed carrier. -/
theorem responses_spacelike :
    sourceLorentzQ
      (causalPlacement.eventPoint 2 - causalPlacement.eventPoint 1) < 0 := by
  simp [point_left, point_right, sourceLorentzQ, sourceLorentzB,
    unitAxis, quotientGram, OPH.PrimitivePortTranslationBridge.dot,
    Fin.sum_univ_succ]
  norm_num

/-- Every authenticated diamond parent edge is exactly null. -/
theorem parentEdge_null {e f : Fin 4} (h : log.ParentEdge e f) :
    sourceLorentzQ
      (causalPlacement.eventPoint f - causalPlacement.eventPoint e) = 0 := by
  have hcase := (parentEdge_iff e f).mp h
  rcases hcase with ⟨he, hf⟩ | ⟨he, hf⟩ | ⟨he, hf⟩ | ⟨he, hf⟩ <;>
    subst he <;> subst hf <;>
    simp [point_zero, point_left, point_right, point_answer,
      sourceLorentzQ, sourceLorentzB, unitAxis, quotientGram,
      OPH.PrimitivePortTranslationBridge.dot, Fin.sum_univ_succ] <;>
    norm_num

end BooleanDiamondPlacement

/-! ## Axiom audit -/

#print axioms sourceSpacetimeCarrier_finrank
#print axioms sourceLorentzB_equiv
#print axioms sourceCarrier_one_three_signature
#print axioms sourceUnitNullVector_null
#print axioms sourceUnitNullVector_futureCausal
#print axioms sourceCausalLE_isPartialOrder
#print axioms RankSpatialCausalPlacement.parentEdge_sourceCausalLE
#print axioms RankSpatialCausalPlacement.generatedBefore_sourceCausalLE
#print axioms FaithfulRankSpatialCausalPlacement.generatedBeforeEq_iff_sourceCausalLE
#print axioms FaithfulRankSpatialCausalPlacement.mem_interval_iff_sourceCausalInterval
#print axioms FaithfulRankSpatialCausalPlacement.eventPoint_injective
#print axioms FaithfulRankSpatialCausalPlacement.toSourceDerivedCausalChartInterface
#print axioms BooleanDiamondPlacement.faithfulPlacement
#print axioms BooleanDiamondPlacement.exactDiamondConeOrder
#print axioms BooleanDiamondPlacement.responses_spacelike
#print axioms BooleanDiamondPlacement.parentEdge_null

end

end OPH.SourceDerivedSpacetime
